sources:
- archive: telegraf-1.36.4.tar.gz
  archive_sha512sum: 8e5afe30104b058ada47d1daf0bd62a2a6ebf77b91cce818f27772683ef1f58237b6552135440f777f332b9329fbb005e6899935039e94c7266ee1f3178a5a46
  archive_type: upstream
  commit_id: 467473bdb7087e42a5c1c11e63d64731883eb079
  missing: []
  skip_list: []
  skip_validation: false
  name: telegraf-1.36.4
  version: 1.36.4
  repo_url: https://github.com/influxdata/telegraf
  url: https://github.com/influxdata/telegraf/archive/refs/tags/v1.36.4.tar.gz
  spdx:
    package:
      detailed_description: Telegraf is an agent written in Go for collecting, processing, aggregating, and writing metrics. Design goals are to have a minimal memory footprint with a plugin system so that developers in the community can easily add support for collecting metrics from well known services (like Hadoop, Postgres, or Redis) and third party APIs (like Mailchimp, AWS CloudWatch, or Google Analytics).
      home_page: https://github.com/influxdata/telegraf
      license_concluded: Apache-2.0 AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND BSD-3-Clause-Clear AND EFL-2.0 AND EPL-2.0 AND ISC AND JSON AND MIT AND MPL-2.0 AND Unlicense
      license_declared: Apache-2.0 AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND BSD-3-Clause-Clear AND EFL-2.0 AND EPL-2.0 AND ISC AND JSON AND MIT AND MPL-2.0 AND Unlicense
      short_summary: agent for collecting, processing, aggregating, and writing metrics.
      supplier: 'Organization: Broadcom, Inc.'
