sources:
- archive: telegraf-1.38.4.tar.gz
  archive_sha512sum: 5431566af12194bbf98f698ba4de68bb2f312377f185be403cef1cd9e9ae4fbb6cecadb35ea517e3a8b0c9e1304e12b576a55f445b643c9da1dd63b7625c8c8f
  archive_type: upstream
  commit_id: c79b06d58e912124624d029a88bbe182254f0ff4
  missing: []
  skip_list: []
  skip_validation: false
  name: telegraf-1.38.4
  version: 1.38.4
  repo_url: https://github.com/influxdata/telegraf
  url: https://github.com/influxdata/telegraf/archive/refs/tags/v1.38.4.tar.gz
  spdx:
    package:
      detailed_description: Telegraf is an agent written in Go for collecting, processing, aggregating, and writing metrics. Design goals are to have a minimal memory footprint with a plugin system so that developers in the community can easily add support for collecting metrics from well known services (like Hadoop, Postgres, or Redis) and third party APIs (like Mailchimp, AWS CloudWatch, or Google Analytics).
      home_page: https://github.com/influxdata/telegraf
      license_concluded: Apache-2.0 AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND BSD-3-Clause-Clear AND EFL-2.0 AND EPL-2.0 AND ISC AND JSON AND MIT AND MPL-2.0 AND Unlicense
      license_declared: Apache-2.0 AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND BSD-3-Clause-Clear AND EFL-2.0 AND EPL-2.0 AND ISC AND JSON AND MIT AND MPL-2.0 AND Unlicense
      short_summary: agent for collecting, processing, aggregating, and writing metrics.
      supplier: 'Organization: Broadcom, Inc.'
