sources:
- archive: cracklib-2.10.3.tar.xz
  archive_sha512sum: 5a86116b888dd324d17495c3ccefb061bfc6b31a7dcebc394324d87878dec5dec268591f9d7ef30cf60f70df9ff3bbf3d891c60efc198dba80f83cc43a08273c
  archive_type: upstream
  name: cracklib-2.10.3
  version: 2.10.3
  url: https://github.com/cracklib/cracklib/releases/download/v2.10.3/cracklib-2.10.3.tar.xz
  repo_url: https://github.com/cracklib/cracklib
  commit_id: e73d5db1789d198b5f9ec44b68b9c775c3e6c042
  skip_list: []
  missing: [test-driver, Makefile.am, test-data, missing, COPYING.LIB, AUTHORS, ChangeLog, compile, configure.ac, doc, README-WORDS, dicts, lib, NEWS, config.h.in, README-LICENSE, README.release.md, python, cracklib.spec.in, words, po, src, historical-tags-before-cleanup.txt, Makefile.in, README, configure, depcomp, ltmain.sh, aclocal.m4, .gitignore, .github, config.rpath, util, install-sh, README.md, INSTALL, m4, ABOUT-NLS, py-compile, config.guess, README-DAWG, config.sub]
  spdx:
    package:
      detailed_description: 'CrackLib tests passwords to determine whether they match
        certain security-oriented characteristics. You can use CrackLib to stop users
        from choosing passwords which would be easy to guess. CrackLib performs certain
        tests:  * It tries to generate words from a username and gecos entry and checks
        those words against the password; * It checks for simplistic patterns in passwords;
        * It checks for the password in a dictionary.  CrackLib is actually a library
        containing a particular C function which is used to check the password, as
        well as other C functions. CrackLib is not a replacement for a passwd program;
        it must be used in conjunction with an existing passwd program.  Install the
        cracklib package if you need a program to check users'' passwords to see if
        they are at least minimally secure. If you install CrackLib, you''ll also
        want to install the cracklib-dicts package.'
      home_page: https://github.com/cracklib/cracklib
      license_concluded: LGPL-2.1-only AND LGPL-2.1-or-later AND Artistic-2.0 AND
        GPL-2.0-only AND GPL-2.0-or-later AND GPL-1.0-or-later AND LGPL-2.0-or-later
      license_declared: LGPL-2.1-only AND LGPL-2.1-or-later AND Artistic-2.0 AND GPL-2.0-only
        AND GPL-2.0-or-later AND GPL-1.0-or-later AND LGPL-2.0-or-later
      short_summary: A password strength-checking library.
      supplier: 'Organization: Broadcom, Inc.'

- archive: cracklib-words-2.10.3.gz
  archive_sha512sum: 4959918989eb925fc63d22891e71f8cbf6f0b8cdf4f11094444704cbeac467f6c67dbb644932e45e349849b682b3b563f33e1ecacfd141485ddda1a6cc37bbaa
  # TODO: Source verification script doesn't handle .gz
  skip_validation: true
  name: cracklib-words-2.10.3
  version: 2.10.3
  url: https://github.com/cracklib/cracklib/releases/download/v2.10.3/cracklib-words-2.10.3.gz
  repo_url: https://github.com/cracklib/cracklib
  commit_id: e73d5db1789d198b5f9ec44b68b9c775c3e6c042
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: scripts and content to build a full size password dictionary.
      home_page: https://github.com/cracklib/cracklib
      license_concluded: GPL-1.0-or-later
      license_declared: GPL-1.0-or-later
      short_summary: scripts and content to build a full size password dictionary
      supplier: 'Organization: Broadcom, Inc.'
