sources:
- archive: suricata-7.0.6.tar.gz
  archive_sha512sum: 628f1d4f7307ad5a8f9f7e52b698dcd8cccebfe089f1328fa5bf6f790669aff1a4e19fff921ff7102125b77c45b7671b88bcf7ae8865d06a5836a9e8d030866c
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The Suricata Engine is an open-source system designed
        for detecting and preventing intrusion in computer networks. '
      home_page: https://suricata.io
      license_concluded: (Apache-2.0 OR Apache-2.0 WITH LLVM-exception OR MIT) AND
        (Apache-2.0 OR MIT) AND (Apache-2.0 OR MIT) AND (MIT OR Unlicense) AND 0BSD
        AND Apache-2.0 AND Apache-2.0 WITH LLVM-exception AND BSD-2-Clause AND BSD-2-Clause-Views
        AND BSD-3-Clause AND CC-BY-NC-4.0 AND CC-BY-SA-4.0 AND CC0-1.0 AND FSFAP AND
        FSFUL AND FSFULLR AND FSFULLRWD AND GPL-1.0-or-later AND GPL-2.0-only AND
        GPL-2.0-only WITH Linux-syscall-note AND GPL-2.0-or-later AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Libtool-exception
        AND GPL-3.0-only AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND LGPL-2.1-only AND LGPL-3.0-or-later AND MIT AND MIT-testregex AND NTP-0
        AND Python-2.0 AND SunPro AND Unicode-DFS-2016 AND Unlicense AND X11 AND Zlib
      license_declared: (Apache-2.0 OR Apache-2.0 WITH LLVM-exception OR MIT) AND
        (Apache-2.0 OR MIT) AND (Apache-2.0 OR MIT) AND (MIT OR Unlicense) AND 0BSD
        AND Apache-2.0 AND Apache-2.0 WITH LLVM-exception AND BSD-2-Clause AND BSD-2-Clause-Views
        AND BSD-3-Clause AND CC-BY-NC-4.0 AND CC-BY-SA-4.0 AND CC0-1.0 AND FSFAP AND
        FSFUL AND FSFULLR AND FSFULLRWD AND GPL-1.0-or-later AND GPL-2.0-only AND
        GPL-2.0-only WITH Linux-syscall-note AND GPL-2.0-or-later AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Libtool-exception
        AND GPL-3.0-only AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND LGPL-2.1-only AND LGPL-3.0-or-later AND MIT AND MIT-testregex AND NTP-0
        AND Python-2.0 AND SunPro AND Unicode-DFS-2016 AND Unlicense AND X11 AND Zlib
      short_summary: Intrusion Detection System
      supplier: 'Organization: Broadcom, Inc.'
