sources:
- archive: mc-4.8.28.tar.xz
  archive_sha512sum: ca3b3a57281e9387cb52bf1fcfc3f39a4d5f438aafc256dc492c192678824f67c983a852c759664efc5bc6d0de471c9b3929834f8301f6302ca1ebeee513fdfd
  license_manual_review:
  - archive_path: lib/strutil/strverscmp.c
    sha256sum: cc753333a1f5160732de0fc2b693176967c89667e6f051f9732f31252d251c14
    spdx_exp: GPL-3.0-or-later AND LGPL-2.1-or-later
  - archive_path: doc/hlp/es/xnc.hlp
    sha256sum: 25e1258a9d497b7e393d7e53a79950aea15e480b79bfe524aa37dbc873d89e26
    spdx_exp: GPL-3.0-or-later
  skip_validation: true
  spdx:
    package:
      detailed_description: 'MC (Midnight Commander) is a text-mode full-screen file
        manager and visual shell. '
      home_page: https://www.midnight-commander.org
      license_concluded: AGPL-3.0-or-later AND Apache-2.0 AND BSD-3-Clause AND FSFAP
        AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-1.0-or-later AND GPL-2.0-or-later
        AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later
        WITH Libtool-exception AND GPL-3.0-only AND GPL-3.0-or-later AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later WITH Libtool-exception
        AND LGPL-2.0-or-later AND LGPL-2.1-or-later AND MIT AND X11
      license_declared: AGPL-3.0-or-later AND Apache-2.0 AND BSD-3-Clause AND FSFAP
        AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-1.0-or-later AND GPL-2.0-or-later
        AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later
        WITH Libtool-exception AND GPL-3.0-only AND GPL-3.0-or-later AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later WITH Libtool-exception
        AND LGPL-2.0-or-later AND LGPL-2.1-or-later AND MIT AND X11
      short_summary: File manager
      supplier: 'Organization: Broadcom, Inc.'
