shared_sources:
  - 90/shared-cfg-yml/cmake.yaml

sources:
- archive: lldb-18.1.8.src.tar.xz
  archive_sha512sum: f356a657d1aec860aeaaeb3aa3190652735160dd1e86dfbbae0441ace0a21cc774621198b0fc26c37d3e7c34d68d8a5f56806097f0c8d94718f5fc03495b1a3e
  skip_validation: true
  spdx:
    package:
      detailed_description: 'LLDB is a next generation, high-performance debugger.
        It is built as a set of reusable components which highly leverage existing
        libraries in the larger LLVM Project, such as the Clang expression parser
        and LLVM disassembler. '
      home_page: http://lldb.llvm.org
      license_concluded: APSL-2.0 AND Apache-2.0 AND Apache-2.0 WITH LLVM-exception
        AND MIT AND ISC AND Apache-1.0 AND FSFAP-no-warranty-disclaimer AND NCSA AND
        Python-2.0
      license_declared: APSL-2.0 AND Apache-2.0 AND Apache-2.0 WITH LLVM-exception
        AND MIT AND ISC AND Apache-1.0 AND FSFAP-no-warranty-disclaimer AND NCSA AND
        Python-2.0
      short_summary: A next generation, high-performance debugger.
      supplier: 'Organization: Broadcom, Inc.'
