sources:
- archive: jwt-2.10.1.gem
  archive_sha512sum: 5b61b2049df5930a66ee69df221ff7b2d2ef71a18c6cac65e6c1c6f0434a220364a54a607464665bd2c5e4572309dc22832ee1fa30f78c70371fe0d1ce991698
  skip_validation: true
  spdx:
    package:
      detailed_description: 'A pure ruby implementation of the RFC 7519 OAuth JSON Web Token (JWT) standard.'
      home_page: https://rubygems.org/gems/jwt
      license_concluded: MIT
      license_declared: MIT
      short_summary: A pure ruby implementation of the RFC 7519 OAuth JSON Web Token (JWT) standard.
      supplier: 'Organization: Broadcom, Inc.'
