sources:
- archive: atftp-0.8.1.tar.gz
  archive_sha512sum: fa6c328cc16cf43983bf8004cc967a0c039d84326e46b4c8c175d27a1422ae2fe3acedf22913fd155285c58e63c22e302d1df2bd727a87e91a4b75faa32452e2
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Multithreaded TFTP server implementing all options (option
        extension and multicast) as specified in RFC1350, RFC2090, RFC2347, RFC2348
        and RFC2349. Atftpd also support multicast protocol knowed as mtftp, defined
        in the PXE specification. The server supports being started from inetd(8)
        as well as a deamon using init scripts. '
      home_page: http://sourceforge.net/projects/atftp
      license_concluded: LGPL-2.1-or-later AND GPL-1.0-or-later AND GPL-2.0-only AND
        GPL-2.0-or-later
      license_declared: LGPL-2.1-or-later AND GPL-1.0-or-later AND GPL-2.0-only AND
        GPL-2.0-or-later
      short_summary: Advanced Trivial File Transfer Protocol (ATFTP) - TFTP server
      supplier: 'Organization: Broadcom, Inc.'
