#!/bin/sh

dev_ram=/dev/ram1
dir_needwrite=/fake/needwrite
directory_list="var/log tmp "

echo -e "Creating ext2fs on $dev_ram ...              \n"
/sbin/mke2fs -m 0 -i 1024 -q $dev_ram > /dev/null 2>&1


echo -e "Mounting ramdisk on $dir_needwrite ...         \n"
mount -n $dev_ram $dir_needwrite

for directory in $directory_list
do
mkdir -p $dir_needwrite/$directory
echo -e "Created directory.. $directory on $dir_ramdisk \n"
done


