sources:
- archive: kapacitor-1.8.5.tar.gz
  archive_type: upstream
  version: 1.8.5
  name: kapacitor-1.8.5
  url: https://github.com/influxdata/kapacitor/archive/refs/tags/v1.8.5.tar.gz
  repo_url: https://github.com/influxdata/kapacitor.git
  commit_id: 1632cc16b34166a05dd52cd9dc718ad68cceab23
  skip_list: []
  missing: []
  archive_sha512sum: de72996bc126f21b9c40f62c7c52a45a6daf6bbcc897a6c5fbf21abd10a5eba2652710eb14b5e164f397d2119896d68f8763948978c1388be4cdc45a1e37fd22
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Kapacitor is an Open source framework for processing,
        monitoring, and alerting on time series data. '
      home_page: https://www.influxdata.com/time-series-platform/kapacitor
      license_concluded: MIT
      license_declared: MIT
      short_summary: Open source framework for processing, monitoring, and alerting
        on time series data
      supplier: 'Organization: Broadcom, Inc.'
- archive: kapacitor-libflux-vendor-0.194.5.tar.gz
  archive_sha512sum: ed0ff9dab6cd6b851184821603ce107b15ab28a4bd1488e7d42ab8dbd406169c47794d62960e3c940596d5c5db3b5de837cb0be6f89d14e01962882aa412b6ea
  skip_validation: true
  spdx:
    package:
      detailed_description: kapacitor dependencies stored as cargo registry
      home_page: https://packages.broadcom.com/photon/photon_sources/1.0/
      license_concluded: Zlib AND blessing AND CC-BY-3.0 AND (Apache-2.0 OR MIT) AND
        Apache-2.0 WITH LLVM-exception AND BSL-1.0 AND CC0-1.0 AND (Apache-2.0 WITH
        LLVM-exception OR Apache-2.0 OR MIT) AND GPL-3.0-only AND MIT-testregex AND
        GPL-2.0-only AND Unlicense AND MIT AND BSD-3-Clause AND Unicode-DFS-2016 AND
        (MIT OR Apache-2.0) AND MPL-2.0 AND (Apache-2.0 OR MIT) AND (MIT OR Unlicense)
        AND OFL-1.1 AND Apache-2.0 AND (MIT OR Apache-2.0)
      license_declared: Zlib AND blessing AND CC-BY-3.0 AND (Apache-2.0 OR MIT) AND
        Apache-2.0 WITH LLVM-exception AND BSL-1.0 AND CC0-1.0 AND (Apache-2.0 WITH
        LLVM-exception OR Apache-2.0 OR MIT) AND GPL-3.0-only AND MIT-testregex AND
        GPL-2.0-only AND Unlicense AND MIT AND BSD-3-Clause AND Unicode-DFS-2016 AND
        (MIT OR Apache-2.0) AND MPL-2.0 AND (Apache-2.0 OR MIT) AND (MIT OR Unlicense)
        AND OFL-1.1 AND Apache-2.0 AND (MIT OR Apache-2.0)
      short_summary: kapacitor dependencies stored as cargo registry
      supplier: 'Organization: Broadcom, Inc.'
