sources:

- archive: postgres-REL_15_19.tar.gz
  archive_sha512sum: e88936cc56b93addae5628d6e8d55db808931d5efc7f9c1c165183a47080c7a69a36c8ad4681fd5c3be016c1a354ef8aad6678004058e16d3014b80dc1b4deb8
  archive_type: upstream
  name: postgres-REL_15_19
  version: '15.19'
  url: https://github.com/postgres/postgres/archive/refs/tags/REL_15_19.tar.gz
  repo_url: https://github.com/postgres/postgres.git
  commit_id: 2ff1375b5dd8bf09d8cb0e795974528180fd75ca
  missing: []
  spdx:
    package:
      detailed_description: PostgreSQL is an advanced Object-Relational database management system (DBMS). The base postgresql package contains the client programs that you'll need to access a PostgreSQL DBMS server. These client programs can be located on the same machine as the PostgreSQL server, or on a remote machine that accesses a PostgreSQL server over a network connection. The PostgreSQL server can be found in the postgresql-server sub-package.  If you want to manipulate a PostgreSQL database on a local or remote PostgreSQL server, you need this package. You also need to install this package if you're installing the postgresql-server package.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND BSD-3-Clause AND NCSA AND Spencer-99 AND FSFUL AND GPL-3.0-or-later WITH Bison-exception-2.2 AND MIT AND BSD-2-Clause AND Apache-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND PostgreSQL AND TCL AND BSL-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-1.0-or-later AND ISC AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND BSD-2-Clause-Views AND X11 AND Apache-2.0 WITH LLVM-exception
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND BSD-3-Clause AND NCSA AND Spencer-99 AND FSFUL AND GPL-3.0-or-later WITH Bison-exception-2.2 AND MIT AND BSD-2-Clause AND Apache-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND PostgreSQL AND TCL AND BSL-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-1.0-or-later AND ISC AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND BSD-2-Clause-Views AND X11 AND Apache-2.0 WITH LLVM-exception
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'

- archive: postgres-REL_16_15.tar.gz
  archive_sha512sum: 25119b44c4e1b8642f13b971d8a4be1b119f75a581af3da8b6a4369d03ccc7522b5bb96e9c06ce83ac9914b312264fcedd3b8f8c585743aad3ec630a0eb1addf
  name: postgres-REL_16_15
  version: '16.15'
  url: https://github.com/postgres/postgres/archive/refs/tags/REL_16_15.tar.gz
  repo_url: https://github.com/postgres/postgres.git
  commit_id: 7d3e000c5961a544302072058a1184e9a588837b
  archive_type: upstream
  missing: []
  spdx:
    package:
      detailed_description: PostgreSQL is an advanced Object-Relational database management system (DBMS). The base postgresql package contains the client programs that you'll need to access a PostgreSQL DBMS server. These client programs can be located on the same machine as the PostgreSQL server, or on a remote machine that accesses a PostgreSQL server over a network connection. The PostgreSQL server can be found in the postgresql-server sub-package.  If you want to manipulate a PostgreSQL database on a local or remote PostgreSQL server, you need this package. You also need to install this package if you're installing the postgresql-server package.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Apache-2.0 WITH LLVM-exception AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND ISC AND Apache-2.0 AND TCL AND BSD-3-Clause AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND BSD-2-Clause AND FSFUL AND BSD-4-Clause-UC AND GPL-1.0-or-later AND MIT AND X11 AND GPL-3.0-or-later WITH Bison-exception-2.2 AND NCSA AND BSL-1.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND Spencer-99 AND PostgreSQL
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Apache-2.0 WITH LLVM-exception AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND ISC AND Apache-2.0 AND TCL AND BSD-3-Clause AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND BSD-2-Clause AND FSFUL AND BSD-4-Clause-UC AND GPL-1.0-or-later AND MIT AND X11 AND GPL-3.0-or-later WITH Bison-exception-2.2 AND NCSA AND BSL-1.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND Spencer-99 AND PostgreSQL
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'

- archive: postgres-REL_17_11.tar.gz
  archive_sha512sum: 8b5cf7463eb4bfeb23278e51391f57ab87fbad2e3e989759938b5adf6500013af5ce9ede890fd1ba5878902c31fef574aa0c8bdb672cc0a2031cc1a5e3bb8032
  archive_type: upstream
  name: postgres-REL_17_11
  version: '17.11'
  url: https://github.com/postgres/postgres/archive/refs/tags/REL_17_11.tar.gz
  repo_url: https://github.com/postgres/postgres.git
  commit_id: 083ac033419f690758508e08c1736089384bbee8
  missing: []
  spdx:
    package:
      detailed_description: PostgreSQL is an advanced Object-Relational database management system (DBMS). The base postgresql package contains the client programs that you'll need to access a PostgreSQL DBMS server. These client programs can be located on the same machine as the PostgreSQL server, or on a remote machine that accesses a PostgreSQL server over a network connection. The PostgreSQL server can be found in the postgresql-server sub-package.  If you want to manipulate a PostgreSQL database on a local or remote PostgreSQL server, you need this package. You also need to install this package if you're installing the postgresql-server package.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Apache-2.0 WITH LLVM-exception AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND ISC AND Apache-2.0 AND TCL AND BSD-3-Clause AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND BSD-2-Clause AND FSFUL AND BSD-4-Clause-UC AND GPL-1.0-or-later AND MIT AND X11 AND GPL-3.0-or-later WITH Bison-exception-2.2 AND NCSA AND BSL-1.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND Spencer-99 AND PostgreSQL
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Apache-2.0 WITH LLVM-exception AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND ISC AND Apache-2.0 AND TCL AND BSD-3-Clause AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND BSD-2-Clause AND FSFUL AND BSD-4-Clause-UC AND GPL-1.0-or-later AND MIT AND X11 AND GPL-3.0-or-later WITH Bison-exception-2.2 AND NCSA AND BSL-1.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND Spencer-99 AND PostgreSQL
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'

- archive: postgres-REL_18_6.tar.gz
  archive_sha512sum: 0d2df0f13e1d5b8189f7cbfff169e5a0bd18006e147b5ff2bfbff9ea248b551b22459f1af3d4016379646fd6bc8e242fe959e80e1fa478bc81a030912305f848
  archive_type: upstream
  name: postgres-REL_18_6
  version: '18.6'
  url: https://github.com/postgres/postgres/archive/refs/tags/REL_18_6.tar.gz
  repo_url: https://github.com/postgres/postgres.git
  commit_id: 724edf9bde9d356724ad384a2e196edc3c9f80f7
  spdx:
    package:
      detailed_description: PostgreSQL is an advanced Object-Relational database management system (DBMS). The base postgresql package contains the client programs that you'll need to access a PostgreSQL DBMS server. These client programs can be located on the same machine as the PostgreSQL server, or on a remote machine that accesses a PostgreSQL server over a network connection. The PostgreSQL server can be found in the postgresql-server sub-package.  If you want to manipulate a PostgreSQL database on a local or remote PostgreSQL server, you need this package. You also need to install this package if you're installing the postgresql-server package.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause-UC AND BSL-1.0 AND FSFUL AND GPL-1.0-or-later AND GPL-2.0-or-later AND GPL-3.0-or-later AND ISC AND MIT AND NCSA AND PostgreSQL AND Spencer-99 AND TCL AND X11
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause-UC AND BSL-1.0 AND FSFUL AND GPL-1.0-or-later AND GPL-2.0-or-later AND GPL-3.0-or-later AND ISC AND MIT AND NCSA AND PostgreSQL AND Spencer-99 AND TCL AND X11
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'
