sources:
- archive: postgresql-10.23.tar.bz2
  skip_validation: true
  archive_sha512sum: 9fd031cad0c3caacae105215167abd5dc4fdd15dea77a12cb0a977fab6e245e3fda163f202cc7786e50c69e5c3f180d32676a3b18ea30a9a14f0bcab56aa19dd
  name: postgresql-10.23
  version: 10.23
  url: http://ftp.postgresql.org/pub/source/v10.23/postgresql-10.23.tar.bz2
  repo_url: https://github.com/postgres/postgres.git
  commit_id: 02991e79f8f58bc208f05dcc8af0c62dbe0a6ea4
  missing: []
  spdx:
    package:
      detailed_description: PostgreSQL is an object-relational database management
        system.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND FSFUL AND MIT AND GPL-3.0-or-later WITH
        Bison-exception-2.2 AND PostgreSQL AND Spencer-99 AND BSD-2-Clause AND GPL-1.0-or-later
        AND Martin-Birgmeier AND ISC AND GPL-3.0-or-later WITH Autoconf-exception-macro
        AND X11 AND TCL AND BSD-2-Clause-Views AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND BSD-3-Clause
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND FSFUL AND MIT AND GPL-3.0-or-later WITH
        Bison-exception-2.2 AND PostgreSQL AND Spencer-99 AND BSD-2-Clause AND GPL-1.0-or-later
        AND Martin-Birgmeier AND ISC AND GPL-3.0-or-later WITH Autoconf-exception-macro
        AND X11 AND TCL AND BSD-2-Clause-Views AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND BSD-3-Clause
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'
- archive: postgresql-13.22.tar.bz2
  skip_validation: true
  archive_sha512sum: 0f578526aad852285de001369dd1c8308f03479c8f4f6c1a1d066b6b77103e340df95b9ab41df3f959c4e17d4fb0c0441b02a04d3e6c01cfcd40a2632c3ac7eb
  name: postgresql-13.22
  version: 13.22
  url: http://ftp.postgresql.org/pub/source/v13.22/postgresql-13.22.tar.bz2
  repo_url: https://github.com/postgres/postgres.git
  commit_id: af2dbe860b638dbd45604270d103e0a59dc0a372
  missing: []
  spdx:
    package:
      detailed_description: PostgreSQL is an advanced Object-Relational database management
        system (DBMS). The base postgresql package contains the client programs that
        you'll need to access a PostgreSQL DBMS server. These client programs can
        be located on the same machine as the PostgreSQL server, or on a remote machine
        that accesses a PostgreSQL server over a network connection. The PostgreSQL
        server can be found in the postgresql13-server sub-package.  If you want to
        manipulate a PostgreSQL database on a local or remote PostgreSQL server, you
        need this package. You also need to install this package if you're installing
        the postgresql13-server package.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND MIT AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND BSD-3-Clause AND GPL-1.0-or-later
        AND BSL-1.0 AND Spencer-99 AND Martin-Birgmeier AND GPL-3.0-or-later WITH
        Bison-exception-2.2 AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND Apache-2.0 WITH LLVM-exception AND X11
        AND PostgreSQL AND TCL AND BSD-2-Clause-Views AND NCSA AND BSD-2-Clause AND
        Apache-2.0 AND FSFUL AND ISC
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND MIT AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND BSD-3-Clause AND GPL-1.0-or-later
        AND BSL-1.0 AND Spencer-99 AND Martin-Birgmeier AND GPL-3.0-or-later WITH
        Bison-exception-2.2 AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND Apache-2.0 WITH LLVM-exception AND X11
        AND PostgreSQL AND TCL AND BSD-2-Clause-Views AND NCSA AND BSD-2-Clause AND
        Apache-2.0 AND FSFUL AND ISC
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'
- archive: postgresql-14.19.tar.bz2
  skip_validation: true
  archive_sha512sum: 8f7f49c439b954fc1091c32d857d16e25db0b6f3687d44a6a2360a6c72002545eb2f9d09f2b460aeed3371aeabbe7abf599d92ff60baa2d1e4882a106ad14139
  name: postgresql-14.19
  version: 14.19
  url: http://ftp.postgresql.org/pub/source/v14.19/postgresql-14.19.tar.bz2
  repo_url: https://github.com/postgres/postgres.git
  commit_id: 4e9da016ade3e75400f6fdc22ed1fed7fdd32f7a
  missing: []
  spdx:
    package:
      detailed_description: PostgreSQL is an advanced Object-Relational database management
        system (DBMS). The base postgresql package contains the client programs that
        you'll need to access a PostgreSQL DBMS server. These client programs can
        be located on the same machine as the PostgreSQL server, or on a remote machine
        that accesses a PostgreSQL server over a network connection. The PostgreSQL
        server can be found in the postgresql-server sub-package.  If you want to
        manipulate a PostgreSQL database on a local or remote PostgreSQL server, you
        need this package. You also need to install this package if you're installing
        the postgresql-server package.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND BSL-1.0 AND Spencer-99
        AND Martin-Birgmeier AND GPL-1.0-or-later AND BSD-2-Clause AND Apache-2.0
        WITH LLVM-exception AND Apache-2.0 AND BSD-3-Clause AND PostgreSQL AND TCL
        AND ISC AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND X11 AND MIT AND NCSA AND BSD-2-Clause-Views
        AND FSFUL AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later
        WITH Bison-exception-2.2
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND BSL-1.0 AND Spencer-99
        AND Martin-Birgmeier AND GPL-1.0-or-later AND BSD-2-Clause AND Apache-2.0
        WITH LLVM-exception AND Apache-2.0 AND BSD-3-Clause AND PostgreSQL AND TCL
        AND ISC AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND X11 AND MIT AND NCSA AND BSD-2-Clause-Views
        AND FSFUL AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later
        WITH Bison-exception-2.2
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'
- archive: postgresql-15.14.tar.bz2
  skip_validation: true
  archive_sha512sum: 6bef254af257eb79a6b4ec1fd09a996351848561a493e529b7e44b053b368753d56cd76de74b07fff6d637606773963e83e4c3bb321682774b12d24dfa1ca8f4
  name: postgresql-15.14
  version: 15.14
  url: http://ftp.postgresql.org/pub/source/v15.14/postgresql-15.14.tar.bz2
  repo_url: https://github.com/postgres/postgres.git
  commit_id: 0ab43b548237b3791261480d6a023f6b95b53942
  missing: []
  spdx:
    package:
      detailed_description: PostgreSQL is an advanced Object-Relational database management
        system (DBMS). The base postgresql package contains the client programs that
        you'll need to access a PostgreSQL DBMS server. These client programs can
        be located on the same machine as the PostgreSQL server, or on a remote machine
        that accesses a PostgreSQL server over a network connection. The PostgreSQL
        server can be found in the postgresql-server sub-package.  If you want to
        manipulate a PostgreSQL database on a local or remote PostgreSQL server, you
        need this package. You also need to install this package if you're installing
        the postgresql-server package.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND BSD-3-Clause
        AND NCSA AND Spencer-99 AND FSFUL AND GPL-3.0-or-later WITH Bison-exception-2.2
        AND MIT AND BSD-2-Clause AND Apache-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND PostgreSQL AND TCL AND BSL-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-2.0
        AND GPL-1.0-or-later AND ISC AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND BSD-2-Clause-Views AND X11 AND Apache-2.0 WITH LLVM-exception
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND BSD-3-Clause AND
        NCSA AND Spencer-99 AND FSFUL AND GPL-3.0-or-later WITH Bison-exception-2.2
        AND MIT AND BSD-2-Clause AND Apache-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND PostgreSQL AND TCL AND BSL-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-2.0
        AND GPL-1.0-or-later AND ISC AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND BSD-2-Clause-Views AND X11 AND Apache-2.0 WITH LLVM-exception
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'
- archive: postgresql-16.10.tar.bz2
  skip_validation: true
  archive_sha512sum: b6de80d522f863b0d9dd8c2bf4f71bea309bd07586859e309a9821e7f6fd5839557dc396351e7b61aebf492bf8c8a053a324f059a1dee621ac1a6d5e8eccea22
  name: postgresql-16.10
  version: 16.10
  url: http://ftp.postgresql.org/pub/source/v16.10/postgresql-16.10.tar.bz2
  repo_url: https://github.com/postgres/postgres.git
  commit_id: c13dd7d50f21268dc64b4b3edbce31993985ab12
  missing: []
  spdx:
    package:
      detailed_description: PostgreSQL is an advanced Object-Relational database management
        system (DBMS). The base postgresql package contains the client programs that
        you'll need to access a PostgreSQL DBMS server. These client programs can
        be located on the same machine as the PostgreSQL server, or on a remote machine
        that accesses a PostgreSQL server over a network connection. The PostgreSQL
        server can be found in the postgresql-server sub-package.  If you want to
        manipulate a PostgreSQL database on a local or remote PostgreSQL server, you
        need this package. You also need to install this package if you're installing
        the postgresql-server package.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Apache-2.0 WITH
        LLVM-exception AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND
        ISC AND Apache-2.0 AND TCL AND BSD-3-Clause AND GPL-3.0-or-later WITH Autoconf-exception-2.0
        AND BSD-2-Clause AND FSFUL AND BSD-4-Clause-UC AND GPL-1.0-or-later AND MIT
        AND X11 AND GPL-3.0-or-later WITH Bison-exception-2.2 AND NCSA AND BSL-1.0
        AND GPL-2.0-or-later WITH Autoconf-exception-generic AND Spencer-99 AND PostgreSQL
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Apache-2.0 WITH
        LLVM-exception AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND
        ISC AND Apache-2.0 AND TCL AND BSD-3-Clause AND GPL-3.0-or-later WITH Autoconf-exception-2.0
        AND BSD-2-Clause AND FSFUL AND BSD-4-Clause-UC AND GPL-1.0-or-later AND MIT
        AND X11 AND GPL-3.0-or-later WITH Bison-exception-2.2 AND NCSA AND BSL-1.0
        AND GPL-2.0-or-later WITH Autoconf-exception-generic AND Spencer-99 AND PostgreSQL
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'
