sources:
- archive: ruamel.yaml-0.19.1.tar.gz
  archive_sha512sum: 726e9348b36bf78cf80c72154d1652ef6f128bcb28b53a3814543a7568e9d079d35be191608691bf6fddc98996cf621b8e77b118510627806aab20b029bfe718
  skip_validation: true
  spdx:
    package:
      detailed_description: 'ruamel.yaml is a YAML parser/emitter that supports roundtrip
        preservation of comments, seq/map flow style, and map key order '
      home_page: https://pypi.org/project/ruamel.yaml
      license_concluded: MIT
      license_declared: MIT
      short_summary: YAML parser/emitter.
      supplier: 'Organization: Broadcom, Inc.'
