sources:
- archive: tzdata2026c.tar.gz
  archive_sha512sum: e0b4b7044b66fbc27bc21d13d18063abcdf78ab58d5ba5fd64bd1a88d86e9d495f45add4d8e65bb6c40249f9c94ca29b72c8ebba8d0e4c468f2965ac77932ef0
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Sources for time zone and daylight saving time data '
      home_page: http://www.iana.org/time-zones
      license_concluded: BSD-3-Clause
      license_declared: BSD-3-Clause
      short_summary: Time zone data
      supplier: 'Organization: Broadcom, Inc.'
