sources:
- archive: Net-SSLeay-1.96.tar.gz
  archive_sha512sum: c8218159b9392aaebc996e4db51e0d3799d395289cb84d7ce4de807698ebed178b9b129b1e6e6a379c1f8247ee85f770e3266ea1f865378e559b37d75748665c
  archive_type: upstream
  name: Net-SSLeay-1.96
  version: 1.96
  url: https://cpan.metacpan.org/authors/id/C/CH/CHRISN/Net-SSLeay-1.96.tar.gz
  repo_url: https://github.com/radiator-software/p5-net-ssleay.git
  commit_id: 006e139250692a04e2c66c122b572d3833199444
  skip_validation: false
  skip_list: ['MANIFEST']
  missing: ['.appveyor.yml', '.git', '.github', '.gitignore', 'MANIFEST.SKIP', 'README.md', 'TODO', 'META.json', 'META.yml', 'Credits', 'inc', 'Test', 'examples', 'helper_script', 'README.OSX', 'README.VMS', 'README.Win32', 't', 'xt']
  spdx:
    package:
      detailed_description: 'Net::SSLeay module contains perl bindings to openssl
        (http://www.openssl.org) library.  Net::SSLeay module basically comprise of:
        * High level functions for accessing web servers (by using HTTP/HTTPS) * Low
        level API (mostly mapped 1:1 to openssl''s C functions) * Convenience functions
        (related to low level API but with more perl friendly interface) * There is
        also a related module called Net::SSLeay::Handle included in this distribution
        that you might want to use instead. It has its own pod documentation. '
      home_page: https://metacpan.org/pod/Net::SSLeay
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Artistic-2.0
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Artistic-2.0
      short_summary: Perl extension for using OpenSSL
      supplier: 'Organization: Broadcom, Inc.'
