sources:
- archive: typing_extensions-4.15.0.tar.gz
  archive_sha512sum: 7ad50638ddbb575a929ffde20ac7b421970abacb311ce1b10b4bbc3b331318784863a8f67b44531327a69be08f5ab7ade65cbd1b5cd35af69fde491d800c8074
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Typing defines a standard notation for Python function
        and variable type annotations. The notation can be used for documenting code
        in a concise, standard format, and it has been designed to also be used by
        static and runtime type checkers, static analyzers, IDEs and other tools.'
      home_page: https://pypi.org/project/typing-extensions
      license_concluded: Python-2.0
      license_declared: Python-2.0
      short_summary: Backported and Experimental Type Hints for Python 3.7+
      supplier: 'Organization: Broadcom, Inc.'
