sources:
- archive: setools-4.5.1.tar.bz2
  archive_sha512sum: 1045c223423fcb056ffbc2f93c4dc0ccc6ae078ce7d2acbe3a3c65de19440fe801b5b9f71038cde62bf9851f52d868c845aafbe33691ee531cf9854217e061d8
  archive_type: upstream
  skip_validation: false
  name: setools
  version: "4.5.1"
  url: https://github.com/SELinuxProject/setools/releases/download/4.5.1/setools-4.5.1.tar.bz2
  repo_url: https://github.com/SELinuxProject/setools
  commit_id: 659ec47aba0126e3a198362ed1659bf600c067eb
  missing: []
  spdx:
    package:
      detailed_description: 'Policy analysis tools for SELinux '
      home_page: https://github.com/SELinuxProject/selinux/wiki
      license_concluded: GPL-2.0-only AND LGPL-2.1-only AND LGPL-2.0-or-later AND
        GPL-1.0-or-later AND LGPL-2.1-or-later AND GPL-2.0-or-later
      license_declared: GPL-2.0-only AND LGPL-2.1-only AND LGPL-2.0-or-later AND GPL-1.0-or-later
        AND LGPL-2.1-or-later AND GPL-2.0-or-later
      short_summary: Policy analysis tools for SELinux
      supplier: 'Organization: Broadcom, Inc.'
