sources:
- archive: apr-util-1.6.3.tar.gz
  archive_sha512sum: 25f078413dc552b3391845b3dc1da72773efe181634deb2f88a9c72a1a49c82883113704bf97db8327012ccafb84a68370267925e3c7cc092ed82fc33fd7954e
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The Apache Portable Runtime Utility Library. '
      home_page: https://apr.apache.org
      license_concluded: OLDAP-2.8 AND RSA-MD AND Sleepycat AND Apache-2.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND BSD-4.3RENO AND MIT AND FSFUL AND
        NTP AND Beerware AND CC0-1.0
      license_declared: OLDAP-2.8 AND RSA-MD AND Sleepycat AND Apache-2.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND BSD-4.3RENO AND MIT AND FSFUL AND
        NTP AND Beerware AND CC0-1.0
      short_summary: The Apache Portable Runtime Utility Library
      supplier: 'Organization: Broadcom, Inc.'
