sources:
- archive: nettle-3.10.2.tar.gz
  archive_type: upstream
  archive_sha512sum: bf37ddd7dca8e78488da2a5286dcf16761d527d620572b42f2ad27bb8ee8c12999d92b0272e06f53766e7155a3f4a1ab7ad9c4b1c3caec47c031878b6b1772fb
  name: nettle-3.10.2
  version: 3.10.2
  url: https://ftp.gnu.org/gnu/nettle/nettle-3.10.2.tar.gz
  repo_url: https://git.lysator.liu.se/nettle/nettle
  commit_id: d9e983c664772f8cbacba9fa084bc079978e3c98
  missing: ['shake.awk', '.gitlab-ci.yml', 'stamp-h.in', 'sha1-compress.nlms', 'index.html', 'aes-test.out', 'desdata.stamp', 'list-obj-sizes.awk', 'test-rules.stamp', '.gdbinit', 'config.h.in', 'nettle.info', '.gitignore', '.c-style', 'misc', 'sha1-f2.nlms', 'sha1-f1-noexp.nlms', 'nettle.html', '.gitattributes', 'configure', 'keymap.h', 'yarrow-test.out', 'eccparams.c', 'nettle.pdf', 'rotors.h']
  skip_validation: false
  license_manual_review:
  - file_paths:
    - nettle-3.10.2/nettle.pdf
    sha256sum: 6fb9ba6d29a0dacc065e004a3cdbfbf635cea54542283d2ed3742a082b608e27
    # Public domain, no license
    spdx_exp:
  spdx:
    package:
      detailed_description: 'GNettle is a cryptographic library that is designed to
        fit easily in more or less any context: In crypto toolkits for object-oriented
        languages (C++, Python, Pike, ...), in applications like LSH or GNUPG, or
        even in kernel space. '
      home_page: http://www.lysator.liu.se/~nisse/nettle
      license_concluded: LGPL-2.1-or-later AND MIT AND FSFUL AND LGPL-2.0-or-later
        AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-2.0-only
        AND FSFULLR AND GPL-3.0-or-later WITH Texinfo-exception AND LGPL-2.0-only
        AND LGPL-3.0-only AND X11 AND GPL-1.0-or-later AND (LGPL-3.0-or-later OR GPL-2.0-or-later)
        AND GPL-2.0-or-later AND GPL-3.0-only AND LGPL-3.0-or-later
      license_declared: LGPL-2.1-or-later AND MIT AND FSFUL AND LGPL-2.0-or-later
        AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-2.0-only
        AND FSFULLR AND GPL-3.0-or-later WITH Texinfo-exception AND LGPL-2.0-only
        AND LGPL-3.0-only AND X11 AND GPL-1.0-or-later AND (LGPL-3.0-or-later OR GPL-2.0-or-later)
        AND GPL-2.0-or-later AND GPL-3.0-only AND LGPL-3.0-or-later
      short_summary: Low level cryptographic libraries
      supplier: 'Organization: Broadcom, Inc.'
