sources:
- archive: kubernetes-dns-1.26.8.tar.gz
  archive_sha512sum: 985bd2d37606b3c0cccfbd56dc525321f0a13a4872c472e8cab440f8f359d839e6adc60e054ef7673f5e2d869748e1f8b8eb9d8b82ac609a48dcc2e9ac352dcd
  archive_type: upstream
  commit_id: 9aa70b8f97dc751445a7370960cd45e411506003
  missing: []
  skip_list: []
  skip_validation: false
  name: dns-1.26.8
  version: '1.26.8'
  repo_url: https://github.com/kubernetes/dns
  url: https://github.com/kubernetes/dns/archive/refs/tags/1.26.8.tar.gz
  spdx:
    package:
      detailed_description: Kubernetes DNS is a name lookup service for kubernetes pods.
      home_page: https://github.com/kubernetes/dns/archive/1.22.20.tar.gz
      license_concluded: (Apache-2.0 OR BSD-3-Clause) AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT
      license_declared: (Apache-2.0 OR BSD-3-Clause) AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT
      short_summary: Kubernetes DNS
      supplier: 'Organization: Broadcom, Inc.'
