sources:
- archive: jq-1.8.1.tar.gz
  archive_type: upstream
  archive_sha512sum: 7eece5744008710d6098d2b945b52250184e981ed3b7a66d4e8e1d0484539a281031900fa9dda7e1004a3fcfa8b5be39814d499c66c34707b35962a365d24fde
  name: jq-jq-1.8.1
  version: 1.8.1
  url: https://github.com/jqlang/jq/archive/refs/tags/jq-1.8.1.tar.gz
  repo_url: https://github.com/jqlang/jq.git
  commit_id: 4467af7068b1bcd7f882defff6e7ea674c5357f4
  missing: ['.gitattributes', '.gitignore']
  skip_validation: false
  spdx:
    package:
      detailed_description: 'jq is a lightweight and flexible command-line JSON processor. '
      home_page: https://github.com/stedolan/jq
      license_concluded: GPL-3.0-or-later WITH Libtool-exception AND FSFULLR AND FSFULLRWD
        AND MIT AND X11 AND BSD-2-Clause AND GPL-3.0-or-later WITH Bison-exception-2.2
        AND BSD-3-Clause AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        GPL-3.0-or-later AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND dtoa AND CC0-1.0 AND FSFUL AND FSFAP AND GPL-2.0-or-later WITH Libtool-exception
        AND CC-BY-3.0
      license_declared: GPL-3.0-or-later WITH Libtool-exception AND FSFULLR AND FSFULLRWD
        AND MIT AND X11 AND BSD-2-Clause AND GPL-3.0-or-later WITH Bison-exception-2.2
        AND BSD-3-Clause AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        GPL-3.0-or-later AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND dtoa AND CC0-1.0 AND FSFUL AND FSFAP AND GPL-2.0-or-later WITH Libtool-exception
        AND CC-BY-3.0
      short_summary: jq is a lightweight and flexible command-line JSON processor.
      supplier: 'Organization: Broadcom, Inc.'
