sources:
- archive: async-http-0.89.0.gem
  archive_sha512sum: a26cd80f1db63712ea12523a9390e0d6a47078d707fb277c97a96316dee906c73b743cd5efdcb9859f0a14bf9ac252d0dd3bfa6c30a9750e3b29495f15b44ec9
  skip_validation: true
  spdx:
    package:
      detailed_description: 'An asynchronous client and server implementation of HTTP/1.0,
        HTTP/1.1 and HTTP/2 including TLS. Support for streaming requests and responses.
        Built on top of async and async-io. falcon provides a rack-compatible server. '
      home_page: https://rubygems.org/gems/async-http/versions/0.89.0
      license_concluded: MIT
      license_declared: MIT
      short_summary: A HTTP client and server library.
      supplier: 'Organization: Broadcom, Inc.'
