sources:
- archive: dotnet-runtime-8.0.17-linux-x64.tar.gz
  archive_sha512sum: d573388bd64deb12e6464fc6a4240f6ed7cd1c6b17370096304b8ac2d800318c3af36f8185a3b780afe52b041824deef9d377a96a6baed759c8283829054649a
  skip_validation: true
  spdx:
    package:
      detailed_description: '.NET Core is a development platform that you can use
        to build command-line applications, microservices and modern websites. '
      home_page: https://github.com/dotnet/core
      license_concluded: BSD-3-Clause AND Zlib AND BSD-4-Clause-UC AND CC0-1.0 AND
        W3C-20150513 AND HP-1989 AND Unicode-3.0 AND NCSA AND LZMA-SDK-9.22 AND Apache-2.0
        AND MIT AND BSD-2-Clause
      license_declared: BSD-3-Clause AND Zlib AND BSD-4-Clause-UC AND CC0-1.0 AND
        W3C-20150513 AND HP-1989 AND Unicode-3.0 AND NCSA AND LZMA-SDK-9.22 AND Apache-2.0
        AND MIT AND BSD-2-Clause
      short_summary: Microsoft .NET Core Runtime
      supplier: 'Organization: Broadcom, Inc.'
