sources:
- archive: dotnet-runtime-8.0.14-linux-x64.tar.gz
  archive_sha512sum: 5b7c7300dd30084650a2265b6618f366f099dff2b292482e5e05f14f3a0b0850c658ecf383683e1dce4e753a616fd2e3c169c1734a679afcc4c0cad488b9f8a0
  skip_validation: true
  spdx:
    package:
      detailed_description: '.NET Core is a development platform that you can use
        to build command-line applications, microservices and modern websites. '
      home_page: https://github.com/dotnet/core
      license_concluded: BSD-3-Clause AND Zlib AND BSD-4-Clause-UC AND CC0-1.0 AND
        W3C-20150513 AND HP-1989 AND Unicode-3.0 AND NCSA AND LZMA-SDK-9.22 AND Apache-2.0
        AND MIT AND BSD-2-Clause
      license_declared: BSD-3-Clause AND Zlib AND BSD-4-Clause-UC AND CC0-1.0 AND
        W3C-20150513 AND HP-1989 AND Unicode-3.0 AND NCSA AND LZMA-SDK-9.22 AND Apache-2.0
        AND MIT AND BSD-2-Clause
      short_summary: Microsoft .NET Core Runtime
      supplier: 'Organization: Broadcom, Inc.'
