sources:
- archive: Vulkan-Tools-1.4.358.tar.gz
  archive_type: upstream
  archive_sha512sum: b3cfce0f700f6ad2e5fc601270b1f4bd8dec7a7cc57c017dcf0218a161229782fd9ceddd6426956c5009538caebf5e9c7905d5969fc1e32f6d2d23dfc91edf7d
  name: "Vulkan-Tools-1.4.358"
  version: 1.4.358
  url: https://github.com/KhronosGroup/Vulkan-Tools/archive/refs/tags/v1.4.358.tar.gz
  repo_url: https://github.com/KhronosGroup/Vulkan-Tools.git
  commit_id: 2ca98085c06deeec789fb1c18e95f66803bdaddb
  skip_list: []
  missing: []
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Vulkan tools '
      home_page: https://github.com/KhronosGroup/Vulkan-Tools
      license_concluded: Apache-2.0 AND CC-BY-ND-4.0 AND BSD-3-Clause AND MIT
      license_declared: Apache-2.0 AND CC-BY-ND-4.0 AND BSD-3-Clause AND MIT
      short_summary: Vulkan tools
      supplier: 'Organization: Broadcom, Inc.'
