sources:
- archive: Mako-1.2.4.tar.gz
  archive_type: upstream
  version: 1.2.4
  name: mako-rel_1_2_4
  url: https://github.com/sqlalchemy/mako/archive/refs/tags/rel_1_2_4.tar.gz
  repo_url: https://github.com/sqlalchemy/mako.git
  commit_id: 2fd5daa24a09fc6a52f60bdb9402faaf91f2e7a1
  skip_list: []
  missing: []
  archive_sha512sum: 7d5c6bfe342ce6d7cb7cf78a507df10b764166faac90dc5e22d1f2e95215c5d4117084ac8f0807f74aca4eb357798565eee5efaadcbb3c586a327d53347c87d0
  skip_validation: false
  spdx:
    package:
      detailed_description: "A super-fast templating language that borrows the best\
        \ ideas from the existing templating languages. Mako is a template library\
        \ written in Python. It provides a familiar, non-XML syntax which compiles\
        \ into Python modules for maximum performance. Mako\u2019s syntax and API\
        \ borrows from the best ideas of many others, including Django templates,\
        \ Cheetah, Myghty, and Genshi. "
      home_page: https://www.makotemplates.org
      license_concluded: BSD-3-Clause AND Python-2.0 AND MIT
      license_declared: BSD-3-Clause AND Python-2.0 AND MIT
      short_summary: Python templating language
      supplier: 'Organization: Broadcom, Inc.'
