sources:
- archive: protocol-hpack-1.5.1.gem
  archive_sha512sum: 6dab3e56b3c6aacc5303262644bdbe568d391abc9a12027483a5a921c6f4dd36b820c6d2fefd801c149b71373d98b29b0ca8bcc1425706c378cd710ec5648876
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Provides a compressor and decompressor for HTTP 2.0 headers,
        HPACK, as defined by RFC7541. '
      home_page: https://rubygems.org/gems/protocol-hpack/versions/1.5.1
      license_concluded: MIT
      license_declared: MIT
      short_summary: A compresssor and decompressor for HTTP 2.0 HPACK.
      supplier: 'Organization: Broadcom, Inc.'
