sources:
- archive: Try-Tiny-0.32.tar.gz
  archive_sha512sum: 18610525e1b754760f41a5d9a836a4e78c22ba1b008f7ac16b2796916ef688b03c7cc3002cfc61b274492455a906e75dbe0e2a06ead4e08b33e1c6a0a8569c4e
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This module provides bare bones try/catch/finally statements
        that are designed to minimize common mistakes with eval blocks, and NOTHING
        else.  This is unlike TryCatch which provides a nice syntax and avoids adding
        another call stack layer, and supports calling return from the try block to
        return from the parent subroutine. These extra features come at a cost of
        a few dependencies, namely Devel::Declare and Scope::Upper which are occasionally
        problematic, and the additional catch filtering uses Moose type constraints
        which may not be desirable either. '
      home_page: http://search.cpan.org/~ether/Try-Tiny-0.28/
      license_concluded: MIT AND MIT-0
      license_declared: MIT AND MIT-0
      short_summary: Minimal try/catch with proper preservation of $@
      supplier: 'Organization: Broadcom, Inc.'
