sources:
- archive: google-guest-agent-20260520.01.tar.gz
  archive_type: upstream
  archive_sha512sum: 774c5b09c960d06a88d85e31ab6308be24bc5c54a1c285d0904d8ad1bdefe22ee42483d925e09cf4b7d087460b6537c40d288c425c13905592c59e063f82336f
  version: "20260520.01"
  name: guest-agent-20260520.01
  url: https://github.com/GoogleCloudPlatform/guest-agent/archive/refs/tags/20260520.01.tar.gz
  repo_url: https://github.com/GoogleCloudPlatform/guest-agent
  commit_id: 34b9f7752240bc8b6ea0a21bad852b3e7534f000
  skip_list: []
  missing: []
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Google Compute Engine guest environment'
      home_page: https://github.com/GoogleCloudPlatform/guest-agent
      license_concluded: Apache-2.0 AND BSD-2-Clause AND MIT AND BSD-3-Clause AND Zlib
      license_declared: Apache-2.0 AND BSD-2-Clause AND MIT AND BSD-3-Clause AND Zlib
      short_summary: Google Compute Engine guest environment
      supplier: 'Organization: Broadcom, Inc.'
