sources:
- archive: libnetconf2-3.5.5.tar.gz
  archive_type: upstream
  archive_sha512sum: 8de6ef5ca31581bdc17f3711175392bc328dbc7560dc491bbdf8d1742b390b01781e750ac40cff504b32a610b9eff978334bd0e0b02b0622439fed34af119398
  name: libnetconf2-3.5.5
  version: "3.5.5"
  url: https://github.com/CESNET/libnetconf2/archive/refs/tags/v3.5.5.tar.gz
  repo_url: https://github.com/CESNET/libnetconf2
  commit_id: 4c7858c9c41f1ac04d2b15c032291e335fc0f5f5
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'libnetconf2 is a NETCONF library in C intended for building
        NETCONF clients and servers. NETCONF is the NETwork CONFiguration protocol
        introduced by IETF. '
      home_page: https://github.com/CESNET/libnetconf2
      license_concluded: BSD-3-Clause
      license_declared: BSD-3-Clause
      short_summary: NETCONF library in C intended for building NETCONF clients and
        servers.
      supplier: 'Organization: Broadcom, Inc.'
