sources:
- archive: aide-0.17.4.tar.gz
  archive_sha512sum: b6dba54fd204e1899d47b0b4139786cbeaa51c388027e2cfc1bb839297a70ae8ad6f37429594a730fac8007d62b4ba5b61a4aa22edbc55cbe986ccfaf5197f31
  skip_validation: true
  spdx:
    package:
      detailed_description: AIDE (Advanced Intrusion Detection Environment) is a file
        integrity checker and intrusion detection program.
      home_page: https://github.com/aide
      license_concluded: GPL-2.0-only AND BSD-3-Clause AND FSFUL AND FSFAP AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND GPL-2.0-or-later AND X11 AND LGPL-2.0-or-later
        AND FSFULLRWD AND GPL-1.0-or-later AND FSFULLR AND LGPL-2.1-only AND GPL-3.0-or-later
        WITH Bison-exception-2.2 AND GPL-2.0-or-later WITH Autoconf-exception-generic
      license_declared: GPL-2.0-only AND BSD-3-Clause AND FSFUL AND FSFAP AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND GPL-2.0-or-later AND X11 AND LGPL-2.0-or-later
        AND FSFULLRWD AND GPL-1.0-or-later AND FSFULLR AND LGPL-2.1-only AND GPL-3.0-or-later
        WITH Bison-exception-2.2 AND GPL-2.0-or-later WITH Autoconf-exception-generic
      short_summary: Intrusion detection environment
      supplier: 'Organization: Broadcom, Inc.'
