sources:
- archive: etcd-3.6.11.tar.gz
  archive_type: upstream
  archive_sha512sum: 56423c42443d9d1d2d06ff28aff389a381ed9b726cbee0d3523ac34fe2a8e22029377a42aa808077bb985f524a153c5fe63fd6166857749e8217b705fdf41910
  skip_validation: false
  version: 3.6.11
  name: etcd-3.6.11
  url: https://github.com/etcd-io/etcd/archive/refs/tags/v3.6.11.tar.gz
  repo_url: https://github.com/etcd-io/etcd
  commit_id: ec166e2292a58365c90e96fcd206b3b74938d49d
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'A highly-available key value store for shared configuration
        and service discovery. '
      home_page: https://github.com/etcd-io/etcd
      license_concluded: MIT AND BSD-3-Clause AND ISC AND Apache-2.0 AND BSD-2-Clause
      license_declared: MIT AND BSD-3-Clause AND ISC AND Apache-2.0 AND BSD-2-Clause
      short_summary: Distributed reliable key-value store
      supplier: 'Organization: Broadcom, Inc.'
