sources:
- archive: tzlocal-5.3.1.tar.gz
  archive_sha512sum: e72581649488e9771d314c7aea149367749866263df18baccb63c4fe369a863c392a8522c6be7987c32ff835dd11aae93b37028b0e7276dcf5c3d6e9a7b63ccc
  url: https://github.com/regebro/tzlocal/archive/refs/tags/5.3.1.tar.gz
  repo_url: https://github.com/regebro/tzlocal
  commit_id: fc98de51ba42f2901fd17573b44df21555065128
  name: tzlocal-5.3.1
  archive_type: upstream
  skip_validation: true
  spdx:
    package:
      detailed_description: "This Python module returns a zoneinfo tzinfo object with\
        \ the local timezone information under Unix and Win-32. This module attempts\
        \ to fix a glaring hole in the zoneinfo module, that there is no way to get\
        \ the local timezone information, unless you know the zoneinfo name, and under\
        \ several Linux distros that\u2019s hard or impossible to figure out. With\
        \ tzlocal you only need to call get_localzone(), and you will get a tzinfo\
        \ object with the local time zone info. On some Unices you will still not\
        \ get to know what the timezone name is, but you don\u2019t need that when\
        \ you have the tzinfo file. However, if the timezone name is readily available\
        \ it will be used. "
      home_page: https://github.com/regebro/tzlocal
      license_concluded: MIT
      license_declared: MIT
      short_summary: tzinfo object for the local timezone.
      supplier: 'Organization: Broadcom, Inc.'
