sources:
- archive: elixir-1.17.3.tar.gz
  archive_type: upstream
  archive_sha512sum: 084514d1362b52e85c0b4d92b8d18c6d2e9fddb4e4eaf4467f8b1c0985f9ceca1b74a0478581d91164935ae0f49610771860c674e080137e52aadc65b666911b
  name: "elixir-1.17.3"
  version: 1.17.3
  repo_url: https://github.com/elixir-lang/elixir
  url: https://github.com/elixir-lang/elixir/archive/refs/tags/v1.17.3.tar.gz
  commit_id: 78f63d08313677a680868685701ae79a2459dcc1
  spdx:
    package:
      detailed_description: 'Elixir is a programming language built on top of the
        Erlang VM. As Erlang, it is a functional language built to support distributed,
        fault-tolerant, non-stop applications with hot code swapping. '
      home_page: http://elixir-lang.org
      license_concluded: MIT AND Apache-2.0
      license_declared: MIT AND Apache-2.0
      short_summary: A modern approach to programming for the Erlang VM
      supplier: 'Organization: Broadcom, Inc.'
