sources:

- archive: pgaudit-1.7.1.tar.gz
  archive_sha512sum: 5516412809adde58883dd407522f2c79fbe65a7a6c70c8d6d69e51aa0a0a6eef2271f4c71f0ed140667c23753158c3124ce190045f99d36fd172416c392ec14a
  name: pgaudit-1.7.1
  version: 1.7.1
  archive_type: upstream
  url: https://github.com/pgaudit/pgaudit/archive/refs/tags/1.7.1.tar.gz
  repo_url: https://github.com/pgaudit/pgaudit
  commit_id: 72da89c3fa02f3f2b9f3933214d91ad9c3428467
  spdx:
    package:
      detailed_description: 'The PostgreSQL Audit extension (pgaudit) provides detailed
        session and/or object audit logging via the standard PostgreSQL logging facility. The
        goal of the PostgreSQL Audit extension (pgaudit) is to provide PostgreSQL
        users with capability to produce audit logs often required to comply with
        government, financial, or ISO certifications.  An audit is an official inspection
        of an individual''s or organization''s accounts, typically by an independent
        body. The information gathered by the PostgreSQL Audit extension (pgaudit)
        is properly called an audit trail or audit log. The term audit log is used
        in this documentation.'
      home_page: http://pgaudit.org
      license_concluded: PostgreSQL
      license_declared: PostgreSQL
      short_summary: PostgreSQL Audit Extension
      supplier: 'Organization: Broadcom, Inc.'

- archive: pgaudit-16.0.tar.gz
  archive_sha512sum: 65a6dffdc648255424fc44d6dd361938ebc6f9520770be2a1acd78d791cb4fc6caaa2f01865ef3e747bac50efa720e8817f9427eadec75fdfdf192c2705e44e2
  name: pgaudit-16.0
  version: 16.0
  archive_type: upstream
  url: https://github.com/pgaudit/pgaudit/archive/refs/tags/16.0.tar.gz
  repo_url: https://github.com/pgaudit/pgaudit
  commit_id: 8b7bf8588d30c1a298638a6a57898ef90c9a63eb
  spdx:
    package:
      detailed_description: 'The PostgreSQL Audit extension (pgaudit) provides detailed
        session and/or object audit logging via the standard PostgreSQL logging facility. The
        goal of the PostgreSQL Audit extension (pgaudit) is to provide PostgreSQL
        users with capability to produce audit logs often required to comply with
        government, financial, or ISO certifications.  An audit is an official inspection
        of an individual''s or organization''s accounts, typically by an independent
        body. The information gathered by the PostgreSQL Audit extension (pgaudit)
        is properly called an audit trail or audit log. The term audit log is used
        in this documentation.'
      home_page: http://pgaudit.org
      license_concluded: PostgreSQL
      license_declared: PostgreSQL
      short_summary: PostgreSQL Audit Extension
      supplier: 'Organization: Broadcom, Inc.'

- archive: pgaudit-17.1.tar.gz
  archive_sha512sum: 670efc1027a38c0f8b4f8408f00166682dbef04f3d468ca1b30865ddab332108a9a644eb22b485a431d5fa320fcb61bb41080b1bce8b47f2d3c05d6cf512603f
  name: pgaudit-17.1
  version: 17.1
  archive_type: upstream
  url: https://github.com/pgaudit/pgaudit/archive/refs/tags/17.1.tar.gz
  repo_url: https://github.com/pgaudit/pgaudit
  commit_id: 538f89a93d8fd0d8913f3d740cacaea7b7eb66d9
  spdx:
    package:
      detailed_description: 'The PostgreSQL Audit extension (pgaudit) provides detailed
        session and/or object audit logging via the standard PostgreSQL logging facility. The
        goal of the PostgreSQL Audit extension (pgaudit) is to provide PostgreSQL
        users with capability to produce audit logs often required to comply with
        government, financial, or ISO certifications.  An audit is an official inspection
        of an individual''s or organization''s accounts, typically by an independent
        body. The information gathered by the PostgreSQL Audit extension (pgaudit)
        is properly called an audit trail or audit log. The term audit log is used
        in this documentation.'
      home_page: http://pgaudit.org
      license_concluded: PostgreSQL
      license_declared: PostgreSQL
      short_summary: PostgreSQL Audit Extension
      supplier: 'Organization: Broadcom, Inc.'

- archive: pgaudit-18.0.tar.gz
  archive_sha512sum: 3d866f98249e9717f7ac7d381a989bc724d29d2f15d9e5399d3dc961c77f2b5b80ca482b465ae6f1af1cd86136e36b551b999a754e565f0192e68bbf58c5c0ca
  name: pgaudit-18.0
  version: 18.0
  archive_type: upstream
  url: https://github.com/pgaudit/pgaudit/archive/refs/tags/18.0.tar.gz
  repo_url: https://github.com/pgaudit/pgaudit
  commit_id: f39f8dbb15dc5bd4cbe5f1e5abe0d930ed7593a8
  spdx:
    package:
      detailed_description: 'The PostgreSQL Audit extension (pgaudit) provides detailed
        session and/or object audit logging via the standard PostgreSQL logging facility. The
        goal of the PostgreSQL Audit extension (pgaudit) is to provide PostgreSQL
        users with capability to produce audit logs often required to comply with
        government, financial, or ISO certifications.  An audit is an official inspection
        of an individual''s or organization''s accounts, typically by an independent
        body. The information gathered by the PostgreSQL Audit extension (pgaudit)
        is properly called an audit trail or audit log. The term audit log is used
        in this documentation.'
      home_page: http://pgaudit.org
      license_concluded: PostgreSQL
      license_declared: PostgreSQL
      short_summary: PostgreSQL Audit Extension
      supplier: 'Organization: Broadcom, Inc.'
