sources:
- archive: cups-2.4.14-source.tar.gz
  repo_url: https://github.com/OpenPrinting/cups.git
  commit_id: 2190813d4e78690806f4033c1f120f8e01e69e07
  archive_type: upstream
  name: cups-2.4.14
  version: '2.4.14'
  url: https://github.com/OpenPrinting/cups/releases/download/v2.4.14/cups-2.4.14-source.tar.gz
  archive_sha512sum: c6d46b737e2fdf37a429947bc5cc3d752785187aa339bd6de94733576aead29929ae510f960c9842cb7ddc86697d7841e5aa6b9d9c9dece907a2b8f468d038a0
  license_manual_review:
  - file_paths:
    - cups-2.4.14/doc/help/spec-ppd.html
    sha256sum: df1c0a31a9ff839e87e625c5bd52f21cb6538a89ae5edb4be5395607f6fd5f40
    spdx_exp: Apache-2.0
  - file_paths:
    - cups-2.4.14/doc/help/ppd-compiler.html
    sha256sum: bb490c1203d8ce17dfb9fe34aef6d4812d0761cb282e9de5dcdeae5cf6ce8c31
    spdx_exp: Apache-2.0
  - file_paths:
    - cups-2.4.14/filter/ppd-compiler.shtml
    sha256sum: cdcf87cf6abc9586982a2dd59946da7d2b6617a3c595d7d7bddbf7f6624a3b4b
    spdx_exp: ''
  - file_paths:
    - cups-2.4.14/filter/spec-ppd.shtml
    sha256sum: e5947e4454682f216b6a34458fa93bd56b84534d004cd7b84adfae2626b13da4
    spdx_exp: ''
  skip_validation: true
  spdx:
    package:
      detailed_description: The Common Unix Printing System (CUPS) is a print spooler
        and associated utilities. It is based on the Internet Printing Protocol and
        provides printing services to most PostScript and raster printers.
      home_page: https://openprinting.github.io/cups
      license_concluded: BSD-2-Clause AND Spencer-94 AND AML AND Zlib AND LGPL-2.0-or-later
        AND MIT AND CC0-1.0 AND GPL-1.0-or-later AND LGPL-2.0-only AND FSFUL AND Apache-2.0
        WITH LLVM-exception AND GPL-2.0-or-later AND EPL-1.0 AND Apache-2.0 AND BSD-3-Clause
        AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-2.0-only
      license_declared: BSD-2-Clause AND Spencer-94 AND AML AND Zlib AND LGPL-2.0-or-later
        AND MIT AND CC0-1.0 AND GPL-1.0-or-later AND LGPL-2.0-only AND FSFUL AND Apache-2.0
        WITH LLVM-exception AND GPL-2.0-or-later AND EPL-1.0 AND Apache-2.0 AND BSD-3-Clause
        AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-2.0-only
      short_summary: The Common UNIX Printing System
      supplier: 'Organization: Broadcom, Inc.'
