sources:
- archive: nfs-utils-2.6.2.tar.xz
  archive_sha512sum: 60ef0dc1842fe751c142313d41e3494a0d2bd8db4b859e970456b711688a606938273f3b43fe66ba9725e0b4e7dc7301e7358504b2f1d2da60cbd3b9f171c103
  skip_validation: true
  spdx:
    package:
      home_page: http://sourceforge.net/projects/nfs
      license_concluded: MIT AND BSD-2-Clause AND FSFAP AND GPL-2.0-or-later AND HPND-export-US-modify
        AND GPL-2.0-only AND BSD-3-Clause AND HPND-sell-variant AND X11 AND GPL-2.0-or-later
        WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-3.0-or-later AND LGPL-2.1-or-later AND FSFULLR AND FSFUL AND FSFULLRWD
        AND GPL-2.0-or-later WITH Autoconf-exception-generic
      license_declared: MIT AND BSD-2-Clause AND FSFAP AND GPL-2.0-or-later AND HPND-export-US-modify
        AND GPL-2.0-only AND BSD-3-Clause AND HPND-sell-variant AND X11 AND GPL-2.0-or-later
        WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-3.0-or-later AND LGPL-2.1-or-later AND FSFULLR AND FSFUL AND FSFULLRWD
        AND GPL-2.0-or-later WITH Autoconf-exception-generic
      short_summary: NFS client utils
      detailed_description: NFS client utils
      supplier: 'Organization: Broadcom, Inc.'
