sources:
- archive: dotnet-sdk-8.0.407-linux-x64.tar.gz
  archive_sha512sum: eb62153ecc9e53a5422ff44f1c6966a89ee442a91f779e971aaa47ad6a66bb131af9b38e4ca012567547b9357b72b0476b77d2b7399a38a9224a8e6ca02a8155
  skip_validation: true
  spdx:
    package:
      detailed_description: '.NET Core is a development platform that you can use
        to build command-line applications, microservices and modern websites. '
      home_page: https://github.com/dotnet/core
      license_concluded: LZMA-SDK-9.22 AND Parity-7.0.0 AND CC0-1.0 AND ICU AND CC-BY-SA-2.0
        AND BSD-3-Clause AND Python-2.0 AND bzip2-1.0.6 AND BSD-2-Clause AND MS-LPL
        AND Apache-2.0 AND Zlib AND Parity-6.0.0 AND SAX-PD AND Unicode-3.0 AND BSD-4-Clause-UC
        AND Apache-1.1 AND NCSA AND HP-1989 AND W3C-20150513 AND MIT
      license_declared: LZMA-SDK-9.22 AND Parity-7.0.0 AND CC0-1.0 AND ICU AND CC-BY-SA-2.0
        AND BSD-3-Clause AND Python-2.0 AND bzip2-1.0.6 AND BSD-2-Clause AND MS-LPL
        AND Apache-2.0 AND Zlib AND Parity-6.0.0 AND SAX-PD AND Unicode-3.0 AND BSD-4-Clause-UC
        AND Apache-1.1 AND NCSA AND HP-1989 AND W3C-20150513 AND MIT
      short_summary: Microsoft .NET Core SDK
      supplier: 'Organization: Broadcom, Inc.'
