sources:
- archive: dotnet-sdk-8.0.411-linux-x64.tar.gz
  archive_sha512sum: e7304c3798c3ad3278a23cfac7e3f873a760d6bfe0719eaafdf6a9666afeff8f2730e7c84f7ff597d34b5e26d1bccb08ecc6e23c7ef4376564c4ed568d6d2430
  skip_validation: true
  license_manual_review:
  - file_paths:
    - sdk/8.0.411/Containers/tasks/net8.0/NuGet.Packaging.dll
    - sdk/8.0.411/NuGet.Packaging.dll
    sha256sum: 5be664349d79037c6aefd29df91bf18c61dca31bc7195c022e58316ed1ab722f
    spdx_exp: ''
  - file_paths:
    - sdk/8.0.411/Containers/containerize/NuGet.Packaging.dll
    sha256sum: cfb5f07068e73ef0262ed3f5b9d1145d2d315314bdb51657ab918b57032f0859
    spdx_exp: ''
  - file_paths:
    - sdk/8.0.411/Containers/tasks/net472/NuGet.Packaging.dll
    - sdk/8.0.411/Sdks/Microsoft.NET.Sdk/tools/net472/NuGet.Packaging.dll
    sha256sum: cae3caa5087a13e9a1b0630d5d62dbf711f6cdace08c4c3ab4eccd6d36fa47f3
    spdx_exp: ''
  - file_paths:
    - sdk/8.0.411/Sdks/NuGet.Build.Tasks.Pack/CoreCLR/NuGet.Build.Tasks.Pack.dll
    sha256sum: 2f27e0f1ae3c7b1263a44b3b6f0a7cc301f4925b6ceead6d171a6dea38054365
    spdx_exp: ''
  - file_paths:
    - sdk/8.0.411/Sdks/NuGet.Build.Tasks.Pack/Desktop/NuGet.Build.Tasks.Pack.dll
    sha256sum: a153f2d4e922c63cf80f30ef987012eda872b266a38fec408089377e7998c554
    spdx_exp: ''
  spdx:
    package:
      detailed_description: '.NET Core is a development platform that you can use
        to build command-line applications, microservices and modern websites. '
      home_page: https://github.com/dotnet/core
      license_concluded: LZMA-SDK-9.22 AND Parity-7.0.0 AND CC0-1.0 AND ICU AND CC-BY-SA-2.0
        AND BSD-3-Clause AND Python-2.0 AND bzip2-1.0.6 AND BSD-2-Clause AND MS-LPL
        AND Apache-2.0 AND Zlib AND Parity-6.0.0 AND SAX-PD AND Unicode-3.0 AND BSD-4-Clause-UC
        AND Apache-1.1 AND NCSA AND HP-1989 AND W3C-20150513 AND MIT
      license_declared: LZMA-SDK-9.22 AND Parity-7.0.0 AND CC0-1.0 AND ICU AND CC-BY-SA-2.0
        AND BSD-3-Clause AND Python-2.0 AND bzip2-1.0.6 AND BSD-2-Clause AND MS-LPL
        AND Apache-2.0 AND Zlib AND Parity-6.0.0 AND SAX-PD AND Unicode-3.0 AND BSD-4-Clause-UC
        AND Apache-1.1 AND NCSA AND HP-1989 AND W3C-20150513 AND MIT
      short_summary: Microsoft .NET Core SDK
      supplier: 'Organization: Broadcom, Inc.'
