sources:
- archive: dotnet-sdk-10.0.300-linux-x64.tar.gz
  archive_sha512sum: a0c404c1a2f85d70e32392ce297eb388c0310c519521b538a031a895469444c67f347d4f9ca1f8441f525967a89c9b75e2cd1676da486f95118cf4025c38d904
  skip_validation: true
  license_manual_review:
  - file_paths:
    - sdk/10.0.300/NuGet.Packaging.dll
    sha256sum: c20dcd47c27efbda3accca2dc864c57ce910a1fda18998d623f31919f0bf868c
    spdx_exp: ''
  - file_paths:
    - sdk/10.0.300/Sdks/Microsoft.NET.Sdk/tools/net472/NuGet.Packaging.dll
    sha256sum: 5702707932ae4735c443750d522e690adfbaad8567ab2e7d6cebd53af718870c
    spdx_exp: ''
  spdx:
    package:
      detailed_description: '.NET Core is a development platform that you can use to build command-line applications, microservices and modern websites.'
      home_page: https://github.com/dotnet/core
      license_concluded: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause-UC AND CC0-1.0 AND HP-1989 AND LZMA-SDK-9.22 AND MIT AND NCSA AND Unicode-3.0 AND W3C-20150513 AND Zlib
      license_declared: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause-UC AND CC0-1.0 AND HP-1989 AND LZMA-SDK-9.22 AND MIT AND NCSA AND Unicode-3.0 AND W3C-20150513 AND Zlib
      short_summary: Microsoft .NET Core SDK
      supplier: 'Organization: Broadcom, Inc.'
