sources:
- archive: nasm-3.02-xdoc.tar.xz
  archive_type: None
  archive_sha512sum: b76d6a0764ce9991a79bb16078bc8fa73ff822183fcc39c7135c6d4d12487d3a2409f40f6fc6ca36f10545bab391b6aadb58e6f3d903cce0153a30dc80ff5184
  name: nasm-3.02-xdoc
  version: 3.02
  url: http://www.nasm.us/pub/nasm/releasebuilds/3.02/nasm-3.02-xdoc.tar.xz
  repo_url: https://github.com/netwide-assembler/nasm.git
  commit_id: 4a56d66ed9626d5a3ded5414c9d8b7f1a48ce065
  skip_list: []
  missing: []
  skip_validation: true
  spdx:
    package:
      detailed_description: Docs for package nasm
      home_page: http://www.nasm.us
      license_concluded: BSD-2-Clause
      license_declared: BSD-2-Clause
      short_summary: Netwide Assembler docs
      supplier: 'Organization: Broadcom, Inc.'
- archive: nasm-3.02.tar.xz
  archive_type: upstream
  archive_sha512sum: dc80d8a9a582423e62703da3cc3f37ee57735939b975faa8a72d061a8b596f763d206c7cc3e48c32d2ad726f38e430dc3b85cffd0c3b32e71e20ad9cc24f4804
  name: nasm-3.02
  version: 3.02
  url: http://www.nasm.us/pub/nasm/releasebuilds/3.02/nasm-3.02.tar.xz
  repo_url: https://github.com/netwide-assembler/nasm.git
  commit_id: 4a56d66ed9626d5a3ded5414c9d8b7f1a48ce065
  skip_validation: false
  skip_list: ['Makefile.in', 'msvc.mak', 'openwcom.mak', 'builtin.mac']
  missing: ['.gitignore', 'configure', 'nasm.1', 'nasm.spec', 'nasm.xml', 'ndisasm.1',
    'ndisasm.xml', 'version.h', 'version.mac', 'version.mak', 'version.sed', 'directbl.c',
    'directiv.h', 'pptok.c', 'pptok.h', 'pptok.ph', 'tokens.h', 'tokhash.c', 'warnings_c.h',
    'aclocal.m4', 'clean.sh', 'config.h.in', 'warnings.src', 'nasmtok.el', 'nasmtok.json',
    'warnings.h', 'macros.c', 'version.nsh', 'iflag.c', 'iflaggen.h', 'insns.xda',
    'insnsa.c', 'insnsb.c', 'insnsd.c', 'insnsi.h', 'insnsn.c', 'regdis.c', 'regdis.h',
    'regflags.c', 'regs.c', 'regs.h', 'regvals.c']
  license_manual_review:
  - file_paths:
    - nasm-3.02/doc/pspdf.pl
    sha256sum: d229a9849a97faad93f8476353f96be92227e145e016c429d88da01546d84f3f
    spdx_exp: ''
  # Reported incorrect license
  spdx:
    package:
      detailed_description: 'NASM (Netwide Assembler) is an 80x86 assembler designed
        for portability and modularity. It includes a disassembler as well. '
      home_page: http://www.nasm.us
      license_concluded: BSD-3-Clause AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND GPL-2.0-or-later AND Artistic-2.0 AND X11 AND GPL-1.0-or-later AND AGPL-3.0-or-later
        AND FSFUL AND FSFULLRWD AND BSD-2-Clause AND ISC AND GPL-3.0-or-later WITH
        Autoconf-exception-generic-3.0 AND LGPL-2.0-or-later
      license_declared: BSD-3-Clause AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND GPL-2.0-or-later AND Artistic-2.0 AND X11 AND GPL-1.0-or-later AND AGPL-3.0-or-later
        AND FSFUL AND FSFULLRWD AND BSD-2-Clause AND ISC AND GPL-3.0-or-later WITH
        Autoconf-exception-generic-3.0 AND LGPL-2.0-or-later
      short_summary: Netwide Assembler.
      supplier: 'Organization: Broadcom, Inc.'
