sources:
- archive: SPIRV-Headers-vulkan-sdk-1.4.313.0.tar.gz
  archive_sha512sum: c89b7992d8bdf956b551b3efa0fe67135574379973be446d18d215b4868799a3f5dab3002d230ccc54d723391ee37240cf0f2cd394898326d40685cbec673670
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Header files from the SPIR-V registry  This includes:  *
        Header files for various languages. * JSON files describing the grammar for
        the SPIR-V core instruction set, and for the GLSL.std.450 extended instruction
        set. * The XML registry file '
      home_page: https://github.com/KhronosGroup/SPIRV-Headers/
      license_concluded: MIT-Khronos-old AND MIT
      license_declared: MIT-Khronos-old AND MIT
      short_summary: Header files from the SPIR-V registry
      supplier: 'Organization: Broadcom, Inc.'
