sources:
- archive: faraday-2.14.1.gem
  archive_sha512sum: ba661ffe8cb520d82ceecb3b31da9e49207c80b9b7f6089b656beabcd3bf662c07f5c0a3d2ef8efc37e79f14882e2fe599948b87d769e0da808c2f2e7662ec42
  skip_validation: true
  spdx:
    package:
      detailed_description: 'HTTP/REST API client library.'
      home_page: https://rubygems.org/gems/faraday
      license_concluded: MIT
      license_declared: MIT
      short_summary: HTTP/REST API client library.
      supplier: 'Organization: Broadcom, Inc.'
