sources:
- archive: fuse-overlayfs-snapshotter-2.1.7.tar.gz
  archive_sha512sum: c6027cdf51828d936d8ec259fb67c91fe1694937f0a9dee57e038d8b7f5600f39df07fad008336ec86c2b9e699a09140fa2d62b57bb4c5d7955ed5049a097223
  archive_type: upstream
  commit_id: da57796c7d0a2b608abf173651cf148706e33337
  missing: []
  skip_list: []
  skip_validation: false
  name: fuse-overlayfs-snapshotter-2.1.7
  version: '2.1.7'
  repo_url: https://github.com/containerd/fuse-overlayfs-snapshotter
  url: https://github.com/containerd/fuse-overlayfs-snapshotter/archive/refs/tags/v2.1.7.tar.gz
  spdx:
    package:
      detailed_description: 'fuse-overlayfs snapshotter plugin for containerd. fuse-overlayfs-snapshotter
        is a non-core sub-project of containerd. '
      home_page: https://github.com/containerd/fuse-overlayfs-snapshotter
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: fuse-overlayfs plugin for rootless containerd
      supplier: 'Organization: Broadcom, Inc.'
