sources:
- archive: userspace-rcu-0.15.6.tar.gz
  archive_sha512sum: 40649c19af80da95d4463600ae06295505ed1865dbcffce7ff201de5ec025a57530ee745184151296669cc64e99aaef16958452e6dbab7b8a655b2e911dafd72
  archive_type: upstream
  name: userspace-rcu-0.15.6
  version: 0.15.6
  url: https://github.com/urcu/userspace-rcu/archive/refs/tags/v0.15.6.tar.gz
  repo_url: https://github.com/urcu/userspace-rcu/
  commit_id: d8bd37fb288a2da7238103f9b24bf25e190902be
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'This data synchronization library provides read-side
        access which scales linearly with the number of cores.'
      home_page: https://github.com/urcu/userspace-rcu
      license_concluded: (GPL-1.0-or-later OR LGPL-2.0-or-later) AND BSD-2-Clause AND Boehm-GC AND CC-BY-4.0 AND CC0-1.0 AND FSFAP AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only AND GPL-3.0-or-later AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND MIT
      license_declared: (GPL-1.0-or-later OR LGPL-2.0-or-later) AND BSD-2-Clause AND Boehm-GC AND CC-BY-4.0 AND CC0-1.0 AND FSFAP AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only AND GPL-3.0-or-later AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND MIT
      short_summary: user space RCU (read-copy-update)
      supplier: 'Organization: Broadcom, Inc.'
