%global security_hardening nopie
%define debug_package %{nil}
%define __os_install_post %{nil}
Summary:        EdgeX Foundry Go Services
Name:           edgex
Version:        0.7.1
Release:        1%{?dist}
License:        Apache-2.0
URL:            https://github.com/edgexfoundry/edgex-go
Group:          Applications/System
Vendor:         VMware, Inc.
Distribution:   Photon
# Wait for official release. For now use git archive to createa tarball:
# git config tar.tar.xz.command "xz -c"
# git archive -o edgex-0.6.0-1261522.tar.xz HEAD
Source0:	edgex-0.7.1.tar.xz
%define sha1 edgex=abeb109c0a1519af6c2193f02bfcb04478879cd8
# glide installed dependencies all in one tarball generated by:
# tar -cJf glide-tarball-for-edgex-0.6.0-1261522.tar.xz vendor/ glide.lock
Source1:	glide-tarball-for-edgex-0.7.1.tar.xz
%define sha1 glide-tarball-for-edgex=eae1ee581335b990ae24b3381b7c81988e40ce24
Source4:	edgex-template.service
Source5:	edgex-config-seed.service

BuildRequires:  go >= 1.9
BuildRequires:  make
BuildRequires:  systemd-devel
BuildRequires:  zeromq-devel
Requires:       systemd
Requires:       consul
Requires:	redis

%description
EdgeX Foundry Go Services

%prep
%setup -c -T -a 0 -n src/github.com/edgexfoundry
mv %{_builddir}/src/github.com/edgexfoundry/edgex-go-0.7.1 %{_builddir}/src/github.com/edgexfoundry/edgex-go
%setup -D -c -T -a 1 -n src/github.com/edgexfoundry/edgex-go

%build
cd %{_builddir}/src/github.com/edgexfoundry/edgex-go
GOPATH=%{_builddir} make build %{?_smp_mflags}

%install
# edgex-go
cd %{_builddir}/src/github.com/edgexfoundry/edgex-go
install -d -m755 %{buildroot}%{_bindir}
install -d -m755 %{buildroot}%{_datadir}/%{name}
install -d -m755 %{buildroot}%{_libdir}/systemd/system

# install binary
for srv in core-command core-data core-metadata export-client export-distro support-logging support-notifications support-scheduler sys-mgmt-agent; do
install -p -m755 cmd/${srv}/${srv} %{buildroot}%{_bindir}/edgex-${srv}
install -d -m755 %{buildroot}%{_datadir}/%{name}/${srv}/res
install -p -m644 cmd/${srv}/res/configuration.toml %{buildroot}%{_datadir}/%{name}/${srv}/res/configuration.toml
# workdir for the service
install -d -m755 %{buildroot}%{_var}/log/%{name}/${srv}
ln -s %{_datadir}/%{name}/${srv}/res %{buildroot}%{_var}/log/%{name}/${srv}/res

sed "s/SERVICE_NAME/${srv}/" %{SOURCE4} > %{buildroot}%{_libdir}/systemd/system/edgex-${srv}.service
done

install -p -m755 cmd/config-seed/config-seed %{buildroot}%{_bindir}/edgex-config-seed
install -d -m755 %{buildroot}%{_datadir}/%{name}/config-seed/res
cd cmd
seed_res=$(find config-seed/res/ -type f)
for file in ${seed_res}; do
install -Dp -m755 ${file} %{buildroot}%{_datadir}/%{name}/${file}
done
install -p -m644 %{SOURCE5} %{buildroot}%{_libdir}/systemd/system/`basename %{SOURCE5}`
install -d -m755 %{buildroot}%{_var}/log/%{name}/config-seed
ln -s %{_datadir}/%{name}/config-seed/res %{buildroot}%{_var}/log/%{name}/config-seed/res

#change config files from mongodb to redisdb by default
cd %{buildroot}%{_datadir}/%{name}
find ./ -type f -exec sed -i -e 's/mongodb/redisdb/g' {} \;
find ./ -type f -exec sed -i -e 's/Port = 27017/Port = 6379/g' {} \;

%files
%defattr(-,root,root)
%{_bindir}/*
%{_datadir}/*
%{_libdir}/*
%{_var}/log/*

%changelog
*   Wed Jan 09 2019 Him Kalyan Bordoloi <bordoloih@vmware.com> 0.7.1-1
-   Upgrade version to 0.7.1
*   Wed Dec 05 2018 Alexey Makhalov <amakhalov@vmware.com> 0.6.0-2
-   Remove 'Requires: mongodb'. But edgex still depends on mongo.
*   Fri Jul 06 2018 Alexey Makhalov <amakhalov@vmware.com> 0.6.0-1
-   Initial version
