sources:
- archive: CGI-4.69.tar.gz
  archive_sha512sum: d8dbb476fdfb43bac1d7674c25e046eabaf15dcf582c453e1810367cb2ed435b7fcc597ecaab32692832997e16d04152928cc145502781f8c6698bfdefcc4407
  skip_validation: true
  spdx:
    package:
      detailed_description: 'CGI.pm is a stable, complete and mature solution for
        processing and preparing HTTP requests and responses. Major features including
        processing form submissions, file uploads, reading and writing cookies, query
        string generation and manipulation, and processing and preparing HTTP headers.
        Some HTML generation utilities are included as well.  CGI.pm performs very
        well in in a vanilla CGI.pm environment and also comes with built-in support
        for mod_perl and mod_perl2 as well as FastCGI. '
      home_page: http://search.cpan.org/dist/CGI
      license_concluded: Artistic-2.0
      license_declared: Artistic-2.0
      short_summary: Handle Common Gateway Interface requests and responses
      supplier: 'Organization: Broadcom, Inc.'
