sources:
- archive: mdadm-4.6.tar.gz
  archive_type: upstream
  archive_sha512sum: d11eefdffedefecea0786f7ec034305339b7d93d75916eb9501726de0a296dc668c8d0091d1c130805a5d47122ad6d944e46bd723430c15414a360c35d8b06be
  version: "4.6"
  name: mdadm-4.6
  url: https://git.kernel.org/pub/scm/utils/mdadm/mdadm.git/snapshot/mdadm-4.6.tar.gz
  repo_url: https://git.kernel.org/pub/scm/utils/mdadm/mdadm.git
  commit_id: 8b414a0d4753693d67b9a5822994e5f0c91b0b0a
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'The mdadm program controls Linux md devices (software RAID arrays)'
      home_page: https://git.kernel.org/pub/scm/utils/mdadm/mdadm.git/about
      license_concluded: GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-or-later AND Zlib
      license_declared: GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-or-later AND Zlib
      short_summary: The mdadm program controls Linux md devices (software RAID arrays)
      supplier: 'Organization: Broadcom, Inc.'
