sources:
- archive: createrepo_c-1.2.2.tar.gz
  archive_sha512sum: c95a376ccd611a3e041ad1c6fd70af0d7c17cc3db7a9926706f0ff9aeacf7f32a80ba18f8a98be4e2c2aea61d572a4b5ba7b0761f828b2faad0ea8f96e641320
  archive_type: upstream
  name: createrepo_c-1.2.2
  version: 1.2.2
  url: https://github.com/rpm-software-management/createrepo_c/archive/refs/tags/1.2.2.tar.gz
  repo_url: https://github.com/rpm-software-management/createrepo_c
  commit_id: 46b86c9b14bd724cb6bec0bfa81a7b179847f3db
  skip_list: []
  missing: [ci.yml]
  spdx:
    package:
      detailed_description: 'C implementation of the createrepo.'
      home_page: https://github.com/rpm-software-management/createrepo_c
      license_concluded: GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-or-later
      license_declared: GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-or-later
      short_summary: Creates a common metadata repository
      supplier: 'Organization: Broadcom, Inc.'
