sources:
- archive: llhttp-ffi-0.5.1.gem
  archive_sha512sum: 78a88af2f46c7715e45ea0be9a397f7ea5eded264779ff99e4634b6abb38e8f4194cd5b61acd8b9d3913ce8b3ba11f95ae73bab4cc4ce1a79d747d2cb9b9f506
  skip_validation: true
  spdx:
    package:
      detailed_description: "An easy-to-use client library for making requests from Ruby. It uses a simple method chaining system for building requests, similar to Python's Requests. "
      home_page: https://rubygems.org/gems/llhttp-ffi
      license_concluded: MPL-2.0
      license_declared: MPL-2.0
      short_summary: An easy-to-use client library for making requests from Ruby.
      supplier: 'Organization: Broadcom, Inc.'
