sources:
- archive: gobgp-4.2.0.tar.gz
  archive_sha512sum: 6c74db94cf3754a39c54032eb553cfa87c8e9f56a12d6a6d170bc84b6f1f4948f5dec62adf93294cc68b3b5e767be0f51ad06baaa45a118a59dbd5313b726ee6
  archive_type: upstream
  name: gobgp-4.2.0
  url: https://github.com/osrg/gobgp/archive/refs/tags/v4.2.0.tar.gz
  repo_url: https://github.com/osrg/gobgp
  commit_id: 8d4da6dbf5d993476743903676ec34710e1001a0
  spdx:
    package:
      detailed_description: 'GoBGP is an open source BGP implementation designed from
        scratch for modern environment, and implemented in a modern programming language,
        the Go Programming Language. '
      home_page: https://github.com/osrg/gobgp
      license_concluded: MIT AND Apache-2.0 AND radvd
      license_declared: MIT AND Apache-2.0 AND radvd
      short_summary: BGP implemented in the Go Programming Language
      supplier: 'Organization: Broadcom, Inc.'
