sources:
- archive: vim-9.2.0670.tar.gz
  archive_sha512sum: 30fdb8ce9e5eb6e63302b692ecca5c2f29b1bd8b51b782cabb8953c241e0582730a6db494bc2f1dc100a5a9c4ed3aad9720d48dda34e19b1200057b49079cde5
  archive_type: upstream
  name: vim-9.2.0670
  url: https://github.com/vim/vim/archive/refs/tags/v9.2.0670.tar.gz
  repo_url: https://github.com/vim/vim
  commit_id: b2338ca90643e2f01ecb6547c1172716aaec4f79
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'The VIM package contains a powerful text editor. '
      home_page: http://www.vim.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (GPL-1.0-or-later OR MIT) AND 0BSD AND Apache-2.0 AND Apache-2.0 WITH Swift-exception AND BSD-2-Clause AND BSD-3-Clause AND CC-BY-3.0 AND FSFUL AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-or-later AND HPND-Markus-Kuhn AND HPND-sell-variant AND ISC AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-or-later AND MIT AND MIT-Modern-Variant AND PSF-2.0 AND Python-2.0 AND Spencer-86 AND TMate AND Vim AND X11
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (GPL-1.0-or-later OR MIT) AND 0BSD AND Apache-2.0 AND Apache-2.0 WITH Swift-exception AND BSD-2-Clause AND BSD-3-Clause AND CC-BY-3.0 AND FSFUL AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-or-later AND HPND-Markus-Kuhn AND HPND-sell-variant AND ISC AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-or-later AND MIT AND MIT-Modern-Variant AND PSF-2.0 AND Python-2.0 AND Spencer-86 AND TMate AND Vim AND X11
      short_summary: Text editor
      supplier: 'Organization: Broadcom, Inc.'
