sources:
- archive: iptraf-ng-v1.2.2.tar.gz
  archive_sha512sum: 275a345ffd3ab9578c4d159c3a8667326224b4a58b2e7787c4db518b81973d87c04b4b6c5275a721858d01a9b44a0200f8defc06c6f88655aa38d4fa6146ea1d
  archive_type: upstream
  skip_validation: true
  name: iptraf-ng-1.2.2
  url: https://github.com/iptraf-ng/iptraf-ng/archive/refs/tags/v1.2.2.tar.gz
  repo_url: https://github.com/iptraf-ng/iptraf-ng
  commit_id: 639850ddfff0e10ad073457b827422f0cc2e2989
  spdx:
    package:
      detailed_description: 'IPTraf-ng is a console-based network monitoring program
        for Linux that displays information about IP traffic. It returns information
        such as: - Current TCP connections - UDP, ICMP, OSPF, and other types of IP
        packets - Packet and byte counts on TCP connections - IP, TCP, UDP, ICMP,
        non-IP, and other packet and byte counts - TCP/UDP counts by ports - Packet
        counts by packet sizes - Packet and byte counts by IP address - Interface
        activity - Flag statuses on TCP packets - LAN station statistics '
      home_page: https://github.com/iptraf-ng/iptraf-ng
      license_concluded: GPL-2.0-only AND GFDL-1.1-only AND GFDL-1.1-or-later AND
        GPL-2.0-or-later AND LGPL-2.0-only
      license_declared: GPL-2.0-only AND GFDL-1.1-only AND GFDL-1.1-or-later AND GPL-2.0-or-later
        AND LGPL-2.0-only
      short_summary: IPTraf-ng is a console-based network statistics utility
      supplier: 'Organization: Broadcom, Inc.'
