sources:
- archive: thin-provisioning-tools-1.0.14.tar.gz
  archive_type: upstream
  version: 1.0.14
  name: thin-provisioning-tools-1.0.14
  url: https://github.com/jthornber/thin-provisioning-tools/archive/refs/tags/v1.0.14.tar.gz
  repo_url: https://github.com/jthornber/thin-provisioning-tools.git
  commit_id: 6be3e0937800cb947f1be7c0150825f155cfca14
  skip_list: []
  missing: []
  archive_sha512sum: a421ebf732f6595dcfec93ae14671cf9e5475b3289370209a658c77fe0760bbfc316c023035775608ced217bf23c535010af97062875178558c6b922c0cd0ff3
  skip_validation: false
  spdx:
    package:
      detailed_description: 'thin-provisioning-tools contains check,dump, restore,
        repair, rmap and metadata_size tools to manage device-mapper thin provisioning
        target metadata devices; cache check, dump, metadata_size, restore and repair
        tools to manage device-mapper cache metadata devices are included and era
        check, dump, restore and invalidate to manage snapshot eras. '
      home_page: https://github.com/jthornber/thin-provisioning-tools
      license_concluded: GPL-2.0-or-later AND GPL-3.0-only
      license_declared: GPL-2.0-or-later AND GPL-3.0-only
      short_summary: Thin provisioning tools
      supplier: 'Organization: Broadcom, Inc.'
- archive: thin-provisioning-tools-deps-1.0.14p1.tar.xz
  archive_sha512sum: 815f9f90613a77dbaa49df8b9d6f51f1da152c2bcd8e772e22a792ab8899b38d7895e6ec298cac99a7a83b376a6b21cb37004df7d650d0921436a46f94f762ba
  skip_validation: true
  spdx:
    package:
      detailed_description: Thin provisioning tools dependencies stored as cargo registry
      home_page: https://packages.vmware.com/photon/photon_sources/1.0/
      license_concluded: MIT AND Unlicense AND Apache-2.0 WITH LLVM-exception AND
        (MIT OR Unlicense) AND BSD-3-Clause AND 0BSD AND (MIT OR Apache-2.0) AND BSD-2-Clause
        AND (BSD-3-Clause OR GPL-2.0-only) AND Unicode-DFS-2016 AND GPL-2.0-only AND
        (MIT OR Apache-2.0) AND MIT-testregex AND (BSD-3-Clause OR GPL-2.0-only) AND
        JSON AND SunPro AND CC0-1.0 AND Zlib AND GPL-3.0-or-later AND (Apache-2.0
        OR MIT) AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0
        OR MIT) AND BSD-2-Clause-Views AND (MIT OR GPL-2.0-only) AND (GPL-2.0-or-later
        OR MIT) AND Apache-2.0 AND GPL-3.0-only
      license_declared: MIT AND Unlicense AND Apache-2.0 WITH LLVM-exception AND (MIT
        OR Unlicense) AND BSD-3-Clause AND 0BSD AND (MIT OR Apache-2.0) AND BSD-2-Clause
        AND (BSD-3-Clause OR GPL-2.0-only) AND Unicode-DFS-2016 AND GPL-2.0-only AND
        (MIT OR Apache-2.0) AND MIT-testregex AND (BSD-3-Clause OR GPL-2.0-only) AND
        JSON AND SunPro AND CC0-1.0 AND Zlib AND GPL-3.0-or-later AND (Apache-2.0
        OR MIT) AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0
        OR MIT) AND BSD-2-Clause-Views AND (MIT OR GPL-2.0-only) AND (GPL-2.0-or-later
        OR MIT) AND Apache-2.0 AND GPL-3.0-only
      short_summary: Thin provisioning tools dependencies stored as cargo registry
      supplier: 'Organization: Broadcom, Inc.'
