sources:
- archive: bind-9.20.29.tar.xz
  archive_type: upstream
  version: 9.20.29
  name: bind-9.20.29
  url: https://downloads.isc.org/isc/bind9/9.20.29/bind-9.20.29.tar.xz
  repo_url: https://github.com/isc-projects/bind9.git
  commit_id: c3d4465e57f2771d780c82f413d4dc4cc779fb64
  skip_list: []
  missing:
  - '*.in'
  - '*.m4'
  - '*.1in'
  - '*.8in'
  - '*.5in'
  - '*.sh'
  - '*.pl'
  - tests
  - testdata
  - include
  - dev
  - design
  - cocci
  - conftools
  - .github
  - .gitlab
  - .clang-format
  - .clang-format.headers
  - .gitlab-ci.yml
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .mailmap
  - .readthedocs.yaml
  - .reuse
  - REUSE.toml
  - LICENSES
  - .uncrustify.cfg
  - .dir-locals.el
  - .gitchangelog.rc
  - .git-blame-ignore-revs
  - .tsan-suppress
  - sonar-project.properties
  - dangerfile.py
  - pyproject.toml
  - FUZZING.md
  - srcid
  - names.csv
  - mainpage
  - startperf
  - dnssec-policy.default.conf
  - suppr-lsan.txt
  - install-sh
  - depcomp
  - compile
  - missing
  - ar-lib
  - test-driver
  - config.guess
  - config.sub
  - configure
  - run-clang-tidy
  - models.c
  - gen-rsa-sha-vectors.c
  - gen-eddsa-vectors.c
  - .agents
  - .claude
  archive_sha512sum: afedc73a1376d662eec86b7f0e5795a3b0302e7184af83f90d06e3b5054efb54f5d7ab73f777e0d1b84b25aa27f299de688c508e28f0a22e67ba5eb07aa46077
  skip_validation: false
  spdx:
    package:
      detailed_description: 'BIND is open source software that implements the Domain
        Name System (DNS) protocols for the Internet. It is a reference implementation
        of those protocols, but it is also production-grade software, suitable for
        use in high-volume and high-reliability applications. '
      home_page: http://www.isc.org/downloads/bind
      license_concluded: FSFAP AND GPL-3.0-or-later WITH Autoconf-exception-3.0 AND
        GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND BSD-2-Clause AND FSFULLR AND GPL-2.0-or-later WITH Libtool-exception AND
        MIT AND HPND AND FSFULLRWD AND Apache-2.0 AND FSFUL AND ISC AND GPL-2.0-only
        AND CC-BY-3.0 AND MPL-2.0 AND X11 AND CC0-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-2.0-or-later AND OpenSSL AND BSD-3-Clause
      license_declared: FSFAP AND GPL-3.0-or-later WITH Autoconf-exception-3.0 AND
        GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND BSD-2-Clause AND FSFULLR AND GPL-2.0-or-later WITH Libtool-exception AND
        MIT AND HPND AND FSFULLRWD AND Apache-2.0 AND FSFUL AND ISC AND GPL-2.0-only
        AND CC-BY-3.0 AND MPL-2.0 AND X11 AND CC0-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-2.0-or-later AND OpenSSL AND BSD-3-Clause
      short_summary: Domain Name System software
      supplier: 'Organization: Broadcom, Inc.'
