sources:
- archive: bind-9.20.23.tar.xz
  archive_type: upstream
  version: 9.20.23
  name: bind-9.20.23
  url: https://downloads.isc.org/isc/bind9/9.20.23/bind-9.20.23.tar.xz
  repo_url: https://github.com/isc-projects/bind9.git
  commit_id: 7d0b4d4d436e7b950225a533e5bc56d8f935cc1c
  skip_list: []
  missing: []
  archive_sha512sum: fce8a69620c15223e54dd197c09c7b00c165e5e3a5b2f62b241f589be5675c581029cf750caa8ed1f1fcb0faf293df04e77c494c205bab89d6d01153395bf4cb
  skip_validation: true
  spdx:
    package:
      detailed_description: 'BIND is open source software that implements the Domain
        Name System (DNS) protocols for the Internet. It is a reference implementation
        of those protocols, but it is also production-grade software, suitable for
        use in high-volume and high-reliability applications. '
      home_page: http://www.isc.org/downloads/bind
      license_concluded: FSFAP AND GPL-3.0-or-later WITH Autoconf-exception-3.0 AND
        GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND BSD-2-Clause AND FSFULLR AND GPL-2.0-or-later WITH Libtool-exception AND
        MIT AND HPND AND FSFULLRWD AND Apache-2.0 AND FSFUL AND ISC AND GPL-2.0-only
        AND CC-BY-3.0 AND MPL-2.0 AND X11 AND CC0-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-2.0-or-later AND OpenSSL AND BSD-3-Clause
      license_declared: FSFAP AND GPL-3.0-or-later WITH Autoconf-exception-3.0 AND
        GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND BSD-2-Clause AND FSFULLR AND GPL-2.0-or-later WITH Libtool-exception AND
        MIT AND HPND AND FSFULLRWD AND Apache-2.0 AND FSFUL AND ISC AND GPL-2.0-only
        AND CC-BY-3.0 AND MPL-2.0 AND X11 AND CC0-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-2.0-or-later AND OpenSSL AND BSD-3-Clause
      short_summary: Domain Name System software
      supplier: 'Organization: Broadcom, Inc.'
