sources:
- archive: docker-compose-5.1.4.tar.gz
  archive_type: upstream
  archive_sha512sum: b9cc1c74251f97b4eef6448f66e58613c3b22b683ea92bebb6d8279b00739c285170d6cdc059e7341cb419c197b47958c6ad446ca763c93121ee524e57412a68
  version: 5.1.4
  name: compose-5.1.4
  url: https://github.com/docker/compose/archive/refs/tags/v5.1.4.tar.gz
  repo_url: https://github.com/docker/compose
  commit_id: 4732a2ed20a49c43a7b44bb4928259162c3ae3be
  skip_list: []
  missing: []
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Docker Compose (V2) plugin for the Docker CLI.  This
        plugin provides the ''docker compose'' subcommand.  The binary can also be
        run standalone as a direct replacement for Docker Compose V1 (''docker-compose''). '
      home_page: https://github.com/docker/compose
      license_concluded: TMate AND Apache-2.0 AND MIT
      license_declared: TMate AND Apache-2.0 AND MIT
      short_summary: Multi-container orchestration for Docker
      supplier: 'Organization: Broadcom, Inc.'
