sources:
- archive: docker-compose-5.5.1.tar.gz
  archive_type: upstream
  archive_sha512sum: 477025f5a18c7d281a774007f01065128e90ab5cae7340daf98913dd1f44854882db5d9f808ef425c15e861e96be9bbb8a4516af3c39d3aa82eb04b284f6bfe3
  version: 5.5.1
  name: compose-5.5.1
  url: https://github.com/docker/compose/archive/refs/tags/v5.5.1.tar.gz
  repo_url: https://github.com/docker/compose
  commit_id: 5f94fb0aa42a2cd1248c6e6c7fafb87546b9c8de
  skip_list: []
  missing: []
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Docker Compose (V2) plugin for the Docker CLI.  This
        plugin provides the ''docker compose'' subcommand.  The binary can also be
        run standalone as a direct replacement for Docker Compose V1 (''docker-compose''). '
      home_page: https://github.com/docker/compose
      license_concluded: TMate AND Apache-2.0 AND MIT
      license_declared: TMate AND Apache-2.0 AND MIT
      short_summary: Multi-container orchestration for Docker
      supplier: 'Organization: Broadcom, Inc.'
