sources:
- archive: pyopenssl-26.3.0.tar.gz
  archive_sha512sum: 47a01ac8d1f7dd4b9920234af5389b932380b8423d9fe85a2e282e02ebeb7ecb95f116413cb3d06362f942499db1de3c3c8968be578fa04cdd7a9989fa6758ff
  archive_type: upstream
  name: pyopenssl-26.3.0
  version: 26.3.0
  url: https://github.com/pyca/pyopenssl/archive/refs/tags/26.3.0.tar.gz
  repo_url: https://github.com/pyca/pyopenssl
  commit_id: f74084cec12d4960a89b135cdd7be95096f83ecc
  spdx:
    package:
      detailed_description: 'High-level wrapper around a subset of the OpenSSL library. '
      home_page: https://github.com/pyca/pyopenssl
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: Python wrapper module around the OpenSSL library
      supplier: 'Organization: Broadcom, Inc.'
