sources:
- archive: ansible-2.20.1.tar.gz
  archive_sha512sum: fa0a4836e3548cd4e432e87b241beb6fb556765699c25b1f3b1c47111a1c44d5ba3244aeb8793408e72ab63564d6e848148becbfb550bd965e466752d7f78229
  skip_validation: false
  archive_type: upstream
  name: ansible-2.20.1
  version: 2.20.1
  url: https://github.com/ansible/ansible/archive/refs/tags/v2.20.1.tar.gz
  repo_url: https://github.com/ansible/ansible
  commit_id: 55ee8acd65cd94a110ce5eb5a3668c320b26f7d8
  skip_list: []
  missing: ['.github']
  spdx:
    package:
      detailed_description: 'Ansible is a radically simple IT automation system. It
        handles configuration-management, application deployment, cloud provisioning,
        ad-hoc task-execution, and multinode orchestration - including trivializing
        things like zero downtime rolling updates with load balancers. '
      home_page: https://www.ansible.com
      license_concluded: (MIT OR GPL-1.0-or-later) AND MIT-0 AND GPL-3.0-or-later
        AND GPL-1.0-or-later AND LGPL-3.0-or-later AND BSD-2-Clause AND BSD-3-Clause
        AND GPL-2.0-or-later AND MIT AND Python-2.0 AND Apache-2.0 AND GPL-3.0-only
      license_declared: (MIT OR GPL-1.0-or-later) AND MIT-0 AND GPL-3.0-or-later AND
        GPL-1.0-or-later AND LGPL-3.0-or-later AND BSD-2-Clause AND BSD-3-Clause AND
        GPL-2.0-or-later AND MIT AND Python-2.0 AND Apache-2.0 AND GPL-3.0-only
      short_summary: Configuration-management, application deployment, cloud provisioning
        system
      supplier: 'Organization: Broadcom, Inc.'
