sources:
- archive: ansible-2.20.4.tar.gz
  archive_sha512sum: 45d66b208f4c49f2fc3c04c1cc317cb26a8571ede3f84daf4f6818e0404d5c1d5a50178be610f03b972119eb944395981d1253cfbbde0472efc553b82ac8c82c
  skip_validation: false
  archive_type: upstream
  name: ansible-2.20.4
  version: 2.20.4
  url: https://github.com/ansible/ansible/archive/refs/tags/v2.20.4.tar.gz
  repo_url: https://github.com/ansible/ansible
  commit_id: 4c777317e90223843c775f75cadb6f37d4ec27e8
  skip_list: []
  missing: [.github]
  spdx:
    package:
      detailed_description: 'Ansible is a radically simple IT automation system. It
        handles configuration-management, application deployment, cloud provisioning,
        ad-hoc task-execution, and multinode orchestration - including trivializing
        things like zero downtime rolling updates with load balancers. '
      home_page: https://www.ansible.com
      license_concluded: (GPL-1.0-or-later OR MIT) AND Apache-2.0 AND
        BSD-2-Clause AND BSD-3-Clause AND CC-BY-4.0 AND GPL-1.0-or-later AND
        GPL-2.0-or-later AND GPL-3.0-only AND GPL-3.0-or-later AND JSON AND
        MIT AND MIT-0 AND Python-2.0
      license_declared: (GPL-1.0-or-later OR MIT) AND Apache-2.0 AND
        BSD-2-Clause AND BSD-3-Clause AND CC-BY-4.0 AND GPL-1.0-or-later AND
        GPL-2.0-or-later AND GPL-3.0-only AND GPL-3.0-or-later AND JSON AND
        MIT AND MIT-0 AND Python-2.0
      short_summary: Configuration-management, application deployment, cloud
        provisioning system
      supplier: 'Organization: Broadcom, Inc.'
