sources:
- archive: libnvme-1.16.1.tar.gz
  archive_sha512sum: 92113cd62af53366fb63f2f385c2059dede171fef4d9a240fa941382e338d2941e90aeb40ae2d202311d7b531e41181839f45f8ab4da1b3a79ce4b597fcd4993
  archive_type: upstream
  skip_validation: false
  name: libnvme-1.16.1
  version: "1.16.1"
  url: https://github.com/linux-nvme/libnvme/archive/refs/tags/v1.16.1.tar.gz
  repo_url: https://github.com/linux-nvme/libnvme
  commit_id: becae3d874b40bfedede672b4b2f58ae8c3be3b5
  missing: []
  skip_list: []
  spdx:
    package:
      detailed_description: 'Provides type definitions for NVMe specification structures,
        enumerations, and bit fields, helper functions to construct, dispatch, and
        decode commands and payloads, and utilities to connect, scan, and manage nvme
        devices on a Linux system. '
      home_page: https://github.com/linux-nvme/libnvme
      license_concluded: BSD-3-Clause AND CC0-1.0 AND GPL-2.0-only AND Apache-2.0
        AND GPL-1.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-2.0-or-later
        AND MIT
      license_declared: BSD-3-Clause AND CC0-1.0 AND GPL-2.0-only AND Apache-2.0 AND
        GPL-1.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-2.0-or-later
        AND MIT
      short_summary: Linux-native nvme device management library
      supplier: 'Organization: Broadcom, Inc.'
