sources:
- archive: httpd-2.4.65.tar.bz2
  archive_sha512sum: 202f8bfe2aafcfbcd7315191d466e9c10b9a8c0abafb7864510b6e1abe4cb660aaacc2456aa77d43e48ef7a49e591d0b54170d3daf67abc3e06c3da1c63fdffc
  name: httpd-2.4.65
  version: 2.4.65
  skip_validation: true
  url: https://dlcdn.apache.org/httpd/httpd-2.4.65.tar.bz2
  repo_url: https://github.com/apache/httpd.git
  commit_id: 47490973d568337011e4073099fb570d4151083b
  skip_list: [VERSIONING, ab.c, ROADMAP]
  missing: ['missing list too big']
  spdx:
    package:
      detailed_description: 'The Apache HTTP Server.'
      home_page: http://httpd.apache.org
      license_concluded: metamail AND BSD-2-Clause AND MIT AND HPND-sell-variant AND
        Spencer-94 AND Apache-2.0 AND GPL-2.0-or-later AND Apache-1.1 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later WITH Bison-exception-2.2
        AND RSA-MD AND BSD-3-Clause AND FSFUL AND GPL-2.0-only AND Beerware AND GPL-2.0-or-later
        WITH Libtool-exception
      license_declared: metamail AND BSD-2-Clause AND MIT AND HPND-sell-variant AND
        Spencer-94 AND Apache-2.0 AND GPL-2.0-or-later AND Apache-1.1 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later WITH Bison-exception-2.2
        AND RSA-MD AND BSD-3-Clause AND FSFUL AND GPL-2.0-only AND Beerware AND GPL-2.0-or-later
        WITH Libtool-exception
      short_summary: The Apache HTTP Server
      supplier: 'Organization: Broadcom, Inc.'
