sources:
- archive: httpd-2.4.66.tar.bz2
  archive_sha512sum: 49031a3465d956ee3b755e65810b6c35561ddd5fac2c624a273b733c238e115b914cd7b246837e5a3090ccfded6e0b8b3059bfd1f8ce4419081c805a38d05a4b
  name: httpd-2.4.66
  version: 2.4.66
  url: https://dlcdn.apache.org/httpd/httpd-2.4.66.tar.bz2
  repo_url: https://github.com/apache/httpd.git
  commit_id: e4a77ef6051b3fe22eafacbcf54855b178a0bddd
  archive_type: upstream
  skip_list: [VERSIONING, ab.c, ROADMAP]
  missing: ['*.fr', '*.xml', '*.tr', '*.ja', '*.ko', '*.meta', '*.ru', '*.be', '*.xsl', '*.de', '*.es', '*-br', '*-cn', 'tmp', 'apr_common.m4', 'config.sub', 'STATUS', '.deps', 'ap_config_auto.h.in', 'configure', 'ltmain.sh', 'changes-entries', 'challenges', 'staging', 'config.guess', 'httpd.spec', 'index.xml.da']
  spdx:
    package:
      detailed_description: 'The Apache HTTP Server.'
      home_page: http://httpd.apache.org
      license_concluded: metamail AND BSD-2-Clause AND MIT AND HPND-sell-variant AND
        Spencer-94 AND Apache-2.0 AND GPL-2.0-or-later AND Apache-1.1 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later WITH Bison-exception-2.2
        AND RSA-MD AND BSD-3-Clause AND FSFUL AND GPL-2.0-only AND Beerware AND GPL-2.0-or-later
        WITH Libtool-exception
      license_declared: metamail AND BSD-2-Clause AND MIT AND HPND-sell-variant AND
        Spencer-94 AND Apache-2.0 AND GPL-2.0-or-later AND Apache-1.1 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later WITH Bison-exception-2.2
        AND RSA-MD AND BSD-3-Clause AND FSFUL AND GPL-2.0-only AND Beerware AND GPL-2.0-or-later
        WITH Libtool-exception
      short_summary: The Apache HTTP Server
      supplier: 'Organization: Broadcom, Inc.'
