sources:
- archive: httpd-2.4.68.tar.bz2
  archive_sha512sum: 134a5bbd3ffe97523ac750490531bcb9441c532cedf0229aa006aa1368e9d25040507c6f519bed6754044f62c371f7c7f9a11b6a311f79b9680d478bf4373eb3
  name: httpd-2.4.68
  version: 2.4.68
  url: https://dlcdn.apache.org/httpd/httpd-2.4.68.tar.bz2
  repo_url: https://github.com/apache/httpd.git
  commit_id: 736bb657405eb73fd68a64772c3a908807bdb887
  archive_type: upstream
  skip_list: [VERSIONING, ab.c, ROADMAP]
  missing: ['*.fr', '*.xml', '*.tr', '*.ja', '*.ko', '*.meta', '*.ru', '*.be', '*.xsl', '*.de', '*.es', '*-br', '*-cn', 'tmp', 'apr_common.m4', 'config.sub', 'STATUS', '.deps', 'ap_config_auto.h.in', 'configure', 'ltmain.sh', 'changes-entries', 'challenges', 'staging', 'config.guess', 'httpd.spec', 'index.xml.da']
  spdx:
    package:
      detailed_description: 'The Apache HTTP Server.'
      home_page: http://httpd.apache.org
      license_concluded: metamail AND BSD-2-Clause AND MIT AND HPND-sell-variant AND
        Spencer-94 AND Apache-2.0 AND GPL-2.0-or-later AND Apache-1.1 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later WITH Bison-exception-2.2
        AND RSA-MD AND BSD-3-Clause AND FSFUL AND GPL-2.0-only AND Beerware AND GPL-2.0-or-later
        WITH Libtool-exception
      license_declared: metamail AND BSD-2-Clause AND MIT AND HPND-sell-variant AND
        Spencer-94 AND Apache-2.0 AND GPL-2.0-or-later AND Apache-1.1 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later WITH Bison-exception-2.2
        AND RSA-MD AND BSD-3-Clause AND FSFUL AND GPL-2.0-only AND Beerware AND GPL-2.0-or-later
        WITH Libtool-exception
      short_summary: The Apache HTTP Server
      supplier: 'Organization: Broadcom, Inc.'
