sources:
- archive: e2fsprogs-1.47.4.tar.xz
  archive_sha512sum: c316ce38d73786fb45b3728cd31991fe81b14a1e61dae645f3471c3f35983c4394e4606b47194c3e607897b7ae5a5ef1d376adb204383afa8c4219db8617d970
  archive_type: upstream
  name: e2fsprogs-1.47.4
  version: 1.47.4
  url: https://www.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.47.4/e2fsprogs-1.47.4.tar.xz
  repo_url: https://github.com/tytso/e2fsprogs
  commit_id: 7ee1d505ef3b37831215f490411f346fe57e9053
  kip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'The E2fsprogs package contains the utilities for handling the ext2 file system.'
      home_page: https://github.com/tytso/e2fsprogs
      license_concluded: 0BSD AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause AND BSD-4.3TAHOE AND FSFAP AND FSFUL AND FSFULLR AND FSFULLRSD AND FSFULLRWD AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-or-later AND HPND-export-US-modify AND ISC AND Kazlib AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND Latex2e AND Latex2e-translated-notice AND MIT AND NTP AND NTP-0 AND X11
      license_declared: 0BSD AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause AND BSD-4.3TAHOE AND FSFAP AND FSFUL AND FSFULLR AND FSFULLRSD AND FSFULLRWD AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-or-later AND HPND-export-US-modify AND ISC AND Kazlib AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND Latex2e AND Latex2e-translated-notice AND MIT AND NTP AND NTP-0 AND X11
      short_summary: Contains the utilities for the ext2 file system
      supplier: 'Organization: Broadcom, Inc.'
