sources:
- archive: log4cpp-1.1.3.tar.gz
  archive_sha512sum: 88e5e10bce8d7d6421c3dcf14aa25385159c4ae52becdc1f3666ab86e1ad3f633786d82afe398c517d4faaa57b3e7b7c0b524361d81c6b9040dbded5cecc19de
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Log for C++ is a library of classes for flexible logging
        to files, syslog, and other destinations. It is modeled after the Log for
        Java library and stays as close to its API as is reasonable. '
      home_page: http://log4cpp.sourceforge.net/
      license_concluded: Artistic-2.0 AND GPL-1.0-or-later AND GPL-2.0-or-later WITH
        Autoconf-exception-generic AND GPL-2.0-only AND FSFUL AND FSFULLR AND FSFULLRWD
        AND X11 AND GPL-3.0-or-later WITH Autoconf-exception-macro AND LGPL-2.0-or-later
        AND GPL-2.0-or-later WITH Libtool-exception AND Artistic-1.0 AND GPL-2.0-or-later
        AND LGPL-2.1-only AND LGPL-2.1-or-later
      license_declared: Artistic-2.0 AND GPL-1.0-or-later AND GPL-2.0-or-later WITH
        Autoconf-exception-generic AND GPL-2.0-only AND FSFUL AND FSFULLR AND FSFULLRWD
        AND X11 AND GPL-3.0-or-later WITH Autoconf-exception-macro AND LGPL-2.0-or-later
        AND GPL-2.0-or-later WITH Libtool-exception AND Artistic-1.0 AND GPL-2.0-or-later
        AND LGPL-2.1-only AND LGPL-2.1-or-later
      short_summary: Log for C++
      supplier: 'Organization: Broadcom, Inc.'
