sources:
- archive: log4cpp-1.1.6.tar.gz
  archive_sha512sum: 2159654c704a311af36f97e85c519e5bf60d4d470ef2fb5e0e9cd80c6fc76d450ad0d3069948010697ac20314461309773eb7cd5594a5c98407e9e6600741d87
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Log for C++ is a library of classes for flexible logging
        to files, syslog, and other destinations. It is modeled after the Log for
        Java library and stays as close to its API as is reasonable. '
      home_page: http://log4cpp.sourceforge.net/
      license_concluded: Artistic-2.0 AND GPL-1.0-or-later AND GPL-2.0-or-later WITH
        Autoconf-exception-generic AND GPL-2.0-only AND FSFUL AND FSFULLR AND FSFULLRWD
        AND X11 AND GPL-3.0-or-later WITH Autoconf-exception-macro AND LGPL-2.0-or-later
        AND GPL-2.0-or-later WITH Libtool-exception AND Artistic-1.0 AND GPL-2.0-or-later
        AND LGPL-2.1-only AND LGPL-2.1-or-later
      license_declared: Artistic-2.0 AND GPL-1.0-or-later AND GPL-2.0-or-later WITH
        Autoconf-exception-generic AND GPL-2.0-only AND FSFUL AND FSFULLR AND FSFULLRWD
        AND X11 AND GPL-3.0-or-later WITH Autoconf-exception-macro AND LGPL-2.0-or-later
        AND GPL-2.0-or-later WITH Libtool-exception AND Artistic-1.0 AND GPL-2.0-or-later
        AND LGPL-2.1-only AND LGPL-2.1-or-later
      short_summary: Log for C++
      supplier: 'Organization: Broadcom, Inc.'
