sources:
- archive: postgresql-10.23.tar.bz2
  skip_validation: true
  archive_sha512sum: 9fd031cad0c3caacae105215167abd5dc4fdd15dea77a12cb0a977fab6e245e3fda163f202cc7786e50c69e5c3f180d32676a3b18ea30a9a14f0bcab56aa19dd
  name: postgresql-10.23
  version: 10.23
  url: http://ftp.postgresql.org/pub/source/v10.23/postgresql-10.23.tar.bz2
  repo_url: https://github.com/postgres/postgres.git
  commit_id: 02991e79f8f58bc208f05dcc8af0c62dbe0a6ea4
  missing: []
  spdx:
    package:
      detailed_description: PostgreSQL is an object-relational database management system.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND GPL-2.0-or-later WITH Autoconf-exception-generic AND FSFUL AND MIT AND GPL-3.0-or-later WITH Bison-exception-2.2 AND PostgreSQL AND Spencer-99 AND BSD-2-Clause AND GPL-1.0-or-later AND Martin-Birgmeier AND ISC AND GPL-3.0-or-later WITH Autoconf-exception-macro AND X11 AND TCL AND BSD-2-Clause-Views AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND BSD-3-Clause
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND GPL-2.0-or-later WITH Autoconf-exception-generic AND FSFUL AND MIT AND GPL-3.0-or-later WITH Bison-exception-2.2 AND PostgreSQL AND Spencer-99 AND BSD-2-Clause AND GPL-1.0-or-later AND Martin-Birgmeier AND ISC AND GPL-3.0-or-later WITH Autoconf-exception-macro AND X11 AND TCL AND BSD-2-Clause-Views AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND BSD-3-Clause
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'

- archive: postgresql-13.23.tar.bz2
  skip_validation: true
  archive_sha512sum: 9589fe26d874eb91244b7325d997d5e54e93d61a13f63b7e9ef247c0ca6c8ade420487303295010b0c45d7775b64da076a2af14bdcb7a03702d06b5edf159c39
  name: postgresql-13.23
  version: '13.23'
  url: http://ftp.postgresql.org/pub/source/v13.23/postgresql-13.23.tar.bz2
  repo_url: https://github.com/postgres/postgres.git
  commit_id: 89df812eb890814b105d871185935b580478e660
  missing: []
  spdx:
    package:
      detailed_description: PostgreSQL is an advanced Object-Relational database management system (DBMS). The base postgresql package contains the client programs that you'll need to access a PostgreSQL DBMS server. These client programs can be located on the same machine as the PostgreSQL server, or on a remote machine that accesses a PostgreSQL server over a network connection. The PostgreSQL server can be found in the postgresql13-server sub-package.  If you want to manipulate a PostgreSQL database on a local or remote PostgreSQL server, you need this package. You also need to install this package if you're installing the postgresql13-server package.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND MIT AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND BSD-3-Clause AND GPL-1.0-or-later AND BSL-1.0 AND Spencer-99 AND Martin-Birgmeier AND GPL-3.0-or-later WITH Bison-exception-2.2 AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND Apache-2.0 WITH LLVM-exception AND X11 AND PostgreSQL AND TCL AND BSD-2-Clause-Views AND NCSA AND BSD-2-Clause AND Apache-2.0 AND FSFUL AND ISC
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND MIT AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND BSD-3-Clause AND GPL-1.0-or-later AND BSL-1.0 AND Spencer-99 AND Martin-Birgmeier AND GPL-3.0-or-later WITH Bison-exception-2.2 AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND Apache-2.0 WITH LLVM-exception AND X11 AND PostgreSQL AND TCL AND BSD-2-Clause-Views AND NCSA AND BSD-2-Clause AND Apache-2.0 AND FSFUL AND ISC
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'

- archive: postgresql-14.22.tar.bz2
  skip_validation: true
  archive_sha512sum: b192189db081c0cb1d6dfba132dc3969a32a8990c69a0acf8f2c79b3fb1e865e727e6153ddd988c099021950cf7896c6619a7a12d83ca22765bf2736f67d66f5
  name: postgresql-14.22
  version: '14.22'
  url: http://ftp.postgresql.org/pub/source/v14.22/postgresql-14.22.tar.bz2
  repo_url: https://github.com/postgres/postgres.git
  commit_id: 966473719c7f8067848dc79b58da0fb17ed136b1
  missing: []
  spdx:
    package:
      detailed_description: PostgreSQL is an advanced Object-Relational database management system (DBMS). The base postgresql package contains the client programs that you'll need to access a PostgreSQL DBMS server. These client programs can be located on the same machine as the PostgreSQL server, or on a remote machine that accesses a PostgreSQL server over a network connection. The PostgreSQL server can be found in the postgresql-server sub-package.  If you want to manipulate a PostgreSQL database on a local or remote PostgreSQL server, you need this package. You also need to install this package if you're installing the postgresql-server package.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND BSL-1.0 AND Spencer-99 AND Martin-Birgmeier AND GPL-1.0-or-later AND BSD-2-Clause AND Apache-2.0 WITH LLVM-exception AND Apache-2.0 AND BSD-3-Clause AND PostgreSQL AND TCL AND ISC AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND X11 AND MIT AND NCSA AND BSD-2-Clause-Views AND FSFUL AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later WITH Bison-exception-2.2
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND BSL-1.0 AND Spencer-99 AND Martin-Birgmeier AND GPL-1.0-or-later AND BSD-2-Clause AND Apache-2.0 WITH LLVM-exception AND Apache-2.0 AND BSD-3-Clause AND PostgreSQL AND TCL AND ISC AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND X11 AND MIT AND NCSA AND BSD-2-Clause-Views AND FSFUL AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later WITH Bison-exception-2.2
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'

- archive: postgresql-15.17.tar.bz2
  skip_validation: true
  archive_sha512sum: 032f27f4028ee8be10f7540edd0174b5e354a2a38f4f228414539178d1bbc542c4b9c599e376685fa9de78a2d918b9ce74997908e7e5c0204b3da88bc4661e2b
  name: postgresql-15.17
  version: '15.17'
  url: http://ftp.postgresql.org/pub/source/v15.17/postgresql-15.17.tar.bz2
  repo_url: https://github.com/postgres/postgres.git
  commit_id: 3eb6f61958ac5027a18791a828a0c7a47accf211
  missing: []
  spdx:
    package:
      detailed_description: PostgreSQL is an advanced Object-Relational database management system (DBMS). The base postgresql package contains the client programs that you'll need to access a PostgreSQL DBMS server. These client programs can be located on the same machine as the PostgreSQL server, or on a remote machine that accesses a PostgreSQL server over a network connection. The PostgreSQL server can be found in the postgresql-server sub-package.  If you want to manipulate a PostgreSQL database on a local or remote PostgreSQL server, you need this package. You also need to install this package if you're installing the postgresql-server package.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND BSD-3-Clause AND NCSA AND Spencer-99 AND FSFUL AND GPL-3.0-or-later WITH Bison-exception-2.2 AND MIT AND BSD-2-Clause AND Apache-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND PostgreSQL AND TCL AND BSL-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-1.0-or-later AND ISC AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND BSD-2-Clause-Views AND X11 AND Apache-2.0 WITH LLVM-exception
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND BSD-3-Clause AND NCSA AND Spencer-99 AND FSFUL AND GPL-3.0-or-later WITH Bison-exception-2.2 AND MIT AND BSD-2-Clause AND Apache-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND PostgreSQL AND TCL AND BSL-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-1.0-or-later AND ISC AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND BSD-2-Clause-Views AND X11 AND Apache-2.0 WITH LLVM-exception
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'

- archive: postgresql-16.13.tar.bz2
  skip_validation: true
  archive_sha512sum: 3ea11b81ce55be5c3c169f0c94ddfa9debae6b3cbe7407086ba3a602fad7668900c2838d4d4488c671b2ccc670a9cd288ece90e42ecf8de953df6b4e103d286d
  name: postgresql-16.13
  version: '16.13'
  url: http://ftp.postgresql.org/pub/source/v16.13/postgresql-16.13.tar.bz2
  repo_url: https://github.com/postgres/postgres.git
  commit_id: 776479eed63aac4185e57adaf7db1ce0810a4d3e
  missing: []
  spdx:
    package:
      detailed_description: PostgreSQL is an advanced Object-Relational database management system (DBMS). The base postgresql package contains the client programs that you'll need to access a PostgreSQL DBMS server. These client programs can be located on the same machine as the PostgreSQL server, or on a remote machine that accesses a PostgreSQL server over a network connection. The PostgreSQL server can be found in the postgresql-server sub-package.  If you want to manipulate a PostgreSQL database on a local or remote PostgreSQL server, you need this package. You also need to install this package if you're installing the postgresql-server package.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Apache-2.0 WITH LLVM-exception AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND ISC AND Apache-2.0 AND TCL AND BSD-3-Clause AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND BSD-2-Clause AND FSFUL AND BSD-4-Clause-UC AND GPL-1.0-or-later AND MIT AND X11 AND GPL-3.0-or-later WITH Bison-exception-2.2 AND NCSA AND BSL-1.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND Spencer-99 AND PostgreSQL
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Apache-2.0 WITH LLVM-exception AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND ISC AND Apache-2.0 AND TCL AND BSD-3-Clause AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND BSD-2-Clause AND FSFUL AND BSD-4-Clause-UC AND GPL-1.0-or-later AND MIT AND X11 AND GPL-3.0-or-later WITH Bison-exception-2.2 AND NCSA AND BSL-1.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND Spencer-99 AND PostgreSQL
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'

- archive: postgresql-17.9.tar.bz2
  skip_validation: true
  archive_sha512sum: 2b9c9ca9d765704895ec4af4107accead2ba3f3ce8bc87eed29fd020cf97b53a49a7d3eb9fa1242a7c430fe2f7e1be726f1ad67557ded2fe8b31b9d8fe659fbf
  name: postgresql-17.9
  version: '17.9'
  url: http://ftp.postgresql.org/pub/source/v17.9/postgresql-17.9.tar.bz2
  repo_url: https://github.com/postgres/postgres.git
  commit_id: 6d396980fc5aed4f1a525e0bd75cb16b25ed40ca
  missing: []
  spdx:
    package:
      detailed_description: PostgreSQL is an advanced Object-Relational database management system (DBMS). The base postgresql package contains the client programs that you'll need to access a PostgreSQL DBMS server. These client programs can be located on the same machine as the PostgreSQL server, or on a remote machine that accesses a PostgreSQL server over a network connection. The PostgreSQL server can be found in the postgresql-server sub-package.  If you want to manipulate a PostgreSQL database on a local or remote PostgreSQL server, you need this package. You also need to install this package if you're installing the postgresql-server package.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Apache-2.0 WITH LLVM-exception AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND ISC AND Apache-2.0 AND TCL AND BSD-3-Clause AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND BSD-2-Clause AND FSFUL AND BSD-4-Clause-UC AND GPL-1.0-or-later AND MIT AND X11 AND GPL-3.0-or-later WITH Bison-exception-2.2 AND NCSA AND BSL-1.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND Spencer-99 AND PostgreSQL
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Apache-2.0 WITH LLVM-exception AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND ISC AND Apache-2.0 AND TCL AND BSD-3-Clause AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND BSD-2-Clause AND FSFUL AND BSD-4-Clause-UC AND GPL-1.0-or-later AND MIT AND X11 AND GPL-3.0-or-later WITH Bison-exception-2.2 AND NCSA AND BSL-1.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND Spencer-99 AND PostgreSQL
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'

- archive: postgresql-18.3.tar.bz2
  archive_sha512sum: fdbe6d726f46738cf14acab96e5c05f7d65aefe78563281b416bb14a27c7c42e4df921e26b32816a5030ddbe506b95767e2c74a35afc589916504df38d1cb11c
  name: postgresql-18.3
  version: '18.3'
  archive_type: upstream
  url: http://ftp.postgresql.org/pub/source/v18.3/postgresql-18.3.tar.bz2
  repo_url: https://github.com/postgres/postgres.git
  commit_id: 62d6c7d3df6287f1bd83199c1a746e50d31571a0
  spdx:
    package:
      detailed_description: PostgreSQL is an advanced Object-Relational database management system (DBMS). The base postgresql package contains the client programs that you'll need to access a PostgreSQL DBMS server. These client programs can be located on the same machine as the PostgreSQL server, or on a remote machine that accesses a PostgreSQL server over a network connection. The PostgreSQL server can be found in the postgresql-server sub-package.  If you want to manipulate a PostgreSQL database on a local or remote PostgreSQL server, you need this package. You also need to install this package if you're installing the postgresql-server package.
      home_page: www.postgresql.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause-UC AND BSL-1.0 AND FSFUL AND GPL-1.0-or-later AND GPL-2.0-or-later AND GPL-3.0-or-later AND ISC AND MIT AND NCSA AND PostgreSQL AND Spencer-99 AND TCL AND X11
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause-UC AND BSL-1.0 AND FSFUL AND GPL-1.0-or-later AND GPL-2.0-or-later AND GPL-3.0-or-later AND ISC AND MIT AND NCSA AND PostgreSQL AND Spencer-99 AND TCL AND X11
      short_summary: PostgreSQL database engine
      supplier: 'Organization: Broadcom, Inc.'
