sources:
- archive: perl-5.40.2.tar.xz
  archive_sha512sum: 1324b119e4370bbeb47a343d152f46c637addb0373ff07f0e214aa9d5912c03cd2bd23987a6e86d43453166412d3a03a52e780201941f679ef4186df16590e41
  license_manual_review:
  - file_paths:
    - perl-5.40.2/cpan/CPAN-Meta/lib/CPAN/Meta/Converter.pm
    sha256sum: 9528d678363d4857b45cba7a0b9efadc488aab4a1d5495baceec58f731444490
    spdx_exp: GPL-1.0-or-later
  - file_paths:
    - perl-5.40.2/cpan/CPAN-Meta/lib/CPAN/Meta/Validator.pm
    sha256sum: cc02695d6c683879171ebd513e3e8e6c2a06b7ec1938fe41f0663ee36a925292
    spdx_exp: GPL-1.0-or-later
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The Perl package contains the Practical Extraction and
        Report Language. '
      home_page: http://www.perl.org/
      license_concluded: (Artistic-1.0 OR GPL-1.0-or-later) AND (Artistic-1.0-Perl
        OR GPL-1.0-or-later OR MIT) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND
        (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (Artistic-1.0-Perl OR GPL-2.0-or-later)
        AND (Artistic-2.0 OR GPL-1.0-or-later) AND AGPL-3.0-only AND Apache-1.1 AND
        Apache-2.0 AND Artistic-1.0 AND Artistic-1.0-Perl AND Artistic-2.0 AND BSD-2-Clause-Views
        AND BSD-3-Clause AND CC0-1.0 AND FSFAP AND GPL-1.0-only AND GPL-1.0-or-later
        AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only AND GPL-3.0-or-later
        WITH Bison-exception-2.2 AND JSON AND LGPL-2.0-or-later AND LGPL-2.1-only
        AND LGPL-3.0-only AND MIT AND MPL-1.0 AND MPL-1.1 AND MPL-2.0 AND Martin-Birgmeier
        AND OpenSSL AND RSA-MD AND SISSL AND Spencer-86 AND TTWL AND X11 AND Zlib
        AND bzip2-1.0.6 AND metamail
      license_declared: (Artistic-1.0 OR GPL-1.0-or-later) AND (Artistic-1.0-Perl
        OR GPL-1.0-or-later OR MIT) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND
        (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (Artistic-1.0-Perl OR GPL-2.0-or-later)
        AND (Artistic-2.0 OR GPL-1.0-or-later) AND AGPL-3.0-only AND Apache-1.1 AND
        Apache-2.0 AND Artistic-1.0 AND Artistic-1.0-Perl AND Artistic-2.0 AND BSD-2-Clause-Views
        AND BSD-3-Clause AND CC0-1.0 AND FSFAP AND GPL-1.0-only AND GPL-1.0-or-later
        AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only AND GPL-3.0-or-later
        WITH Bison-exception-2.2 AND JSON AND LGPL-2.0-or-later AND LGPL-2.1-only
        AND LGPL-3.0-only AND MIT AND MPL-1.0 AND MPL-1.1 AND MPL-2.0 AND Martin-Birgmeier
        AND OpenSSL AND RSA-MD AND SISSL AND Spencer-86 AND TTWL AND X11 AND Zlib
        AND bzip2-1.0.6 AND metamail
      short_summary: Practical Extraction and Report Language
      supplier: 'Organization: Broadcom, Inc.'
- archive: perl-cross-1.6.2.tar.gz
  archive_sha512sum: 51b45bf972304634d706d09e27d457636e43f9f27f739004eca529b21245ba78612dcb08b54225fc7ca19511983642c37915939ea8aa1c1a4560093474d9e76b
  skip_validation: true
  spdx:
    package:
      detailed_description: perl-cross provides alternative configure script, top-level
        Makefile as well as some auxilliary files for the standard perl distribution
        intended to allow cross-compiling perl in a relatively straighforward way.
      home_page: https://arsv.github.io/perl-cross
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0
      short_summary: Cross-compiling perl
      supplier: 'Organization: Broadcom, Inc.'
