" Begin /etc/vimrc

set shell=/bin/bash
set nocompatible
set backspace=2
set ruler
set tags=./tags;/

syntax on
color desert

if (&term == "iterm") || (&term == "putty")
  set background=dark
endif

" Binds
nmap <F2> :w<CR>
imap <F2> <Esc>:w<CR>
nmap <F10> :q!<CR>
nmap <Esc><Esc> :q<CR>

" Use 4 space characters instead of tab for python files
au BufEnter,BufNew *.py set tabstop=4 shiftwidth=4 expandtab

" Move the swap file location to protect against CVE-2017-1000382
" More information at http://security.cucumberlinux.com/security/details.php?id=120
try
  if ! isdirectory("~/.vim/swap/")
    call system('install -d -m 700 ~/.vim/swap')
  endif
  set directory=~/.vim/swap/
catch /E145/
endtry

let skip_defaults_vim=1

" End /etc/vimrc
