sources:
- archive: libtracefs-1.8.3.tar.gz
  archive_sha512sum: 4b24bf2b0543c16781be798387cfe5227f150c37304971ac5bd11c2715df22ba03e5909b05c97422b69102113279b3b4a606d0babe4b97000120e458755f9b7c
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The libtracefs(3) library provides APIs to access kernel
        trace file system. '
      home_page: https://git.kernel.org/pub/scm/libs/libtrace/libtracefs.git
      license_concluded: GPL-3.0-or-later WITH Bison-exception-2.2 AND LGPL-2.1-or-later
        AND GPL-2.0-only AND LGPL-2.1-only AND GPL-1.0-or-later AND GPL-2.0-or-later
      license_declared: GPL-3.0-or-later WITH Bison-exception-2.2 AND LGPL-2.1-or-later
        AND GPL-2.0-only AND LGPL-2.1-only AND GPL-1.0-or-later AND GPL-2.0-or-later
      short_summary: Linux kernel trace file system library
      supplier: 'Organization: Broadcom, Inc.'
