sources:
- archive: systemd-journal-2.1.2.gem
  archive_sha512sum: f8f01a92df266d646777281625ae09b41dee87bc67d4d78305a0b7728c8b6766db78bd011602c6ceccb7f738ceae577362d5da1aeb6200e34cc4523fd53bac75
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Provides the ability to navigate and read entries from
        the systemd journal in ruby, as well as write events to the journal. '
      home_page: https://rubygems.org/gems/systemd-journal/versions/2.1.2
      license_concluded: MIT
      license_declared: MIT
      short_summary: Provides the ability to navigate and read entries from the systemd
        journal in ruby
      supplier: 'Organization: Broadcom, Inc.'
