sources:
    - archive: acl-2.3.1.tar.gz
      archive_sha512sum: f101e27058c959f4c412f475c3fc77a90d1ead8728701e4ce04ff08b34139d35e0e72278c9ac7622ba6054e81c0aeca066e09491b5f5666462e3866705a0e892
      skip_validation: true
      spdx:
          package:
              short_summary: Commands for Manipulating POSIX Access Control Lists
              detailed_description:
                  "This package contains the getfacl and setfacl utilities
                  needed for manipulating access control lists. "
              home_page: https://savannah.nongnu.org/projects/acl
              license_concluded: LGPL-2.1-only AND GPL-2.0-only AND BSD-Source-beginning-file AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-2.0-or-later WITH Libtool-exception AND FSFULLR AND FSFUL AND FSFULLRWD AND GPL-3.0-or-later WITH Libtool-exception AND LGPL-2.1-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND X11 AND GPL-1.0-or-later AND LGPL-2.0-or-later AND GPL-3.0-or-later AND GPL-2.0-or-later
              license_declared: LGPL-2.1-only AND GPL-2.0-only AND BSD-Source-beginning-file AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-2.0-or-later WITH Libtool-exception AND FSFULLR AND FSFUL AND FSFULLRWD AND GPL-3.0-or-later WITH Libtool-exception AND LGPL-2.1-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND X11 AND GPL-1.0-or-later AND LGPL-2.0-or-later AND GPL-3.0-or-later AND GPL-2.0-or-later
              supplier: "Organization: Broadcom, Inc."
