sources:
- archive: timescaledb-2.19.2.tar.gz
  archive_type: upstream
  archive_sha512sum: a340d1306e26cf7bd73517aeced5d2f2c65ba1275867e870551cc0919fb1cd28399bc797bfb2ffa3871b88bae5f9d71689a7ee83ae3e775cf4c012248e00348f
  name: timescaledb-2.19.2
  version: 2.19.2
  url: https://github.com/timescale/timescaledb/archive/refs/tags/2.19.2.tar.gz
  repo_url: https://github.com/timescale/timescaledb
  commit_id: d454524eb6ef63196e3d22bc8a2e3cdf0719cfaf
  spdx:
    package:
      detailed_description: TimescaleDB is a database for making SQL more scalable
        for time-series data. It is engineered up from PostgreSQL, providing automatic
        partitioning across time and space (partitioning key), as well as full SQL
        support.
      home_page: https://www.timescale.com
      license_concluded: MIT AND Python-2.0 AND BSD-3-Clause AND Apache-2.0 AND PostgreSQL
      license_declared: MIT AND Python-2.0 AND BSD-3-Clause AND Apache-2.0 AND PostgreSQL
      short_summary: A PostgreSQL extension for high-performance real-time analytics
      supplier: 'Organization: Broadcom, Inc.'

- archive: timescaledb-2.20.2.tar.gz
  archive_sha512sum: e466832872fc59c5580d2c5d12d9d1860b64cb92cd43068121912c03643c8914a536aea0c8ca5445eac32ae2d77adca925206ddcb3743a48464c2c63a21f656e
  name: timescaledb-2.20.2
  version: 2.20.2
  archive_type: upstream
  url: https://github.com/timescale/timescaledb/archive/refs/tags/2.20.2.tar.gz
  repo_url: https://github.com/timescale/timescaledb
  commit_id: b7c7cd02585388ac6b555097ef8831c1217cc402
  spdx:
    package:
      detailed_description: TimescaleDB is a database for making SQL more scalable
        for time-series data. It is engineered up from PostgreSQL, providing automatic
        partitioning across time and space (partitioning key), as well as full SQL
        support.
      home_page: https://www.timescale.com
      license_concluded: Apache-2.0 AND MIT AND PostgreSQL AND Python-2.0 AND BSD-3-Clause
      license_declared: Apache-2.0 AND MIT AND PostgreSQL AND Python-2.0 AND BSD-3-Clause
      short_summary: A PostgreSQL extension for high-performance real-time analytics
      supplier: 'Organization: Broadcom, Inc.'


- archive: timescaledb-2.25.0.tar.gz
  archive_sha512sum: ff2542f91f7321410fd22eeb8c89bbcbb49793a602d52a80d8ffec41dfe6adb9974831c939405ec0702ad168e216d84d9686300ef3b7d7ec72f361c174258955
  name: timescaledb-2.25.0
  version: 2.25.0
  archive_type: upstream
  url: https://github.com/timescale/timescaledb/archive/refs/tags/2.25.0.tar.gz
  repo_url: https://github.com/timescale/timescaledb
  commit_id: a686498674d7a6c3bc36bdf665d464e5f371bd25
  spdx:
    package:
      detailed_description: TimescaleDB is a database for making SQL more scalable
        for time-series data. It is engineered up from PostgreSQL, providing automatic
        partitioning across time and space (partitioning key), as well as full SQL
        support.
      home_page: https://www.timescale.com
      license_concluded: Apache-2.0 AND MIT AND PostgreSQL AND Python-2.0 AND BSD-3-Clause
      license_declared: Apache-2.0 AND MIT AND PostgreSQL AND Python-2.0 AND BSD-3-Clause
      short_summary: A PostgreSQL extension for high-performance real-time analytics
      supplier: 'Organization: Broadcom, Inc.'
