sources:
- archive: rsync-3.4.4.tar.gz
  archive_type: upstream
  archive_sha512sum: cf9a838b1f019b70fd67fa2c293f267be3f24e579c2ea33177ec7afc502c97ce0b613ff0854088c0eb28acd14ee0a75706ae8445115cef4669bd586c505d8453
  name: rsync-3.4.4
  version: 3.4.4
  url: https://github.com/RsyncProject/rsync/releases/download/v3.4.4/rsync-3.4.4.tar.gz
  repo_url: https://github.com/RsyncProject/rsync.git
  commit_id: f26f747b8017b321d3776becc69f330dd889fa21
  skip_list: ['release.py']
  missing: ['.github', 'aclocal.m4', 'config.h.in', 'configure.sh', 'rrsync.1', 'rrsync.1.html', 'rsync-ssl.1', 'rsync-ssl.1.html', 'rsync.1', 'rsync.1.html', 'rsyncd.conf.5', 'rsyncd.conf.5.html']
  license_manual_review:
  # Optional - only needed if copied from this archive to the final build directory
  - file_paths:
    - rsync-3.4.4/lib/sysacls.c
    sha256sum: 99c3a32dec83217e6eb7481c0ce959563b5c17100a57a22e0daf75fabdb90f15
    spdx_exp: GPL-3.0-or-later
  skip_validation: true
  spdx:
    package:
      detailed_description: Rsync is a fast and extraordinarily versatile file copying
        tool. It can copy locally, to/from another host over any remote shell, or
        to/from a remote rsync daemon.
      home_page: https://rsync.samba.org
      license_concluded: Zlib AND GPL-3.0-only AND FSFUL AND GPL-1.0-or-later AND
        ISC AND GPL-2.0-or-later AND PostgreSQL AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-2.0-only AND snprintf AND AGPL-3.0-or-later AND GPL-3.0-or-later AND
        FSFULLRWD AND X11
      license_declared: Zlib AND GPL-3.0-only AND FSFUL AND GPL-1.0-or-later AND ISC
        AND GPL-2.0-or-later AND PostgreSQL AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-2.0-only AND snprintf AND AGPL-3.0-or-later AND GPL-3.0-or-later AND
        FSFULLRWD AND X11
      short_summary: Fast incremental file transfer.
      supplier: 'Organization: Broadcom, Inc.'
