sources:
- archive: traces-0.15.2.gem
  archive_sha512sum: 95147024783dc94c03bd86c2e6e48d494f9ce528d88d72c7bdf67bb9e7a5539dc67f64659b90ffb550b00835aa689cc3c920fac6124b86f5783f148044361b63
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Provides low level cross-platform primitives for constructing
        event loops, with support for select, kqueue, epoll and io_uring. '
      home_page: https://rubygems.org/gems/traces/versions/0.11.1
      license_concluded: MIT
      license_declared: MIT
      short_summary: An event loop.
      supplier: 'Organization: Broadcom, Inc.'
