sources:
- archive: traces-0.18.2.gem
  archive_sha512sum: 6b7882d1ace11f9df7df9b70b02c43908bfd90d06f7ea5ed4ab20f405e98142689c7272a99406c12e57e938a2abeb11979fb4f2dfcc248e9f6d8d910dd819519
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Provides low level cross-platform primitives for constructing
        event loops, with support for select, kqueue, epoll and io_uring. '
      home_page: https://rubygems.org/gems/traces/versions/0.18.2
      license_concluded: MIT
      license_declared: MIT
      short_summary: An event loop.
      supplier: 'Organization: Broadcom, Inc.'
