sources:
- archive: docker-buildx-0.34.1.tar.gz
  archive_type: upstream
  name: buildx-0.34.1
  url: https://github.com/docker/buildx/archive/refs/tags/v0.34.1.tar.gz
  archive_sha512sum: be69ff92a136e169456710c369099bd33ed0ae17271133fe0322fe1664c868ad76dd74265879fa783fa257a6ed6dca37c213d1153de9e903833b59cde4181d0b
  commit_id: e0b0e77d18d3379bc1e0d55f3b37de288d36fe47
  repo_url: https://github.com/docker/buildx.git
  version: '0.34.1'
  skip_list: []
  missing: []
  skip_validation: false
  license_manual_review:
  - # CC-BY-SA covers the README and CONTRIBUTING.md only, neither of which are
    # packaged by us
    file_paths:
    - buildx-0.32.0/vendor/github.com/opencontainers/go-digest/README.md
    sha256sum: cde5e79ad3a2c65cd30a5df53b0f990480ab632e9305065a8162ea204d7e297b
    spdx_exp: 'Apache-2.0'
  - # CC-BY-SA doesn't apply to any files we package (no docs)
    file_paths:
    - buildx-0.32.0/vendor/github.com/opencontainers/go-digest/LICENSE.docs
    sha256sum: a1d1adec3ba691ef6e377a78bbe9e9e2501f2f4a1723d08857da1ac6564e4fed
    spdx_exp: ''
  spdx:
    package:
      detailed_description: 'Docker CLI plugin for extended build capabilities with
        BuildKit. '
      home_page: https://github.com/docker/buildx
      license_concluded: Unicode-DFS-2016 AND GPL-1.0-or-later AND MIT AND MPL-2.0
        AND JSON AND BSD-2-Clause AND ISC AND BSD-3-Clause AND CC0-1.0 AND CC-BY-SA-4.0
        AND Apache-2.0
      license_declared: Unicode-DFS-2016 AND GPL-1.0-or-later AND MIT AND MPL-2.0
        AND JSON AND BSD-2-Clause AND ISC AND BSD-3-Clause AND CC0-1.0 AND CC-BY-SA-4.0
        AND Apache-2.0
      short_summary: Docker CLI plugin for extended build capabilities with BuildKit
      supplier: 'Organization: Broadcom, Inc.'
