sources:
- archive: sphinxcontrib_applehelp-2.0.0.tar.gz
  archive_sha512sum: 8fefd599e413f1e9e53fa62a0fbeafed8ac231e18805e56950d45fe9eda670051dea6a938aea5df58c8fc93f61d524a129495fc4c609fcba7653ba1511d6bc6b
  skip_validation: true
  spdx:
    package:
      detailed_description: 'sphinxcontrib-applehelp is a sphinx extension which outputs
        Apple help books.'
      home_page: https://pypi.org/project/sphinxcontrib-applehelp
      license_concluded: BSD-2-Clause AND BSD-3-Clause
      license_declared: BSD-2-Clause AND BSD-3-Clause
      short_summary: Sphinx extension for Apple help books
      supplier: 'Organization: Broadcom, Inc.'
