sources:
- archive: tdnf-3.5.14.tar.gz
  archive_type: upstream
  archive_sha512sum: d83017b188bd97795154a310075b7b0a802b7967a5ef7eefc1ab5312fefc005f8334eb24091fdbc40ca38b472cfc93ff02d75bc5fbcc1668a99f9dbd00b80de1
  version: 3.5.14
  name: tdnf-3.5.14
  url: https://github.com/vmware/tdnf/archive/refs/tags/v3.5.14.tar.gz
  repo_url: https://github.com/vmware/tdnf.git
  commit_id: fc64fe7f3474689b0c27217b532565787a53d324
  spdx:
    package:
      detailed_description: tdnf - tiny dandified yum
      home_page: https://github.com/vmware/tdnf
      license_concluded: GPL-2.0-only AND BSD-3-Clause AND LGPL-2.1-or-later AND LGPL-2.1-only
      license_declared: GPL-2.0-only AND BSD-3-Clause AND LGPL-2.1-or-later AND LGPL-2.1-only
      short_summary: tdnf - tiny dandified yum
      supplier: 'Organization: Broadcom, Inc.'
