sources:
- archive: tdnf-3.5.12.tar.gz
  archive_type: upstream
  archive_sha512sum: afc960c5d874b5fa04c0dcc342b6c6b371c98cb1f058c8bef3e4e3377edf32ccb826b33a82839aae921c15754ed12d4bced98add6f037945bdc95f37e51a90e8
  version: 3.5.12
  name: tdnf-3.5.12
  url: https://github.com/vmware/tdnf/archive/refs/tags/v3.5.12.tar.gz
  repo_url: https://github.com/vmware/tdnf.git
  commit_id: 177057a492860d631568a197e64644db71b55b0f
  spdx:
    package:
      detailed_description: tdnf - tiny dandified yum
      home_page: https://github.com/vmware/tdnf
      license_concluded: GPL-2.0-only AND BSD-3-Clause AND LGPL-2.1-or-later AND LGPL-2.1-only
      license_declared: GPL-2.0-only AND BSD-3-Clause AND LGPL-2.1-or-later AND LGPL-2.1-only
      short_summary: tdnf - tiny dandified yum
      supplier: 'Organization: Broadcom, Inc.'
