sources:
- archive: tdnf-3.5.11.tar.gz
  archive_type: upstream
  archive_sha512sum: 8e739ccd34be84d78a03bd7e92c139739e8be031cba7bba012f806e8d11655ea8f9edf4416b8abf1b7a7072c5231f18e5995b8c381f0f85a5ac323c721759f1b
  version: 3.5.11
  name: tdnf-3.5.11
  url: https://github.com/vmware/tdnf/archive/refs/tags/v3.5.11.tar.gz
  repo_url: https://github.com/vmware/tdnf.git
  commit_id: fb924f8693f9dcea8c43f0193d944e15ecb4178d
  spdx:
    package:
      detailed_description: tdnf - tiny dandified yum
      home_page: https://github.com/vmware/tdnf
      license_concluded: GPL-2.0-only AND BSD-3-Clause AND LGPL-2.1-or-later AND LGPL-2.1-only
      license_declared: GPL-2.0-only AND BSD-3-Clause AND LGPL-2.1-or-later AND LGPL-2.1-only
      short_summary: tdnf - tiny dandified yum
      supplier: 'Organization: Broadcom, Inc.'
