sources:
- archive: tdnf-3.5.13.tar.gz
  archive_type: upstream
  archive_sha512sum: d79cc4407b19f7a1412f8d44152bf8134eb9863339f0255e98fdfc4653ec62ee7ced7affa5b3f9d1290cf29e29ac81273e08439573aa6160fec92eb123eb6362
  version: 3.5.13
  name: tdnf-3.5.13
  url: https://github.com/vmware/tdnf/archive/refs/tags/v3.5.13.tar.gz
  repo_url: https://github.com/vmware/tdnf.git
  commit_id: 6ff457fe4500e00d4c0040e809852837fa864f3e
  spdx:
    package:
      detailed_description: tdnf - tiny dandified yum
      home_page: https://github.com/vmware/tdnf
      license_concluded: GPL-2.0-only AND BSD-3-Clause AND LGPL-2.1-or-later AND LGPL-2.1-only
      license_declared: GPL-2.0-only AND BSD-3-Clause AND LGPL-2.1-or-later AND LGPL-2.1-only
      short_summary: tdnf - tiny dandified yum
      supplier: 'Organization: Broadcom, Inc.'
