sources:
- archive: OTP-27.3.4.10.tar.gz
  archive_sha512sum: 4234947c74b0bd74f899b0026a6c6977da82d19bcd661e3fc66a3c0573490640f7e808fff7971ac6c5a30573647240b20af1b6958e5a4c2b237e9f15589e0931
  archive_type: upstream
  name: otp-OTP-27.3.4.10
  version: 27.3.4.10
  url: https://github.com/erlang/otp/archive/refs/tags/OTP-27.3.4.10.tar.gz
  repo_url: https://github.com/erlang/otp
  commit_id: 0aa261a7765c9698aabc7f7c5be878a8850a9c5f
  skip_list:
  - .gitattributes
  - .gitignore
  spdx:
    package:
      detailed_description: 'Erlang is a general-purpose programming language and
        runtime environment. Erlang has built-in support for concurrency, distribution
        and fault tolerance. Erlang is used in several large telecommunication systems
        from Ericsson.'
      home_page: https://www.erlang.org
      license_concluded: (MIT OR GPL-2.0-only) AND (Apache-2.0 OR LGPL-2.1-or-later)
        AND (Apache-2.0 OR BSL-1.0) AND MIT AND TCL AND CC0-1.0 AND BSL-1.0 AND BSD-3-Clause
        AND Zlib AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND Apache-2.0
        WITH LLVM-exception AND OpenSSL AND LGPL-2.1-or-later AND FSFUL AND LGPL-2.0-or-later
        WITH WxWindows-exception-3.1 AND Apache-2.0 AND MPL-1.0 AND X11 AND BSD-2-Clause
        AND GPL-1.0-or-later AND Unlicense
      license_declared: (MIT OR GPL-2.0-only) AND (Apache-2.0 OR LGPL-2.1-or-later)
        AND (Apache-2.0 OR BSL-1.0) AND MIT AND TCL AND CC0-1.0 AND BSL-1.0 AND BSD-3-Clause
        AND Zlib AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND Apache-2.0
        WITH LLVM-exception AND OpenSSL AND LGPL-2.1-or-later AND FSFUL AND LGPL-2.0-or-later
        WITH WxWindows-exception-3.1 AND Apache-2.0 AND MPL-1.0 AND X11 AND BSD-2-Clause
        AND GPL-1.0-or-later AND Unlicense
      short_summary: erlang
      supplier: 'Organization: Broadcom, Inc.'
