sources:
- archive: OTP-27.3.4.11.tar.gz
  archive_sha512sum: 3250045151b05779e340a3ed719b664295e852faed009be20bb80b71afc29c780b7108e619046733f12704451b450e70b1986f1d4d9df7cde3b5740fe72ee560
  archive_type: upstream
  name: otp-OTP-27.3.4.11
  version: 27.3.4.11
  url: https://github.com/erlang/otp/archive/refs/tags/OTP-27.3.4.11.tar.gz
  repo_url: https://github.com/erlang/otp
  commit_id: c0ce26bb20ab5fcd6e214fa285aec5a409772e61
  skip_list:
  - .gitattributes
  - .gitignore
  spdx:
    package:
      detailed_description: 'Erlang is a general-purpose programming language and
        runtime environment. Erlang has built-in support for concurrency, distribution
        and fault tolerance. Erlang is used in several large telecommunication systems
        from Ericsson.'
      home_page: https://www.erlang.org
      license_concluded: (MIT OR GPL-2.0-only) AND (Apache-2.0 OR LGPL-2.1-or-later)
        AND (Apache-2.0 OR BSL-1.0) AND MIT AND TCL AND CC0-1.0 AND BSL-1.0 AND BSD-3-Clause
        AND Zlib AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND Apache-2.0
        WITH LLVM-exception AND OpenSSL AND LGPL-2.1-or-later AND FSFUL AND LGPL-2.0-or-later
        WITH WxWindows-exception-3.1 AND Apache-2.0 AND MPL-1.0 AND X11 AND BSD-2-Clause
        AND GPL-1.0-or-later AND Unlicense
      license_declared: (MIT OR GPL-2.0-only) AND (Apache-2.0 OR LGPL-2.1-or-later)
        AND (Apache-2.0 OR BSL-1.0) AND MIT AND TCL AND CC0-1.0 AND BSL-1.0 AND BSD-3-Clause
        AND Zlib AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND Apache-2.0
        WITH LLVM-exception AND OpenSSL AND LGPL-2.1-or-later AND FSFUL AND LGPL-2.0-or-later
        WITH WxWindows-exception-3.1 AND Apache-2.0 AND MPL-1.0 AND X11 AND BSD-2-Clause
        AND GPL-1.0-or-later AND Unlicense
      short_summary: erlang
      supplier: 'Organization: Broadcom, Inc.'
