sources:
- archive: OTP-27.3.4.15.tar.gz
  archive_sha512sum: abb5d50390ced87bd39f87d1f3fb1bfb70b16c034b35e0fa0d07ef5149b3bdf2ceef8c88bb8d8f52200dc42ea1a6d5dcff18319c6f2751fbc8663dbbdaca1adf
  archive_type: upstream
  name: otp-OTP-27.3.4.15
  version: 27.3.4.15
  url: https://github.com/erlang/otp/archive/refs/tags/OTP-27.3.4.15.tar.gz
  repo_url: https://github.com/erlang/otp
  commit_id: 30106b0ecf7264bfc1aa5a7e2011f3b999904ee8
  skip_list:
  - .gitattributes
  - .gitignore
  spdx:
    package:
      detailed_description: 'Erlang is a general-purpose programming language and
        runtime environment. Erlang has built-in support for concurrency, distribution
        and fault tolerance. Erlang is used in several large telecommunication systems
        from Ericsson.'
      home_page: https://www.erlang.org
      license_concluded: (MIT OR GPL-2.0-only) AND (Apache-2.0 OR LGPL-2.1-or-later)
        AND (Apache-2.0 OR BSL-1.0) AND MIT AND TCL AND CC0-1.0 AND BSL-1.0 AND BSD-3-Clause
        AND Zlib AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND Apache-2.0
        WITH LLVM-exception AND OpenSSL AND LGPL-2.1-or-later AND FSFUL AND LGPL-2.0-or-later
        WITH WxWindows-exception-3.1 AND Apache-2.0 AND MPL-1.0 AND X11 AND BSD-2-Clause
        AND GPL-1.0-or-later AND Unlicense
      license_declared: (MIT OR GPL-2.0-only) AND (Apache-2.0 OR LGPL-2.1-or-later)
        AND (Apache-2.0 OR BSL-1.0) AND MIT AND TCL AND CC0-1.0 AND BSL-1.0 AND BSD-3-Clause
        AND Zlib AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND Apache-2.0
        WITH LLVM-exception AND OpenSSL AND LGPL-2.1-or-later AND FSFUL AND LGPL-2.0-or-later
        WITH WxWindows-exception-3.1 AND Apache-2.0 AND MPL-1.0 AND X11 AND BSD-2-Clause
        AND GPL-1.0-or-later AND Unlicense
      short_summary: erlang
      supplier: 'Organization: Broadcom, Inc.'
