sources:
- archive: google-apis-core-1.0.2.gem
  archive_sha512sum: 1e42852539b989b478b9e24a9cc7a00bb4401eb67880c7735192d593ab0d0729269978d50fd50f791a465ba1e7a9343c4c7407374fcebddea3773cf035eb8231
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Common utility and base classes for legacy Google REST clients'
      home_page: https://rubygems.org/gems/google-apis-core
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: Common utility and base classes for legacy Google REST clients
      supplier: 'Organization: Broadcom, Inc.'
