# CVE patches shared across all Linux kernel flavours
# Patch range reserved: 3000–3999
# DO NOT add non-CVE patches to this file.

# Fix CVE-2017-1000252
Patch3000: KVM-Don-t-accept-obviously-wrong-gsi-values-via-KVM_.patch

# Fix CVE-2026-43083
Patch3001: 0001-net-ioam6-fix-OOB-and-missing-lock.patch

# Fix CVE-2025-68359
Patch3002: 0001-btrfs-fix-double-free-of-qgroup-record-after-failure.patch

# Fix CVE-2026-43101
Patch3003: 0001-ipv6-adopt-skb_dst_dev-and-skb_dst_dev_net-_rcu-help.patch
Patch3004: 0002-ipv6-ioam-fix-potential-NULL-dereferences-in-__ioam6.patch
