sources:
- archive: jinja2-3.1.6.tar.gz
  archive_sha512sum: bddd5e142f1462426c57b2efafdfafdfc6b66de257668707940896feae71eabdf19e0b6e34ef49b965153baf9b1eb59bb5a97349bb287ea0921dd2a751e967ab
  archive_type: upstream
  name: jinja2-3.1.6
  version: "3.1.6"
  url: https://files.pythonhosted.org/packages/df/bf/f7da0350254c0ed7c72f3e33cef02e048281fec7ecec5f032d4aac52226b/jinja2-3.1.6.tar.gz
  repo_url: https://github.com/pallets/jinja/
  commit_id: 15206881c006c79667fe5154fe80c01c65410679
  missing: ['.devcontainer', '.editorconfig', '.github', '.gitignore', '.pre-commit-config.yaml', '.readthedocs.yaml', 'CHANGES.rst', 'artwork', 'examples', 'scripts', 'PKG-INFO']
  skip_list: []
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Jinja2 is a template engine written in pure Python. It
        provides a Django inspired non-XML syntax but supports inline expressions
        and an optional sandboxed environment. '
      home_page: https://github.com/pallets/jinja
      license_concluded: BSD-3-Clause
      license_declared: BSD-3-Clause
      short_summary: A fast and easy to use template engine written in pure Python
      supplier: 'Organization: Broadcom, Inc.'
