sources:
- archive: unicode-display_width-3.2.0.gem
  archive_sha512sum: 6d8c51c6c728875a7ab6022c4106a8bc11572a5d9516d7252de2c6508d459bc9c236a1d9e09e8f20157b78820b30f511ddc5576ac10857d98a433f4cfbed1ce5
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Determines the monospace display width of a string in
        Ruby. Implementation based on EastAsianWidth.txt and other data, 100% in Ruby.
        Other than wcwidth(), which fulfills a similar purpose, it does not rely on
        the OS vendor to provide an up-to-date method for measuring string width. '
      home_page: https://github.com/janlelis/unicode-display_width
      license_concluded: MIT
      license_declared: MIT
      short_summary: Unicode::DisplayWidth.
      supplier: 'Organization: Broadcom, Inc.'
