# GN args template for the Headless Chrome library
#
# Add import to arg.gn in out directory and run gn gen on the directory to use.
# E.g. for out directory out/foo:
# echo 'import("//build/args/headless.gn")' > out/foo/args.gn
# gn gen out/foo
#
# Use gn args to add your own build preference args.
use_ozone = true
ozone_auto_platforms = false
ozone_platform = "headless"
angle_enable_vulkan = true
angle_enable_swiftshader = false
# Embed resource.pak into binary to simplify deployment.
headless_use_embedded_resources = true
# Disable headless commands support.
headless_enable_commands = false
# Don't use Prefs component, disabling access to Local State prefs.
headless_use_prefs = false
# Don't use Policy component, disabling all policies.
headless_use_policy = false
# Remove a dependency on a system fontconfig library.
use_bundled_fontconfig = true
# In order to simplify deployment we build ICU data file
# into binary.
icu_use_data_file = false
# Use embedded data instead external files for headless in order
# to simplify deployment.
v8_use_external_startup_data = false
#use_goma=false
enable_print_preview = false
enable_remoting = false
use_alsa = false
use_bluez = false
use_cups = false
use_dbus = false
use_gio = false
use_kerberos = false
use_libpci = false
use_pulseaudio = false
use_udev = false
rtc_use_pipewire = false
v8_enable_lazy_source_positions = false
use_glib = false
use_gtk = false
use_pangocairo = false

is_debug=false
is_official_build=true
symbol_level=0
blink_symbol_level=0
chrome_pgo_phase=0

is_component_build = false
dcheck_always_on = false
v8_enable_system_instrumentation=false
clang_use_chrome_plugins = false  # disable chromium plugin, not needed

# Headless mode
use_aura = true
use_gtk = false
use_glib = false
ozone_platform_headless = true
ozone_auto_platforms = false
ozone_platform_x11 = false
ozone_platform_wayland = false
ozone_platform_drm = false

# Disable GPU/ANGLE (software only)
angle_enable_vulkan = true

# Keep only V8 & PDF printing
enable_pdf = true

# Disable extras
enable_widevine = false
enable_remoting = false
enable_reporting = false
enable_mdns = false
enable_ipc_fuzzer = false

# Disable tests
rtc_include_tests = false
dcheck_always_on = false

build_dawn_tests=false
enable_perfetto_unittests=false
disable_fieldtrial_testing_config=true

v8_enable_fuzztest = false
v8_enable_test_features = false
angle_build_tests = false
build_angle_perftests = false
dawn_tests_use_angle = false
enable_nocompile_tests = false
enable_rust = true
enable_screen_ai_browsertests = false
gtest_enable_absl_printers = false
register_fuzztests_in_test_suites = false
rtc_build_dcsctp = false
skia_enable_skshaper_tests = false
tint_build_unittests = false
use_base_test_suite = false
use_fuzztest_wrapper = false
pdf_is_standalone = true
pdf_is_complete_lib = true
rtc_enable_sctp = false

use_libfuzzer=false
register_fuzztests_in_test_suites=false
