sources:
- archive: metrics-0.15.0.gem
  archive_sha512sum: 7d7f9bc1a0ddf06965c10c428be2f444dae2324cf1f9a0ce4c9d44a94a04d88ab82345fee67b9f1bf9ee29c85bd26f44c1bdefbe982e2b4dd46c8a83f88c8eba
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Collects and exposes metrics from Ruby applications'
      home_page: https://rubygems.org/gems/metrics
      license_concluded: MIT
      license_declared: MIT
      short_summary: Collects and exposes metrics from Ruby applications
      supplier: 'Organization: Broadcom, Inc.'
