sources:
- archive: constantly-23.10.4.tar.gz
  archive_sha512sum: 14c99ec39cf5ec588d24818ca56909ed59c646093fbf1d061a8a6e6bec8e7258c64dafd346e0dbb8aeef35260fe1e03efa649150b60b1fd3e7865fa59e96ce49
  archive_type: upstream
  skip_validation: false
  name: constantly-23.10.4
  version: "23.10.4"
  url: https://files.pythonhosted.org/packages/4d/6f/cb2a94494ff74aa9528a36c5b1422756330a75a8367bf20bd63171fc324d/constantly-23.10.4.tar.gz
  repo_url: https://github.com/twisted/constantly
  commit_id: c63aa51794c314778b5699dd1cec9b3547fe6911
  missing: ['tox.ini', '.travis.yml', 'constantly.egg-info', '.coveragerc', '.github', '.gitattributes', 'setup.cfg', 'PKG-INFO', 'admin', '.gitignore', 'docs']
  skip_list: ['_version.py']
  spdx:
    package:
      detailed_description: 'A library that provides symbolic constant support. It
        includes collections and constants with text, numeric, and bit flag values.
        Originally twisted.python.constants from the Twisted project. '
      home_page: https://pypi.python.org/pypi/constantly
      license_concluded: MIT
      license_declared: MIT
      short_summary: Symbolic constants in Python.
      supplier: 'Organization: Broadcom, Inc.'
