sources:
- archive: console-1.34.2.gem
  archive_sha512sum: 3fcd1d2dd8c96c4bf92d6163401ffbacca3619069a51406954cc52351c00c7bd2fac6d66b306b1256c6b691cd0ebb2ca298728e8a92eb5c25c65455e69abaf8c
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Provides beautiful console logging for Ruby applications.
        Implements fast, buffered log output. '
      home_page: https://rubygems.org/gems/console/versions/1.34.2
      license_concluded: MIT
      license_declared: MIT
      short_summary: Beautiful logging for Ruby.
      supplier: 'Organization: Broadcom, Inc.'
