FROM k8s-base-image:2.0

MAINTAINER kulkarniv@vmware.com

# Minimum Docker API version required for libnetwork.
ENV DOCKER_API_VERSION 1.21

# Install required packages
COPY [ "./stage-rpms-tdnf.conf", "./tmp/stage-rpms.repo", "/tmp/tdnf/" ]
RUN tdnf -c /tmp/tdnf/stage-rpms-tdnf.conf install -y initscripts iproute2 \
         net-tools ipset iptables iputils runit --refresh

# Copy binaries needed by calico/node
COPY [ "./tmp/calico/usr/share/calico/docker/fs/etc", "/etc/" ]
COPY [ "./tmp/calico/usr/share/calico/docker/fs/sbin/restart-calico-confd", \
       "./tmp/calico/usr/share/calico/docker/fs/sbin/start_runit", \
       "./tmp/calico/usr/share/calico/docker/fs/sbin/versions", \
       "/usr/sbin/" ]
COPY [ "./tmp/calico/usr/bin/allocate-ipip-addr", \
       "./tmp/calico/usr/bin/startup", \
       "./tmp/calico/usr/bin/calico-bgp-daemon", \
       "./tmp/calico/usr/bin/gobgp", \
       "./tmp/calico/usr/bin/bird", \
       "./tmp/calico/usr/bin/bird6", \
       "./tmp/calico/usr/bin/birdcl", \
       "./tmp/calico/usr/bin/confd", \
       "./tmp/calico/usr/bin/calico-felix", \
       "./tmp/calico/usr/share/calico/docker/libnetwork-plugin", \
       "/usr/bin/" ]

CMD ["start_runit"]
