FROM k8s-base-image:3.0

MAINTAINER kulkarniv@vmware.com

COPY [ "./tmp/calico/opt/cni/bin/calico", \
       "./tmp/calico/opt/cni/bin/calico-ipam", \
       "./tmp/calico/opt/cni/bin/portmap", \
       "./tmp/calico/opt/cni/bin/flannel", \
       "./tmp/calico/opt/cni/bin/host-local", \
       "./tmp/calico/opt/cni/bin/loopback", \
       "/opt/cni/bin/" ]
COPY ./tmp/calico/usr/share/calico-cni/k8s/install-cni.sh /install-cni.sh
COPY ./tmp/calico/usr/share/calico-cni/k8s/calico.conf.default /calico.conf.tmp

ENV PATH=$PATH:/opt/cni/bin
VOLUME /opt/cni
WORKDIR /opt/cni/bin
CMD ["/opt/cni/bin/calico"]
