sources:
- archive: libselinux-3.10.tar.gz
  archive_sha512sum: 
    5783f737675eb94e0bdff082013589e5bddfa0669a357df185eb89f4f88cec8b90779e86c4b17b58f5c248175da0208c80cc2642046e348c7384dd799f1ba4c1
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Security-enhanced Linux is a feature of the Linux® kernel
        and a number of utilities with enhanced security functionality designed to
        add mandatory access controls to Linux.  The Security-enhanced Linux kernel
        contains new architectural components originally developed to improve the
        security of the Flask operating system. These architectural components provide
        general support for the enforcement of many kinds of mandatory access control
        policies, including those based on the concepts of Type Enforcement®, Role-based
        Access Control, and Multi-level Security.  libselinux provides an API for
        SELinux applications to get and set process and file security contexts and
        to obtain security policy decisions.  Required for any applications that use
        the SELinux API. '
      home_page: https://github.com/SELinuxProject/selinux/wiki
      license_concluded: GPL-2.0-only AND libselinux-1.0
      license_declared: GPL-2.0-only AND libselinux-1.0
      short_summary: SELinux library and simple utilities
      supplier: 'Organization: Broadcom, Inc.'
