sources:
- archive: libselinux-3.5.tar.gz
  archive_type: upstream
  archive_sha512sum: 4e13261a5821018a5f3cdce676f180bb62e5bc225981ca8a498ece0d1c88d9ba8eaa0ce4099dd0849309a8a7c5a9a0953df841a9922f2c284e5a109e5d937ba7
  skip_validation: false
  version: "3.5"
  name: libselinux-3.5
  url: https://github.com/SELinuxProject/selinux/releases/download/3.5/libselinux-3.5.tar.gz
  repo_url: https://github.com/SELinuxProject/selinux
  commit_id: d6e96c5929a3f1aa1dce93505edd9f0158757ac2
  skip_list: ['LICENSE', 'Makefile']
  missing: ['sandbox', 'restorecond', 'dbus', '.gitignore', 'policycoreutils', 'semodule-utils', 'scripts', 'CONTRIBUTING.md', 'utils', 'SECURITY.md', 'gui', 'lgtm.yml', '.circleci', 'man', 'include', 'CleanSpec.mk', 'mcstrans', 'libsepol', 'secilc', '.travis.yml', 'src', 'python', 'libselinux', 'libsemanage', 'checkpolicy', 'README.md', '.github']
  spdx:
    package:
      detailed_description: "Security-enhanced Linux is a feature of the Linux\xAE\
        \ kernel and a number of utilities with enhanced security functionality designed\
        \ to add mandatory access controls to Linux.  The Security-enhanced Linux\
        \ kernel contains new architectural components originally developed to improve\
        \ the security of the Flask operating system. These architectural components\
        \ provide general support for the enforcement of many kinds of mandatory access\
        \ control policies, including those based on the concepts of Type Enforcement\xAE\
        , Role-based Access Control, and Multi-level Security.  libselinux provides\
        \ an API for SELinux applications to get and set process and file security\
        \ contexts and to obtain security policy decisions.  Required for any applications\
        \ that use the SELinux API. "
      home_page: https://github.com/SELinuxProject/selinux/wiki
      license_concluded: libselinux-1.0 AND GPL-2.0-only
      license_declared: libselinux-1.0 AND GPL-2.0-only
      short_summary: SELinux library and simple utilities
      supplier: 'Organization: Broadcom, Inc.'
