sources:
- archive: ansible-posix-2.0.0.tar.gz
  archive_sha512sum: 30e71afefc7415d04ac46eb32ce247b01c3f8c074f8ed72f6c9ca355f2018a1617161826d6f2ac40e0b8cb5d99048c866f58777a1b9c093fd2fbc5290799cbe6
  skip_validation: true
  spdx:
    package:
      detailed_description: 'An Ansible Collection of modules and plugins that target
        POSIX UNIX/Linux and derivative Operating Systems. '
      home_page: https://github.com/ansible-collections/ansible.posix
      license_concluded: GPL-3.0-only AND GPL-3.0-or-later AND Python-2.0 AND GPL-1.0-or-later
      license_declared: GPL-3.0-only AND GPL-3.0-or-later AND Python-2.0 AND GPL-1.0-or-later
      short_summary: Ansible Collection targeting POSIX and POSIX-ish platforms
      supplier: 'Organization: Broadcom, Inc.'
