sources:
- archive: nio4r-2.7.5.gem
  archive_sha512sum: 9be8d843506807b279d63f3521f369d036fbc8dfb09578f5ef7eb9378c2b2e5bf00fed14e9bed18188b80346f1b39272ef68c97ba597852e1e23751731eb61c6
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Cross-platform asynchronous I/O primitives for scalable network clients and servers. Inspired by the Java NIO API, but simplified for ease-of-use. '
      home_page: https://rubygems.org/gems/nio4r/versions/2.7.5
      license_concluded: (BSD-2-Clause OR GPL-2.0-or-later) AND BSD-2-Clause AND MIT
      license_declared: (BSD-2-Clause OR GPL-2.0-or-later) AND BSD-2-Clause AND MIT
      short_summary: Cross-platform asynchronous I/O primitives for scalable network clients and servers.
      supplier: 'Organization: Broadcom, Inc.'
