sources:
- archive: nokogiri-1.18.8.gem
  archive_sha512sum: 972f5d3aba21a2e9baa373c19344dcc4fe6bc6190b1ae7b6eccd34af5d4be025df1172c57e25ae82b4b3e71d95fd418e5e7a8e981958da6ff34a240ea90a4040
  skip_validation: true
  license_manual_review:
  - file_paths:
    - nokogiri-1.18.8/ports/archives/libxml2-2.13.8.tar.xz-extract/libxml2-2.13.8/test/schemas/changelog093_1.xsd
    sha256sum: 415769142ed8530e213000b9e3430bf702d372822ec0c8164691a4bdd34088a2
    spdx_exp: ''
  - file_paths:
    - nokogiri-1.18.8/ports/archives/libxml2-2.13.8.tar.xz-extract/libxml2-2.13.8/result/intsubset2.xml
    sha256sum: a243b10390a9a6d3316a08c1c520f27051756602931965a1cea1a8780fb9edba
    spdx_exp: ''
  - file_paths:
    - nokogiri-1.18.8/ports/archives/libxml2-2.13.8.tar.xz-extract/libxml2-2.13.8/result/noent/intsubset2.xml.sax2
    sha256sum: 92eefb73d7f167dc8c19ed6ed412625a0e490d150b9b2786e3e962f1c52d677c
    spdx_exp: ''
  - file_paths:
    - nokogiri-1.18.8/ports/archives/libxml2-2.13.8.tar.xz-extract/libxml2-2.13.8/result/noent/intsubset2.xml
    sha256sum: a243b10390a9a6d3316a08c1c520f27051756602931965a1cea1a8780fb9edba
    spdx_exp: ''
  - file_paths:
    - nokogiri-1.18.8/ports/archives/libxml2-2.13.8.tar.xz-extract/libxml2-2.13.8/result/intsubset2.xml.sax2
    sha256sum: 92eefb73d7f167dc8c19ed6ed412625a0e490d150b9b2786e3e962f1c52d677c
    spdx_exp: ''
  - file_paths:
    - nokogiri-1.18.8/ports/archives/libxml2-2.13.8.tar.xz-extract/libxml2-2.13.8/result/intsubset2.xml.sax
    sha256sum: 3225772007aa0c92dea1e3b4121fc6fda2b61614fbb5081b3b9a08ebfef498b6
    spdx_exp: ''
  - file_paths:
    - nokogiri-1.18.8/ports/archives/libxml2-2.13.8.tar.xz-extract/libxml2-2.13.8/test/intsubset2.xml
    sha256sum: 817a075583738093b43723ecf4bbd5663625e84cdbf5e7d71e3cce2fd0aeacb2
    spdx_exp: ''
  - file_paths:
    - nokogiri-1.18.8/ports/archives/libxml2-2.13.8.tar.xz-extract/libxml2-2.13.8/result/intsubset2.xml.rde
    sha256sum: eadcd256c7648c434af64f0b76227e61c916fc70632ae43040c75988b0df23ac
    spdx_exp: ''
  - file_paths:
    - nokogiri-1.18.8/ports/archives/libxml2-2.13.8.tar.xz-extract/libxml2-2.13.8/result/intsubset2.xml.rdr
    sha256sum: eadcd256c7648c434af64f0b76227e61c916fc70632ae43040c75988b0df23ac
    spdx_exp: ''
  spdx:
    package:
      detailed_description: "Nokogiri is an HTML, XML, SAX, and Reader parser. Among Nokogiri's many features is the ability to search documents via XPath or CSS3 selectors. "
      home_page: https://rubygems.org/gems/nokogiri/
      license_concluded: Apache-2.0 AND BSD-3-Clause AND CC-BY-SA-2.0 AND CC-BY-SA-4.0 AND FSFAP AND FSFUL AND FSFULLR AND FSFULLRWD AND GFDL-1.1-or-later AND GFDL-1.2-or-later AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND ISC-Veillard AND LGPL-2.0-only AND Latex2e-translated-notice AND MIT AND MPL-2.0 AND W3C-19980720 AND X11 AND Zlib
      license_declared: Apache-2.0 AND BSD-3-Clause AND CC-BY-SA-2.0 AND CC-BY-SA-4.0 AND FSFAP AND FSFUL AND FSFULLR AND FSFULLRWD AND GFDL-1.1-or-later AND GFDL-1.2-or-later AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND ISC-Veillard AND LGPL-2.0-only AND Latex2e-translated-notice AND MIT AND MPL-2.0 AND W3C-19980720 AND X11 AND Zlib
      short_summary: Nokogiri is an HTML, XML, SAX, and Reader parser.
      supplier: 'Organization: Broadcom, Inc.'
