sources:
- archive: dbus-python-1.4.0.tar.gz
  archive_sha512sum: 02294240589aeb8a25b1499ff492945fdb5f11e53925bafdac70e2073d73aa8a3bbf3aa4491eab8acd141569c51d6a1e2a25c36b5529826b71fac856fb6f4eea
  skip_validation: true
  url: https://files.pythonhosted.org/packages/source/d/dbus-python/dbus-python-1.4.0.tar.gz
  spdx:
    package:
      detailed_description: 'D-Bus python bindings for use with python programs. '
      home_page: http://www.freedesktop.org/wiki/Software/DBusBindings/
      license_concluded: (AFL-2.1 OR GPL-2.0-or-later) AND AFL-2.1 AND
        GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only AND GPL-3.0-or-later
        AND MIT
      license_declared: (AFL-2.1 OR GPL-2.0-or-later) AND AFL-2.1 AND
        GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only AND GPL-3.0-or-later
        AND MIT
      short_summary: Python bindings for D-Bus
      supplier: 'Organization: Broadcom, Inc.'
