sources:
- archive: monitoring-plugins-2.3.5.tar.gz
  archive_sha512sum: 7b24027003b7f46bef4a55f216b3cf20998385f3f91ecba7959f254748cac6d884012b7423087ba9f34fec2ceb9ffc1748e62f004befcc75953887cf4cb76df7
  archive_type: upstream
  name: monitoring-plugins-2.3.5
  url: https://github.com/monitoring-plugins/monitoring-plugins/archive/refs/tags/v2.3.5.tar.gz
  repo_url: https://github.com/monitoring-plugins/monitoring-plugins
  commit_id: 70e55c0a7a833365670113e6bef03d43377e8f6b
  skip_list: []
  missing: []
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Monitoring plugins maintains a bundle of more than 50
        standard plugins. Typically, the monitoring software runs these plugins to
        determine the current status of hosts and services on your network. Each plugin
        is a stand alone command line tool that provides a specific type to check. '
      home_page: https://github.com/monitoring-plugins
      license_concluded: (GPL-1.0-or-later OR Artistic-1.0-Perl) AND (GPL-1.0-or-later
        OR Artistic-1.0) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND BSD-2-Clause
        AND LGPL-2.0-or-later AND Artistic-2.0 AND Apache-1.1 AND FSFUL AND GPL-3.0-only
        AND GPL-2.0-or-later AND MPL-1.0 AND GPL-2.0-or-later WITH Libtool-exception
        AND MIT AND TMate AND GPL-3.0-or-later AND FSFULLR AND Artistic-1.0 AND OpenSSL
        AND GPL-2.0-only WITH Linux-syscall-note AND GPL-1.0-only AND GPL-1.0-or-later
        AND Apache-2.0 AND Zlib AND curl AND LGPL-2.1-or-later AND GFDL-1.1-or-later
        AND GPL-3.0-or-later WITH Autoconf-exception-generic AND ISC AND MPL-1.1 AND
        AGPL-3.0-or-later AND GPL-2.0-only AND Artistic-1.0-Perl AND BSD-3-Clause
      license_declared: (GPL-1.0-or-later OR Artistic-1.0-Perl) AND (GPL-1.0-or-later
        OR Artistic-1.0) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND BSD-2-Clause
        AND LGPL-2.0-or-later AND Artistic-2.0 AND Apache-1.1 AND FSFUL AND GPL-3.0-only
        AND GPL-2.0-or-later AND MPL-1.0 AND GPL-2.0-or-later WITH Libtool-exception
        AND MIT AND TMate AND GPL-3.0-or-later AND FSFULLR AND Artistic-1.0 AND OpenSSL
        AND GPL-2.0-only WITH Linux-syscall-note AND GPL-1.0-only AND GPL-1.0-or-later
        AND Apache-2.0 AND Zlib AND curl AND LGPL-2.1-or-later AND GFDL-1.1-or-later
        AND GPL-3.0-or-later WITH Autoconf-exception-generic AND ISC AND MPL-1.1 AND
        AGPL-3.0-or-later AND GPL-2.0-only AND Artistic-1.0-Perl AND BSD-3-Clause
      short_summary: Monitoring plugins are used to monitor status of hosts and services
        on the network
      supplier: 'Organization: Broadcom, Inc.'
