sources:
- archive: zope.interface-8.2.tar.gz
  archive_sha512sum: 9338ad23b2a1ab6c3af900058fb8bd8f94c48005107eaddf22740e53b2140b5e75541d2e73b83eb50b21f2c2fe9662f163b0be3703807de64030e553f994ae43
  archive_type: upstream
  skip_validation: false
  name: zope.interface-8.2
  version: "8.2"
  url: https://github.com/zopefoundation/zope.interface/archive/refs/tags/8.2.tar.gz
  repo_url: https://github.com/zopefoundation/zope.interface
  commit_id: 042df54deaf208f5308b02396a0bc3b6f1c459ee
  missing: []
  spdx:
    package:
      detailed_description: "This package is intended to be independently reusable\
        \ in any Python project. It is maintained by the Zope Toolkit project.  This\
        \ package provides an implementation of \u201Cobject interfaces\u201D for\
        \ Python. Interfaces are a mechanism for labeling objects as conforming to\
        \ a given API or contract. So, this package can be considered as implementation\
        \ of the Design By Contract methodology support in Python.  For detailed documentation,\
        \ please visit http://docs.zope.org/zope.interface "
      home_page: https://github.com/zopefoundation/zope.interface
      license_concluded: ZPL-2.1
      license_declared: ZPL-2.1
      short_summary: Interfaces for Python
      supplier: 'Organization: Broadcom, Inc.'
