sources:
- archive: kubernetes-1.36.1.tar.gz
  archive_type: upstream
  archive_sha512sum: 348d91a1e1068ee55a302ce1224b4d6db3d764d96595cdf0f46b31be4e0c57d8dbd29dd32aa23bbd6436e39dc0326f2a8c89ee660c44b38b3387636717be5422
  version: "1.36.1"
  name: kubernetes-1.36.1
  url: https://github.com/kubernetes/kubernetes/archive/refs/tags/v1.36.1.tar.gz
  repo_url: https://github.com/kubernetes/kubernetes
  commit_id: 756939600b9a7180fc2df6550a4585b638875e67
  skip_list: ['version.sh', 'base.go']
  missing: []
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Kubernetes is an open source implementation of container
        cluster management. '
      home_page: 
        https://github.com/kubernetes/kubernetes/archive/v1.27.13.tar.gz
      license_concluded: (BSD-3-Clause OR OpenSSL) AND Apache-2.0 AND 
        BSD-2-Clause AND BSD-3-Clause AND CC-BY-4.0 AND CC-BY-SA-4.0 AND 
        GPL-1.0-or-later AND ISC AND JSON AND MIT
      license_declared: (BSD-3-Clause OR OpenSSL) AND Apache-2.0 AND 
        BSD-2-Clause AND BSD-3-Clause AND CC-BY-4.0 AND CC-BY-SA-4.0 AND 
        GPL-1.0-or-later AND ISC AND JSON AND MIT
      short_summary: Kubernetes cluster management
      supplier: 'Organization: Broadcom, Inc.'
