sources:
- archive: subversion-1.14.5.tar.bz2
  archive_sha512sum: e4800564d0cc68be98f19aa58d89181de83f237f0ccff10824d9237f8c65eb0071f7176ac54e9e8f8ecbf685849bd3e94be48f678f4c23ed6a5fd7fb6edd0321
  skip_validation: true
  license_manual_review:
  - file_paths:
    - subversion-1.14.5/configure.ac
    sha256sum: d0cfd6c6e8368436342820fc280038652186607b4a16e11ca5a5162793192523
    spdx_exp: Apache-2.0
  - file_paths:
    - subversion-1.14.5/configure
    sha256sum: 6ef97bc66920aa8ee8b9a6f38dfcf12703bf1be0a72da96db7c74e95838c67f4
    spdx_exp: Apache-2.0
  spdx:
    package:
      detailed_description: The Apache version control system.
      home_page: http://subversion.apache.org
      license_concluded: GPL-3.0-or-later WITH Libtool-exception AND MIT AND FSFULLR
        AND HPND-Markus-Kuhn AND Unlicense AND Unicode-3.0 AND FSFUL AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND Apache-2.0 AND FSFAP AND AGPL-3.0-only
        AND BSD-3-Clause AND X11 AND BSD-2-Clause AND GPL-2.0-or-later WITH Libtool-exception
        AND GPL-3.0-or-later AND ICU
      license_declared: GPL-3.0-or-later WITH Libtool-exception AND MIT AND FSFULLR
        AND HPND-Markus-Kuhn AND Unlicense AND Unicode-3.0 AND FSFUL AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND Apache-2.0 AND FSFAP AND AGPL-3.0-only
        AND BSD-3-Clause AND X11 AND BSD-2-Clause AND GPL-2.0-or-later WITH Libtool-exception
        AND GPL-3.0-or-later AND ICU
      short_summary: The Apache Subversion control system
      supplier: 'Organization: Broadcom, Inc.'
