sources:
- archive: readline-8.2.tar.gz
  archive_sha512sum: 0a451d459146bfdeecc9cdd94bda6a6416d3e93abd80885a40b334312f16eb890f8618a27ca26868cebbddf1224983e631b1cbc002c1a4d1cd0d65fba9fea49a
  license_manual_review:
  # Optional - only needed if copied from this archive to the final build directory
  - file_paths:
    - readline-8.2/doc/rluserman.info
    sha256sum: 6d64db954627199edad6bf6cea65a026455a9dd72a342c3ce7e071d482ab4bf0
    spdx_exp: ''
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The Readline package is a set of libraries that offers
        command-line editing and history capabilities. '
      home_page: http://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
      license_concluded: BSD-3-Clause AND CC-BY-SA-4.0 AND FSFUL AND FSFULLR AND FSFULLRWD
        AND GFDL-1.1-or-later AND GFDL-1.3-only AND GFDL-1.3-or-later AND GPL-1.0-or-later
        AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND GPL-3.0-only AND GPL-3.0-or-later AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-3.0-or-later WITH Texinfo-exception AND HPND-Markus-Kuhn AND LGPL-2.1-or-later
        AND Latex2e AND Latex2e-translated-notice AND NTP AND OFL-1.1
      license_declared: BSD-3-Clause AND CC-BY-SA-4.0 AND FSFUL AND FSFULLR AND FSFULLRWD
        AND GFDL-1.1-or-later AND GFDL-1.3-only AND GFDL-1.3-or-later AND GPL-1.0-or-later
        AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND GPL-3.0-only AND GPL-3.0-or-later AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-3.0-or-later WITH Texinfo-exception AND HPND-Markus-Kuhn AND LGPL-2.1-or-later
        AND Latex2e AND Latex2e-translated-notice AND NTP AND OFL-1.1
      short_summary: Command-line editing and history capabilities
      supplier: 'Organization: Broadcom, Inc.'
