sources:
- archive: setuptools_scm-9.2.2.tar.gz
  archive_sha512sum: 757ca11a3d13601606b6914ea70e3d271d287f26ada976ec77334fc0f611208669585d2580994f1ddff830cd698a837d3e882dd5cdccdaf9f8eba34fdd8cb708
  skip_validation: true
  name: setuptools_scm-9.2.2
  version: "9.2.2"
  url: https://files.pythonhosted.org/packages/7b/b1/19587742aad604f1988a8a362e660e8c3ac03adccdb71c96d86526e5eb62/setuptools_scm-9.2.2.tar.gz
  repo_url: https://github.com/pypa/setuptools-scm
  commit_id: e56b78fcd4c1e79aa36c1e4700fca34c8ff540fe
  missing: ['nextgen', 'setup.cfg', 'PKG-INFO', 'setuptools_scm.egg-info', '.pre-commit-config.yaml', '.cursor', '.git_archival.txt', '.readthedocs.yaml']
  spdx:
    package:
      detailed_description: "setuptools_scm handles managing your python package versions\
        \ in scm metadata instead of declaring them as the version argument or in\
        \ a scm managed file.  It also handles file finders for the supported scm\u2019\
        s. "
      home_page: https://pypi.python.org/pypi/setuptools_scm
      license_concluded: MIT
      license_declared: MIT
      short_summary: the blessed package to manage your versions by scm tags.
      supplier: 'Organization: Broadcom, Inc.'
