sources:
- archive: aws-sdk-s3-1.185.0.gem
  archive_sha512sum: f5adf048971e42e987c6d9ef38e4ec703510c62640cde62871544e226a1db238d6fbf58ebc411d236f5f7c07297a3b727f5126e6f129de13c9170d0d1bad8ca8
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Official AWS Ruby gem for Amazon Simple Storage Service
        (Amazon S3). This gem is part of the AWS SDK for Ruby. '
      home_page: https://rubygems.org/gems/aws-sdk-s3/versions/1.185.0
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: Official AWS Ruby gem for Amazon Simple Storage Service (Amazon
        S3).
      supplier: 'Organization: Broadcom, Inc.'
