sources:
  - archive: ImageMagick-7.1.2-18.tar.gz
    archive_sha512sum: 168326e62c2ca5608a660e030b9777c7200458f9eb128854867e9bf20e1aa3d603a819aa3095fb3cf13133ceb9a9c9859374b7ce872bebb179c3afdf943ec831
    archive_type: upstream
    name: ImageMagick-7.1.2-18
    version: 7.1.2-18
    url: https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.2-18.tar.gz
    repo_url: https://github.com/ImageMagick/ImageMagick
    commit_id: d4e4b2b35a573fb7d96bc64ff1a417415bbe0f4c
    skip_list: []
    missing: []
    license_manual_review:
    - file_paths:
      - ImageMagick-7.1.2-18/MagickCore/nt-base.c
      sha256sum: 076aed9955e303213e2ccc1ba6a11ff62bd8a88b299d3daecc941e2cc239bec1
      spdx_exp: ""
    spdx:
      package:
        detailed_description: 'ImageMagick is a free, open-source software suite for creating, editing, converting, and displaying images.'
        short_summary: 'ImageMagick is a free, open-source software suite for creating, editing, converting, and displaying images.'
        home_page: https://imagemagick.org/
        license_concluded: BSD-2-Clause AND FSFAP AND FSFAP-no-warranty-disclaimer AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND IJG AND ImageMagick AND LGPL-3.0-only AND Libpng AND MIT AND X11
        license_declared: BSD-2-Clause AND FSFAP AND FSFAP-no-warranty-disclaimer AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND IJG AND ImageMagick AND LGPL-3.0-only AND Libpng AND MIT AND X11
        supplier: "Organization: Broadcom, Inc."
