sources:
  - archive: ImageMagick-7.1.2-19.tar.gz
    archive_sha512sum: be9d35e64828f727b6005f5c02740d85f25e1b3dee45403f0a19e702b00e418dcedf8fc159f03764ef251dcaa1dcd38fd04b41c356b30555a6c9f2f95486a9cb
    archive_type: upstream
    name: ImageMagick-7.1.2-19
    version: 7.1.2-19
    url: https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.2-19.tar.gz
    repo_url: https://github.com/ImageMagick/ImageMagick
    commit_id: 9fbd2b79450e930edb95e8158d412e57a7b27e83
    skip_list: []
    missing: []
    license_manual_review:
    - file_paths:
      - ImageMagick-7.1.2-19/MagickCore/nt-base.c
      sha256sum: 076aed9955e303213e2ccc1ba6a11ff62bd8a88b299d3daecc941e2cc239bec1
      spdx_exp: ""
    spdx:
      package:
        detailed_description: 'ImageMagick is a free, open-source software suite for creating, editing, converting, and displaying images.'
        short_summary: 'ImageMagick is a free, open-source software suite for creating, editing, converting, and displaying images.'
        home_page: https://imagemagick.org/
        license_concluded: BSD-2-Clause AND FSFAP AND FSFAP-no-warranty-disclaimer AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND IJG AND ImageMagick AND LGPL-3.0-only AND Libpng AND MIT AND X11
        license_declared: BSD-2-Clause AND FSFAP AND FSFAP-no-warranty-disclaimer AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND IJG AND ImageMagick AND LGPL-3.0-only AND Libpng AND MIT AND X11
        supplier: "Organization: Broadcom, Inc."
