sources:
- archive: async-http-0.94.0.gem
  archive_sha512sum: 337bacad179df596cc67c07cd1f79c6ce844d88a033f9d10791a4824a51615c5fdcd4f2998c199215268092495104279074631d56e1040c09219425bb780add7
  skip_validation: true
  spdx:
    package:
      detailed_description: 'An asynchronous client and server implementation of HTTP/1.0,
        HTTP/1.1 and HTTP/2 including TLS. Support for streaming requests and responses.
        Built on top of async and async-io. falcon provides a rack-compatible server. '
      home_page: https://rubygems.org/gems/async-http/versions/0.94.0
      license_concluded: MIT
      license_declared: MIT
      short_summary: A HTTP client and server library.
      supplier: 'Organization: Broadcom, Inc.'
