sources:
- archive: aws-sdk-core-3.223.0.gem
  archive_sha512sum: 15f04d0bbd97aa6d95a16f98fe8e60a8e90ffa451f1f2c800254a5950da1b961b699175f986783ec8f13eaee52f3c1130acaa2acb67a6d20c8dbef1fb681b060
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Provides API clients for AWS. This gem is part of the
        official AWS SDK for Ruby.. '
      home_page: https://rubygems.org/gems/aws-sdk-core/versions/3.223.0
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: Provides API clients for AWS.
      supplier: 'Organization: Broadcom, Inc.'
