sources:
- archive: zookeeper-3.9.4-source.tar.gz
  archive_sha512sum: 3cee277cb97279eb1597dd4dfa3ceef73b9c9eb24efaa6d9cf8ead13adda748b25486ad15001c8abd1685d054e9005fdcdc30d89386823901df9d0b8daa90957
  archive_type: upstream
  name: zookeeper-release-3.9.4
  version: 3.9.4
  url: https://github.com/apache/zookeeper/archive/refs/tags/release-3.9.4.tar.gz
  repo_url: https://github.com/apache/zookeeper
  commit_id: 7246445ec281f3dbf53dc54e970c914f39713903
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'ZooKeeper is a centralized service for maintaining configuration information,
      naming, providing distributed synchronization, and providing group services.
      This package provides the Java server, client scripts, libraries, and systemd unit.'
      home_page: http://zookeeper.apache.org
      license_concluded: (EPL-1.0 OR LGPL-2.1-only) AND APSL-2.0 AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-Attribution-HPND-disclaimer AND EPL-1.0 AND EPL-2.0 AND FSFUL AND ISC AND LGPL-2.1-only AND MIT AND OpenSSL
      license_declared: (EPL-1.0 OR LGPL-2.1-only) AND APSL-2.0 AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-Attribution-HPND-disclaimer AND EPL-1.0 AND EPL-2.0 AND FSFUL AND ISC AND LGPL-2.1-only AND MIT AND OpenSSL
      short_summary: High-performance coordination service for distributed applications
      supplier: 'Organization: Broadcom, Inc.'
