sources:
- archive: zookeeper-3.9.4.tar.gz
  archive_sha512sum: 36bffae6440ed0d71ed83a621b8c52c583860b414812197373237f0c148bd16e6b599977c90e5eb81c0fce6b82ef44aa782621535417cffc4c2a0a51a56f2cdf
  skip_validation: true
  spdx:
    package:
      detailed_description: 'ZooKeeper is a centralized service for maintaining configuration
        information, naming, providing distributed synchronization, and providing
        group services. All of these kinds of services are used in some form or another
        by distributed applications. Each time they are implemented there is a lot
        of work that goes into fixing the bugs and race conditions that are inevitable.
        Because of the difficulty of implementing these kinds of services, applications
        initially usually skimp on them, which make them brittle in the presence of
        change and difficult to manage. Even when done correctly, different implementations
        of these services lead to management complexity when the applications are
        deployed. '
      home_page: http://zookeeper.apache.org/
      license_concluded: (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND
        (GPL-2.0-only WITH Classpath-exception-2.0 OR CDDL-1.0) AND (EPL-1.0 OR Apache-2.0)
        AND (CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0) AND (MIT OR GPL-3.0-only)
        AND (EPL-1.0 OR LGPL-2.1-only) AND SSLeay-standalone AND BSD-3-Clause AND
        LGPL-2.1-only AND OpenSSL-standalone AND ISC AND GPL-2.0-only AND GPL-2.0-only
        WITH Classpath-exception-2.0 AND CDDL-1.0 AND Zlib AND EPL-1.0 AND EPL-2.0
        AND OpenSSL AND BSD-2-Clause AND Apache-2.0 AND MIT
      license_declared: (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND
        (GPL-2.0-only WITH Classpath-exception-2.0 OR CDDL-1.0) AND (EPL-1.0 OR Apache-2.0)
        AND (CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0) AND (MIT OR GPL-3.0-only)
        AND (EPL-1.0 OR LGPL-2.1-only) AND SSLeay-standalone AND BSD-3-Clause AND
        LGPL-2.1-only AND OpenSSL-standalone AND ISC AND GPL-2.0-only AND GPL-2.0-only
        WITH Classpath-exception-2.0 AND CDDL-1.0 AND Zlib AND EPL-1.0 AND EPL-2.0
        AND OpenSSL AND BSD-2-Clause AND Apache-2.0 AND MIT
      short_summary: Highly reliable distributed coordination
      supplier: 'Organization: Broadcom, Inc.'
