sources:
- archive: JSON-XS-4.04.tar.gz
  archive_sha512sum: 018d02c7db58a8469afd8454c7822602a50d09a1658e41511ae38bc0f0cfe88f180758ae1dc0f1a933869c8e5c1e7535a2e4d312a9d206544df0ccb4cba11295
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This module converts Perl data structures to JSON and
        vice versa. Its primary goal is to be correct and its secondary goal is to
        be fast. To reach the latter goal it was written in C. '
      home_page: http://search.cpan.org/dist/JSON-XS/
      license_concluded: Artistic-1.0-Perl OR GPL-1.0-or-later
      license_declared: Artistic-1.0-Perl OR GPL-1.0-or-later
      short_summary: JSON serializing/deserializing, done correctly and fast
      supplier: 'Organization: Broadcom, Inc.'
