sources:
- archive: frr-10.5.4.tar.gz
  archive_type: upstream
  archive_sha512sum: 69e5c9ca70efa0cfb84cb251b213a2b3bd526ec7b8477f0d269b9463bf9e85338ad7e28c3e0aa2bd2dbe9e6c9fc412b12afcff28898bdbaa2f3a9c420b074f2d
  name: frr-frr-10.5.4
  version: 10.5.4
  url: https://github.com/FRRouting/frr/archive/refs/tags/frr-10.5.4.tar.gz
  repo_url: https://github.com/FRRouting/frr
  commit_id: 4cb6d9e6bfe4ad503d1fab21e6f665804b0649ac
  skip_list:
  - RCS
  - CVS
  - tags
  - .git
  - .hg
  - .bzr
  - _darcs
  - __pycache__
  missing: []
  spdx:
    package:
      detailed_description: 'FRRouting is free software that manages TCP/IP based
        routing protocols. It takes a multi-server and multi-threaded approach to
        resolve the current complexity of the Internet.  FRRouting supports BGP4,
        OSPFv2, OSPFv3, ISIS, RIP, RIPng, PIM, NHRP, PBR, EIGRP and BFD.  FRRouting
        is a fork of Quagga. '
      home_page: https://frrouting.org
      license_concluded: (ISC OR GPL-2.0-or-later) AND GPL-3.0-or-later WITH Autoconf-exception-macro
        AND BSD-3-Clause-Clear AND GPL-3.0-only AND Latex2e-translated-notice AND
        GPL-3.0-or-later AND Latex2e AND MIT AND LGPL-2.1-or-later AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND GPL-2.0-only WITH Linux-syscall-note AND
        BSD-2-Clause AND Unlicense AND BSD-3-Clause AND GPL-2.0-or-later WITH Autoconf-exception-2.0
        AND GPL-2.0-or-later WITH Linux-syscall-note AND GPL-2.0-or-later AND ISC
        AND GPL-2.0-only AND GPL-1.0-or-later AND LGPL-2.1-only AND FSFAP AND Apache-2.0
      license_declared: (ISC OR GPL-2.0-or-later) AND GPL-3.0-or-later WITH Autoconf-exception-macro
        AND BSD-3-Clause-Clear AND GPL-3.0-only AND Latex2e-translated-notice AND
        GPL-3.0-or-later AND Latex2e AND MIT AND LGPL-2.1-or-later AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND GPL-2.0-only WITH Linux-syscall-note AND
        BSD-2-Clause AND Unlicense AND BSD-3-Clause AND GPL-2.0-or-later WITH Autoconf-exception-2.0
        AND GPL-2.0-or-later WITH Linux-syscall-note AND GPL-2.0-or-later AND ISC
        AND GPL-2.0-only AND GPL-1.0-or-later AND LGPL-2.1-only AND FSFAP AND Apache-2.0
      short_summary: Internet Routing Protocol
      supplier: 'Organization: Broadcom, Inc.'



