sources:
- archive: frr-10.2.1.tar.gz
  archive_type: upstream
  archive_sha512sum: 8544280a0c536e8688cbf2811d96cdc2fa3413f662013bb1b58cb02d4d56a08d98e870b39e477f6b0294e6aceb5dcc99c5facdeee165ce7597c2150ebb79101e
  name: frr-frr-10.2.1
  version: 10.2.1
  url: https://github.com/FRRouting/frr/archive/refs/tags/frr-10.2.1.tar.gz
  repo_url: https://github.com/FRRouting/frr
  commit_id: 5f0beaa0fdd00b7a60c1765067d1b6fa65ce96c0
  skip_list:
  - RCS
  - CVS
  - tags
  - .git
  - .hg
  - .bzr
  - _darcs
  - __pycache__
  missing: []
  spdx:
    package:
      detailed_description: 'FRRouting is free software that manages TCP/IP based
        routing protocols. It takes a multi-server and multi-threaded approach to
        resolve the current complexity of the Internet.  FRRouting supports BGP4,
        OSPFv2, OSPFv3, ISIS, RIP, RIPng, PIM, NHRP, PBR, EIGRP and BFD.  FRRouting
        is a fork of Quagga. '
      home_page: https://frrouting.org
      license_concluded: (ISC OR GPL-2.0-or-later) AND GPL-3.0-or-later WITH Autoconf-exception-macro
        AND BSD-3-Clause-Clear AND GPL-3.0-only AND Latex2e-translated-notice AND
        GPL-3.0-or-later AND Latex2e AND MIT AND LGPL-2.1-or-later AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND GPL-2.0-only WITH Linux-syscall-note AND
        BSD-2-Clause AND Unlicense AND BSD-3-Clause AND GPL-2.0-or-later WITH Autoconf-exception-2.0
        AND GPL-2.0-or-later WITH Linux-syscall-note AND GPL-2.0-or-later AND ISC
        AND GPL-2.0-only AND GPL-1.0-or-later AND LGPL-2.1-only AND FSFAP AND Apache-2.0
      license_declared: (ISC OR GPL-2.0-or-later) AND GPL-3.0-or-later WITH Autoconf-exception-macro
        AND BSD-3-Clause-Clear AND GPL-3.0-only AND Latex2e-translated-notice AND
        GPL-3.0-or-later AND Latex2e AND MIT AND LGPL-2.1-or-later AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND GPL-2.0-only WITH Linux-syscall-note AND
        BSD-2-Clause AND Unlicense AND BSD-3-Clause AND GPL-2.0-or-later WITH Autoconf-exception-2.0
        AND GPL-2.0-or-later WITH Linux-syscall-note AND GPL-2.0-or-later AND ISC
        AND GPL-2.0-only AND GPL-1.0-or-later AND LGPL-2.1-only AND FSFAP AND Apache-2.0
      short_summary: Internet Routing Protocol
      supplier: 'Organization: Broadcom, Inc.'
