sources:
- archive: openssh-10.3p1.tar.gz
  archive_sha512sum: cb2bd67086491c25e305879b924c3dfa8236502a60c7f250b2fd17d2d9a79ebfc2e40b2f43e42dcf598cc510996e00cc03df9b8e38f34bc2dc71a3d4ff3788fa
  archive_type: upstream
  name: openssh-10.3p1
  version: 10.3p1
  url: https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-10.3p1.tar.gz
  repo_url: https://github.com/openssh/openssh-portable
  commit_id: 2d98db98331803cbb820211b2fb0d31a6e71e58e
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'The OpenSSH package contains ssh clients and the sshd
        daemon. This is useful for encrypting authentication and subsequent traffic
        over a network. The ssh and scp commands are secure implementions of telnet
        and rcp respectively.'
      home_page: https://www.openssh.com
      license_concluded: GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND
        BSD-3-Clause AND FSFUL AND snprintf AND GPL-1.0-or-later AND SSLeay-standalone
        AND SSH-OpenSSH AND SSH-short AND ISC AND ssh-keyscan AND X11-distribute-modifications-variant
        AND HPND AND FSFULLRWD AND MIT AND BSD-2-Clause AND X11 AND OpenSSL-standalone
        AND BSD-4.3TAHOE
      license_declared: GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND BSD-3-Clause
        AND FSFUL AND snprintf AND GPL-1.0-or-later AND SSLeay-standalone AND SSH-OpenSSH
        AND SSH-short AND ISC AND ssh-keyscan AND X11-distribute-modifications-variant
        AND HPND AND FSFULLRWD AND MIT AND BSD-2-Clause AND X11 AND OpenSSL-standalone
        AND BSD-4.3TAHOE
      short_summary: Free version of the SSH connectivity tools
      supplier: 'Organization: Broadcom, Inc.'
