sources:
- archive: IO-Socket-SSL-2.090.tar.gz
  archive_sha512sum: d75d3fff50045f41c5ccfe6bbd80149f5d06845423a9149d7c2e9631cbe5cc68b1d9edc5e05a802609928b05ef4648ff645cc4d7cb8f46f194ec2a441aef7428
  skip_validation: true
  spdx:
    package:
      detailed_description: 'IO::Socket::SSL makes using SSL/TLS much easier by wrapping
        the necessary functionality into the familiar IO::Socket interface and providing
        secure defaults whenever possible. This way, existing applications can be
        made SSL-aware without much effort, at least if you do blocking I/O and don''t
        use select or poll. '
      home_page: https://metacpan.org/dist/IO-Socket-SSL
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND MPL-2.0
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND MPL-2.0
      short_summary: SSL sockets with IO::Socket interface
      supplier: 'Organization: Broadcom, Inc.'
