sources:
- archive: ldb-2.8.2.tar.gz
  archive_sha512sum: df1c228307ede75920a927ae3124cd0d507dfcf00f93b6f5c14b79f4e1a23dbe00249bc92b3ee3ed1e5ce06fe363f0be1eb3dab491fbe79e83b1a1b35a6e50e1
  archive_type: None
  skip_validation: true
  name: "ldb-2.8.2"
  version: 2.8.2
  url: https://download.samba.org/pub/ldb/ldb-2.8.2.tar.gz
  repo_url: https://gitlab.com/samba-team/samba/-/tree/master/lib/ldb
  commit_id: 8d4a277d2588acae26ac1aadee422e1aad6f41e6
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'An extensible library that implements an LDAP like API
        to access remote LDAP servers, or use local tdb databases. '
      home_page: http://ldb.samba.org/
      license_concluded: AGPL-3.0-or-later AND BSD-3-Clause AND LGPL-3.0-only AND
        PostgreSQL AND X11 AND Apache-2.0 AND ISC AND LGPL-2.1-or-later AND BSD-2-Clause
        AND GPL-3.0-or-later AND snprintf AND LGPL-3.0-or-later AND LGPL-2.0-or-later
      license_declared: AGPL-3.0-or-later AND BSD-3-Clause AND LGPL-3.0-only AND PostgreSQL
        AND X11 AND Apache-2.0 AND ISC AND LGPL-2.1-or-later AND BSD-2-Clause AND
        GPL-3.0-or-later AND snprintf AND LGPL-3.0-or-later AND LGPL-2.0-or-later
      short_summary: A schema-less, ldap like, API and database
      supplier: 'Organization: Broadcom, Inc.'
