sources:
- archive: squid-6.12.tar.xz
  archive_sha512sum: 7ab61f19416426fb8284de7bddc1ea9a5a7b3148fc54c018a243071ba5854610ef38a248f6a22634a2acb7d3ea408b582af1f48818dfe698ade0b7b8c00fd183
  skip_validation: true
  spdx:
    package:
      detailed_description: SQUID Web Proxy Cache
      home_page: https://github.com/squid-cache/squid
      license_concluded: (LGPL-3.0-or-later OR GPL-2.0-or-later) AND BSD-3-Clause
        AND ISC AND LGPL-2.0-or-later WITH Libtool-exception AND MIT AND FSFULLRWD
        AND LGPL-2.0-or-later AND CC-BY-SA-3.0 AND Artistic-1.0-Perl AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND BSD-4-Clause AND BSL-1.0 AND CC-BY-2.5
        AND LGPL-2.1-or-later AND CC-BY-3.0 AND FSFULLR AND X11 AND RSA-MD AND OLDAP-2.8
        AND FSFAP-no-warranty-disclaimer AND FSFAP AND BSD-2-Clause AND GPL-2.0-or-later
        AND LGPL-2.1-only AND Beerware AND OpenSSL AND GPL-2.0-only AND GPL-1.0-or-later
        AND HPND-Fenneberg-Livingston AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND libtiff AND MIT-CMU AND BSD-4-Clause-UC AND FSFUL AND GPL-2.0-or-later
        WITH Libtool-exception
      license_declared: (LGPL-3.0-or-later OR GPL-2.0-or-later) AND BSD-3-Clause AND
        ISC AND LGPL-2.0-or-later WITH Libtool-exception AND MIT AND FSFULLRWD AND
        LGPL-2.0-or-later AND CC-BY-SA-3.0 AND Artistic-1.0-Perl AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND BSD-4-Clause AND BSL-1.0 AND CC-BY-2.5
        AND LGPL-2.1-or-later AND CC-BY-3.0 AND FSFULLR AND X11 AND RSA-MD AND OLDAP-2.8
        AND FSFAP-no-warranty-disclaimer AND FSFAP AND BSD-2-Clause AND GPL-2.0-or-later
        AND LGPL-2.1-only AND Beerware AND OpenSSL AND GPL-2.0-only AND GPL-1.0-or-later
        AND HPND-Fenneberg-Livingston AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND libtiff AND MIT-CMU AND BSD-4-Clause-UC AND FSFUL AND GPL-2.0-or-later
        WITH Libtool-exception
      short_summary: SQUID Web Proxy Cache
      supplier: 'Organization: Broadcom, Inc.'
