sources:
- archive: flannel-0.28.4.tar.gz
  archive_type: upstream
  archive_sha512sum: a58267e9e660e5ceb141c7844b3dbb396e76bff48ed390de81aefb50df5254595367daf1579f640ae3a99fe9d3ded6feb495c4caa3b114a98b6b0600eb1e25e9
  version: 0.28.4
  name: flannel-0.28.4
  url: https://github.com/flannel-io/flannel/archive/refs/tags/v0.28.4.tar.gz
  repo_url: https://github.com/flannel-io/flannel
  commit_id: 3adfe3e04407869b9f84be0a68a6cebb73df9c6e
  skip_list: []
  missing: []
  skip_validation: false
  spdx:
    package:
      detailed_description: 'flannel is a virtual network that provides a subnet to
        a container runtime host OS for use with containers. flannel uses etcd to
        store the network configuration, allocated subnets, and additional data. '
      home_page: https://github.com/coreos/flannel
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: Overlay network for containers based on etcd
      supplier: 'Organization: Broadcom, Inc.'
