sources:
- archive: ansible-community-general-10.7.0.tar.gz
  archive_sha512sum: 0205c73758e8f483560e731127f80b4061218e01da03ba21cbc5457b1249a67a1e075a85e711189a84efe475a15aacf1d736eef567aa10650aa6cc9b211e8aff
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This repository contains the community.general Ansible
        Collection. The collection is a part of the Ansible package and includes many
        modules and plugins supported by Ansible community which are not part of more
        specialized community collections. '
      home_page: https://github.com/ansible-collections/community.general
      license_concluded: BSD-2-Clause AND Apache-2.0 AND GPL-3.0-only AND GPL-3.0-or-later
        AND MIT AND Python-2.0 AND PSF-2.0 AND BSD-3-Clause
      license_declared: BSD-2-Clause AND Apache-2.0 AND GPL-3.0-only AND GPL-3.0-or-later
        AND MIT AND Python-2.0 AND PSF-2.0 AND BSD-3-Clause
      short_summary: Modules and plugins supported by Ansible community
      supplier: 'Organization: Broadcom, Inc.'
