sources:
- archive: tevent-0.17.1.tar.gz
  archive_sha512sum: 781f8aced9ad135e64ce3953a013434feb84a6945ccfbce58a6ff21cb3da48af1e32324a5a950a55256a02545c2e1808a4cd8b209a3f970375347c8b390df258
  skip_validation: true
  archive_type: None
  name: tevent-0.17.1
  version: 0.17.1
  url: https://download.samba.org/pub/tevent/tevent-0.17.1.tar.gz
  repo_url: https://gitlab.com/samba-team/samba/
  commit_id: ebf4c4773733d2aae14c96f70681211ae40c1c18
  skip_list: []
  missing: []
  license_manual_review:
  - file_paths:
    - tevent-0.17.1/lib/talloc/man/talloc.3.xml
    sha256sum: 8e5ca81cdafeb321224f9a26ab41c58c336c248f333d9957267f674cd25a1184
    spdx_exp: LGPL-3.0-or-later
  spdx:
    package:
      detailed_description: 'Tevent is an event system based on the talloc memory
        management library. Tevent has support for many event types, including timers,
        signals, and the classic file descriptor events. Tevent also provide helpers
        to deal with asynchronous code providing the tevent_req (Tevent Request) functions. '
      home_page: http://tevent.samba.org/
      license_concluded: snprintf AND ISC AND LGPL-3.0-or-later AND GPL-3.0-or-later
        AND Apache-2.0 AND LGPL-2.1-or-later AND PostgreSQL AND BSD-3-Clause AND LGPL-2.0-or-later
        AND AGPL-3.0-or-later
      license_declared: snprintf AND ISC AND LGPL-3.0-or-later AND GPL-3.0-or-later
        AND Apache-2.0 AND LGPL-2.1-or-later AND PostgreSQL AND BSD-3-Clause AND LGPL-2.0-or-later
        AND AGPL-3.0-or-later
      short_summary: The tevent library
      supplier: 'Organization: Broadcom, Inc.'
