sources:
- archive: greenlet-3.3.1.tar.gz
  archive_sha512sum: 890e9a56f15c39101b45aabb006545640777a987d8f962c63859c2b4e26adfb5ae33310905982475809d3fcfb3b0ee5a9b11817c380708bba2d3c25cd5ad1822
  archive_type: upstream
  skip_validation: false
  name: greenlet-3.3.1
  version: "3.3.1"
  url: https://files.pythonhosted.org/packages/8a/99/1cd3411c56a410994669062bd73dd58270c00cc074cac15f385a1fd91f8a/greenlet-3.3.1.tar.gz
  repo_url: https://github.com/python-greenlet/greenlet
  commit_id: d1a0a3fa740425b8dd4dceafbecedda21d70cc08
  missing: ['.gitignore', 'PKG-INFO', 'setup.cfg', 'greenlet.egg-info']
  spdx:
    package:
      detailed_description: "The greenlet package is a spin-off of Stackless, a version\
        \ of CPython that supports micro-threads called \u201Ctasklets\u201D. Tasklets\
        \ run pseudo-concurrently (typically in a single or a few OS-level threads)\
        \ and are synchronized with data exchanges on \u201Cchannels\u201D.  A \u201C\
        greenlet\u201D, on the other hand, is a still more primitive notion of micro-thread\
        \ with no implicit scheduling; coroutines, in other words. This is useful\
        \ when you want to control exactly when your code runs. You can build custom\
        \ scheduled micro-threads on top of greenlet; however, it seems that greenlets\
        \ are useful on their own as a way to make advanced control flow structures.\
        \ For example, we can recreate generators; the difference with Python\u2019\
        s own generators is that our generators can call nested functions and the\
        \ nested functions can yield values too. Additionally, you don\u2019t need\
        \ a \u201Cyield\u201D keyword. See the example in tests/test_generator.py. "
      home_page: https://pypi.python.org/pypi/greenlet
      license_concluded: Python-2.0 AND PSF-2.0 AND MIT
      license_declared: Python-2.0 AND PSF-2.0 AND MIT
      short_summary: Lightweight in-process concurrent programming
      supplier: 'Organization: Broadcom, Inc.'
