sources:
- archive: YAML-Tiny-1.76.tar.gz
  archive_sha512sum: dff7f494bd2640b1577f793e4d8a11de381e7b928db1f62a60ce2e19636b4355df7fffb5613a496dda7e98dc404d7106d1538a0610dec210a8e922d5ec5c06a1
  skip_validation: true
  spdx:
    package:
      detailed_description: 'YAML::Tiny is a Perl class for reading and writing YAML-style
        files, written with as little code as possible, reducing load time and memory
        overhead. '
      home_page: http://search.cpan.org/dist/YAML-Tiny/
      license_concluded: (GPL-1.0-or-later OR Artistic-1.0) AND (Artistic-1.0-Perl
        OR GPL-1.0-or-later) AND Artistic-1.0-Perl AND GPL-1.0-only AND Artistic-1.0
      license_declared: (GPL-1.0-or-later OR Artistic-1.0) AND (Artistic-1.0-Perl
        OR GPL-1.0-or-later) AND Artistic-1.0-Perl AND GPL-1.0-only AND Artistic-1.0
      short_summary: Read/Write YAML files with as little code as possible
      supplier: 'Organization: Broadcom, Inc.'
