sources:
- archive: sphinx-9.1.0.tar.gz
  archive_sha512sum: 2c8b16935e14a8f827110461c530275f431949159eef47380198115d8abadaafdca06680c09722c0df7fd8ed8e16dbe1e3aa62a774164b7987247f6d8f8a20d3
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Sphinx is a tool that makes it easy to create intelligent
        and beautiful documentation for Python projects (or other documents consisting
        of multiple reStructuredText sources), written by Georg Brandl. It was originally
        created to translate the new Python documentation, but has now been cleaned
        up in the hope that it will be useful to many other projects.'
      home_page: www.sphinx-doc.org
      license_concluded: BSD-3-Clause AND FSFAP AND MIT AND BSD-2-Clause
      license_declared: BSD-3-Clause AND FSFAP AND MIT AND BSD-2-Clause
      short_summary: Python documentation generator
      supplier: 'Organization: Broadcom, Inc.'
