sources:
- archive: google-cloud-errors-1.4.0.gem
  archive_sha512sum: 3c12e59795abc2e3aee62b463fa7ab70deca6b5cecaa919b925bcb03ed7a1e67455e40a5bfb9c1380aae16d5a5e9bd9a125d0ef8d346aa54c07545dc32b8a042
  skip_validation: true
  spdx:
    package:
      detailed_description: 'google-cloud-errors defines error classes for google-cloud-ruby.'
      home_page: https://rubygems.org/gems/google-cloud-errors
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: google-cloud-errors defines error classes for google-cloud-ruby.
      supplier: 'Organization: Broadcom, Inc.'
