sources:
- archive: jdk-11.0.28-ga.tar.gz
  archive_sha512sum: 01d166fa8a4914c402a340409096530ab6313f5850d13b866ba354e02343a8b567bccee563b1d8b9b4ac5101f16d31c73a6549e21a96dd306da4b644d4609f89
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The OpenJDK package installs java class library and javac
        java compiler. '
      home_page: https://github.com/openjdk/jdk11u
      license_concluded: (FTL OR GPL-2.0-only) AND (MIT OR GPL-1.0-or-later) AND (BSD-3-Clause
        OR Apache-2.0) AND (MIT OR GPL-3.0-only) AND (CDDL-1.0 OR GPL-2.0-only WITH
        Classpath-exception-2.0) AND SAX-PD AND BSD-2-Clause AND UPL-1.0 AND GPL-2.0-only
        WITH Classpath-exception-2.0 AND GPL-2.0-only AND SunPro AND FTL AND HPND-export2-US
        AND SMLNJ AND Apache-1.1 AND W3C AND MIT AND GPL-3.0-only AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND ISC AND MPL-2.0 AND Unicode-DFS-2015 AND
        Unicode-3.0 AND LGPL-2.1-or-later AND BSD-3-Clause AND Zlib AND MIT-open-group
        AND BSD-3-Clause-No-Nuclear-License AND softSurfer AND Libpng AND MIT-Modern-Variant
        AND CC0-1.0 AND W3C-19980720 AND Apache-2.0 AND GPL-3.0-or-later AND Unicode-DFS-2016
        AND LGPL-2.1-only AND IJG
      license_declared: (FTL OR GPL-2.0-only) AND (MIT OR GPL-1.0-or-later) AND (BSD-3-Clause
        OR Apache-2.0) AND (MIT OR GPL-3.0-only) AND (CDDL-1.0 OR GPL-2.0-only WITH
        Classpath-exception-2.0) AND SAX-PD AND BSD-2-Clause AND UPL-1.0 AND GPL-2.0-only
        WITH Classpath-exception-2.0 AND GPL-2.0-only AND SunPro AND FTL AND HPND-export2-US
        AND SMLNJ AND Apache-1.1 AND W3C AND MIT AND GPL-3.0-only AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND ISC AND MPL-2.0 AND Unicode-DFS-2015 AND
        Unicode-3.0 AND LGPL-2.1-or-later AND BSD-3-Clause AND Zlib AND MIT-open-group
        AND BSD-3-Clause-No-Nuclear-License AND softSurfer AND Libpng AND MIT-Modern-Variant
        AND CC0-1.0 AND W3C-19980720 AND Apache-2.0 AND GPL-3.0-or-later AND Unicode-DFS-2016
        AND LGPL-2.1-only AND IJG
      short_summary: OpenJDK
      supplier: 'Organization: Broadcom, Inc.'
- archive: jdk-17.0.16-ga.tar.gz
  archive_sha512sum: df6cf32fa5884a004c1edc8de6fac9210efb740dd962860d415e97cfd3d2a232f19210c3d7fc21d1248e3424a160ca9e087db92c509eb79e815aeec0a40f212c
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The OpenJDK package installs java class library and javac
        java compiler. '
      home_page: https://github.com/openjdk/jdk17u
      license_concluded: (MIT OR GPL-1.0-or-later) AND (FTL OR GPL-2.0-only) AND (CDDL-1.0
        OR GPL-2.0-only WITH Classpath-exception-2.0) AND (BSD-3-Clause OR Apache-2.0)
        AND MIT-Modern-Variant AND IJG AND SAX-PD AND MIT-open-group AND GPL-3.0-only
        AND CC0-1.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-only
        WITH Classpath-exception-2.0 AND SunPro AND Apache-2.0 AND UPL-1.0 AND W3C-19980720
        AND GPL-2.0-only AND BSD-2-Clause AND Unicode-3.0 AND W3C AND BSD-3-Clause
        AND Zlib AND MPL-2.0 AND ICU AND Apache-1.1 AND SMLNJ AND softSurfer AND ISC
        AND FTL AND Unicode-TOU AND Libpng AND MIT AND HPND-export2-US
      license_declared: (MIT OR GPL-1.0-or-later) AND (FTL OR GPL-2.0-only) AND (CDDL-1.0
        OR GPL-2.0-only WITH Classpath-exception-2.0) AND (BSD-3-Clause OR Apache-2.0)
        AND MIT-Modern-Variant AND IJG AND SAX-PD AND MIT-open-group AND GPL-3.0-only
        AND CC0-1.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-only
        WITH Classpath-exception-2.0 AND SunPro AND Apache-2.0 AND UPL-1.0 AND W3C-19980720
        AND GPL-2.0-only AND BSD-2-Clause AND Unicode-3.0 AND W3C AND BSD-3-Clause
        AND Zlib AND MPL-2.0 AND ICU AND Apache-1.1 AND SMLNJ AND softSurfer AND ISC
        AND FTL AND Unicode-TOU AND Libpng AND MIT AND HPND-export2-US
      short_summary: OpenJDK
      supplier: 'Organization: Broadcom, Inc.'
- archive: jdk-21.0.8-ga.tar.gz
  archive_sha512sum: be96bfa216efedd0cb094c8b4a2307f84ff6fa8a3a2c30f2f6610023e24979eee7be6b96305d893eb7cf19ed3750167a76436201cfdbc623713236c852eea917
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The OpenJDK package installs java class library and javac
        java compiler. '
      home_page: https://github.com/openjdk/jdk21u
      license_concluded: (FTL OR GPL-2.0-only) AND (BSD-3-Clause OR Apache-2.0) AND
        (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND (MIT OR GPL-1.0-or-later)
        AND W3C-19980720 AND HPND-export2-US AND CC0-1.0 AND Libpng AND MIT-Modern-Variant
        AND MIT-open-group AND UPL-1.0 AND MPL-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND BSD-3-Clause AND IJG AND BSD-2-Clause AND Unicode-TOU AND GPL-2.0-only
        AND Apache-2.0 AND ICU AND Apache-1.1 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND Unicode-DFS-2016 AND GPL-2.0-only WITH Classpath-exception-2.0 AND GPL-3.0-only
        AND FTL AND NAIST-2003 AND Unicode-3.0 AND SunPro AND ISC AND SMLNJ AND W3C
        AND MIT AND SAX-PD AND Zlib AND softSurfer
      license_declared: (FTL OR GPL-2.0-only) AND (BSD-3-Clause OR Apache-2.0) AND
        (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND (MIT OR GPL-1.0-or-later)
        AND W3C-19980720 AND HPND-export2-US AND CC0-1.0 AND Libpng AND MIT-Modern-Variant
        AND MIT-open-group AND UPL-1.0 AND MPL-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND BSD-3-Clause AND IJG AND BSD-2-Clause AND Unicode-TOU AND GPL-2.0-only
        AND Apache-2.0 AND ICU AND Apache-1.1 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND Unicode-DFS-2016 AND GPL-2.0-only WITH Classpath-exception-2.0 AND GPL-3.0-only
        AND FTL AND NAIST-2003 AND Unicode-3.0 AND SunPro AND ISC AND SMLNJ AND W3C
        AND MIT AND SAX-PD AND Zlib AND softSurfer
      short_summary: OpenJDK
      supplier: 'Organization: Broadcom, Inc.'
