sources:
- archive: jdk-11.0.26-ga.tar.gz
  archive_sha512sum: b5375de7c39aafa4fe1ef6556e17bf5c8ace577953ea8e666c4e8adc3e8b0f6fdbf20b7c426a156420acb99787363e0e4c9d36df20cefcef5e74a48bb75eeb24
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The OpenJDK package installs java class library and javac
        java compiler. '
      home_page: https://github.com/openjdk/jdk11u
      license_concluded: (FTL OR GPL-2.0-only) AND (MIT OR GPL-1.0-or-later) AND (BSD-3-Clause
        OR Apache-2.0) AND (MIT OR GPL-3.0-only) AND (CDDL-1.0 OR GPL-2.0-only WITH
        Classpath-exception-2.0) AND SAX-PD AND BSD-2-Clause AND UPL-1.0 AND GPL-2.0-only
        WITH Classpath-exception-2.0 AND GPL-2.0-only AND SunPro AND FTL AND HPND-export2-US
        AND SMLNJ AND Apache-1.1 AND W3C AND MIT AND GPL-3.0-only AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND ISC AND MPL-2.0 AND Unicode-DFS-2015 AND
        Unicode-3.0 AND LGPL-2.1-or-later AND BSD-3-Clause AND Zlib AND MIT-open-group
        AND BSD-3-Clause-No-Nuclear-License AND softSurfer AND Libpng AND MIT-Modern-Variant
        AND CC0-1.0 AND W3C-19980720 AND Apache-2.0 AND GPL-3.0-or-later AND Unicode-DFS-2016
        AND LGPL-2.1-only AND IJG
      license_declared: (FTL OR GPL-2.0-only) AND (MIT OR GPL-1.0-or-later) AND (BSD-3-Clause
        OR Apache-2.0) AND (MIT OR GPL-3.0-only) AND (CDDL-1.0 OR GPL-2.0-only WITH
        Classpath-exception-2.0) AND SAX-PD AND BSD-2-Clause AND UPL-1.0 AND GPL-2.0-only
        WITH Classpath-exception-2.0 AND GPL-2.0-only AND SunPro AND FTL AND HPND-export2-US
        AND SMLNJ AND Apache-1.1 AND W3C AND MIT AND GPL-3.0-only AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND ISC AND MPL-2.0 AND Unicode-DFS-2015 AND
        Unicode-3.0 AND LGPL-2.1-or-later AND BSD-3-Clause AND Zlib AND MIT-open-group
        AND BSD-3-Clause-No-Nuclear-License AND softSurfer AND Libpng AND MIT-Modern-Variant
        AND CC0-1.0 AND W3C-19980720 AND Apache-2.0 AND GPL-3.0-or-later AND Unicode-DFS-2016
        AND LGPL-2.1-only AND IJG
      short_summary: OpenJDK
      supplier: 'Organization: Broadcom, Inc.'
- archive: jdk-17.0.14-ga.tar.gz
  archive_sha512sum: 0643ac52b68e5884734289ab13592feef7273db96f7b5c0fd77d801e4d4e44a84abcc439fd1b138119c5583986f1d0b058aa74f55b00e0dfd31333cbb536744d
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The OpenJDK package installs java class library and javac
        java compiler. '
      home_page: https://github.com/openjdk/jdk17u
      license_concluded: (MIT OR GPL-1.0-or-later) AND (FTL OR GPL-2.0-only) AND (CDDL-1.0
        OR GPL-2.0-only WITH Classpath-exception-2.0) AND (BSD-3-Clause OR Apache-2.0)
        AND MIT-Modern-Variant AND IJG AND SAX-PD AND MIT-open-group AND GPL-3.0-only
        AND CC0-1.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-only
        WITH Classpath-exception-2.0 AND SunPro AND Apache-2.0 AND UPL-1.0 AND W3C-19980720
        AND GPL-2.0-only AND BSD-2-Clause AND Unicode-3.0 AND W3C AND BSD-3-Clause
        AND Zlib AND MPL-2.0 AND ICU AND Apache-1.1 AND SMLNJ AND softSurfer AND ISC
        AND FTL AND Unicode-TOU AND Libpng AND MIT AND HPND-export2-US
      license_declared: (MIT OR GPL-1.0-or-later) AND (FTL OR GPL-2.0-only) AND (CDDL-1.0
        OR GPL-2.0-only WITH Classpath-exception-2.0) AND (BSD-3-Clause OR Apache-2.0)
        AND MIT-Modern-Variant AND IJG AND SAX-PD AND MIT-open-group AND GPL-3.0-only
        AND CC0-1.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-only
        WITH Classpath-exception-2.0 AND SunPro AND Apache-2.0 AND UPL-1.0 AND W3C-19980720
        AND GPL-2.0-only AND BSD-2-Clause AND Unicode-3.0 AND W3C AND BSD-3-Clause
        AND Zlib AND MPL-2.0 AND ICU AND Apache-1.1 AND SMLNJ AND softSurfer AND ISC
        AND FTL AND Unicode-TOU AND Libpng AND MIT AND HPND-export2-US
      short_summary: OpenJDK
      supplier: 'Organization: Broadcom, Inc.'
- archive: jdk-21.0.6-ga.tar.gz
  archive_sha512sum: fb03362608a35b0f6e131eaa974a52e6ff8a96f90d3bdaeccd2e1268f46db65c72387ed7bba1c8b0d9457c56950eae607fba29e102a338b009259262e1024726
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The OpenJDK package installs java class library and javac
        java compiler. '
      home_page: https://github.com/openjdk/jdk21u
      license_concluded: (FTL OR GPL-2.0-only) AND (BSD-3-Clause OR Apache-2.0) AND
        (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND (MIT OR GPL-1.0-or-later)
        AND W3C-19980720 AND HPND-export2-US AND CC0-1.0 AND Libpng AND MIT-Modern-Variant
        AND MIT-open-group AND UPL-1.0 AND MPL-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND BSD-3-Clause AND IJG AND BSD-2-Clause AND Unicode-TOU AND GPL-2.0-only
        AND Apache-2.0 AND ICU AND Apache-1.1 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND Unicode-DFS-2016 AND GPL-2.0-only WITH Classpath-exception-2.0 AND GPL-3.0-only
        AND FTL AND NAIST-2003 AND Unicode-3.0 AND SunPro AND ISC AND SMLNJ AND W3C
        AND MIT AND SAX-PD AND Zlib AND softSurfer
      license_declared: (FTL OR GPL-2.0-only) AND (BSD-3-Clause OR Apache-2.0) AND
        (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND (MIT OR GPL-1.0-or-later)
        AND W3C-19980720 AND HPND-export2-US AND CC0-1.0 AND Libpng AND MIT-Modern-Variant
        AND MIT-open-group AND UPL-1.0 AND MPL-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND BSD-3-Clause AND IJG AND BSD-2-Clause AND Unicode-TOU AND GPL-2.0-only
        AND Apache-2.0 AND ICU AND Apache-1.1 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND Unicode-DFS-2016 AND GPL-2.0-only WITH Classpath-exception-2.0 AND GPL-3.0-only
        AND FTL AND NAIST-2003 AND Unicode-3.0 AND SunPro AND ISC AND SMLNJ AND W3C
        AND MIT AND SAX-PD AND Zlib AND softSurfer
      short_summary: OpenJDK
      supplier: 'Organization: Broadcom, Inc.'
