sources:
- archive: jdk-11.0.29-ga.tar.gz
  archive_sha512sum: 85cdccee7e359e6b51aee7ebb23bff75c26dd2fa6054a853b23b3bfa3b13bcad3c195fea91ffe5d4078c05ebb7fd9db6cf276451f2029073108f406ca362f611
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The OpenJDK package installs java class library and javac
        java compiler.'
      home_page: https://github.com/openjdk/jdk11u
      license_concluded: (FTL OR GPL-2.0-only) AND (MIT OR GPL-1.0-or-later) AND (BSD-3-Clause
        OR Apache-2.0) AND (MIT OR GPL-3.0-only) AND (CDDL-1.0 OR GPL-2.0-only WITH
        Classpath-exception-2.0) AND SAX-PD AND BSD-2-Clause AND UPL-1.0 AND GPL-2.0-only
        WITH Classpath-exception-2.0 AND GPL-2.0-only AND SunPro AND FTL AND HPND-export2-US
        AND SMLNJ AND Apache-1.1 AND W3C AND MIT AND GPL-3.0-only AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND ISC AND MPL-2.0 AND Unicode-DFS-2015 AND
        Unicode-3.0 AND LGPL-2.1-or-later AND BSD-3-Clause AND Zlib AND MIT-open-group
        AND BSD-3-Clause-No-Nuclear-License AND softSurfer AND Libpng AND MIT-Modern-Variant
        AND CC0-1.0 AND W3C-19980720 AND Apache-2.0 AND GPL-3.0-or-later AND Unicode-DFS-2016
        AND LGPL-2.1-only AND IJG
      license_declared: (FTL OR GPL-2.0-only) AND (MIT OR GPL-1.0-or-later) AND (BSD-3-Clause
        OR Apache-2.0) AND (MIT OR GPL-3.0-only) AND (CDDL-1.0 OR GPL-2.0-only WITH
        Classpath-exception-2.0) AND SAX-PD AND BSD-2-Clause AND UPL-1.0 AND GPL-2.0-only
        WITH Classpath-exception-2.0 AND GPL-2.0-only AND SunPro AND FTL AND HPND-export2-US
        AND SMLNJ AND Apache-1.1 AND W3C AND MIT AND GPL-3.0-only AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND ISC AND MPL-2.0 AND Unicode-DFS-2015 AND
        Unicode-3.0 AND LGPL-2.1-or-later AND BSD-3-Clause AND Zlib AND MIT-open-group
        AND BSD-3-Clause-No-Nuclear-License AND softSurfer AND Libpng AND MIT-Modern-Variant
        AND CC0-1.0 AND W3C-19980720 AND Apache-2.0 AND GPL-3.0-or-later AND Unicode-DFS-2016
        AND LGPL-2.1-only AND IJG
      short_summary: OpenJDK
      supplier: 'Organization: Broadcom, Inc.'

- archive: jdk-17.0.17-ga.tar.gz
  archive_sha512sum: ddb409fe2c8714af081e1174df2b1febcb05097dd83eed60abe9cdaf6b9cfb9a960626480ff4f8719e8890480274ca5ce2abb449317aeb617d9bfe964b33ad29
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The OpenJDK package installs java class library and javac
        java compiler.'
      home_page: https://github.com/openjdk/jdk17u
      license_concluded: (MIT OR GPL-1.0-or-later) AND (FTL OR GPL-2.0-only) AND (CDDL-1.0
        OR GPL-2.0-only WITH Classpath-exception-2.0) AND (BSD-3-Clause OR Apache-2.0)
        AND MIT-Modern-Variant AND IJG AND SAX-PD AND MIT-open-group AND GPL-3.0-only
        AND CC0-1.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-only
        WITH Classpath-exception-2.0 AND SunPro AND Apache-2.0 AND UPL-1.0 AND W3C-19980720
        AND GPL-2.0-only AND BSD-2-Clause AND Unicode-3.0 AND W3C AND BSD-3-Clause
        AND Zlib AND MPL-2.0 AND ICU AND Apache-1.1 AND SMLNJ AND softSurfer AND ISC
        AND FTL AND Unicode-TOU AND Libpng AND MIT AND HPND-export2-US
      license_declared: (MIT OR GPL-1.0-or-later) AND (FTL OR GPL-2.0-only) AND (CDDL-1.0
        OR GPL-2.0-only WITH Classpath-exception-2.0) AND (BSD-3-Clause OR Apache-2.0)
        AND MIT-Modern-Variant AND IJG AND SAX-PD AND MIT-open-group AND GPL-3.0-only
        AND CC0-1.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-only
        WITH Classpath-exception-2.0 AND SunPro AND Apache-2.0 AND UPL-1.0 AND W3C-19980720
        AND GPL-2.0-only AND BSD-2-Clause AND Unicode-3.0 AND W3C AND BSD-3-Clause
        AND Zlib AND MPL-2.0 AND ICU AND Apache-1.1 AND SMLNJ AND softSurfer AND ISC
        AND FTL AND Unicode-TOU AND Libpng AND MIT AND HPND-export2-US
      short_summary: OpenJDK
      supplier: 'Organization: Broadcom, Inc.'

- archive: jdk-21.0.9-ga.tar.gz
  archive_sha512sum: f209839c830e5db7080613b5d5e7c33ccd6a55cb72a2e6237bb26646569691a34a7b93349c9fa219a3496e111e156c2d24abda3b389056b16625668e8756aed0
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The OpenJDK package installs java class library and javac
        java compiler.'
      home_page: https://github.com/openjdk/jdk21u
      license_concluded: (FTL OR GPL-2.0-only) AND (BSD-3-Clause OR Apache-2.0) AND
        (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND (MIT OR GPL-1.0-or-later)
        AND W3C-19980720 AND HPND-export2-US AND CC0-1.0 AND Libpng AND MIT-Modern-Variant
        AND MIT-open-group AND UPL-1.0 AND MPL-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND BSD-3-Clause AND IJG AND BSD-2-Clause AND Unicode-TOU AND GPL-2.0-only
        AND Apache-2.0 AND ICU AND Apache-1.1 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND Unicode-DFS-2016 AND GPL-2.0-only WITH Classpath-exception-2.0 AND GPL-3.0-only
        AND FTL AND NAIST-2003 AND Unicode-3.0 AND SunPro AND ISC AND SMLNJ AND W3C
        AND MIT AND SAX-PD AND Zlib AND softSurfer
      license_declared: (FTL OR GPL-2.0-only) AND (BSD-3-Clause OR Apache-2.0) AND
        (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND (MIT OR GPL-1.0-or-later)
        AND W3C-19980720 AND HPND-export2-US AND CC0-1.0 AND Libpng AND MIT-Modern-Variant
        AND MIT-open-group AND UPL-1.0 AND MPL-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND BSD-3-Clause AND IJG AND BSD-2-Clause AND Unicode-TOU AND GPL-2.0-only
        AND Apache-2.0 AND ICU AND Apache-1.1 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND Unicode-DFS-2016 AND GPL-2.0-only WITH Classpath-exception-2.0 AND GPL-3.0-only
        AND FTL AND NAIST-2003 AND Unicode-3.0 AND SunPro AND ISC AND SMLNJ AND W3C
        AND MIT AND SAX-PD AND Zlib AND softSurfer
      short_summary: OpenJDK
      supplier: 'Organization: Broadcom, Inc.'
