sources:
- archive: node-v24.16.0.tar.gz
  archive_sha512sum: 0c3299404fae5d372b18d12f1964f51c58923ccc9f80680554a36563e8cd1f4f2ad314d93c524ba68ad8a114536594de8d6bcad90256552a119b45b89104af63
  skip_validation: true
  license_manual_review:
  - file_paths:
    - node-v24.16.0/deps/npm/node_modules/spdx-license-ids/index.json
    sha256sum: d5ef45aff38fd904a68c563bf5814172bb0caa656220be820b3a81601e637241
    spdx_exp: ''
  # index.json contains list of all licenses in an array as string for parsing.
  # Removed AGPL-30, AGPL-1.0, CC-BY-SA & SSPL-1.0
  - file_paths:
    - node-v24.16.0/deps/npm/node_modules/spdx-license-ids/deprecated.json
    sha256sum: 29c9e630daa0adc09dec96ddeb6f81d1046210e81824bebda6486250450fb130
    spdx_exp: ''
  # index.js contains list of all Licenses for identification purpose.
  # Removed AGPL-1.0, AGPL-2.0, AGPL-3.0 & AGPL-3.0-or-later
  - file_paths:
    - node-v24.16.0/deps/npm/test/schemas/cyclonedx/spdx.schema.json
    sha256sum: 4f6e2b05c05d26a4f2dc5879fbc2fca94b0a28db46289d0c51345621b71cfbfc
    spdx_exp: ''
  # spdx.schema.json contains all Licenses as strings for identification purpose
  # Removed AGPL-1.0, AGPL-1.0-only, AGPL-1.0-or-later, AGPL-3.0, AGPL-3.0-only,
  # AGPL-3.0-or-later, CC-BY-SA-2.0, CC-BY-SA-4.0 & SSPL-1.0
  spdx:
    package:
      detailed_description: 'Node.js is a JavaScript runtime built on Chrome''s V8
        JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that
        makes it lightweight and efficient. The Node.js package ecosystem, npm, is
        the largest ecosystem of open source libraries in the world. '
      home_page: https://github.com/nodejs/node
      license_concluded: (Apache-2.0 OR BSD-2-Clause) AND (Apache-2.0 OR BSD-3-Clause)
        AND (Apache-2.0 OR MIT) AND (Artistic-1.0 OR GPL-1.0-or-later) AND (Artistic-1.0-Perl
        OR GPL-1.0-or-later) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (BSD-2-Clause
        OR CC0-1.0) AND (BSD-2-Clause OR OpenSSL) AND (BSD-3-Clause OR GPL-1.0-or-later
        OR GPL-2.0-only OR OpenSSL) AND (BSD-3-Clause OR GPL-1.0-or-later OR OpenSSL)
        AND (BSD-3-Clause OR GPL-2.0-only) AND (BSD-3-Clause OR GPL-2.0-only) AND
        (BSD-3-Clause OR GPL-2.0-or-later OR LGPL-2.1-or-later OR MPL-1.1) AND (BSD-3-Clause
        OR OpenSSL) AND (GPL-1.0-or-later OR MIT) AND (ISC OR MIT) AND AFL-3.0 AND
        AGPL-1.0-only AND AGPL-3.0-only AND AGPL-3.0-or-later AND APSL-1.0 AND APSL-1.1
        AND APSL-2.0 AND Apache-1.1 AND Apache-2.0 AND Apache-2.0 WITH LLVM-exception
        AND Artistic-1.0 AND Artistic-2.0 AND BSD-2-Clause AND BSD-2-Clause-Patent
        AND BSD-2-Clause-Views AND BSD-3-Clause AND BSD-3-Clause-Clear AND BSD-3-Clause-Modification
        AND BSD-3-Clause-No-Military-License AND BSD-4-Clause AND BSD-4-Clause-Shortened
        AND BSD-4-Clause-UC AND BSD-Source-Code AND BSL-1.0 AND BlueOak-1.0.0 AND
        CAL-1.0 AND CAL-1.0-Combined-Work-Exception AND CC-BY-3.0 AND CC-BY-4.0 AND
        CC-BY-SA-2.0 AND CC-BY-SA-4.0 AND CC0-1.0 AND CDDL-1.0 AND CDDL-1.1 AND CECILL-2.0
        AND CECILL-2.1 AND CERN-OHL-1.1 AND CERN-OHL-1.2 AND CERN-OHL-P-2.0 AND CERN-OHL-S-2.0
        AND CERN-OHL-W-2.0 AND CPOL-1.02 AND EFL-2.0 AND EPL-1.0 AND FSFAP AND FSFUL
        AND FSFULLR AND FSFULLRWD AND Frameworx-1.0 AND GFDL-1.1-invariants-only AND
        GFDL-1.1-invariants-or-later AND GFDL-1.1-no-invariants-only AND GFDL-1.1-no-invariants-or-later
        AND GFDL-1.1-only AND GFDL-1.2-invariants-only AND GFDL-1.2-invariants-or-later
        AND GFDL-1.2-no-invariants-only AND GFDL-1.2-no-invariants-or-later AND GFDL-1.3-invariants-only
        AND GFDL-1.3-invariants-or-later AND GFDL-1.3-no-invariants-only AND GFDL-1.3-no-invariants-or-later
        AND GPL-1.0-only AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later
        AND GPL-2.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later WITH
        Autoconf-exception-generic AND GPL-2.0-or-later WITH Libtool-exception AND
        GPL-2.0-or-later WITH eCos-exception-2.0 AND GPL-3.0-only AND GPL-3.0-or-later
        AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH
        Autoconf-exception-generic-3.0 AND HPND AND HPND-sell-variant AND HaskellReport
        AND IBM-pibs AND ICU AND ISC AND Interbase-1.0 AND JSON AND LAL-1.3 AND LGPL-2.0-or-later
        AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND LGPL-3.0-or-later
        AND LiLiQ-P-1.1 AND LiLiQ-R-1.1 AND LiLiQ-Rplus-1.1 AND Linux-man-pages-copyleft
        AND MIT AND MIT-0 AND MIT-Wu AND MPL-1.0 AND MPL-2.0 AND NAIST-2003 AND NCGL-UK-2.0
        AND NGPL AND NIST-PD AND NIST-PD-fallback AND NTP AND NTP-0 AND OFL-1.1-no-RFN
        AND OGC-1.0 AND OGDL-Taiwan-1.0 AND OGL-Canada-2.0 AND OGL-UK-1.0 AND OGL-UK-2.0
        AND OGL-UK-3.0 AND OpenSSL AND PSF-2.0 AND Parity-6.0.0 AND Parity-7.0.0 AND
        PolyForm-Noncommercial-1.0.0 AND PolyForm-Small-Business-1.0.0 AND Python-2.0
        AND SSPL-1.0 AND Spencer-86 AND SunPro AND TAPR-OHL-1.0 AND TMate AND TU-Berlin-1.0
        AND TU-Berlin-2.0 AND UCL-1.0 AND Unicode-3.0 AND WTFPL AND X11 AND Zimbra-1.3
        AND Zimbra-1.4 AND Zlib AND blessing AND bzip2-1.0.6 AND copyleft-next-0.3.0
        AND copyleft-next-0.3.1 AND curl AND etalab-2.0 AND libselinux-1.0 AND snprintf
      license_declared: (Apache-2.0 OR BSD-2-Clause) AND (Apache-2.0 OR BSD-3-Clause)
        AND (Apache-2.0 OR MIT) AND (Artistic-1.0 OR GPL-1.0-or-later) AND (Artistic-1.0-Perl
        OR GPL-1.0-or-later) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (BSD-2-Clause
        OR CC0-1.0) AND (BSD-2-Clause OR OpenSSL) AND (BSD-3-Clause OR GPL-1.0-or-later
        OR GPL-2.0-only OR OpenSSL) AND (BSD-3-Clause OR GPL-1.0-or-later OR OpenSSL)
        AND (BSD-3-Clause OR GPL-2.0-only) AND (BSD-3-Clause OR GPL-2.0-only) AND
        (BSD-3-Clause OR GPL-2.0-or-later OR LGPL-2.1-or-later OR MPL-1.1) AND (BSD-3-Clause
        OR OpenSSL) AND (GPL-1.0-or-later OR MIT) AND (ISC OR MIT) AND AFL-3.0 AND
        AGPL-1.0-only AND AGPL-3.0-only AND AGPL-3.0-or-later AND APSL-1.0 AND APSL-1.1
        AND APSL-2.0 AND Apache-1.1 AND Apache-2.0 AND Apache-2.0 WITH LLVM-exception
        AND Artistic-1.0 AND Artistic-2.0 AND BSD-2-Clause AND BSD-2-Clause-Patent
        AND BSD-2-Clause-Views AND BSD-3-Clause AND BSD-3-Clause-Clear AND BSD-3-Clause-Modification
        AND BSD-3-Clause-No-Military-License AND BSD-4-Clause AND BSD-4-Clause-Shortened
        AND BSD-4-Clause-UC AND BSD-Source-Code AND BSL-1.0 AND BlueOak-1.0.0 AND
        CAL-1.0 AND CAL-1.0-Combined-Work-Exception AND CC-BY-3.0 AND CC-BY-4.0 AND
        CC-BY-SA-2.0 AND CC-BY-SA-4.0 AND CC0-1.0 AND CDDL-1.0 AND CDDL-1.1 AND CECILL-2.0
        AND CECILL-2.1 AND CERN-OHL-1.1 AND CERN-OHL-1.2 AND CERN-OHL-P-2.0 AND CERN-OHL-S-2.0
        AND CERN-OHL-W-2.0 AND CPOL-1.02 AND EFL-2.0 AND EPL-1.0 AND FSFAP AND FSFUL
        AND FSFULLR AND FSFULLRWD AND Frameworx-1.0 AND GFDL-1.1-invariants-only AND
        GFDL-1.1-invariants-or-later AND GFDL-1.1-no-invariants-only AND GFDL-1.1-no-invariants-or-later
        AND GFDL-1.1-only AND GFDL-1.2-invariants-only AND GFDL-1.2-invariants-or-later
        AND GFDL-1.2-no-invariants-only AND GFDL-1.2-no-invariants-or-later AND GFDL-1.3-invariants-only
        AND GFDL-1.3-invariants-or-later AND GFDL-1.3-no-invariants-only AND GFDL-1.3-no-invariants-or-later
        AND GPL-1.0-only AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later
        AND GPL-2.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later WITH
        Autoconf-exception-generic AND GPL-2.0-or-later WITH Libtool-exception AND
        GPL-2.0-or-later WITH eCos-exception-2.0 AND GPL-3.0-only AND GPL-3.0-or-later
        AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH
        Autoconf-exception-generic-3.0 AND HPND AND HPND-sell-variant AND HaskellReport
        AND IBM-pibs AND ICU AND ISC AND Interbase-1.0 AND JSON AND LAL-1.3 AND LGPL-2.0-or-later
        AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND LGPL-3.0-or-later
        AND LiLiQ-P-1.1 AND LiLiQ-R-1.1 AND LiLiQ-Rplus-1.1 AND Linux-man-pages-copyleft
        AND MIT AND MIT-0 AND MIT-Wu AND MPL-1.0 AND MPL-2.0 AND NAIST-2003 AND NCGL-UK-2.0
        AND NGPL AND NIST-PD AND NIST-PD-fallback AND NTP AND NTP-0 AND OFL-1.1-no-RFN
        AND OGC-1.0 AND OGDL-Taiwan-1.0 AND OGL-Canada-2.0 AND OGL-UK-1.0 AND OGL-UK-2.0
        AND OGL-UK-3.0 AND OpenSSL AND PSF-2.0 AND Parity-6.0.0 AND Parity-7.0.0 AND
        PolyForm-Noncommercial-1.0.0 AND PolyForm-Small-Business-1.0.0 AND Python-2.0
        AND SSPL-1.0 AND Spencer-86 AND SunPro AND TAPR-OHL-1.0 AND TMate AND TU-Berlin-1.0
        AND TU-Berlin-2.0 AND UCL-1.0 AND Unicode-3.0 AND WTFPL AND X11 AND Zimbra-1.3
        AND Zimbra-1.4 AND Zlib AND blessing AND bzip2-1.0.6 AND copyleft-next-0.3.0
        AND copyleft-next-0.3.1 AND curl AND etalab-2.0 AND libselinux-1.0 AND snprintf
      short_summary: A JavaScript runtime built on Chrome's V8 JavaScript engine.
      supplier: 'Organization: Broadcom, Inc.'
