sources:
- archive: mistune-3.3.4.tar.gz
  archive_sha512sum: 5ce0215de01c8d8b33e6ba5b19c9cebbc6bbbf25670e6611cf9f29efbc19007dd66005f6c5f1f6f7a53b766c466e9f9e8104b493ae72fc7428a31086b67e9bc2
  archive_type: upstream
  name: mistune-3.3.4
  url: https://github.com/lepture/mistune/archive/refs/tags/v3.3.4.tar.gz
  repo_url: https://github.com/lepture/mistune
  commit_id: 69ec2b8a6d5b37ecb3c56d96df4b40b9d3004657
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'The fastest markdown parser in pure Python with renderer
        features, inspired by marked.'
      home_page: https://pypi.python.org/pypi/mistune
      license_concluded: BSD-3-Clause
      license_declared: BSD-3-Clause
      short_summary: The fastest markdown parser in pure Python.
      supplier: 'Organization: Broadcom, Inc.'
