sources:
- archive: mistune-3.2.0.tar.gz
  archive_sha512sum: 0fc30fb323bc901830472626fc34fc4d99fc066a7492c61c7d2672df473e95220accad02f98ddcf070ddbd9fe918585319251f767e7c41443eaa37918e007838
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The fastest markdown parser in pure Python with renderer
        features, inspired by marked.'
      home_page: https://pypi.python.org/pypi/mistune
      license_concluded: BSD-3-Clause
      license_declared: BSD-3-Clause
      short_summary: The fastest markdown parser in pure Python.
      supplier: 'Organization: Broadcom, Inc.'
