sources:
- archive: expat-2.8.1.tar.xz
  archive_type: upstream
  archive_sha512sum: 186e9677a4255d054364c06f68318df3e9039793da29e7b286ed7c6b12e93f62f2d096b5f7535bde29844fc25a934b84616e72228f6584e9d655fd8ed95c639a
  name: "expat-2.8.1"
  version: 2.8.1
  url: https://github.com/libexpat/libexpat/releases/download/R_2_8_1/expat-2.8.1.tar.xz
  repo_url: https://github.com/libexpat/libexpat.git
  commit_id: c7ffbf3879f6aef7a7b020ef84ddb4ee00222b19
  skip_list: [AUTHORS, CMake.README, CMakeLists.txt, Changes, ConfigureChecks.cmake, Makefile.am, Makefile.in, acinclude.m4, aclocal.m4, buildconf.sh, cmake, configure, configure.ac, conftools, doc, examples, expat.pc.cmake, expat.pc.in, expat_config.h, expat_config.h.cmake, expat_config.h.in, fix-xmltest-log.sh, fuzz, lib, m4, run.sh.in, test-driver-wrapper.sh, tests, win32, xmlwf, CONTRIBUTING.md, pull_request_template.md, COPYING]
  missing: [cmake, test-driver-wrapper.sh, expat_config.h.in, run.sh.in, xmlwf, fuzz, testdata, .ci.sh, AUTHORS, examples, SECURITY.md, expat, buildconf.sh, win32, .mailmap, Changes, expat.pc.cmake, configure.ac, Brewfile, m4, ConfigureChecks.cmake, configure, tests, expat_config.h.cmake, Makefile.in, .github, expat.pc.in, .gitignore, aclocal.m4, CMake.README, CMakeLists.txt, expat_config.h, fix-xmltest-log.sh, conftools, acinclude.m4, lib, Makefile.am, doc, .gitattributes]
  spdx:
    package:
      detailed_description: 'The Expat package contains a stream oriented C library
        for parsing XML. '
      home_page: http://expat.sourceforge.net/
      license_concluded: GPL-2.0-or-later AND Apache-2.0 AND MIT AND FSFULLRWD AND
        GFDL-1.1-only AND GPL-2.0-or-later WITH Autoconf-exception-generic AND CC0-1.0
        AND GPL-3.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH
        Libtool-exception AND FSFAP AND FSFULLR AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-2.0-only AND X11 AND BSD-3-Clause AND FSFUL
      license_declared: GPL-2.0-or-later AND Apache-2.0 AND MIT AND FSFULLRWD AND
        GFDL-1.1-only AND GPL-2.0-or-later WITH Autoconf-exception-generic AND CC0-1.0
        AND GPL-3.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH
        Libtool-exception AND FSFAP AND FSFULLR AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-2.0-only AND X11 AND BSD-3-Clause AND FSFUL
      short_summary: An XML parser library
      supplier: 'Organization: Broadcom, Inc.'
