sources:
- archive: expat-2.7.4.tar.xz
  archive_type: upstream
  archive_sha512sum: a5533b99b1e0b73adcbe1f1b4816ce04e963fb6b734e6018c823597297a367a0524f31e040e3320122398833371f3f7caf4f9bf3cb91594a38151b2672edfa8f
  name: "expat-2.7.4"
  version: 2.7.4
  url: https://github.com/libexpat/libexpat/releases/download/R_2_7_4/expat-2.7.4.tar.xz
  repo_url: https://github.com/libexpat/libexpat.git
  commit_id: f5c2890d8ff91f88a018173d293a9bd02f76389e
  skip_list: [AUTHORS, CMake.README, CMakeLists.txt, Changes, ConfigureChecks.cmake, Makefile.am, Makefile.in, acinclude.m4, aclocal.m4, buildconf.sh, cmake, configure, configure.ac, conftools, doc, examples, expat.pc.cmake, expat.pc.in, expat_config.h, expat_config.h.cmake, expat_config.h.in, fix-xmltest-log.sh, fuzz, lib, m4, run.sh.in, test-driver-wrapper.sh, tests, win32, xmlwf, CONTRIBUTING.md, pull_request_template.md]
  missing: [cmake, test-driver-wrapper.sh, expat_config.h.in, run.sh.in, xmlwf, fuzz, testdata, .ci.sh, AUTHORS, examples, SECURITY.md, expat, buildconf.sh, win32, .mailmap, Changes, expat.pc.cmake, configure.ac, Brewfile, m4, ConfigureChecks.cmake, configure, tests, expat_config.h.cmake, Makefile.in, .github, expat.pc.in, .gitignore, aclocal.m4, CMake.README, CMakeLists.txt, expat_config.h, fix-xmltest-log.sh, conftools, acinclude.m4, lib, Makefile.am, doc, .gitattributes]
  spdx:
    package:
      detailed_description: 'The Expat package contains a stream oriented C library
        for parsing XML. '
      home_page: http://expat.sourceforge.net/
      license_concluded: GPL-2.0-or-later AND Apache-2.0 AND MIT AND FSFULLRWD AND
        GFDL-1.1-only AND GPL-2.0-or-later WITH Autoconf-exception-generic AND CC0-1.0
        AND GPL-3.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH
        Libtool-exception AND FSFAP AND FSFULLR AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-2.0-only AND X11 AND BSD-3-Clause AND FSFUL
      license_declared: GPL-2.0-or-later AND Apache-2.0 AND MIT AND FSFULLRWD AND
        GFDL-1.1-only AND GPL-2.0-or-later WITH Autoconf-exception-generic AND CC0-1.0
        AND GPL-3.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH
        Libtool-exception AND FSFAP AND FSFULLR AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-2.0-only AND X11 AND BSD-3-Clause AND FSFUL
      short_summary: An XML parser library
      supplier: 'Organization: Broadcom, Inc.'
