sources:
- archive: git-2.53.0.tar.gz
  skip_validation: false
  archive_sha512sum: bb68811f80926294327c09f4abd4650234c7caa256e2e870b80e3617fee1fd62a88b24fb370a28624505c62a8f426f46ff97f7dcc9f8a446e39cfb2610094d75
  archive_type: upstream
  name: git-2.53.0
  version: 2.53.0
  repo_url: https://github.com/git/git/
  commit_id: 67ad42147a7acc2af6074753ebd03d904476118f
  url: https://www.kernel.org/pub/software/scm/git/git-2.53.0.tar.gz
  license_manual_review:
  - file_paths:
    - git-2.53.0/Documentation/technical/large-object-promisors.adoc
    sha256sum: b76baff2c662164b423673ce3f7a663c96181f84998a7e71ada39bd650594e2f
    spdx_exp: ''
  skip_list:
  - RCS
  - CVS
  - tags
  - .git
  - .hg
  - .bzr
  - _darcs
  - __pycache__
  missing:
  - version
  - configure
  spdx:
    package:
      detailed_description: 'Git is a free and open source, distributed version control
        system designed to handle everything from small to very large projects with
        speed and efficiency. Every Git clone is a full-fledged repository with complete
        history and full revision tracking capabilities, not dependent on network
        access or a central server. Branching and merging are fast and easy to do.
        Git is used for version control of files, much like tools such as Mercurial,
        Bazaar, Subversion-1.7.8, CVS-1.11.23, Perforce, and Team Foundation Server. '
      home_page: http://git-scm.com
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (GPL-2.0-only
        OR MIT) AND Apache-2.0 AND BSD-3-Clause AND BSL-1.0 AND CC-PDDC AND FSFUL
        AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only
        AND ISC AND LGPL-2.1-only AND LGPL-2.1-or-later AND MIT AND Zlib
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (GPL-2.0-only
        OR MIT) AND Apache-2.0 AND BSD-3-Clause AND BSL-1.0 AND CC-PDDC AND FSFUL
        AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only
        AND ISC AND LGPL-2.1-only AND LGPL-2.1-or-later AND MIT AND Zlib
      short_summary: Fast distributed version control system
      supplier: 'Organization: Broadcom, Inc.'
