sources:
- archive: git-2.40.4.tar.xz
  archive_sha512sum: 0491d759d9bc44edb705acc30058ba24bf03dc9336ee825680d00c4690a825bdd36b2b2911e7f12889bca9a6a72644ce9b299cc16fe74fd033e74f7f114a4c2f
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Git is a free and open source, distributed version control
        system designed to handle everything from small to very large projects with
        speed and efficiency. Every Git clone is a full-fledged repository with complete
        history and full revision tracking capabilities, not dependent on network
        access or a central server. Branching and merging are fast and easy to do.
        Git is used for version control of files, much like tools such as Mercurial,
        Bazaar, Subversion-1.7.8, CVS-1.11.23, Perforce, and Team Foundation Server. '
      home_page: http://git-scm.com
      license_concluded: (MIT OR GPL-2.0-only) AND (Artistic-1.0-Perl OR GPL-1.0-or-later)
        AND MIT AND ISC AND GPL-2.0-or-later AND Apache-2.0 AND GPL-3.0-only AND BSD-3-Clause
        AND GPL-1.0-or-later AND BSL-1.0 AND GPL-2.0-only AND FSFUL AND CC-PDDC AND
        LGPL-2.1-or-later AND LGPL-2.1-only AND Zlib
      license_declared: (MIT OR GPL-2.0-only) AND (Artistic-1.0-Perl OR GPL-1.0-or-later)
        AND MIT AND ISC AND GPL-2.0-or-later AND Apache-2.0 AND GPL-3.0-only AND BSD-3-Clause
        AND GPL-1.0-or-later AND BSL-1.0 AND GPL-2.0-only AND FSFUL AND CC-PDDC AND
        LGPL-2.1-or-later AND LGPL-2.1-only AND Zlib
      short_summary: Fast distributed version control system
      supplier: 'Organization: Broadcom, Inc.'
