sources:
- archive: parallel-20221122.tar.bz2
  archive_sha512sum: cdae4ec3a5aaf1ae6c0d9dc35bad930c2b34ad4f91209de80d55258f1945e2df345708000a2facef3b647b6e0d4c275c909faf073961ae0b80b89efa8831211f
  skip_validation: true
  spdx:
    package:
      detailed_description: 'GNU parallel is a shell tool for executing jobs concurrently
        locally or using remote computers. A job is typically a single command or
        a small script that has to be run for each of the lines in the input. The
        typical input is a list of files, a list of hosts, a list of users, a list
        of URLs, or a list of tables. '
      home_page: https://www.gnu.org/software/parallel/
      license_concluded: BSD-3-Clause AND CC-BY-SA-4.0 AND FSFUL AND FSFULLR AND FSFULLRWD
        AND GFDL-1.1-or-later AND GFDL-1.3-only AND GFDL-1.3-or-later AND GPL-1.0-or-later
        AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND GPL-3.0-only AND GPL-3.0-or-later AND LGPL-2.1-or-later AND X11
      license_declared: BSD-3-Clause AND CC-BY-SA-4.0 AND FSFUL AND FSFULLR AND FSFULLRWD
        AND GFDL-1.1-or-later AND GFDL-1.3-only AND GFDL-1.3-or-later AND GPL-1.0-or-later
        AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND GPL-3.0-only AND GPL-3.0-or-later AND LGPL-2.1-or-later AND X11
      short_summary: Shell tool for executing jobs in parallel
      supplier: 'Organization: Broadcom, Inc.'
  license_manual_review:
  - archive_path: Makefile.am
    sha256sum: a7da03a4b36708229a8e1e2e6894fa295947beb28d27b9a08c01535a83468166
    spdx_exp: GPL-3.0-or-later
  - archive_path: Makefile.in
    sha256sum: 204d1dc7ca8c6d19295eb025074a6c374b748dd58c6f6bbe9b1dc8d0e8a282a5
    spdx_exp: GPL-3.0-or-later AND FSFULLRWD
