sources:
- archive: ptyprocess-0.7.0.tar.gz
  archive_sha512sum: 791d8f2e79900627215ce80ce67ee9c79173dbc08297c6219d5058f9b80c5e323b93049e6836a70c4073f43548d22e3cf310f2e9948ef12f96bcaa15b0ddb2f3
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Launch a subprocess in a pseudo terminal (pty), and interact
        with both the process and its pty. '
      home_page: https://github.com/pexpect/ptyprocess
      license_concluded: BSD-3-Clause AND ISC
      license_declared: BSD-3-Clause AND ISC
      short_summary: Run a subprocess in a pseudo terminal.
      supplier: 'Organization: Broadcom, Inc.'
