sources:
- archive: aws-sdk-cpp-1.11.712.tar.gz
  # This is custom built tarball, hence skip validation
  # The other values are for completeness
  skip_validation: true
  archive_sha512sum: e84a29224582b40c81607dad9541196be93f8d1c5ecf97da6ac00a6758fd9f92aa63922def76540b6016911716c0248b49ba2179b07d0774719227d3dcac8f16
  name: aws-sdk-cpp-1.11.712
  version: 1.11.712
  url: https://github.com/aws/aws-sdk-cpp/archive/refs/tags/1.11.712.tar.gz
  repo_url: https://github.com/aws/aws-sdk-cpp
  commit_id: 4aca5630ba6e49869a0f173f9439ae73722d4558
  skip_list: []
  missing: [crt, codebuild, update-version.sh, .clang-tidy, tmp, .gitmodules, clang-tidy, .github, tests, .gitattributes, source, CODE_OF_CONDUCT.md, docsrc, CONTRIBUTING.md, make-docs.py, format-check.py, .clang-format, include, CMakeLists.txt, builder.json, VERSION, bin, LICENSE, cmake, .gitignore, NOTICE, .builder, README.md]
  spdx:
    package:
      detailed_description: 'The AWS SDK for C++ provides a modern C++ (version C++11 or later) interface for Amazon Web Services (AWS).'
      home_page: https://github.com/aws/aws-sdk-cpp
      license_concluded: Nokia AND MIT-0 AND APSL-2.0 AND JSON AND Apache-2.0 AND
        ISC AND OpenSSL-standalone AND SSLeay-standalone AND BSD-3-Clause AND (Apache-2.0
        OR ISC) AND CC0-1.0 AND MIT AND (BSD-3-Clause OR GPL-2.0-only) AND PostgreSQL
        AND (BSD-3-Clause OR GPL-1.0-or-later) AND GPL-1.0-or-later AND Brian-Gladman-2-Clause
        AND BSD-2-Clause AND Zlib AND EPL-1.0 AND GPL-2.0-only
      license_declared: Nokia AND MIT-0 AND APSL-2.0 AND JSON AND Apache-2.0 AND ISC
        AND OpenSSL-standalone AND SSLeay-standalone AND BSD-3-Clause AND (Apache-2.0
        OR ISC) AND CC0-1.0 AND MIT AND (BSD-3-Clause OR GPL-2.0-only) AND PostgreSQL
        AND (BSD-3-Clause OR GPL-1.0-or-later) AND GPL-1.0-or-later AND Brian-Gladman-2-Clause
        AND BSD-2-Clause AND Zlib AND EPL-1.0 AND GPL-2.0-only
      short_summary: aws sdk for c++
      supplier: 'Organization: Broadcom, Inc.'
