sources:
- archive: lm-sensors-3.6.2.tar.gz
  archive_sha512sum: a89ae984814f5224bf621727252042d2b84a5cc5c125dd7024ff1be223e4c269b1e7c23512e56b3f2f38c088d7c6e54df47af51d63740deb09c44f837060695a
  archive_type: upstream
  name: lm-sensors-3-6-2
  version: 3.6.2
  url: https://github.com/lm-sensors/lm-sensors/archive/refs/tags/V3-6-2.tar.gz
  repo_url: https://github.com/lm-sensors/lm-sensors
  commit_id: 5c3ba50f806dea27c3b1e368966191c735459111
  spdx:
    package:
      detailed_description: 'The lm_sensors package provides user-space support for
        the hardware monitoring drivers in the Linux kernel. This is useful for monitoring
        the temperature of the CPU and adjusting the performance of some hardware
        (such as cooling fans). '
      home_page: https://github.com/lm-sensors/lm-sensors/releases
      license_concluded: GPL-2.0-or-later AND LGPL-2.0-or-later AND Linux-man-pages-copyleft
        AND GPL-1.0-or-later AND LGPL-2.1-or-later AND Linux-man-pages-copyleft-var
        AND LGPL-2.1-only AND GPL-2.0-only
      license_declared: GPL-2.0-or-later AND LGPL-2.0-or-later AND Linux-man-pages-copyleft
        AND GPL-1.0-or-later AND LGPL-2.1-or-later AND Linux-man-pages-copyleft-var
        AND LGPL-2.1-only AND GPL-2.0-only
      short_summary: The lm_sensors package provides user-space support for the hardware
        monitoring drivers in the Linux kernel.
      supplier: 'Organization: Broadcom, Inc.'
