sources:
- archive: mysql-8.4.10.tar.gz
  archive_sha512sum: 0e85b84bee32414959755a1f59c997bc4a7c81fe3a12267a7963cd2c6607ebccfd49ab23c872a429a80e319c65ba92c104f0b4445494e90c4aacab32b6cc6d9e
  skip_validation: true
  license_manual_review:
  - file_paths:
    - mysql-8.4.10/LICENSE
    sha256sum: b971ab677d232904fc158f196e8b9dbc0cf3fee4501ba08285260a37841be25a
    spdx_exp: GPL-2.0-only AND (GPL-2.0-only WITH Universal-FOSS-exception-1.0 AND
      GPL-2.0-only AND GPL-1.0-or-later) AND GPL-2.0-only WITH Universal-FOSS-exception-1.0
      AND BSL-1.0 AND curl AND BSD-Attribution-HPND-disclaimer AND RSA-MD AND dtoa
      AND BSD-3-Clause AND BSD-2-Clause AND Zlib AND (MIT AND fmt-exception) AND Apache-2.0
      AND ICU AND (ICU AND BSD-3-Clause) AND (BSD-3-Clause AND NAIST-2003) AND NAIST-2003
      AND CC-BY-4.0 AND OpenVision AND HPND-export2-US AND MIT AND FSFULLRWD AND OLDAP-2.8
      AND BSD-2-Clause-first-lines AND MIT-CMU AND CMU-Mach-nodoc AND (BSD-2-Clause
      AND HPND-export-US-acknowledgement) AND BSD-4-Clause-UC AND BSD-4-Clause AND
      ISC AND HPND-export-US-modify AND (BSD-2-Clause OR GPL-2.0-or-later) AND LGPL-2.1-only
      AND (ISC AND MIT) AND (Apache-2.0 AND OpenSSL) AND (MIT AND JSON AND BSD-3-Clause)
      AND (BSD-3-Clause AND JSON) AND (JSON AND MIT) AND Unicode-TOU AND ((BSD-3-Clause
      OR GPL-2.0-only) AND BSD-3-Clause)
  # we do not build kerberos auth plugin
  - file_paths:
    - mysql-8.4.10/router/LICENSE.router
    sha256sum: bb99cfd950547e725bff133a9665b4f548b1c1a48e0458d69bbf872be8bf3705
    spdx_exp: ''
  # we build with DWITH_ROUTER=OFF so this is not applicable
  spdx:
    package:
      detailed_description: 'MySQL is a free, widely used SQL engine. It can be used
        as a fast database as well as a rock-solid DBMS using a modular engine architecture.'
      home_page: http://www.mysql.com
      license_concluded: GPL-3.0-only AND MIT-CMU AND BSD-4-Clause-UC AND Python-2.0
        AND LGPL-2.1-or-later AND (BSD-3-Clause OR GPL-2.0-only) AND (BSD-2-Clause
        OR GPL-2.0-or-later) AND (curl AND ISC) AND GPL-1.0-only AND Zlib AND NAIST-2003
        AND FSFULLRWD AND GPL-2.0-or-later AND dtoa AND curl AND RSA-MD AND Apache-2.0
        AND BSD-2-Clause-Views AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND GPL-2.0-only AND OpenVision AND Artistic-2.0 AND GPL-3.0-or-later WITH
        Autoconf-exception-generic-3.0 AND BSD-Attribution-HPND-disclaimer AND FSFULLR
        AND LGPL-2.1-only AND GPL-2.0-or-later WITH Libtool-exception AND BSD-2-Clause-first-lines
        AND FSFUL AND HPND-export-US-modify AND CC-BY-SA-3.0 AND GPL-2.0-only WITH
        Universal-FOSS-exception-1.0 AND MIT AND FSFAP AND GPL-1.0-or-later AND HPND-export2-US
        AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND ICU AND Artistic-1.0-Perl
        AND BSD-3-Clause AND X11 AND Beerware AND BSD-4-Clause AND HPND-export-US-acknowledgement
        AND (MIT OR CC0-1.0) AND BSL-1.0 AND BSD-2-Clause AND ISC AND CC0-1.0 AND
        GPL-3.0-or-later WITH Bison-exception-2.2 AND JSON AND (BSD-2-Clause OR GPL-2.0-only)
        AND GPL-3.0-or-later AND CMU-Mach-nodoc AND OLDAP-2.8 AND (BSD-3-Clause OR
        GPL-2.0-only)
      license_declared: GPL-3.0-only AND MIT-CMU AND BSD-4-Clause-UC AND Python-2.0
        AND LGPL-2.1-or-later AND (BSD-3-Clause OR GPL-2.0-only) AND (BSD-2-Clause
        OR GPL-2.0-or-later) AND (curl AND ISC) AND GPL-1.0-only AND Zlib AND NAIST-2003
        AND FSFULLRWD AND GPL-2.0-or-later AND dtoa AND curl AND RSA-MD AND Apache-2.0
        AND BSD-2-Clause-Views AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND GPL-2.0-only AND OpenVision AND Artistic-2.0 AND GPL-3.0-or-later WITH
        Autoconf-exception-generic-3.0 AND BSD-Attribution-HPND-disclaimer AND FSFULLR
        AND LGPL-2.1-only AND GPL-2.0-or-later WITH Libtool-exception AND BSD-2-Clause-first-lines
        AND FSFUL AND HPND-export-US-modify AND CC-BY-SA-3.0 AND GPL-2.0-only WITH
        Universal-FOSS-exception-1.0 AND MIT AND FSFAP AND GPL-1.0-or-later AND HPND-export2-US
        AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND ICU AND Artistic-1.0-Perl
        AND BSD-3-Clause AND X11 AND Beerware AND BSD-4-Clause AND HPND-export-US-acknowledgement
        AND (MIT OR CC0-1.0) AND BSL-1.0 AND BSD-2-Clause AND ISC AND CC0-1.0 AND
        GPL-3.0-or-later WITH Bison-exception-2.2 AND JSON AND (BSD-2-Clause OR GPL-2.0-only)
        AND GPL-3.0-or-later AND CMU-Mach-nodoc AND OLDAP-2.8 AND (BSD-3-Clause OR
        GPL-2.0-only)
      short_summary: MySQL.
      supplier: 'Organization: Broadcom, Inc.'
