sources:
- archive: Module-Build-0.42_35.tar.gz
  archive_sha512sum: f43168a90ec2dbc92aee55958af5c4f3581f78177d3dda48fe83086aa004ad79ca7aef8a8078b47e85d8faeeeb2f1a53054c043afe78d3c99b6cba0aa1191ebe
  archive_type: upstream
  name: Module-Build-0.42_35
  version: 0.42_35
  url: https://www.cpan.org/authors/id/L/LE/LEONT/Module-Build-0.42_35.tar.gz
  repo_url: https://github.com/Perl-Toolchain-Gang/Module-Build.git
  commit_id: a2ecdf98c25af7dfc7070280232513e8ccec4986
  skip_validation: false
  skip_list: ['Build.PL', 'Build.pm', 'API.pod']
  missing: ['.appveyor.cmd', '.appveyor.yml', '.git', '.gitignore', '.perltidyrc', '.travis.yml', 'MANIFEST.SKIP', 'TODO', 'configs', 'devtools', 'LICENSE', 'META.json', 'META.yml', 'README', 'ModuleBuildBuilder.pm']
  spdx:
    package:
      detailed_description: 'Module::Build is a system for building, testing, and
        installing Perl modules. It is meant to be an alternative to ExtUtils::MakeMaker. '
      home_page: http://search.cpan.org/dist/Module-Build/
      license_concluded: (Artistic-1.0 OR GPL-1.0-or-later) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND
        Apache-1.1 AND Apache-2.0 AND Artistic-1.0 AND Artistic-1.0-Perl AND Artistic-2.0 AND Artistic-dist
        AND BSD-3-Clause AND GPL-1.0-only AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-3.0-only AND
        LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-3.0-only AND MIT AND MPL-1.0 AND
        MPL-1.1 AND MPL-2.0
      license_declared: (Artistic-1.0 OR GPL-1.0-or-later) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND
        Apache-1.1 AND Apache-2.0 AND Artistic-1.0 AND Artistic-1.0-Perl AND Artistic-2.0 AND Artistic-dist
        AND BSD-3-Clause AND GPL-1.0-only AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-3.0-only AND
        LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-3.0-only AND MIT AND MPL-1.0 AND
        MPL-1.1 AND MPL-2.0
      short_summary: Build and install Perl modules
      supplier: 'Organization: Broadcom, Inc.'
