sources:
- archive: go1.26.8.linux-amd64.tar.gz
  archive_sha512sum: bfed9e8e85e05c5bedf2b853062b879a223db41e63085b74ffdf2a3b4f816032d4df3816fcbf7e484e2a34782803f39531705dc873bbd9dc7f3031bc4edadcdf
  archive_type: upstream
  name: go
  version: 1.26.8
  url: https://go.dev/dl/go1.26.8.linux-amd64.tar.gz
  repo_url: https://github.com/golang/go
  commit_id: c293dd49cbe25e1fe8d97d94a5cb618e7b6d831e
  skip_list: []
  missing: [zdefaultcc.go, zcgo.go, .gitattributes, bin, pkg, .github, zbootstrap.go, zversion.go, zzipdata.go, .gitignore]
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Go is an open source programming language that makes
        it easy to build simple, reliable, and efficient software.'
      home_page: https://golang.org
      license_concluded: IJG AND OpenSSL-standalone AND MIT-testregex AND BSD-1-Clause
        AND GPL-2.0-only AND SSLeay-standalone AND MIT AND BSD-3-Clause AND Apache-2.0
        AND ISC AND BSD-2-Clause AND GPL-1.0-or-later AND MPEG-SSG AND SunPro AND
        CC-BY-4.0
      license_declared: IJG AND OpenSSL-standalone AND MIT-testregex AND BSD-1-Clause
        AND GPL-2.0-only AND SSLeay-standalone AND MIT AND BSD-3-Clause AND Apache-2.0
        AND ISC AND BSD-2-Clause AND GPL-1.0-or-later AND MPEG-SSG AND SunPro AND
        CC-BY-4.0
      short_summary: Go
      supplier: 'Organization: Broadcom, Inc.'
- archive: go1.26.8.linux-arm64.tar.gz
  archive_sha512sum: 9b77bfe592785400a65ff3abd1b9f9a2ff440db7b37ef34ee009a94bf41b88f3801ec4227ffc55316001379123c7cf3bd2ce3226a317a6ba86f68d8d178193d6
  archive_type: upstream
  name: go
  version: 1.26.8
  url: https://go.dev/dl/go1.26.8.linux-arm64.tar.gz
  repo_url: https://github.com/golang/go
  commit_id: c293dd49cbe25e1fe8d97d94a5cb618e7b6d831e
  skip_list: []
  missing: [zdefaultcc.go, zcgo.go, .gitattributes, bin, pkg, .github, zbootstrap.go, zversion.go, zzipdata.go, .gitignore]
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Go is an open source programming language that makes
        it easy to build simple, reliable, and efficient software.'
      home_page: https://golang.org
      license_concluded: IJG AND OpenSSL-standalone AND MIT-testregex AND BSD-1-Clause
        AND GPL-2.0-only AND SSLeay-standalone AND MIT AND BSD-3-Clause AND Apache-2.0
        AND ISC AND BSD-2-Clause AND GPL-1.0-or-later AND MPEG-SSG AND SunPro AND
        CC-BY-4.0
      license_declared: IJG AND OpenSSL-standalone AND MIT-testregex AND BSD-1-Clause
        AND GPL-2.0-only AND SSLeay-standalone AND MIT AND BSD-3-Clause AND Apache-2.0
        AND ISC AND BSD-2-Clause AND GPL-1.0-or-later AND MPEG-SSG AND SunPro AND
        CC-BY-4.0
      short_summary: Go
      supplier: 'Organization: Broadcom, Inc.'
