sources:
- archive: go1.26.3.linux-amd64.tar.gz
  archive_sha512sum: cc49ca9764b1dff5983d7635bc6e8f9fe71754bf48ec310a43512cef6103c4a88ed446e9b759742affa9bbcac507957fb9993011cb94343b88ba938c17632c28
  archive_type: upstream
  name: go
  version: 1.26.3
  url: https://go.dev/dl/go1.26.3.linux-amd64.tar.gz
  repo_url: https://github.com/golang/go
  commit_id: 2dc996f71b0ebafb77e64433e58333e049488a3c
  skip_list: []
  missing: [zdefaultcc.go, zcgo.go, .gitattributes, bin, pkg, .github, zbootstrap.go, zversion.go, zzipdata.go, .gitignore]
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Go is an open source programming language that makes
        it easy to build simple, reliable, and efficient software.'
      home_page: https://golang.org
      license_concluded: IJG AND OpenSSL-standalone AND MIT-testregex AND BSD-1-Clause
        AND GPL-2.0-only AND SSLeay-standalone AND MIT AND BSD-3-Clause AND Apache-2.0
        AND ISC AND BSD-2-Clause AND GPL-1.0-or-later AND MPEG-SSG AND SunPro AND
        CC-BY-4.0
      license_declared: IJG AND OpenSSL-standalone AND MIT-testregex AND BSD-1-Clause
        AND GPL-2.0-only AND SSLeay-standalone AND MIT AND BSD-3-Clause AND Apache-2.0
        AND ISC AND BSD-2-Clause AND GPL-1.0-or-later AND MPEG-SSG AND SunPro AND
        CC-BY-4.0
      short_summary: Go
      supplier: 'Organization: Broadcom, Inc.'
- archive: go1.26.3.linux-arm64.tar.gz
  archive_sha512sum: 443ebe1f87b426cf21954048d1fee8a122e3f082fb285eae3ef7ba8f793a8efcd5599f46f85777560f38de573011a6dba4a1a6effc457c4367f34d621a66f976
  archive_type: upstream
  name: go
  version: 1.26.3
  url: https://go.dev/dl/go1.26.3.linux-arm64.tar.gz
  repo_url: https://github.com/golang/go
  commit_id: 2dc996f71b0ebafb77e64433e58333e049488a3c
  skip_list: []
  missing: [zdefaultcc.go, zcgo.go, .gitattributes, bin, pkg, .github, zbootstrap.go, zversion.go, zzipdata.go, .gitignore]
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Go is an open source programming language that makes
        it easy to build simple, reliable, and efficient software.'
      home_page: https://golang.org
      license_concluded: IJG AND OpenSSL-standalone AND MIT-testregex AND BSD-1-Clause
        AND GPL-2.0-only AND SSLeay-standalone AND MIT AND BSD-3-Clause AND Apache-2.0
        AND ISC AND BSD-2-Clause AND GPL-1.0-or-later AND MPEG-SSG AND SunPro AND
        CC-BY-4.0
      license_declared: IJG AND OpenSSL-standalone AND MIT-testregex AND BSD-1-Clause
        AND GPL-2.0-only AND SSLeay-standalone AND MIT AND BSD-3-Clause AND Apache-2.0
        AND ISC AND BSD-2-Clause AND GPL-1.0-or-later AND MPEG-SSG AND SunPro AND
        CC-BY-4.0
      short_summary: Go
      supplier: 'Organization: Broadcom, Inc.'
