sources:
- archive: bash-5.3.tar.gz
  archive_sha512sum: 426702c8b0fb9e0c9956259973ce5b657890fd47f4f807a64febf20077bb48d0b91474ed6e843d2ef277186b46c5fffa79b808da9b48d4ec027d5e2de1b28ed8
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The package contains the Bourne-Again SHell '
      home_page: http://www.gnu.org/software/bash
      license_concluded: HPND AND BSD-4-Clause-UC AND GFDL-1.3-invariants-only AND
        GFDL-1.3-or-later AND GPL-2.0-only AND Latex2e AND LGPL-2.1-or-later AND GPL-1.0-or-later
        AND GPL-3.0-or-later AND GPL-3.0-only AND FSFUL AND GPL-3.0-or-later WITH
        Texinfo-exception AND OFL-1.1 AND FSFULLRWD AND CC-BY-SA-4.0 AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND GFDL-1.3-only AND GPL-2.0-or-later AND
        GPL-3.0-or-later WITH Bison-exception-2.2 AND FSFAP AND GFDL-1.1-or-later
        AND X11 AND FSFULLR AND GPL-3.0-or-later
      license_declared: HPND AND BSD-4-Clause-UC AND GFDL-1.3-invariants-only AND
        GFDL-1.3-or-later AND GPL-2.0-only AND Latex2e AND LGPL-2.1-or-later AND GPL-1.0-or-later
        AND GPL-3.0-or-later AND GPL-3.0-only AND FSFUL AND GPL-3.0-or-later WITH
        Texinfo-exception AND OFL-1.1 AND FSFULLRWD AND CC-BY-SA-4.0 AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND GFDL-1.3-only AND GPL-2.0-or-later AND
        GPL-3.0-or-later WITH Bison-exception-2.2 AND FSFAP AND GFDL-1.1-or-later
        AND X11 AND FSFULLR AND GPL-3.0-or-later
      short_summary: Bourne-Again SHell
      supplier: 'Organization: Broadcom, Inc.'
