sources:
- archive: webrick-1.9.2.gem
  archive_sha512sum: d5ef4bb969177773f83a5047909b4257383c26dfb3c45ebfb18f7d1a4d1a12d3f8c165df956db212b00d0e542bef7c4dd8d81ab119556977b1db82a805e6e498
  skip_validation: true
  spdx:
    package:
      detailed_description: 'WEBrick is an HTTP server toolkit that can be configured
        as an HTTPS server, a proxy server, and a virtual-host server. '
      home_page: https://rubygems.org/gems/webrick/versions/1.9.2
      license_concluded: MIT AND BSD-2-Clause
      license_declared: MIT AND BSD-2-Clause
      short_summary: HTTP server toolkit
      supplier: 'Organization: Broadcom, Inc.'
