sources:
- archive: protocol-http2-0.24.0.gem
  archive_sha512sum: feee9bbb61694cafd754afbb7537909804d0be4bbfa710b82f6a0776c29da49fd2dd0b987bc9cda7caf2379d7718cd7263864e53b74e3055741ef8e51d52fad4
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Provides a low-level implementation of the HTTP/2 protocol. '
      home_page: https://rubygems.org/gems/protocol-http2/versions/0.24.0
      license_concluded: MIT
      license_declared: MIT
      short_summary: A low level implementation of the HTTP/2 protocol.
      supplier: 'Organization: Broadcom, Inc.'
