sources:
- archive: sphinxcontrib_htmlhelp-2.1.0.tar.gz
  archive_sha512sum: 9aa2650ed27712a94de6ea16954db952db9c4a0c5f509aba42e33c69ba46f7069e9ee01c09a31e531fd096882c0248cf72334404d717a9f35aafc22e3976530e
  skip_validation: true
  spdx:
    package:
      detailed_description: 'sphinxcontrib-htmlhelp is a sphinx extension which renders
        HTML help files.'
      home_page: https://pypi.org/project/sphinxcontrib-htmlhelp
      license_concluded: BSD-3-Clause AND BSD-2-Clause
      license_declared: BSD-3-Clause AND BSD-2-Clause
      short_summary: Sphinx extension for HTML help files
      supplier: 'Organization: Broadcom, Inc.'
