sources:
- archive: bundler-4.0.4.gem
  archive_sha512sum: 77ec51ce0b7038bb8c5e1efbc9e809fd65127c31c0f2990a36eaecdc2b58076f3635f4fc6c0bf38585809b862fc7a8acf15d9a41a24445916591827fd0d518e3
  skip_validation: true
  spdx:
    package:
      detailed_description: "Bundler manages an application's dependencies through its entire life across many machines, systematically and repeatably. "
      home_page: https://rubygems.org/gems/bundler/versions/4.0.4
      license_concluded: (BSD-2-Clause OR Ruby) AND BSD-2-Clause AND MIT AND Ruby
      license_declared: (BSD-2-Clause OR Ruby) AND BSD-2-Clause AND MIT AND Ruby
      short_summary: manages an application's dependencies
      supplier: 'Organization: Broadcom, Inc.'
