sources:
- archive: libostree-2025.2.tar.xz
  archive_type: upstream
  version: 2025.2
  name: libostree-2025.2
  url: https://github.com/ostreedev/ostree/releases/download/v2025.2/libostree-2025.2.tar.xz
  repo_url: https://github.com/ostreedev/ostree.git
  commit_id: 1dd64eb264be462475a1163c6fee686c1f191994
  skip_list: []
  missing: []
  archive_sha512sum: 5e732a22da238b378e779c3886445977da49e2f810d18cb3580b030175e5e9db53408bcba245e840cdaea7e193907d284a369c42b3b7104c270e58a8c38f4f6a
  skip_validation: true
  spdx:
    package:
      detailed_description: 'OSTree is a tool for managing bootable, immutable, versioned
        filesystem trees. While it takes over some of the roles of tradtional "package
        managers" like dpkg and rpm, it is not a package system; nor is it a tool
        for managing full disk images. Instead, it sits between those levels, offering
        a blend of the advantages (and disadvantages) of both. '
      home_page: https://ostree.readthedocs.io/en/latest
      license_concluded: (Apache-2.0 OR GPL-2.0-only) AND (CC-BY-SA-3.0 OR GFDL-1.3-or-later)
        AND BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND FSFAP-no-warranty-disclaimer
        AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-2.0-only AND GPL-2.0-or-later
        AND GPL-2.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later WITH
        Autoconf-exception-generic AND GPL-2.0-or-later WITH Libtool-exception AND
        GPL-3.0-or-later AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND LGPL-2.0-only AND LGPL-2.0-or-later
        AND LGPL-2.1-only AND LGPL-2.1-or-later AND MIT AND X11
      license_declared: (Apache-2.0 OR GPL-2.0-only) AND (CC-BY-SA-3.0 OR GFDL-1.3-or-later)
        AND BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND FSFAP-no-warranty-disclaimer
        AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-2.0-only AND GPL-2.0-or-later
        AND GPL-2.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later WITH
        Autoconf-exception-generic AND GPL-2.0-or-later WITH Libtool-exception AND
        GPL-3.0-or-later AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND LGPL-2.0-only AND LGPL-2.0-or-later
        AND LGPL-2.1-only AND LGPL-2.1-or-later AND MIT AND X11
      short_summary: Git for operating system binaries
      supplier: 'Organization: Broadcom, Inc.'
  license_manual_review:
  - file_paths:
    - libostree-2025.2/README.md
    sha256sum: 8673dfeea260a26dcad4d3456264f2a1ccdc96fc1c4009ae8b5623e6ce5555ca
    spdx_exp: LGPL-2.0-or-later
