sources:
- archive: containerd-2.3.1.tar.gz
  archive_type: upstream
  version: 2.3.1
  name: containerd-2.3.1
  url: https://github.com/containerd/containerd/archive/refs/tags/v2.3.1.tar.gz
  repo_url: https://github.com/containerd/containerd.git
  commit_id: 64b425cf570b3b8dd1d4cc46da7c1fce65c6651a
  skip_list: []
  missing: []
  archive_sha512sum: a0dbb73c73267205a5e880afa370371b84cbb45d3c64071b9e6f9b8124377c0833a20799e4492df0636781f0af7016703475e96d4750ce235f9706c9d90f5191
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Containerd is an open source project. It is available
        as a daemon for Linux, which manages the complete container lifecycle of its
        host system. '
      home_page: https://containerd.io/docs
      license_concluded: MIT AND GPL-1.0-or-later AND BSD-2-Clause AND CC-BY-SA-4.0
        AND MPL-2.0 AND Apache-2.0 AND ISC AND BSD-3-Clause
      license_declared: MIT AND GPL-1.0-or-later AND BSD-2-Clause AND CC-BY-SA-4.0
        AND MPL-2.0 AND Apache-2.0 AND ISC AND BSD-3-Clause
      short_summary: Containerd
      supplier: 'Organization: Broadcom, Inc.'
