sources:
- archive: containerd-1.6.38.tar.gz
  archive_sha512sum: c908e1bb8167ce44d801eeeedb9190f5429de66663b6a3989c9626334af2c79162830de58f24dc534b116cf74f1388945d242c74f9b4dc858b34cd4399e45fbb
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Containerd is an open source project. It is available
        as a daemon for Linux, which manages the complete container lifecycle of its
        host system. '
      home_page: https://containerd.io/docs
      license_concluded: MIT AND GPL-1.0-or-later AND BSD-2-Clause AND CC-BY-SA-4.0
        AND MPL-2.0 AND Apache-2.0 AND ISC AND BSD-3-Clause
      license_declared: MIT AND GPL-1.0-or-later AND BSD-2-Clause AND CC-BY-SA-4.0
        AND MPL-2.0 AND Apache-2.0 AND ISC AND BSD-3-Clause
      short_summary: Containerd
      supplier: 'Organization: Broadcom, Inc.'
