sources:
- archive: containerd-2.3.2.tar.gz
  archive_type: upstream
  version: 2.3.2
  name: containerd-2.3.2
  url: https://github.com/containerd/containerd/archive/refs/tags/v2.3.2.tar.gz
  repo_url: https://github.com/containerd/containerd.git
  commit_id: fff62f14765df376e5fc36f5a8f8e795b5670f61
  skip_list: []
  missing: []
  archive_sha512sum: 2ce4744e0a93917fa45c2930c22853315577f217fe66d4761a96f4289241cdc930b52e8f646a28e0277747396f031964085c03885824a2f12dd6950ab651b348
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Containerd is an open source project. It is available
        as a daemon for Linux, which manages the complete container lifecycle of its
        host system. '
      home_page: https://containerd.io/docs
      license_concluded: MIT AND GPL-1.0-or-later AND BSD-2-Clause AND CC-BY-SA-4.0
        AND MPL-2.0 AND Apache-2.0 AND ISC AND BSD-3-Clause
      license_declared: MIT AND GPL-1.0-or-later AND BSD-2-Clause AND CC-BY-SA-4.0
        AND MPL-2.0 AND Apache-2.0 AND ISC AND BSD-3-Clause
      short_summary: Containerd
      supplier: 'Organization: Broadcom, Inc.'
