sources:
- archive: mesa-23.0.0.tar.gz
  archive_sha512sum: 79e115c2e21198b61353d98f2eb44093ff7247e2793163b17bb00b6f30125253dc64761c3290bfb456df6de7b5dba9b7b7e9cc503aa0ff28516483f2f26f00ba
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Mesa is an OpenGL compatible 3D graphics library. '
      home_page: http://www.mesa3d.org
      license_concluded: (GPL-2.0-only WITH Linux-syscall-note OR MIT) AND (GPL-3.0-only
        OR MIT) AND (MIT OR Unlicense) AND (GPL-2.0-only OR MIT) AND (Apache-2.0 OR
        MIT) AND Apache-2.0 AND GPL-1.0-or-later AND GPL-1.0-or-later WITH Linux-syscall-note
        AND BSL-1.0 AND ISC AND X11 AND MIT AND BSD-2-Clause AND BSD-3-Clause AND
        NCSA AND MIT-Khronos-old AND GPL-2.0-only AND HPND AND HPND-sell-variant AND
        GPL-2.0-only WITH Linux-syscall-note AND CC0-1.0 AND SGI-B-2.0 AND ICU
      license_declared: (GPL-2.0-only WITH Linux-syscall-note OR MIT) AND (GPL-3.0-only
        OR MIT) AND (MIT OR Unlicense) AND (GPL-2.0-only OR MIT) AND (Apache-2.0 OR
        MIT) AND Apache-2.0 AND GPL-1.0-or-later AND GPL-1.0-or-later WITH Linux-syscall-note
        AND BSL-1.0 AND ISC AND X11 AND MIT AND BSD-2-Clause AND BSD-3-Clause AND
        NCSA AND MIT-Khronos-old AND GPL-2.0-only AND HPND AND HPND-sell-variant AND
        GPL-2.0-only WITH Linux-syscall-note AND CC0-1.0 AND SGI-B-2.0 AND ICU
      short_summary: Mesa is an OpenGL compatible 3D graphics library.
      supplier: 'Organization: Broadcom, Inc.'
