sources:
- archive: flit_core-3.12.0.tar.gz
  skip_validation: true
  archive_sha512sum: 189dcd674722164b165e18b11c4dc72b8309fa2e3c82fc1ed6a9160bb5c6c1f86e2b2cfa111603cf73dca0dba74a496a664d5cbb6242587b47f139c42f7ae8bd
  name: flit_core-3.12.0
  version: 3.12.0
  url: https://files.pythonhosted.org/packages/69/59/b6fc2188dfc7ea4f936cd12b49d707f66a1cb7a1d2c16172963534db741b/flit_core-3.12.0.tar.gz
  repo_url: https://github.com/pypa/flit
  commit_id: 1c8141722066ffe1497e511982feeea0f091ddb6
  missing: [update-vendored-tomli.sh, .pre-commit-config.yaml, .coveragerc, config.py, wheel.py, codecov.yml, .github, SECURITY.md, bootstrap_install.py, .gitignore, .bumpversion.cfg, prepare_license_list.py, tests, vendor, LICENSE, flit_core, tox.ini, bootstrap_dev.py, doc, sdist.py, versionno.py, __init__.py, _spdx_data.py, .readthedocs.yml, PKG-INFO, buildapi.py, common.py, flit, tests_core, pyproject.toml, build_dists.py, README.rst]
  skip_list: [README.rst, pyproject.toml]
  spdx:
    package:
      detailed_description: 'This is the extensible, standards compliant build backend
        used by Hatch.'
      home_page: https://pypi.org/project/flit_core/
      license_concluded: BSD-3-Clause AND BSD-2-Clause AND MIT
      license_declared: BSD-3-Clause AND BSD-2-Clause AND MIT
      short_summary: The build backend used by Hatch
      supplier: 'Organization: Broadcom, Inc.'
