sources:
- archive: headers-more-nginx-module-0.37.tar.gz
  archive_sha512sum: 0cc2fffe506194d439e3669644d41b7943e2c3cffa3483eb70b92067930b358d506a14646eff8362b191a11c624db29f6b53d830876929dcb4ce1c9d7b2bc40d
  skip_validation: false
  repo_url: https://github.com/openresty/headers-more-nginx-module
  url: https://github.com/openresty/headers-more-nginx-module/archive/refs/tags/v0.37.tar.gz
  commit_id: 06dc0be56e5ec9f7fd814e881b066b5540a85bec
  name: "headers-more-nginx-module-0.37"
  version: 0.37
  archive_type: upstream
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: Set, add, and clear arbitrary output headers in NGINX
        http servers.
      home_page: https://github.com/openresty/headers-more-nginx-module
      license_concluded: BSD-3-Clause AND BSD-2-Clause
      license_declared: BSD-3-Clause AND BSD-2-Clause
      short_summary: Set, add, and clear arbitrary output headers in NGINX http servers.
      supplier: 'Organization: Broadcom, Inc.'
- archive: nginx-1.30.4.tar.gz
  archive_sha512sum: 48c21de65fa188137a4088d02c28e2533a7164040bf19281637e025012e6d03afcacb0ee15463a107685a2a221037f24ce15fc89c46b6f7a36b94443d3993bf1
  skip_validation: false
  archive_type: upstream
  name: "nginx-1.30.4"
  version: 1.30.4
  url: https://github.com/nginx/nginx/releases/download/release-1.30.4/nginx-1.30.4.tar.gz
  repo_url: https://github.com/nginx/nginx
  commit_id: bcf342539875c809e59348561856130b52ae29ce
  skip_list: []
  missing: [html, docs, CHANGES, misc, man, configure, CHANGES.ru, .gitignore, .github]
  spdx:
    package:
      detailed_description: 'NGINX is a free, open-source, high-performance HTTP server
        and reverse proxy, as well as an IMAP/POP3 proxy server. '
      home_page: http://nginx.org
      license_concluded: GPL-1.0-or-later AND BSD-2-Clause AND BSD-3-Clause
      license_declared: GPL-1.0-or-later AND BSD-2-Clause AND BSD-3-Clause
      short_summary: High-performance HTTP server and reverse proxy
      supplier: 'Organization: Broadcom, Inc.'
- archive: nginx-njs-0.9.6.tar.gz
  archive_sha512sum: 8696be2cc676308bd409cc1ed2c19d7e71dbd162cc13e8b679e813b7a66690a7ab0071057fc9d4ca242a6e1e5bc216fbf07f58f309e4c6f44182a2eeb82380fc
  archive_type: upstream
  skip_validation: false
  commit_id: e7ecb2c7365dd4f5a36d9b9b14bdb5dc4533360d
  url: https://github.com/nginx/njs/archive/refs/tags/0.9.6.tar.gz
  repo_url: https://github.com/nginx/njs.git
  name: "njs-0.9.6"
  version: 0.9.6
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: A subset of JavaScript language to use in nginx.
      home_page: https://github.com/nginx/njs
      license_concluded: BSD-3-Clause AND MIT AND GPL-2.0-or-later AND BSD-2-Clause
      license_declared: BSD-3-Clause AND MIT AND GPL-2.0-or-later AND BSD-2-Clause
      short_summary: A subset of JavaScript language to use in nginx.
      supplier: 'Organization: Broadcom, Inc.'
