sources:
- archive: googleauth-1.16.1.gem
  archive_sha512sum: 29987bd929c72f64adc6160e7bca55a868bd27a7dcceb168fb6b5177a0e06fc3df0006eec5862cdb99b352e0175ada757de17cc268ef64af7a92609bc99afa9a
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Google Auth Library for Ruby'
      home_page: https://rubygems.org/gems/googleauth
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: Google Auth Library for Ruby
      supplier: 'Organization: Broadcom, Inc.'
