sources:
- archive: unbound-1.25.1.tar.gz
  archive_sha512sum: e7104a70cd734a5e445890224b19510eac068b46c02fb65a7db911ad2f66db512b8aeae1dd44b505dc1288a315fd39dd54ca9decb78713bf6eb59fc6350ab804
  archive_type: upstream
  name: unbound-release-1.25.1
  version: 1.25.1
  url: https://github.com/NLnetLabs/unbound/archive/refs/tags/release-1.25.1.tar.gz
  repo_url: https://github.com/NLnetLabs/unbound
  commit_id: 75b6dba593d4fff000434cd64807c6ebd50bd244
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'Unbound is a validating, recursive, and caching DNS resolver.'
      home_page: http://www.unbound.net
      license_concluded: CC0-1.0 AND FSFULLR AND ISC AND HPND AND MIT AND GPL-3.0-or-later
        AND BSD-3-Clause AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        DOC AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH
        Bison-exception-2.2 AND GPL-3.0-or-later WITH Libtool-exception AND GPL-2.0-or-later
        WITH Autoconf-exception-macro AND FSFULLRWD AND BSD-2-Clause AND GPL-3.0-or-later
        WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND FSFUL AND Apache-2.0 AND X11
      license_declared: CC0-1.0 AND FSFULLR AND ISC AND HPND AND MIT AND GPL-3.0-or-later
        AND BSD-3-Clause AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        DOC AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH
        Bison-exception-2.2 AND GPL-3.0-or-later WITH Libtool-exception AND GPL-2.0-or-later
        WITH Autoconf-exception-macro AND FSFULLRWD AND BSD-2-Clause AND GPL-3.0-or-later
        WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND FSFUL AND Apache-2.0 AND X11
      short_summary: unbound dns server
      supplier: 'Organization: Broadcom, Inc.'
