sources:
- archive: libaio-0.3.113.tar.gz
  archive_sha512sum: 65c30a102433bf8386581b03fc706d84bd341be249fbdee11a032b237a7b239e8c27413504fef15e2797b1acd67f752526637005889590ecb380e2e120ab0b71
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The Linux-native asynchronous I/O facility ("async I/O",
        or "aio") has a richer API and capability set than the simple POSIX async
        I/O facility. This library, libaio, provides the Linux-native API for async
        I/O. The POSIX async I/O facility requires this library in order to provide
        kernel-accelerated async I/O capabilities, as do applications which require
        the Linux-native async I/O API. '
      home_page: https://git.fedorahosted.org/git/libaio.git
      license_concluded: LGPL-2.1-only AND GPL-2.0-only AND LGPL-2.0-or-later
      license_declared: LGPL-2.1-only AND GPL-2.0-only AND LGPL-2.0-or-later
      short_summary: Linux-native asynchronous I/O access library
      supplier: 'Organization: Broadcom, Inc.'
