sources:
- archive: libclc-18.1.8.tar.xz
  archive_sha512sum: 532e990b164b0e45ad92b4ca80d53fc6ec79fd31406d239079615342866e7f70e7a9aa8bbe025b82ee61d9c52a286b280797e83f8ac69f96dbdbbe8591dad9f0
  skip_validation: true
  spdx:
    package:
      short_summary: libclc is an open source implementation of the OpenCL C programming language library requirements.
      detailed_description: libclc provides the OpenCL C standard library as required by the OpenCL 1.1 specification. It supplies bitcode libraries for use by OpenCL implementations and drivers, enabling OpenCL C kernel compilation.
      home_page: https://libclc.llvm.org
      supplier: 'Organization: VMware, Inc.'
      license_concluded: (MIT OR NCSA) AND Apache-2.0 WITH LLVM-exception AND BSD-3-Clause AND MIT AND NCSA AND SunPro
      license_declared: (MIT OR NCSA) AND Apache-2.0 WITH LLVM-exception AND BSD-3-Clause AND MIT AND NCSA AND SunPro
      copyright_text: Copyright (c) 2025 VMware, Inc.
