sources:
- archive: docker-cli-28.2.2.tar.gz
  archive_type: upstream
  version: 28.2.2
  name: cli-28.2.2
  url: https://github.com/docker/cli/archive/refs/tags/v28.2.2.tar.gz
  repo_url: https://github.com/docker/cli.git
  commit_id: e6534b4eb700e592f25e7213568a02f3ce37460d
  skip_list: []
  missing: []
  archive_sha512sum: 1ba62398322c65e6994c0c6821b912c9a9b215083593d63557c5255064c407bd25f72044336ebb19977fe6d03215ec47174c6617890a817b9e34ed010535fb6b
  skip_validation: false
  spdx:
    package:
      detailed_description: Docker CLI
      home_page: https://github.com/docker/cli
      license_concluded: BSD-3-Clause AND CC-BY-SA-4.0 AND Apache-2.0 AND BSD-2-Clause
        AND MIT
      license_declared: BSD-3-Clause AND CC-BY-SA-4.0 AND Apache-2.0 AND BSD-2-Clause
        AND MIT
      short_summary: Docker CLI
      supplier: 'Organization: Broadcom, Inc.'
- archive: moby-28.2.2.tar.gz
  archive_type: upstream
  version: 28.2.2
  name: moby-28.2.2
  url: https://github.com/moby/moby/archive/refs/tags/v28.2.2.tar.gz
  repo_url: https://github.com/moby/moby.git
  commit_id: 45873be4ae3f5488c9498b3d9f17deaddaf609f4
  skip_list: []
  missing: []
  archive_sha512sum: e63ce38bb7badb01de918f678ad9fb216b279170177fe7d7c4120c8a1196add485cc974f9dff239a274220ebab60a2dc6852f07dc2ddafe8cec07c65dbd19a49
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Docker is an open source project to build, ship and run
        any application as a lightweight container. '
      home_page: http://docs.docker.com
      license_concluded: (OpenSSL OR BSD-3-Clause) AND (Apache-2.0 OR GPL-2.0-or-later)
        AND MIT AND ISC AND CC-BY-SA-4.0 AND CC0-1.0 AND GPL-2.0-only AND BSD-2-Clause
        AND Apache-2.0 AND CC-BY-4.0 AND GPL-1.0-or-later AND BSD-3-Clause AND MPL-2.0
      license_declared: (OpenSSL OR BSD-3-Clause) AND (Apache-2.0 OR GPL-2.0-or-later)
        AND MIT AND ISC AND CC-BY-SA-4.0 AND CC0-1.0 AND GPL-2.0-only AND BSD-2-Clause
        AND Apache-2.0 AND CC-BY-4.0 AND GPL-1.0-or-later AND BSD-3-Clause AND MPL-2.0
      short_summary: Docker
      supplier: 'Organization: Broadcom, Inc.'
