sources:
- archive: checkpolicy-3.10.tar.gz
  archive_sha512sum: b5e18d4664ba96d33f2b74b89972e056680e3cc0ede8327599f8b0972ac031eed1ff8e219ad90fb3537e29d711dd51cbdde73db589ca35ec27b7c63bc72c7afd
  skip_validation: true
  spdx:
    package:
      detailed_description: 'checkpolicy is a program that checks and compiles a SELinux
        security policy configuration into a binary representation that can be loaded
        into the kernel. '
      home_page: https://github.com/SELinuxProject/selinux/wiki
      license_concluded: GPL-2.0-only AND LGPL-2.1-or-later
      license_declared: GPL-2.0-only AND LGPL-2.1-or-later
      short_summary: SELinux policy compiler
      supplier: 'Organization: Broadcom, Inc.'
