sources:
- archive: os-1.1.4.gem
  archive_sha512sum: 988eccce8c32aafecdaeec6eb09e079699a2da886e5763541e93f3374d82963cc6582eb905e353008e3ac8a2994eff0e7f9e6bf8005dc10eeb7956cfd949dd48
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The OS gem allows for some easy telling if you're on windows or not.'
      home_page: https://rubygems.org/gems/os
      license_concluded: MIT
      license_declared: MIT
      short_summary: The OS gem allows for some easy telling if you're on windows or not.
      supplier: 'Organization: Broadcom, Inc.'
