sources:
- archive: sysdig-0.39.0.tar.gz
  archive_sha512sum: d43c816d4c29cc283d3247ac0ac3591b8adea7a08194a80b4e530f0c45730a824d16eda7b07bb70e4658cbae0f851fbb67ec880eedf33477bf5bfc911d8a7936
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Sysdig is open source, system-level exploration, capture
        system state and activity from a running Linux instance. Then save, filter
        and analyze. Sysdig is scriptable in Lua and includes a command line interface
        and a powerful interactive UI, csysdig, that runs in your terminal'
      home_page: http://www.sysdig.org
      license_concluded: Apache-2.0 AND GPL-1.0-or-later AND GPL-2.0-only AND LGPL-2.0-or-later AND MIT
      license_declared: Apache-2.0 AND GPL-1.0-or-later AND GPL-2.0-only AND LGPL-2.0-or-later AND MIT
      short_summary: Sysdig is a universal system visibility tool with native support
        for containers.
      supplier: 'Organization: Broadcom, Inc.'

- archive: falconsecurity-libs-0.19.0.tar.gz
  archive_sha512sum: 5b011c804b07bf2f3eb6a6d7e8c9ef4e54bcc8d74116020e887465aba3dec737bdf8fc854778a8230f7e23e87da29423c6320a8054873eb5c9c957ce40ef3825
  skip_validation: true
  spdx:
    package:
      detailed_description: This project contains libsinsp, libscap, the kernel module
        and the eBPF probes sources
      home_page: https://github.com/falcosecurity/libs/
      license_concluded: (GPL-1.0-or-later OR MIT) AND (GPL-2.0-only OR MIT) AND Apache-2.0 AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND MIT
      license_declared: (GPL-1.0-or-later OR MIT) AND (GPL-2.0-only OR MIT) AND Apache-2.0 AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND MIT
      short_summary: This project contains libsinsp, libscap, the kernel module and
        the eBPF probes sources
      supplier: 'Organization: Broadcom, Inc.'

- archive: nlohman-json-3.3.0.tar.gz
  archive_sha512sum: cb81e89797a9b8b322a7b421422f919cf1dadc939d83688196664aefc365fa52ec3601ca5419782c99e09e594b56301ac9ea909ac0f5231b70cfa3ff1257a964
  skip_validation: true
  spdx:
    package:
      detailed_description: A popular, header-only C++ library designed for seamless JSON parsing and manipulation with a focus on intuitive syntax.
      home_page: https://json.nlohmann.me/
      license_concluded: BSD-3-Clause AND MIT
      license_declared: BSD-3-Clause AND MIT
      short_summary: A popular, header-only C++ library designed for seamless JSON parsing and manipulation with a focus on intuitive syntax.
      supplier: 'Organization: Broadcom, Inc.'

- archive: uthash-1.9.8.tar.gz
  archive_sha512sum: 2ea7f35d662f711e216b1d2d26a1fae698b5f0a71f7151c4747161046de9d8c632dc756cb5948863394694dde47fa6f9383f46ca572c83bb6803383da0f2f740
  skip_validation: true
  spdx:
    package:
      detailed_description: uthash is a header-only library that provides a set of C macros for hash tables, dynamic arrays, and linked lists.
        Unlike traditional libraries, it does not require linking against an external object; instead, it is implemented entirely in C macros,
        making it highly portable across platforms including Linux, Windows, and macOS.
      home_page: https://github.com/troydhanson/uthash
      license_concluded: BSD-1-Clause AND BSD-3-Clause AND GPL-1.0-or-later AND Unlicense
      license_declared: BSD-1-Clause AND BSD-3-Clause AND GPL-1.0-or-later AND Unlicense
      short_summary: A set of C macros that allow any C structure to be stored in a hash table.
      supplier: 'Organization: Broadcom, Inc.'

- archive: valijson-1.0.2.tar.gz
  archive_sha512sum: c1141e533d6a791a01883c5b7ab9501eebc39057a850d784670a4bcf99bff3fee4c3120107128dcaa9db0505adf2ae794700620c02163b3e636f0b635031df80
  skip_validation: true
  spdx:
    package:
      detailed_description: A header-only C++ library for JSON Schema validation.
      home_page: https://github.com/tristanpenman/valijson
      license_concluded: BSD-2-Clause AND BSL-1.0 AND MIT
      license_declared: BSD-2-Clause AND BSL-1.0 AND MIT
      short_summary: A header-only C++ library for JSON Schema validation.
      supplier: 'Organization: Broadcom, Inc.'

- archive: tbb-2022.0.0.tar.gz
  archive_sha512sum: c87b84964b2c323f61895a532968dfa6413a774c177cffbf6e798a07e74e8da5d449144875771df0a1b02657eeb2a7ae4d41c6c432dbf7ea50e3d5a9ea9f8cd3
  skip_validation: true
  spdx:
    package:
      detailed_description: This project contains libsinsp, libscap, the kernel module
        and the eBPF probes sources
      home_page: https://github.com/falcosecurity/libs/
      license_concluded: 0BSD AND Apache-2.0 AND BSD-3-Clause AND BSL-1.0 AND MIT AND bzip2-1.0.6
      license_declared: 0BSD AND Apache-2.0 AND BSD-3-Clause AND BSL-1.0 AND MIT AND bzip2-1.0.6
      short_summary: This project contains libsinsp, libscap, the kernel module and
        the eBPF probes sources
      supplier: 'Organization: Broadcom, Inc.'
