sources:
- archive: sysdig-0.34.1-dependencies.tar.gz
  archive_sha512sum: 27192269e2c8578e0440ad4a1e1ad7fde98a7f00f064f3b1b0d395bc7c24f9b1ce9354430e25c6f51ac74067c37f9cbcb7eb55e1c8f6e5a3912beb91193212b9
  skip_validation: true
  spdx:
    package:
      detailed_description: vendor sources to build sysdig
      home_page: https://github.com/vmware/photon
      license_concluded: (MIT OR GPL-1.0-or-later) AND (MIT OR GPL-2.0-only) AND (MIT
        OR CC0-1.0) AND GPL-2.0-only WITH Linux-syscall-note AND bzip2-1.0.6 AND BSD-2-Clause
        AND GPL-3.0-or-later WITH GCC-exception-3.1 AND MIT AND GPL-2.0-only AND dtoa
        AND GPL-3.0-only AND JSON AND Apache-2.0 WITH LLVM-exception AND Zlib AND
        Apache-2.0 AND BSD-3-Clause AND BSL-1.0 AND NCSA AND GPL-1.0-or-later
      license_declared: (MIT OR GPL-1.0-or-later) AND (MIT OR GPL-2.0-only) AND (MIT
        OR CC0-1.0) AND GPL-2.0-only WITH Linux-syscall-note AND bzip2-1.0.6 AND BSD-2-Clause
        AND GPL-3.0-or-later WITH GCC-exception-3.1 AND MIT AND GPL-2.0-only AND dtoa
        AND GPL-3.0-only AND JSON AND Apache-2.0 WITH LLVM-exception AND Zlib AND
        Apache-2.0 AND BSD-3-Clause AND BSL-1.0 AND NCSA AND GPL-1.0-or-later
      short_summary: vendor sources to build sysdig
      supplier: 'Organization: Broadcom, Inc.'
- archive: sysdig-0.34.1.tar.gz
  archive_sha512sum: 2d7c6369eb6ae85cb7fca50da049470830eb8a88002414f257e5ccf1eb438fe36890d51107ffd782b2cd3b7358094de0795641a1cb6b086a4e29b9a5b6edad4f
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Sysdig is open source, system-level exploration, capture
        system state and activity from a running Linux instance. Then save, filter
        and analyze. Sysdig is scriptable in Lua and includes a command line interface
        and a powerful interactive UI, csysdig, that runs in your terminal '
      home_page: http://www.sysdig.org
      license_concluded: GPL-2.0-only AND Apache-2.0 AND MIT AND GPL-1.0-or-later
        AND LGPL-2.0-or-later
      license_declared: GPL-2.0-only AND Apache-2.0 AND MIT AND GPL-1.0-or-later AND
        LGPL-2.0-or-later
      short_summary: Sysdig is a universal system visibility tool with native support
        for containers.
      supplier: 'Organization: Broadcom, Inc.'
- archive: falconsecurity-libs-0.13.4.tar.gz
  archive_sha512sum: e4c9ab4cd8bbe544f13403573df7751b21c977ecefe4ea7c0b71c576a77c308d2f64f5a3d933a2493f23aacbc63148f24be0e897ca779a73879a48c63cbbad33
  skip_validation: true
  spdx:
    package:
      detailed_description: This project contains libsinsp, libscap, the kernel module
        and the eBPF probes sources
      home_page: https://github.com/falcosecurity/libs/
      license_concluded: (MIT OR GPL-1.0-or-later) AND (MIT OR GPL-2.0-only) AND GPL-1.0-or-later
        AND MIT AND GPL-2.0-only AND GPL-2.0-only WITH Linux-syscall-note AND Apache-2.0
      license_declared: (MIT OR GPL-1.0-or-later) AND (MIT OR GPL-2.0-only) AND GPL-1.0-or-later
        AND MIT AND GPL-2.0-only AND GPL-2.0-only WITH Linux-syscall-note AND Apache-2.0
      short_summary: This project contains libsinsp, libscap, the kernel module and
        the eBPF probes sources
      supplier: 'Organization: Broadcom, Inc.'
