sources:
- archive: rdiscount-2.2.7.4.gem
  archive_sha512sum: 83108dad15cca3bad30fe40442aaadd4cdfc9bc9872309be3ce0c6cdc8efd9d73617bfcf66abac12218772c633bee38761aed631f9c45b6115a31a3f75070e51
  skip_validation: true
  spdx:
    package:
      detailed_description: "RDiscount converts documents in Markdown syntax to HTML.\
        \ It uses the excellent Discount processor by David Loren Parsons for this\
        \ purpose, and thereby inherits Discount\u2019s numerous useful extensions\
        \ to the Markdown language. "
      home_page: https://rubygems.org/gems/rdiscount/versions/2.2.7.3
      license_concluded: BSD-3-Clause
      license_declared: BSD-3-Clause
      short_summary: Fast Implementation of Gruber's Markdown in C
      supplier: 'Organization: Broadcom, Inc.'
