sources:
- archive: trace-cmd-v3.3.4.tar.gz
  archive_sha512sum: ea7329010e6bc7fb1f2fc3324dd97f6496c45f3d25b551843e9027b8cc34425d1e34c6c07f875ea5d03397d1b4c83b64b9283d21b930efcdc961e08a93a04362
  archive_type: upstream
  name: trace-cmd-v3.3.4
  version: "3.3.4"
  url: https://git.kernel.org/pub/scm/utils/trace-cmd/trace-cmd.git/snapshot/trace-cmd-v3.3.4.tar.gz
  repo_url: https://git.kernel.org/pub/scm/utils/trace-cmd/trace-cmd.git
  commit_id: 3360b56d57abcd3153d8b7ef3b4a446e18616771
  missing: ['.gitignore', '.gitattributes']
  spdx:
    package:
      detailed_description: 'trace-cmd is a user-space command line tool that makes
        it convenient to use the Ftrace functionality in the kernel by providing appropriate
        command interfaces to record and analyze the traces. '
      home_page: https://git.kernel.org/pub/scm/utils/trace-cmd/trace-cmd.git
      license_concluded: GPL-2.0-or-later AND GPL-2.0-only AND GPL-1.0-or-later AND
        LGPL-2.1-only AND LGPL-2.1-or-later
      license_declared: GPL-2.0-or-later AND GPL-2.0-only AND GPL-1.0-or-later AND
        LGPL-2.1-only AND LGPL-2.1-or-later
      short_summary: trace-cmd is a user-space front-end command-line tool for Ftrace
      supplier: 'Organization: Broadcom, Inc.'
