sources:
- archive: pip-25.3.tar.gz
  archive_type: upstream
  archive_sha512sum: aca54dc7daaba195ba5873e24296242d935a225ed5f4d2e0da672d68573a48650a5028d42051a7a61170de335f122ffb8f97faafc3ad86c488f8bdac3b8bbe1d
  name: pip-25.3
  version: "25.3"
  repo_url: https://github.com/pypa/pip.git
  url: https://files.pythonhosted.org/packages/fe/6e/74a3f0179a4a73a53d66ce57fdb4de0080a8baa1de0063de206d6167acc2/pip-25.3.tar.gz
  commit_id: a52069365063ea813fe3a3f8bac90397c9426d35
  missing: [urllib3.pyi, setup.cfg, reporters.pyi, .github, pkg_resources.pyi, resolvers.pyi, requests.pyi, news, tests, structs.pyi, .pre-commit-config.yaml, collections_abc.pyi, msgpack.pyi, __init__.pyi, tools, .readthedocs-custom-redirects.yml, pyproject_hooks.pyi, .mailmap, .gitattributes, typing_extensions.pyi, providers.pyi, pygments.pyi, .readthedocs.yml, PKG-INFO, .git-blame-ignore-revs, .gitignore, noxfile.py, distlib.pyi, pip.egg-info]
  spdx:
    package:
      detailed_description: 'Pip is the package installer for Python. You can use
        pip to install packages from the Python Package Index and other indexes. '
      home_page: https://pypi.org/project/pip/
      license_concluded: BSD-3-Clause AND (BSD-2-Clause OR Apache-2.0) AND MIT AND
        Apache-2.0 AND (BSD-3-Clause OR Apache-2.0) AND ISC AND (BSD-2-Clause OR Apache-2.0)
        AND LGPL-2.1-only AND 0BSD AND LGPL-2.1-or-later AND Python-2.0 AND MPL-2.0
        AND BSD-2-Clause
      license_declared: BSD-3-Clause AND (BSD-2-Clause OR Apache-2.0) AND MIT AND
        Apache-2.0 AND (BSD-3-Clause OR Apache-2.0) AND ISC AND (BSD-2-Clause OR Apache-2.0)
        AND LGPL-2.1-only AND 0BSD AND LGPL-2.1-or-later AND Python-2.0 AND MPL-2.0
        AND BSD-2-Clause
      short_summary: The PyPA recommended tool for installing Python packages.
      supplier: 'Organization: Broadcom, Inc.'
