sources:
- archive: pip-24.3.1.tar.gz
  archive_sha512sum: 2fad7072473d67fa0dbfc2c060b1b4752ea1b0d021051ebef44a668e6c9c731a530b1afb38872fdbc2efec0598fae532e61a5ed545524875b51a3fe0a8d11d96
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Pip is the package installer for Python. You can use
        pip to install packages from the Python Package Index and other indexes. '
      home_page: https://pypi.org/project/pip/
      license_concluded: BSD-3-Clause AND (BSD-2-Clause OR Apache-2.0) AND MIT AND
        Apache-2.0 AND (BSD-3-Clause OR Apache-2.0) AND ISC AND (BSD-2-Clause OR Apache-2.0)
        AND LGPL-2.1-only AND 0BSD AND LGPL-2.1-or-later AND Python-2.0 AND MPL-2.0
        AND BSD-2-Clause
      license_declared: BSD-3-Clause AND (BSD-2-Clause OR Apache-2.0) AND MIT AND
        Apache-2.0 AND (BSD-3-Clause OR Apache-2.0) AND ISC AND (BSD-2-Clause OR Apache-2.0)
        AND LGPL-2.1-only AND 0BSD AND LGPL-2.1-or-later AND Python-2.0 AND MPL-2.0
        AND BSD-2-Clause
      short_summary: The PyPA recommended tool for installing Python packages.
      supplier: 'Organization: Broadcom, Inc.'
