sources:
- archive: mini_portile2-2.8.9.gem
  archive_sha512sum: 7107b3eb3376e19bcf083ece525a5241f6c2f5253cba0d20f4fbdaccf156a7ea8ac15b3d8275c2b0b91720642d24e10de61c31628640a6e0cd49de697219d7be
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Simplistic port-like solution for developers. It provides
        a standard and simplified way to compile against dependency libraries without
        messing up your system. '
      home_page: https://rubygems.org/gems/mini_portile2/
      license_concluded: MIT
      license_declared: MIT
      short_summary: Simplistic port-like solution for developers
      supplier: 'Organization: Broadcom, Inc.'
