sources:
- archive: fuse-2.9.9.tar.gz
  archive_sha512sum: 1acd51a647ec3dbf9eaafb80cec92bd8542bcbb2cf4510fc8b079b4f8aaa8f4b301e469ddefe4f1cc4ae2bf941e028077601c20d97f187cc618cea8710cbe331
  skip_validation: true
  spdx:
    package:
      detailed_description: 'With FUSE it is possible to implement a fully functional
        filesystem in a userspace program. '
      home_page: http://fuse.sourceforge.net/
      license_concluded: GPL-1.0-or-later AND LGPL-2.1-only AND GPL-2.0-only AND LGPL-2.0-only
        AND BSD-2-Clause
      license_declared: GPL-1.0-or-later AND LGPL-2.1-only AND GPL-2.0-only AND LGPL-2.0-only
        AND BSD-2-Clause
      short_summary: File System in Userspace (FUSE) utilities
      supplier: 'Organization: Broadcom, Inc.'
