sources:
- archive: apache-tomcat-10.1.46-src.tar.gz
  archive_type: upstream
  archive_sha512sum: 4abb5a5fad013135c4107508e4530673e4af623658b6aff5c4fc18fd557dfca37b58a9c5c0479e52e240b53d469ad91a34225a80b718aa2f91b8d385d16d9682
  name: apache-tomcat-10.1.46-src
  version: 10.1.46
  url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.46/src/apache-tomcat-10.1.46-src.tar.gz
  repo_url: https://github.com/apache/tomcat.git
  commit_id: c13c35870418153273725eab75ce1c3a8364a331
  skip_list:
  - RCS
  - CVS
  - tags
  - .git
  - .hg
  - .bzr
  - _darcs
  - __pycache__
  missing:
  - owb
  - stuffed
  - cxf
  spdx:
    package:
      detailed_description: 'The Apache Tomcat package contains binaries for the Apache
        Tomcat servlet container. '
      home_page: http://tomcat.apache.org
      license_concluded: (EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND
        (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND LGPL-2.0-or-later
        AND GPL-2.0-only AND bzip2-1.0.6 AND Zlib AND CPL-1.0 AND CDDL-1.0 AND EPL-2.0
        AND EPL-1.0 AND CC0-1.0 AND Apache-2.0
      license_declared: (EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND
        (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND LGPL-2.0-or-later
        AND GPL-2.0-only AND bzip2-1.0.6 AND Zlib AND CPL-1.0 AND CDDL-1.0 AND EPL-2.0
        AND EPL-1.0 AND CC0-1.0 AND Apache-2.0
      short_summary: Apache Tomcat 10.1
      supplier: 'Organization: Broadcom, Inc.'
- archive: apache-tomcat-9.0.109-src.tar.gz
  archive_type: upstream
  archive_sha512sum: 5ff1fdc882ffd3e3bd05be17b6dc45f914fb2b6553f2438ef30f929f2255cde49b1bac3e39f1a1b1440664b5477e64bde6c408a477e7eab097aa8cee01b82850
  name: apache-tomcat-9.0.109-src
  version: 9.0.109
  url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.109/src/apache-tomcat-9.0.109-src.tar.gz
  repo_url: https://github.com/apache/tomcat.git
  commit_id: 312541e51725cdfe98d8cc6414b31d36d913fdd1
  skip_list:
  - RCS
  - CVS
  - tags
  - .git
  - .hg
  - .bzr
  - _darcs
  - __pycache__
  missing:
  - owb
  - cxf
  spdx:
    package:
      detailed_description: The Apache Tomcat package provides the Apache Tomcat servlet
        container.
      home_page: http://tomcat.apache.org
      license_concluded: (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND
        Apache-2.0 AND LGPL-2.0-or-later AND CPL-1.0 AND GPL-2.0-only AND bzip2-1.0.6
        AND EPL-1.0 AND CC0-1.0 AND CDDL-1.0 AND Zlib
      license_declared: (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND
        Apache-2.0 AND LGPL-2.0-or-later AND CPL-1.0 AND GPL-2.0-only AND bzip2-1.0.6
        AND EPL-1.0 AND CC0-1.0 AND CDDL-1.0 AND Zlib
      short_summary: Apache Tomcat 9
      supplier: 'Organization: Broadcom, Inc.'
- archive: base-for-apache-tomcat-10.1.46.tar.gz
  archive_sha512sum: 2894b243248f3189eab6cbaf90190118584cb904d4694627c9d152b519608ccba28a0e6439164a435391a5ba20649b049c75c74f52c04520f88eff373251b2ee
  skip_validation: true
  license_manual_review:
  # Icon uses cc-by-sa-4.0 license
  - file_paths:
    - base-for-apache-tomcat-10.1.46/nsis-3.11-src/Contrib/MakeLangId/MakeLangId.cpp
    sha256sum: 1cb56a65d201465110930fde78929f0ef0881b30c64d6b14dc014d97ca0d5774
    spdx_exp: ''
  spdx:
    package:
      detailed_description: base-for-apache-tomcat is a cached -Dbase.path folder
        after apache-tomcat build
      home_page: https://github.com/vmware/photon
      license_concluded: (Apache-2.0 OR EPL-2.0) AND Zlib AND FSFULLR AND OpenSSL
        AND Bitstream-Vera AND GPL-3.0-or-later AND GPL-2.0-or-later AND CC-BY-SA-4.0
        AND BSD-2-Clause-Views AND bzip2-1.0.6 AND FSFULLRWD AND EPL-2.0 AND CC0-1.0
        AND MPL-2.0 AND LGPL-2.1-or-later AND BSD-3-Clause AND MIT AND EPL-1.0 AND
        BSD-2-Clause AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND
        X11 AND CPL-1.0 AND GPL-2.0-only AND GPL-2.0-or-later WITH Libtool-exception
        AND GPL-3.0-only AND CDDL-1.0 AND LGPL-2.1-only AND FSFUL AND UPL-1.0 AND
        GPL-2.0-only WITH Classpath-exception-2.0 AND LGPL-2.0-or-later WITH WxWindows-exception-3.1
        AND Apache-2.0
      license_declared: (Apache-2.0 OR EPL-2.0) AND Zlib AND FSFULLR AND OpenSSL AND
        Bitstream-Vera AND GPL-3.0-or-later AND GPL-2.0-or-later AND CC-BY-SA-4.0
        AND BSD-2-Clause-Views AND bzip2-1.0.6 AND FSFULLRWD AND EPL-2.0 AND CC0-1.0
        AND MPL-2.0 AND LGPL-2.1-or-later AND BSD-3-Clause AND MIT AND EPL-1.0 AND
        BSD-2-Clause AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND
        X11 AND CPL-1.0 AND GPL-2.0-only AND GPL-2.0-or-later WITH Libtool-exception
        AND GPL-3.0-only AND CDDL-1.0 AND LGPL-2.1-only AND FSFUL AND UPL-1.0 AND
        GPL-2.0-only WITH Classpath-exception-2.0 AND LGPL-2.0-or-later WITH WxWindows-exception-3.1
        AND Apache-2.0
      short_summary: Cached -Dbase.path folder of apache-tomcat build
      supplier: 'Organization: Broadcom, Inc.'
- archive: base-for-apache-tomcat-9.0.109.tar.gz
  archive_sha512sum: b04c30118979069868b9e4166a520467f011a82b51d23181e192a2495ca6d628f4b9463f7bddfe4102df369e71ce1126cd0d09ec89bbfed6bae0ffd5e4b15e52
  skip_validation: true
  license_manual_review:
  # Icon uses cc-by-sa-4.0 license
  - file_paths:
    - base-for-apache-tomcat-9.0.109/nsis-3.11-src/Contrib/MakeLangId/MakeLangId.cpp
    sha256sum: 1cb56a65d201465110930fde78929f0ef0881b30c64d6b14dc014d97ca0d5774
    spdx_exp: ''
  spdx:
    package:
      detailed_description: base-for-apache-tomcat is a cached -Dbase.path folder
        after apache-tomcat build
      home_page: https://github.com/vmware/photon
      license_concluded: (Apache-2.0 OR EPL-2.0) AND CC-BY-SA-4.0 AND BSD-2-Clause
        AND GPL-3.0-only AND OpenSSL AND BSD-3-Clause AND Zlib AND GPL-3.0-or-later
        AND EPL-1.0 AND GPL-2.0-or-later AND CC0-1.0 AND Bitstream-Vera AND UPL-1.0
        AND bzip2-1.0.6 AND LGPL-2.0-or-later WITH WxWindows-exception-3.1 AND MIT
        AND GPL-2.0-only WITH Classpath-exception-2.0 AND MPL-2.0 AND BSD-2-Clause-Views
        AND FSFUL AND CPL-1.0 AND LGPL-2.1-only AND LGPL-2.1-or-later AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND Apache-2.0 AND CDDL-1.0 AND EPL-2.0
        AND GPL-2.0-only
      license_declared: (Apache-2.0 OR EPL-2.0) AND CC-BY-SA-4.0 AND BSD-2-Clause
        AND GPL-3.0-only AND OpenSSL AND BSD-3-Clause AND Zlib AND GPL-3.0-or-later
        AND EPL-1.0 AND GPL-2.0-or-later AND CC0-1.0 AND Bitstream-Vera AND UPL-1.0
        AND bzip2-1.0.6 AND LGPL-2.0-or-later WITH WxWindows-exception-3.1 AND MIT
        AND GPL-2.0-only WITH Classpath-exception-2.0 AND MPL-2.0 AND BSD-2-Clause-Views
        AND FSFUL AND CPL-1.0 AND LGPL-2.1-only AND LGPL-2.1-or-later AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND Apache-2.0 AND CDDL-1.0 AND EPL-2.0
        AND GPL-2.0-only
      short_summary: Cached -Dbase.path folder of apache-tomcat build
      supplier: 'Organization: Broadcom, Inc.'
