sources:
- archive: apache-tomcat-10.1.43-src.tar.gz
  archive_type: upstream
  archive_sha512sum: 24672a4ea4d6e0bfd5e7dbb8694f260216bea47f21c347dd549d3e0851915aa7616695356cbf6714780ff1527f346ad2119f7f52f66779c4d0510ad0f83e9978
  name: apache-tomcat-10.1.43-src
  version: 10.1.43
  url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.43/src/apache-tomcat-10.1.43-src.tar.gz
  repo_url: https://github.com/apache/tomcat.git
  commit_id: e6c2a4b773a2bf03f94a31ed8fc30df1a735217e
  skip_list:
  - RCS
  - CVS
  - tags
  - .git
  - .hg
  - .bzr
  - _darcs
  - __pycache__
  missing:
  - owb
  - stuffed
  - cxf
  spdx:
    package:
      detailed_description: 'The Apache Tomcat package contains binaries for the Apache
        Tomcat servlet container. '
      home_page: http://tomcat.apache.org
      license_concluded: (EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND
        (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND LGPL-2.0-or-later
        AND GPL-2.0-only AND bzip2-1.0.6 AND Zlib AND CPL-1.0 AND CDDL-1.0 AND EPL-2.0
        AND EPL-1.0 AND CC0-1.0 AND Apache-2.0
      license_declared: (EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND
        (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND LGPL-2.0-or-later
        AND GPL-2.0-only AND bzip2-1.0.6 AND Zlib AND CPL-1.0 AND CDDL-1.0 AND EPL-2.0
        AND EPL-1.0 AND CC0-1.0 AND Apache-2.0
      short_summary: Apache Tomcat 10.1
      supplier: 'Organization: Broadcom, Inc.'
- archive: apache-tomcat-9.0.107-src.tar.gz
  archive_type: upstream
  archive_sha512sum: 4db3eb936aaea9e0679504bb73c07e982d646a7e7a574f9be1f465f79dd1f229dff22055a049a7dc2ad59619752dae79505ab92f44a317df966fa3b039e459c3
  name: apache-tomcat-9.0.107-src
  version: 9.0.107
  url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.107/src/apache-tomcat-9.0.107-src.tar.gz
  repo_url: https://github.com/apache/tomcat.git
  commit_id: 43d5ad023d2eee2ca162eded597a23afa0b92296
  skip_list:
  - RCS
  - CVS
  - tags
  - .git
  - .hg
  - .bzr
  - _darcs
  - __pycache__
  missing:
  - owb
  - cxf
  spdx:
    package:
      detailed_description: The Apache Tomcat package provides the Apache Tomcat servlet
        container.
      home_page: http://tomcat.apache.org
      license_concluded: (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND
        Apache-2.0 AND LGPL-2.0-or-later AND CPL-1.0 AND GPL-2.0-only AND bzip2-1.0.6
        AND EPL-1.0 AND CC0-1.0 AND CDDL-1.0 AND Zlib
      license_declared: (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND
        Apache-2.0 AND LGPL-2.0-or-later AND CPL-1.0 AND GPL-2.0-only AND bzip2-1.0.6
        AND EPL-1.0 AND CC0-1.0 AND CDDL-1.0 AND Zlib
      short_summary: Apache Tomcat 9
      supplier: 'Organization: Broadcom, Inc.'
- archive: base-for-apache-tomcat-10.1.43.tar.gz
  archive_sha512sum: 56bb0d1dd85bcbf8af0483ce0dee62515e7f0e5f59b74c3a9284c5ac21b475cb4037098c4209377913df7a8ba522d17e910c083e2e36718125d323c9af71b9d0
  skip_validation: true
  license_manual_review:
  # Icon uses cc-by-sa-4.0 license
  - file_paths:
    - base-for-apache-tomcat-10.1.43/nsis-3.11-src/Contrib/MakeLangId/MakeLangId.cpp
    sha256sum: 1cb56a65d201465110930fde78929f0ef0881b30c64d6b14dc014d97ca0d5774
    spdx_exp: ''
  spdx:
    package:
      detailed_description: base-for-apache-tomcat is a cached -Dbase.path folder
        after apache-tomcat build
      home_page: https://github.com/vmware/photon
      license_concluded: (Apache-2.0 OR EPL-2.0) AND Zlib AND FSFULLR AND OpenSSL
        AND Bitstream-Vera AND GPL-3.0-or-later AND GPL-2.0-or-later AND CC-BY-SA-4.0
        AND BSD-2-Clause-Views AND bzip2-1.0.6 AND FSFULLRWD AND EPL-2.0 AND CC0-1.0
        AND MPL-2.0 AND LGPL-2.1-or-later AND BSD-3-Clause AND MIT AND EPL-1.0 AND
        BSD-2-Clause AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND
        X11 AND CPL-1.0 AND GPL-2.0-only AND GPL-2.0-or-later WITH Libtool-exception
        AND GPL-3.0-only AND CDDL-1.0 AND LGPL-2.1-only AND FSFUL AND UPL-1.0 AND
        GPL-2.0-only WITH Classpath-exception-2.0 AND LGPL-2.0-or-later WITH WxWindows-exception-3.1
        AND Apache-2.0
      license_declared: (Apache-2.0 OR EPL-2.0) AND Zlib AND FSFULLR AND OpenSSL AND
        Bitstream-Vera AND GPL-3.0-or-later AND GPL-2.0-or-later AND CC-BY-SA-4.0
        AND BSD-2-Clause-Views AND bzip2-1.0.6 AND FSFULLRWD AND EPL-2.0 AND CC0-1.0
        AND MPL-2.0 AND LGPL-2.1-or-later AND BSD-3-Clause AND MIT AND EPL-1.0 AND
        BSD-2-Clause AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND
        X11 AND CPL-1.0 AND GPL-2.0-only AND GPL-2.0-or-later WITH Libtool-exception
        AND GPL-3.0-only AND CDDL-1.0 AND LGPL-2.1-only AND FSFUL AND UPL-1.0 AND
        GPL-2.0-only WITH Classpath-exception-2.0 AND LGPL-2.0-or-later WITH WxWindows-exception-3.1
        AND Apache-2.0
      short_summary: Cached -Dbase.path folder of apache-tomcat build
      supplier: 'Organization: Broadcom, Inc.'
- archive: base-for-apache-tomcat-9.0.107.tar.gz
  archive_sha512sum: 09b9bb27bc109734ae9daf3e501f1f5ddeff158ab466dc4d767c13b706272d3d2437a5400c9b12ab92ea467e7c3b9448dd61c6399673c528f91cb368751e74c8
  skip_validation: true
  license_manual_review:
  # Icon uses cc-by-sa-4.0 license
  - file_paths:
    - base-for-apache-tomcat-9.0.107/nsis-3.11-src/Contrib/MakeLangId/MakeLangId.cpp
    sha256sum: 1cb56a65d201465110930fde78929f0ef0881b30c64d6b14dc014d97ca0d5774
    spdx_exp: ''
  spdx:
    package:
      detailed_description: base-for-apache-tomcat is a cached -Dbase.path folder
        after apache-tomcat build
      home_page: https://github.com/vmware/photon
      license_concluded: (Apache-2.0 OR EPL-2.0) AND CC-BY-SA-4.0 AND BSD-2-Clause
        AND GPL-3.0-only AND OpenSSL AND BSD-3-Clause AND Zlib AND GPL-3.0-or-later
        AND EPL-1.0 AND GPL-2.0-or-later AND CC0-1.0 AND Bitstream-Vera AND UPL-1.0
        AND bzip2-1.0.6 AND LGPL-2.0-or-later WITH WxWindows-exception-3.1 AND MIT
        AND GPL-2.0-only WITH Classpath-exception-2.0 AND MPL-2.0 AND BSD-2-Clause-Views
        AND FSFUL AND CPL-1.0 AND LGPL-2.1-only AND LGPL-2.1-or-later AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND Apache-2.0 AND CDDL-1.0 AND EPL-2.0
        AND GPL-2.0-only
      license_declared: (Apache-2.0 OR EPL-2.0) AND CC-BY-SA-4.0 AND BSD-2-Clause
        AND GPL-3.0-only AND OpenSSL AND BSD-3-Clause AND Zlib AND GPL-3.0-or-later
        AND EPL-1.0 AND GPL-2.0-or-later AND CC0-1.0 AND Bitstream-Vera AND UPL-1.0
        AND bzip2-1.0.6 AND LGPL-2.0-or-later WITH WxWindows-exception-3.1 AND MIT
        AND GPL-2.0-only WITH Classpath-exception-2.0 AND MPL-2.0 AND BSD-2-Clause-Views
        AND FSFUL AND CPL-1.0 AND LGPL-2.1-only AND LGPL-2.1-or-later AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND Apache-2.0 AND CDDL-1.0 AND EPL-2.0
        AND GPL-2.0-only
      short_summary: Cached -Dbase.path folder of apache-tomcat build
      supplier: 'Organization: Broadcom, Inc.'
