sources:
- archive: kpatch-v0.9.10.tar.gz
  archive_type: upstream
  archive_sha512sum: d27f0e92d93539cc6ae6137419a99d124e5e2dba8bfbf67d15b0bf89230d2e92584c974ccae6932ce7a02460d73da9d46806e9104ee019ea3c6d3cfe8658be83
  name: "kpatch-0.9.10"
  version: 0.9.10
  url: https://github.com/dynup/kpatch/archive/refs/tags/v0.9.10.tar.gz
  repo_url: https://github.com/dynup/kpatch
  commit_id: 903dfe2b644ec41d9b4bc50344fdadf9664e948f
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'Contains the kpatch utility, which allows loading of
        kernel livepatches. kpatch is a Linux dynamic kernel patching tool which allows
        you to patch a running kernel without rebooting or restarting any processes.  It
        enables sysadmins to apply critical security patches to the kernel immediately,
        without having to wait for long-running tasks to complete, users to log off,
        or for scheduled reboot windows.  It gives more control over up-time without
        sacrificing security or stability. '
      home_page: http://github.com/dynup/kpatch
      license_concluded: GPL-2.0-only AND GPL-2.0-or-later
      license_declared: GPL-2.0-only AND GPL-2.0-or-later
      short_summary: Dynamic kernel patching
      supplier: 'Organization: Broadcom, Inc.'

- archive: photon-kpatch-utils-1.1.tar.gz
  archive_sha512sum: 6b78b720e76a40f6bf5ed1e7d21ec9689da9b342c299650884480bfcd1cc62d93ec914cc8a21bb0afa746364b59b00676b531f1f151845be6733329695e7243e
  skip_validation: true
  spdx:
    package:
      detailed_description: kpatch-build photon wrapper scripts
      home_page: https://github-vcf.devops.broadcom.net/vcf/photon-kpatch
      license_concluded: GPL-2.0-only
      license_declared: GPL-2.0-only
      short_summary: kpatch-build photon wrapper scripts
      supplier: "Organization: Broadcom, Inc."
