sources:
- archive: coredns-1.14.3.tar.gz
  archive_sha512sum: 39b87ff29460e8eb2fd9db53ae6fe19d7b7c99da0a7cfc9e93b22d93c2c53c5cfd2bb493610901a6cfae578430d1fc215b9c9d70e95cc31f0c4084b618e60864
  archive_type: upstream
  commit_id: 17fceec6d93fd1dde5ba6888c363f131ff6d647f
  missing: []
  skip_list: []
  skip_validation: false
  name: coredns-1.14.3
  version: '1.14.3'
  repo_url: https://github.com/coredns/coredns
  url: https://github.com/coredns/coredns/archive/refs/tags/v1.14.3.tar.gz
  spdx:
    package:
      detailed_description: 'CoreDNS is a DNS server that chains plugins '
      home_page: https://github.com/coredns/coredns
      license_concluded: Apache-2.0 AND BSD-3-Clause
      license_declared: Apache-2.0 AND BSD-3-Clause
      short_summary: CoreDNS
      supplier: 'Organization: Broadcom, Inc.'
