sources:
- archive: unicode-display_width-3.1.4.gem
  archive_sha512sum: f829512fa2d0fd88453d3e7fcf595fd73191b18b183e149eb006f1daf45488d495982e634d26574785f53c40653250494e31946fabf3837490d887438c8388fb
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Determines the monospace display width of a string in
        Ruby. Implementation based on EastAsianWidth.txt and other data, 100% in Ruby.
        Other than wcwidth(), which fulfills a similar purpose, it does not rely on
        the OS vendor to provide an up-to-date method for measuring string width. '
      home_page: https://github.com/janlelis/unicode-display_width
      license_concluded: MIT
      license_declared: MIT
      short_summary: Unicode::DisplayWidth.
      supplier: 'Organization: Broadcom, Inc.'
