sources:
- archive: open-vmdk-0.3.12.tar.gz
  archive_sha512sum: 4a038c899a9e3c013b830dab6514260e72d6905d6e5c2da864bdcc71f125639dc2aba68e9a4a27e96037a0200bd04d0ca2cc17306e8eaf2bf2913f9eaa0afb41
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Tools to create OVA files from raw disk images. This
        includes ''vmdk-convert'' to create VMDKs from raw disk images, and ''ova-compose''
        to create OVA files that can be imported by VMware vSphere or Fusion and Workstation. '
      home_page: https://github.com/vmware/open-vmdk
      license_concluded: Apache-2.0 AND MIT
      license_declared: Apache-2.0 AND MIT
      short_summary: Tools to create OVA files from raw disk images
      supplier: 'Organization: Broadcom, Inc.'
