sources:
- archive: open-vmdk-0.3.11.tar.gz
  archive_sha512sum: e9ece44aed19baa139ad8c58a93c32d62d8121b4660f553688bdd8b77cb30a86905199984e21ba82e4638f3bc0a2c1d612feb91a8adeda8ff486bba951f405ec
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Tools to create OVA files from raw disk images. This
        includes ''vmdk-convert'' to create VMDKs from raw disk images, and ''ova-compose''
        to create OVA files that can be imported by VMware vSphere or Fusion and Workstation. '
      home_page: https://github.com/vmware/open-vmdk
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: Tools to create OVA files from raw disk images
      supplier: 'Organization: Broadcom, Inc.'
