sources:
- archive: haproxy-dataplaneapi-3.3.4.tar.gz
  archive_type: upstream
  archive_sha512sum: 8bf1d552d8878b26fc3cf4dd0cef7bceb21b6335600617f35f205e577dc751aedbdc609867f90c4cb237d9ef49c9f7ae0ef76aa74b2bc476b1869ea8460d0363
  name: "dataplaneapi-3.3.4"
  version: 3.3.4
  repo_url: https://github.com/haproxytech/dataplaneapi
  url: https://github.com/haproxytech/dataplaneapi/archive/refs/tags/v3.3.4.tar.gz
  commit_id: 8fd880f168ba1374578cda91d0238bd5da4086bf
  skip_list: []
  missing: []
  skip_validation: false
  spdx:
    package:
      detailed_description: 'HAProxy Data Plane API is a sidecar process that runs
        next to HAProxy and provides API endpoints for managing HAProxy. '
      home_page: https://github.com/haproxytech/dataplaneapi
      license_concluded: CC0-1.0 AND Apache-2.0
      license_declared: CC0-1.0 AND Apache-2.0
      short_summary: A sidecar process for managing HAProxy.
      supplier: 'Organization: Broadcom, Inc.'
