sources:
- archive: sphinxcontrib_devhelp-2.0.0.tar.gz
  archive_sha512sum: 72d0bef99f46422160e54053e2594f04a90cd5bc0d8a7ce51259e013472fb9b5102dd87a2807771455d04ceceea94df5fd77cea08e922688f70b62630087083e
  skip_validation: true
  spdx:
    package:
      detailed_description: 'sphinxcontrib-devhelp is a sphinx extension which outputs
        Devhelp document.'
      home_page: https://pypi.org/project/sphinxcontrib-devhelp
      license_concluded: BSD-2-Clause AND BSD-3-Clause
      license_declared: BSD-2-Clause AND BSD-3-Clause
      short_summary: Sphinx extension for Devhelp documents
      supplier: 'Organization: Broadcom, Inc.'
