sources:
- archive: falco-0.39.2.tar.gz
  archive_sha512sum: 198405e9383625ca4d78822de7674c62863d15b3108ba5b06d4cf6ff20850f7eec9123fe7d98d049acc2931b98e4b09d7ef0d66136a31363ce59a64ad9e8eda0
  skip_validation: true
  spdx:
    package:
      home_page: https://falco.org
      license_concluded: Apache-2.0 AND MIT
      license_declared: Apache-2.0 AND MIT
      short_summary: The Behavioral Activity Monitor With Container Support
      detailed_description: The Behavioral Activity Monitor With Container Support
      supplier: 'Organization: Broadcom, Inc.'

- archive: falconsecurity-libs-0.19.0.tar.gz
  archive_sha512sum: 5b011c804b07bf2f3eb6a6d7e8c9ef4e54bcc8d74116020e887465aba3dec737bdf8fc854778a8230f7e23e87da29423c6320a8054873eb5c9c957ce40ef3825
  skip_validation: true
  spdx:
    package:
      home_page: https://falco.org
      license_concluded: (GPL-1.0-or-later OR MIT) AND (GPL-2.0-only OR MIT) AND Apache-2.0 AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND MIT
      license_declared: (GPL-1.0-or-later OR MIT) AND (GPL-2.0-only OR MIT) AND Apache-2.0 AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND MIT
      short_summary: The Behavioral Activity Monitor With Container Support
      detailed_description: The Behavioral Activity Monitor With Container Support
      supplier: 'Organization: Broadcom, Inc.'

- archive: nlohman-json-3.11.3.tar.gz
  archive_sha512sum: 7df19b621de34f08d5d5c0a25e8225975980841ef2e48536abcf22526ed7fb99f88ad954a2cb823115db59ccc88d1dbe74fe6c281b5644b976b33fb78db9d717
  skip_validation: true
  spdx:
    package:
      home_page: https://json.nlohmann.me/
      license_concluded: BSD-3-Clause AND MIT
      license_declared: BSD-3-Clause AND MIT
      short_summary: A popular, single-header C++ library for parsing and manipulating JSON 
      detailed_description: A popular, single-header C++ library for parsing and manipulating JSON
      supplier: 'Organization: Broadcom, Inc.'

- archive: tbb-2022.0.0.tar.gz
  archive_sha512sum: c87b84964b2c323f61895a532968dfa6413a774c177cffbf6e798a07e74e8da5d449144875771df0a1b02657eeb2a7ae4d41c6c432dbf7ea50e3d5a9ea9f8cd3
  skip_validation: true
  spdx:
    package:
      home_page: https://github.com/uxlfoundation/oneTBB
      license_concluded: 0BSD AND Apache-2.0 AND BSD-3-Clause AND BSL-1.0 AND MIT AND bzip2-1.0.6
      license_declared: 0BSD AND Apache-2.0 AND BSD-3-Clause AND BSL-1.0 AND MIT AND bzip2-1.0.6
      short_summary: A widely used C++ library for shared memory parallel programming and heterogeneous computing that abstracts low-level threading details.
      detailed_description: A widely used C++ library for shared memory parallel programming and heterogeneous computing that abstracts low-level threading details.
      supplier: 'Organization: Broadcom, Inc.'

- archive: valijson-1.0.2.tar.gz
  archive_sha512sum: c1141e533d6a791a01883c5b7ab9501eebc39057a850d784670a4bcf99bff3fee4c3120107128dcaa9db0505adf2ae794700620c02163b3e636f0b635031df80
  skip_validation: true
  spdx:
    package:
      home_page: https://github.com/tristanpenman/valijson
      license_concluded: BSD-2-Clause AND BSL-1.0 AND MIT
      license_declared: BSD-2-Clause AND BSL-1.0 AND MIT
      short_summary: A header-only C++ library for JSON Schema validation that supports multiple third-party JSON parser libraries through adapters.
      detailed_description: A header-only C++ library for JSON Schema validation that supports multiple third-party JSON parser libraries through adapters.
      supplier: 'Organization: Broadcom, Inc.'

- archive: cpp-httplib-0.15.3.tar.gz
  archive_sha512sum: f7fc9c9eb71f091b82958e023a7b417b30d2590fd5d1a920d1c98361f34bcaca796dbeda7f9fdb8b2c722a8968977b77463c6cbb252cba9823a79c22471fa439
  skip_validation: true
  spdx:
    package:
      home_page: https://github.com/yhirose/cpp-httplib
      license_concluded: Apache-2.0 AND BSD-3-Clause AND MIT
      license_declared: Apache-2.0 AND BSD-3-Clause AND MIT
      short_summary: A C++11 single-file header-only cross-platform HTTP/HTTPS library.
      detailed_description: A C++11 single-file header-only cross-platform HTTP/HTTPS library.
      supplier: 'Organization: Broadcom, Inc.'

- archive: cxxopts-3.0.0.tar.gz
  archive_sha512sum: 239479a3b35ddef6fc380ac9371e1cf7e3aea066f03e1ea538151fa2fff4296838daa976d55e988d8f87f40c0ae027767bcb214754177499413af1081315565c
  skip_validation: true
  spdx:
    package:
      home_page: https://github.com/jarro2783/cxxopts
      license_concluded: BSL-1.0 AND MIT
      license_declared: BSL-1.0 AND MIT
      short_summary: A lightweight, header-only C++ option parser library.
      detailed_description: A lightweight, header-only C++ option parser library.
      supplier: 'Organization: Broadcom, Inc.'

- archive: falcoctl-0.10.1.tar.gz
  archive_sha512sum: b55dc0bd53e24897934c72f7f4c524d956c517ec3e754d27664964eaf69b6015f7001214603b0474fc82e7388094c143ad2570f4eed4a8ccbbb30619deba5595
  skip_validation: true
  spdx:
    package:
      home_page: https://github.com/falcosecurity/falcoctl
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: A CLI tool used to manage Falco artifacts, such as rulesets and plugins.
      detailed_description: A CLI tool used to manage Falco artifacts, such as rulesets and plugins.
      supplier: 'Organization: Broadcom, Inc.'

- archive: falco-rules-3.2.0.tar.gz
  archive_sha512sum: b0c02e8bfb4c17b1197fc17adef0eb22557d70eebbb81efb61aaf06f87be3f00d3c517a72c1070d40dbb2f3713c99d8f98afbabf776fb259a6f3be1587da7279
  skip_validation: true
  spdx:
    package:
      home_page: https://github.com/falcosecurity/rules
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: The official community-contributed ruleset for Falco, providing pre-defined detection for security threats and abnormal behaviors.
      detailed_description: The official community-contributed ruleset for Falco, providing pre-defined detection for security threats and abnormal behaviors.
      supplier: 'Organization: Broadcom, Inc.'
