sources:
- archive: dovecot-2.4.5.tar.gz
  archive_sha512sum: d23607289ab5b4ac6fa0a87ffb6d461357980cf1f6a7a5037f9c5fb13b89b1778557e73465d1042ac2ee4cdd5893c9f44b3c80a0d87c2fc708d2928702a6b69b
  archive_type: upstream
  name: dovecot-2.4.5
  version: 2.4.5
  url: https://dovecot.org/releases/2.4/dovecot-2.4.5.tar.gz
  repo_url: https://github.com/dovecot/core.git
  commit_id: 0cbb641e3e88d1616c2e8c1ff109c67c0985ddc6
  skip_list: []
  missing: ['*.1', '*.txt', ltoptions.m4, unicode-data-types.c, config.sub, fuzz-http-request-parser.dict, .clang-tidy, test.out~2004081.core.2004143, install-sh, var-expand-parser.c, event-filter-parser.h, unicode-data-types.h, var-expand-lexer.c, README, event-filter-lexer.c, configure, AGENTS.md, dovecot-version.h, .gitignore, .luacheckrc, INSTALL, fuzz-http-response-parser.dict, .editorconfig, .gitkeep, depcomp, test-driver, ltversion.m4, .clang-format, .clangd, pyproject.toml, autogen.sh, coccinelle, libtool.m4, config.h.in, Makefile.in, doveadm-search-query.7, stamp-man, unicode-data-tables.c, index.html, ax_python_module.m4, ltsugar.m4, fts-build-private.h, compile, event-filter-parser.c, lt~obsolete.m4, ltmain.sh, unicode-data-tables.h, config.guess, settings-history-core.h, missing, worker-pool.h, CONTRIBUTING.md, all-settings.c, aclocal.m4, var-expand-parser.h, ylwrap]
  license_manual_review:
  - file_paths:
      # This is a huge C file which contains some data (~13MB), skip it
    - src/lib/unicode-data-tables.c
    sha256sum: a71a4db095c9e603e5749d732f63a9521207f15f4df4cd99098fe007c11803ae
    spdx_exp: ''
  spdx:
    package:
      detailed_description: 'Dovecot is an open source IMAP and POP3 server for Linux/UNIX-like systems'
      home_page: https://dovecot.org/
      license_concluded: Apache-2.0 AND BSD-3-Clause AND Beerware AND FSFULLR AND GPL-2.0-or-later AND GPL-3.0-or-later AND LGPL-2.0-or-later AND LGPL-2.1-only AND MIT AND Unicode-3.0 AND X11 AND bcrypt-Solar-Designer
      license_declared: Apache-2.0 AND BSD-3-Clause AND Beerware AND FSFULLR AND GPL-2.0-or-later AND GPL-3.0-or-later AND LGPL-2.0-or-later AND LGPL-2.1-only AND MIT AND Unicode-3.0 AND X11 AND bcrypt-Solar-Designer
      short_summary: Secure IMAP and POP3 server
      supplier: 'Organization: Broadcom, Inc.'
