sources:
- archive: rubyzip-3.2.2.gem
  archive_sha512sum: 80c373455fba0aca30e841ce4de546913530cca662acfe26d71c82e78201a0cf05c71ea107c7bba856f1ec140a1dba8c6f2c51bc8f066866279bf9bed1adde93
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Ruby library for reading and writing Zip files '
      home_page: https://rubygems.org/gems/rubyzip
      license_concluded: (BSD-2-Clause OR Ruby) AND BSD-2-Clause
      license_declared: (BSD-2-Clause OR Ruby) AND BSD-2-Clause
      short_summary: Ruby library for reading and writing Zip files
      supplier: 'Organization: Broadcom, Inc.'
