sources:
- archive: haproxy-3.2.1.tar.gz
  archive_sha512sum: f77531828d252bb145860d258c4e50454abe9552803cc746f73d627d8906b336efb2ea9427abd7c79b2d357812dadae6b9d0660ef1788c3c503d3d52c30166ef
  skip_validation: true
  name: haproxy-3.2.1
  version: 3.2.1
  repo_url: https://github.com/haproxy/haproxy
  url: http://www.haproxy.org/download/3.2/src/haproxy-3.2.1.tar.gz
  spdx:
    package:
      detailed_description: 'HAProxy is a fast and reliable solution offering high
        availability, load balancing, and proxying for TCP and HTTP-based applications.
        It is suitable for very high traffic web-sites. '
      home_page: http://www.haproxy.org
      license_concluded: MIT-0 AND GPL-2.0-only AND LGPL-2.1-only WITH x11vnc-openssl-exception
        AND GPL-2.0-or-later AND GPL-3.0-or-later AND MIT AND GPL-1.0-or-later AND
        LGPL-2.0-or-later AND BSD-2-Clause AND GPL-2.0-only WITH x11vnc-openssl-exception
        AND MPL-2.0-no-copyleft-exception AND LGPL-2.1-or-later AND LGPL-2.1-only
      license_declared: MIT-0 AND GPL-2.0-only AND LGPL-2.1-only WITH x11vnc-openssl-exception
        AND GPL-2.0-or-later AND GPL-3.0-or-later AND MIT AND GPL-1.0-or-later AND
        LGPL-2.0-or-later AND BSD-2-Clause AND GPL-2.0-only WITH x11vnc-openssl-exception
        AND MPL-2.0-no-copyleft-exception AND LGPL-2.1-or-later AND LGPL-2.1-only
      short_summary: A fast, reliable HA, load balancing, and proxy solution.
      supplier: 'Organization: Broadcom, Inc.'
