sources:
- archive: qemu-7.2.0.tar.xz
  archive_sha512sum: f3cfa00da739ba819a218d7e6e95c77fb79a8e0f487b024ddd281602e785249b81144595e3f8c746c32a4f5c4d1a88c6aebae3c162603edfbb50ae3722d7ed13
  skip_validation: true
  license_manual_review:
  - archive_path: block/copy-on-read.c
    sha256sum: dd25c604eeb86e2de8a94e422cee17679ca12ed4503f1cfc72c8736a1cf0766f
    spdx_exp: GPL-2.0-or-later
  - archive_path: block/throttle-groups.c
    sha256sum: cf3d3ff414a78d4c73103c5a8fd586b5994f74e98aed34c0021da3f69bc60476
    spdx_exp: GPL-2.0-or-later
  - archive_path: block/throttle.c
    sha256sum: cc7cd9e02f7ecc87f549e8c54af18a405ef67920ee07bfd1b3df8b61de91a03a
    spdx_exp: GPL-2.0-or-later
  - archive_path: include/block/throttle-groups.h
    sha256sum: fd6193addc346d4342d8751fcc26f81e2d9cd9724194a99246ac0472abbcefca
    spdx_exp: GPL-2.0-or-later
  - archive_path: include/qemu/throttle.h
    sha256sum: bcac02ccaece13f05363ebc702af1e8d08ad8707cb8453aeb191ae0b2b9de6d1
    spdx_exp: GPL-2.0-or-later
  - archive_path: include/ui/qemu-spice-module.h
    sha256sum: e2bb1bba94478673777e34bcea197cfc5104177bc5188d42a742109fccd2fa3c
    spdx_exp: GPL-2.0-or-later
  - archive_path: include/ui/qemu-spice.h
    sha256sum: b82315dedcd7cd5aae01d7887c985ebbaeab8886a49453ba9801d889016929c1
    spdx_exp: GPL-2.0-or-later
  - archive_path: tests/unit/socket-helpers.h
    sha256sum: a2c9ec342f38e3b3fcabeccd87a4275fa13f693e0a9ed04865f42e0d12ed339d
    spdx_exp: GPL-2.0-or-later
  - archive_path: ui/spice-module.c
    sha256sum: e5cfb5df402015207b9ad5eb0ede68c3bfcbb79d4d20012e062a854215754733
    spdx_exp: GPL-2.0-or-later
  - archive_path: ui/vnc-ws.c
    sha256sum: 7627740241c7da0be8ed241c5c9c256b4e5e905c351b2db52fd3819f903c7301
    spdx_exp: GPL-2.0-or-later
  - archive_path: ui/vnc-ws.h
    sha256sum: 4320fbcc9baf06938809f6db03828b0eb2ea6754f62ee12ae3525a56e042e8ae
    spdx_exp: GPL-2.0-or-later
  - archive_path: util/throttle.c
    sha256sum: 951b5d3a57350ee9caaeaf304c1fc34292c1d967468125ee56e9363c6dda2769
    spdx_exp: GPL-2.0-or-later
  - archive_path: meson/docs/markdown/legal.md
    sha256sum: 78b49c95035c716b9c7fe979a6a2f4910c4cb23dbb96cc7773761591d03e6681
    spdx_exp: ''
  spdx:
    package:
      detailed_description: 'Qemu-img is the tool used to create, manage, convert
        shrink etc. the disk images of virtual machines. '
      home_page: https://www.qemu.org
      license_concluded: (Apache-2.0 OR GPL-2.0-or-later) AND (Artistic-2.0 OR GPL-2.0-or-later)
        AND (BSD-2-Clause OR GPL-2.0-only WITH Linux-syscall-note) AND (BSD-2-Clause
        OR GPL-2.0-only) AND (BSD-2-Clause OR GPL-2.0-or-later) AND (BSD-2-Clause
        OR LGPL-2.1-only) AND (BSD-2-Clause OR OpenSSL) AND (BSD-3-Clause OR GPL-1.0-or-later
        OR GPL-2.0-only OR OpenSSL) AND (BSD-3-Clause OR GPL-1.0-or-later OR OpenSSL)
        AND (BSD-3-Clause OR GPL-2.0-only WITH Linux-syscall-note) AND (BSD-3-Clause
        OR GPL-2.0-only) AND (BSD-3-Clause OR GPL-2.0-only) AND (BSD-3-Clause OR GPL-2.0-or-later
        OR LGPL-2.1-or-later OR MPL-1.1) AND (BSD-3-Clause OR GPL-2.0-or-later) AND
        (BSD-3-Clause OR GPL-2.0-or-later) AND (BSD-3-Clause OR MIT) AND (BSD-3-Clause
        OR OpenSSL) AND (BSD-3-Clause-Clear OR GPL-2.0-only) AND (BSD-3-Clause-acpica
        OR GPL-2.0-only) AND (CC0-1.0 OR MIT) AND (CPL-1.0 OR LGPL-2.1-only) AND (GPL-1.0-or-later
        OR MIT) AND (GPL-2.0-only OR GPL-3.0-only) AND (GPL-2.0-only OR IBM-pibs)
        AND (GPL-2.0-only OR Linux-OpenIB) AND (GPL-2.0-only OR MIT) AND (GPL-2.0-only
        OR MIT) AND (GPL-2.0-only OR MPL-1.1) AND (GPL-2.0-only OR RHeCos-1.1) AND
        (GPL-2.0-only OR X11) AND (GPL-2.0-or-later OR MIT) AND (GPL-2.0-or-later
        OR X11) AND AGPL-3.0-only AND Apache-2.0 AND Artistic-1.0-Perl AND Artistic-2.0
        AND BSD-1-Clause AND BSD-2-Clause AND BSD-2-Clause-Patent AND BSD-3-Clause
        AND BSD-3-Clause-acpica AND BSD-4-Clause AND BSD-4.3TAHOE AND BSD-Source-Code
        AND BSL-1.0 AND Beerware AND CC-BY-3.0 AND CC-BY-SA-4.0 AND CC0-1.0 AND CMU-Mach
        AND FSFAP AND FSFAP-no-warranty-disclaimer AND FreeBSD-DOC AND GPL-1.0-or-later
        AND GPL-2.0-only AND GPL-2.0-only WITH Linux-syscall-note AND GPL-2.0-only
        WITH eCos-exception-2.0 AND GPL-2.0-only WITH mif-exception AND GPL-2.0-only
        WITH u-boot-exception-2.0 AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND GPL-2.0-or-later WITH Font-exception-2.0 AND GPL-2.0-or-later WITH GCC-exception-2.0
        AND GPL-2.0-or-later WITH Linux-syscall-note AND GPL-2.0-or-later WITH UBDL-exception
        AND GPL-2.0-or-later WITH eCos-exception-2.0 AND GPL-2.0-or-later WITH mif-exception
        AND GPL-3.0-only AND GPL-3.0-or-later AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-3.0-or-later WITH Bison-exception-2.2 AND HPND AND HPND-sell-variant
        AND ISC AND Intel AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only
        AND LGPL-2.1-or-later AND LGPL-3.0-only AND LZMA-SDK-9.22 AND MIT AND NTP-0
        AND OFL-1.1 AND OpenSSL AND Parity-7.0.0 AND Python-2.0 AND SSPL-1.0 AND Unicode-DFS-2016
        AND Vim AND X11 AND Zlib AND bzip2-1.0.6 AND snprintf
      license_declared: (Apache-2.0 OR GPL-2.0-or-later) AND (Artistic-2.0 OR GPL-2.0-or-later)
        AND (BSD-2-Clause OR GPL-2.0-only WITH Linux-syscall-note) AND (BSD-2-Clause
        OR GPL-2.0-only) AND (BSD-2-Clause OR GPL-2.0-or-later) AND (BSD-2-Clause
        OR LGPL-2.1-only) AND (BSD-2-Clause OR OpenSSL) AND (BSD-3-Clause OR GPL-1.0-or-later
        OR GPL-2.0-only OR OpenSSL) AND (BSD-3-Clause OR GPL-1.0-or-later OR OpenSSL)
        AND (BSD-3-Clause OR GPL-2.0-only WITH Linux-syscall-note) AND (BSD-3-Clause
        OR GPL-2.0-only) AND (BSD-3-Clause OR GPL-2.0-only) AND (BSD-3-Clause OR GPL-2.0-or-later
        OR LGPL-2.1-or-later OR MPL-1.1) AND (BSD-3-Clause OR GPL-2.0-or-later) AND
        (BSD-3-Clause OR GPL-2.0-or-later) AND (BSD-3-Clause OR MIT) AND (BSD-3-Clause
        OR OpenSSL) AND (BSD-3-Clause-Clear OR GPL-2.0-only) AND (BSD-3-Clause-acpica
        OR GPL-2.0-only) AND (CC0-1.0 OR MIT) AND (CPL-1.0 OR LGPL-2.1-only) AND (GPL-1.0-or-later
        OR MIT) AND (GPL-2.0-only OR GPL-3.0-only) AND (GPL-2.0-only OR IBM-pibs)
        AND (GPL-2.0-only OR Linux-OpenIB) AND (GPL-2.0-only OR MIT) AND (GPL-2.0-only
        OR MIT) AND (GPL-2.0-only OR MPL-1.1) AND (GPL-2.0-only OR RHeCos-1.1) AND
        (GPL-2.0-only OR X11) AND (GPL-2.0-or-later OR MIT) AND (GPL-2.0-or-later
        OR X11) AND AGPL-3.0-only AND Apache-2.0 AND Artistic-1.0-Perl AND Artistic-2.0
        AND BSD-1-Clause AND BSD-2-Clause AND BSD-2-Clause-Patent AND BSD-3-Clause
        AND BSD-3-Clause-acpica AND BSD-4-Clause AND BSD-4.3TAHOE AND BSD-Source-Code
        AND BSL-1.0 AND Beerware AND CC-BY-3.0 AND CC-BY-SA-4.0 AND CC0-1.0 AND CMU-Mach
        AND FSFAP AND FSFAP-no-warranty-disclaimer AND FreeBSD-DOC AND GPL-1.0-or-later
        AND GPL-2.0-only AND GPL-2.0-only WITH Linux-syscall-note AND GPL-2.0-only
        WITH eCos-exception-2.0 AND GPL-2.0-only WITH mif-exception AND GPL-2.0-only
        WITH u-boot-exception-2.0 AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND GPL-2.0-or-later WITH Font-exception-2.0 AND GPL-2.0-or-later WITH GCC-exception-2.0
        AND GPL-2.0-or-later WITH Linux-syscall-note AND GPL-2.0-or-later WITH UBDL-exception
        AND GPL-2.0-or-later WITH eCos-exception-2.0 AND GPL-2.0-or-later WITH mif-exception
        AND GPL-3.0-only AND GPL-3.0-or-later AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GPL-3.0-or-later WITH Bison-exception-2.2 AND HPND AND HPND-sell-variant
        AND ISC AND Intel AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only
        AND LGPL-2.1-or-later AND LGPL-3.0-only AND LZMA-SDK-9.22 AND MIT AND NTP-0
        AND OFL-1.1 AND OpenSSL AND Parity-7.0.0 AND Python-2.0 AND SSPL-1.0 AND Unicode-DFS-2016
        AND Vim AND X11 AND Zlib AND bzip2-1.0.6 AND snprintf
      short_summary: QEMU disk image utility
      supplier: 'Organization: Broadcom, Inc.'
