sources:
- archive: tpm2-pytss-1.2.0.tar.gz
  archive_sha512sum: 9f317b2144e27ac0e6b876d1987cd5c64f4c1f70d1689cea3d926749d9778b2ad813335269cff70c8335f15b72b1233fffe062f4cb5791c5480c58119cf42db7
  archive_type: upstream
  version: 1.2.0
  name: tpm2-pytss-1.2.0
  url: https://github.com/tpm2-software/tpm2-pytss/archive/refs/tags/1.2.0.tar.gz
  repo_url: https://github.com/tpm2-software/tpm2-pytss
  commit_id: 8ebc054af8e4e6c5fdadfbe5fbfd7876a98483fa
  skip_validation: false
  license_manual_review:
  - file_paths:
    - tpm2-pytss-1.2.0-build/tpm2-pytss-1.2.0/src/tpm2_pytss/internal/crypto.py
    sha256sum: f452250bd4aeede57d5043e0219ba4c2d883c450ad3d69f533d1b8eb0acdfbd6
    spdx_exp: ''
  spdx:
    package:
      detailed_description: 'TPM2 TSS Python bindings for Enhanced System API (ESYS).
        This package primarily exposes the TPM 2.0 Enhanced System API. '
      home_page: https://github.com/tpm2-software/tpm2-pytss
      license_concluded: BSD-3-Clause AND BSD-2-Clause
      license_declared: BSD-3-Clause AND BSD-2-Clause
      short_summary: Python bindings for tpm2-tss
      supplier: 'Organization: Broadcom, Inc.'
