sources:
- archive: Exporter-Tiny-1.006003.tar.gz
  archive_sha512sum: bed019dae6cca43b35eea37daf46e62100f1325de679ab8eab89a24cf9822f889586789428e11bcd182ae0fc8dbed5ef181a22830c7fd00723d14534eb1b6d97
  archive_type: upstream
  name: Exporter-Tiny-1.006003
  version: 1.006003
  url: https://cpan.metacpan.org/authors/id/T/TO/TOBYINK/Exporter-Tiny-1.006003.tar.gz
  repo_url: https://github.com/tobyink/p5-exporter-tiny.git
  commit_id: b37d9d3db007810c1a785caaf11be2c736f82072
  skip_validation: false
  skip_list: []
  missing: ['.git', '.github', '.hgtags', 'meta', 'COPYRIGHT', 'CREDITS', 'Changes', 'INSTALL', 'LICENSE', 'TODO', 't', 'MANIFEST', 'META.json', 'META.yml', 'Makefile.PL', 'README', 'SIGNATURE', 'doap.ttl']
  spdx:
    package:
      detailed_description: 'Exporter::Tiny supports many of Sub::Exporter''s external-facing
        features including renaming imported functions with the -as, -prefix and -suffix
        options; explicit destinations with the into option; and alternative installers
        with the installer option. But it''s written in only about 40%% as many lines
        of code and with zero non-core dependencies.  Its internal-facing interface
        is closer to Exporter.pm, with configuration done through the @EXPORT, @EXPORT_OK
        and %%EXPORT_TAGS package variables.  Exporter::Tiny performs most of its
        internal duties (including resolution of tag names to sub names, resolution
        of sub names to coderefs, and installation of coderefs into the target package)
        as method calls, which means they can be overridden to provide interesting
        behavior. '
      home_page: http://search.cpan.org/dist/Exporter-Tiny/
      license_concluded:  (Artistic-1.0 OR GPL-1.0-or-later) AND (Artistic-1.0-Perl OR
        GPL-1.0-or-later) AND Artistic-1.0 AND Artistic-1.0-Perl AND GPL-1.0-only AND
        GPL-1.0-or-later AND MIT
      license_declared: (Artistic-1.0 OR GPL-1.0-or-later) AND (Artistic-1.0-Perl OR
        GPL-1.0-or-later) AND Artistic-1.0 AND Artistic-1.0-Perl AND GPL-1.0-only AND
        GPL-1.0-or-later AND MIT
      short_summary: An exporter with the features of Sub::Exporter but only core
        dependencies
      supplier: 'Organization: Broadcom, Inc.'
