sources:
- archive: net-http-0.9.1.gem
  archive_sha512sum: ee8f452ac00b992bb274e7077676bd6b375692749c0fd428f42e4047b17efba142be3b9b45abab951c16976a6b1de4c94ed4ff47f727b4773b5143d5e31abb1f
  skip_validation: true
  spdx:
    package:
      detailed_description: 'HTTP client api for Ruby.'
      home_page: https://rubygems.org/gems/net-http
      license_concluded: Ruby AND BSD-2-Clause
      license_declared: Ruby AND BSD-2-Clause
      short_summary: HTTP client api for Ruby.
      supplier: 'Organization: Broadcom, Inc.'
