sources:
- archive: Python-3.14.5.tar.xz
  archive_sha512sum: efbaf629703cd004f6b7bc75fb16df794185589adaf8807cd45928f212271045a399df3cd9573e47c8708fb5c5002f9d4efe4e41dde4313b81a3e9d73158769f
  archive_type: upstream
  skip_validation: false
  name: Python-3.14.5
  version: "3.14.5"
  url: https://www.python.org/ftp/python/3.14.5/Python-3.14.5.tar.xz
  repo_url: https://github.com/python/cpython
  commit_id: 5607950ef232dad16d75c0cf53101d9649d89115
  missing: ['mypy', 'NEWS', '.gitignore', 'NEWS.d', '.azure-pipelines', '.gitattributes', '.github']
  license_manual_review:
  - file_paths:
    - Python-3.14.5/Modules/blake2module.c
    sha256sum: e471acd6c8317fe31ef56d129f6e3426ebd6a4c9cd6d64a09d39bc558a491f10
    spdx_exp: ''
  spdx:
    package:
      detailed_description: 'The Python 3 package contains a new version of Python
        development environment. Python 3 brings more efficient ways of handling dictionaries,
        better unicode strings support, easier and more intuitive syntax, and removes
        the deprecated code. It is incompatible with Python 2.x releases. '
      home_page: http://www.python.org
      license_concluded: (Python-2.0 OR GPL-2.0-only) AND (BSD-3-Clause OR Apache-2.0)
        AND (MIT OR Apache-2.0) AND (MIT OR PSF-2.0) AND (BSD-2-Clause OR Apache-2.0)
        AND GPL-1.0-or-later AND LGPL-2.1-or-later AND FSFULLRWD AND PSF-2.0 AND CNRI-Python
        AND HPND AND dtoa AND 0BSD AND MIT-CMU AND CC0-1.0 AND FSFAP AND BSD-Source-Code
        AND FSFUL AND FSFULLR AND BSD-2-Clause AND Apache-2.0 AND Python-2.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND OpenSSL AND X11 AND MIT AND BSD-3-Clause
        AND Python-2.0.1 AND Zlib AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND MS-RL
      license_declared: (Python-2.0 OR GPL-2.0-only) AND (BSD-3-Clause OR Apache-2.0)
        AND (MIT OR Apache-2.0) AND (MIT OR PSF-2.0) AND (BSD-2-Clause OR Apache-2.0)
        AND GPL-1.0-or-later AND LGPL-2.1-or-later AND FSFULLRWD AND PSF-2.0 AND CNRI-Python
        AND HPND AND dtoa AND 0BSD AND MIT-CMU AND CC0-1.0 AND FSFAP AND BSD-Source-Code
        AND FSFUL AND FSFULLR AND BSD-2-Clause AND Apache-2.0 AND Python-2.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND OpenSSL AND X11 AND MIT AND BSD-3-Clause
        AND Python-2.0.1 AND Zlib AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND MS-RL
      short_summary: A high-level scripting language
      supplier: 'Organization: Broadcom, Inc.'
- archive: pip-wheel.ph5-1.0-3.tar.xz
  archive_sha512sum: dee27c816930640189a55961e163f54fe8ebbd844c41b0a77fb37d23f20d21c86f46c082879e30a458c95454e8a9d3bd476c5390c3086f6f3fc6ae08dfbdfc89
  skip_validation: true
  spdx:
    package:
      detailed_description: Installation wheel for pip.
      home_page: https://pypi.org/project/pip/
      license_concluded: (BSD-3-Clause OR Apache-2.0) AND (BSD-2-Clause OR Apache-2.0)
        AND Apache-2.0 AND BSD-2-Clause AND Python-2.0 AND BSD-3-Clause AND MIT
      license_declared: (BSD-3-Clause OR Apache-2.0) AND (BSD-2-Clause OR Apache-2.0)
        AND Apache-2.0 AND BSD-2-Clause AND Python-2.0 AND BSD-3-Clause AND MIT
      short_summary: Installation wheels for setup tools and pip.
      supplier: 'Organization: Broadcom, Inc.'
