sources:
- archive: Python-3.11.9.tar.xz
  archive_sha512sum: 2b0a1d936b4ef8376f9655797aece8ffdff75031ad7bfa840f330cac2aed189aecc80c163edc12ea772851d7a011f3fc1960470a73d9d4290cf3ab8ad6ed7e6a
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The Python 3 package contains a new version of Python
        development environment. Python 3 brings more efficient ways of handling dictionaries,
        better unicode strings support, easier and more intuitive syntax, and removes
        the deprecated code. It is incompatible with Python 2.x releases. '
      home_page: http://www.python.org
      license_concluded: (Python-2.0 OR GPL-2.0-only) AND (BSD-3-Clause OR Apache-2.0)
        AND (MIT OR Apache-2.0) AND (MIT OR PSF-2.0) AND (BSD-2-Clause OR Apache-2.0)
        AND GPL-1.0-or-later AND LGPL-2.1-or-later AND FSFULLRWD AND PSF-2.0 AND CNRI-Python
        AND HPND AND dtoa AND 0BSD AND MIT-CMU AND CC0-1.0 AND FSFAP AND BSD-Source-Code
        AND FSFUL AND FSFULLR AND BSD-2-Clause AND Apache-2.0 AND Python-2.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND OpenSSL AND X11 AND MIT AND BSD-3-Clause
        AND Python-2.0.1 AND Zlib AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND MS-RL
      license_declared: (Python-2.0 OR GPL-2.0-only) AND (BSD-3-Clause OR Apache-2.0)
        AND (MIT OR Apache-2.0) AND (MIT OR PSF-2.0) AND (BSD-2-Clause OR Apache-2.0)
        AND GPL-1.0-or-later AND LGPL-2.1-or-later AND FSFULLRWD AND PSF-2.0 AND CNRI-Python
        AND HPND AND dtoa AND 0BSD AND MIT-CMU AND CC0-1.0 AND FSFAP AND BSD-Source-Code
        AND FSFUL AND FSFULLR AND BSD-2-Clause AND Apache-2.0 AND Python-2.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND OpenSSL AND X11 AND MIT AND BSD-3-Clause
        AND Python-2.0.1 AND Zlib AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND MS-RL
      short_summary: A high-level scripting language
      supplier: 'Organization: Broadcom, Inc.'
- archive: setuptools-pip-wheels.ph5-1.0-2.tar.xz
  archive_sha512sum: bb98b9975b611d3bb99644803f9579b8d4ee5216a9d057c5191d214dd4d6a6cc0a8d72b4f33c893c85543a78faf7feec002c53648646c19baa0eeba5f9c0ed7e
  skip_validation: true
  spdx:
    package:
      detailed_description: Installation wheels for setup tools and pip.
      home_page: https://pypi.org/project/pip/
      license_concluded: (BSD-3-Clause OR Apache-2.0) AND (BSD-2-Clause OR Apache-2.0)
        AND Apache-2.0 AND BSD-2-Clause AND Python-2.0 AND BSD-3-Clause AND MIT
      license_declared: (BSD-3-Clause OR Apache-2.0) AND (BSD-2-Clause OR Apache-2.0)
        AND Apache-2.0 AND BSD-2-Clause AND Python-2.0 AND BSD-3-Clause AND MIT
      short_summary: Installation wheels for setup tools and pip.
      supplier: 'Organization: Broadcom, Inc.'
