sources:
- archive: pyinstaller-6.16.0.tar.gz
  archive_sha512sum: f5b697dfd3abba7a4cba61e79f72416814107f469d9bd2c371167d10d6f6db9cfe0b085d377d84cf4bf38f46a7031a6f1fec02eb96ba5c530e1bc071e68e8d0c
  url: https://github.com/pyinstaller/pyinstaller/archive/refs/tags/v6.16.0.tar.gz
  commit_id: 7f2ae63f703ae27955722eac4891678b546d513a
  repo_url: https://github.com/pyinstaller/pyinstaller
  name: pyinstaller-6.16.0
  archive_type: upstream
  skip_validation: true
  spdx:
    package:
      detailed_description: 'PyInstaller bundles a Python application and all its dependencies into a single package. The user can run the packaged app without installing a Python interpreter or any modules. PyInstaller reads a Python script written by you. It analyzes your code to discover every other module and library your script needs in order to execute. Then it collects copies of all those files – including the active Python interpreter! – and puts them with your script in a single folder, or optionally in a single executable file. PyInstaller is tested against Windows, Mac OS X, and Linux. However, it is not a cross-compiler: to make a Windows app you run PyInstaller in Windows; to make a Linux app you run it in Linux, etc. PyInstaller has been used successfully with AIX, Solaris, and FreeBSD, but is not tested against them. '
      home_page: https://pypi.python.org/pypi/PyInstaller
      license_concluded: (GPL-2.0-or-later WITH Bootloader-exception OR MIT) AND Apache-2.0 AND BSD-3-Clause AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Bootloader-exception AND GPL-3.0-only AND LGPL-2.1-only AND MIT AND Zlib
      license_declared: (GPL-2.0-or-later WITH Bootloader-exception OR MIT) AND Apache-2.0 AND BSD-3-Clause AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Bootloader-exception AND GPL-3.0-only AND LGPL-2.1-only AND MIT AND Zlib
      short_summary: PyInstaller bundles a Python application and all its dependencies into a single package.
      supplier: 'Organization: Broadcom, Inc.'
