sources:
- archive: shim-16.1.tar.bz2
  archive_sha512sum: ca5f80e82f3b80b622028f03ef23105c98ee1b6a25f52a59c823080a3202dd4b9962266489296e99f955eb92e36ce13e0b1d57f688350006bba45f2718f159fb
  archive_type: upstream
  name: shim-16.1
  version: '16.1'
  url: https://github.com/rhboot/shim/releases/download/16.1/shim-16.1.tar.bz2
  repo_url: https://github.com/rhboot/shim
  commit_id: afc49558b34548644c1cd0ad1b6526a9470182ed
  skip_validation: true
  spdx:
    package:
      detailed_description: 'First stage UEFI bootloader that attempts to open, validate,
        and execute another application. It also installs a protocol which permits
        the second-stage bootloader to perform similar binary validation. '
      home_page: https://github.com/rhboot/shim
      license_concluded: MIT AND OpenSSL-standalone AND LGPL-2.1-or-later AND GPL-3.0-or-later
        AND OpenSSL AND GPL-1.0-or-later AND snprintf AND GPL-2.0-or-later AND BSD-2-Clause
        AND GPL-3.0-only AND Nokia AND BSD-2-Clause-Patent AND BSD-3-Clause AND SSLeay-standalone
        AND BSD-Source-Code
      license_declared: MIT AND OpenSSL-standalone AND LGPL-2.1-or-later AND GPL-3.0-or-later
        AND OpenSSL AND GPL-1.0-or-later AND snprintf AND GPL-2.0-or-later AND BSD-2-Clause
        AND GPL-3.0-only AND Nokia AND BSD-2-Clause-Patent AND BSD-3-Clause AND SSLeay-standalone
        AND BSD-Source-Code
      short_summary: UEFI shim loader
      supplier: 'Organization: Broadcom, Inc.'
