sources:
- archive: async-2.35.3.gem
  archive_sha512sum: 2c4ea547e7a31894790a3f85556977bc1ee0ebabfae4c240fdf090424c9a3e47ebf8666632ec93b321af5a13942822b73b823eda1bbf3c3f1035018b1c044d5f
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Async provides a modern asynchronous I/O framework for
        Ruby, based on nio4r. It implements the reactor pattern, providing both IO
        and timer based events. '
      home_page: https://rubygems.org/gems/async/versions/2.35.3
      license_concluded: MIT
      license_declared: MIT
      short_summary: Async provides a modern asynchronous I/O framework for Ruby,
        based on nio4r.
      supplier: 'Organization: Broadcom, Inc.'
