sources:
- archive: rabbitmq-server-4.0.4.tar.xz
  archive_type: upstream
  archive_sha512sum: b5ae8fdf9a8816b53b84c4fe5b74837ac7887f27c993350a4fd2448ce1e857f5eaf90a5e82dd95df912a39e5f6ce6ff555728bb6f38ea4af7649c8a903a3fb8b
  name: rabbitmq-server-4.0.4
  version: "4.0.4"
  url: https://github.com/rabbitmq/rabbitmq-server/releases/download/v4.0.4/rabbitmq-server-4.0.4.tar.xz
  repo_url: https://github.com/rabbitmq/rabbitmq-server
  commit_id: bdb30ca0edc7065a5be58decb4714d2488ce7362
  skip_list: ['LICENSE', 'LICENSE-APACHE2', 'plugins.mk', '4.0.4.md']
  missing: ['aten', 'LICENSE-MPL-2.0', 'recon', 'LICENSE-MPL2', 'khepri', '.bazelrc', 'systemd', 'LICENSE-httpc_aws', '.mix', 'bazel', 'observer_cli', 'gen_batch_server', 'BUILD.bazel', 'git-revisions.txt', 'docker', 'rabbitmq-mix.mk', '.gitignore', 'rabbitmq_run.bzl', 'LICENSE-Apache-2.0', 'jose', 'osiris', 'rabbitmq_amqp_client', 'rabbitmq_ct_client_helpers', 'BUILD.bats', 'MODULE.bazel', 'LICENSE-rabbitmq_aws', 'elvis_mk', 'cowlib', 'rabbitmq_home.bzl', 'rabbitmqctl.bzl', 'seshat', 'user-template.bazelrc', 'LICENSE-MIT-Mochi', 'cowboy', 'packaging', 'LICENSE-BSD-recon', '.git-blame-ignore-revs', 'examples', 'LICENSE-MIT-jQuery', '.gitkeep', 'BUILD.package_generic_unix', 'cuttlefish', 'khepri_mnesia_migration', 'prometheus', 'stdout_formatter', 'PKG_LINUX.md', 'quantile_estimator', 'activemq.bzl', 'sysmon_handler', 'rabbitmq_ct_helpers', 'tools', 'getopt', '.hgignore', 'csv', 'LICENSE-MIT-Sammy060', 'LICENSE-MIT-Erlware-Commons', '.hex', 'test', 'rabbitmq.bzl', 'LICENSE-BSD-base64js', 'doc', 'rabbitmq_package_generic_unix.bzl', 'LICENSE-MIT-EJS10', 'LICENSE-APL2-Stomp-Websocket', 'LICENSE-APACHE2-excanvas', 'ra', 'base64url', 'json', 'LICENSE-MIT-EJS', 'app.bzl', 'syslog', 'thoas', 'PKG_WINDOWS.md', 'enough', 'ranch', 'trust_store_http', 'horus', 'LICENSE-MPL', 'gun', 'mix.lock', 'LICENSE-MIT-Sammy', 'bats.bzl', 'erlang_ls.config', 'accept', 'credentials_obfuscation', 'LICENSE-ISC-cowboy', 'eetcd', 'moduleindex.yaml', 'LICENSE-APACHE2-ExplorerCanvas', 'LICENSE-MIT-jQuery164', 'LICENSE-erlcloud', 'redbug', '.github', 'dist.bzl', 'LICENSE-MIT-Flot']
  spdx:
    package:
      detailed_description: 'rabbitmq messaging server '
      home_page: https://github.com/rabbitmq/rabbitmq-server
      license_concluded: MIT AND ISC AND Apache-2.0 AND ErlPL-1.1 AND MPL-1.0 AND
        CC0-1.0 AND (BSD-3-Clause OR EPL-2.0) AND BSD-2-Clause AND (Apache-2.0 OR
        MPL-2.0) AND BSD-3-Clause AND MPL-2.0 AND MPL-1.1
      license_declared: MIT AND ISC AND Apache-2.0 AND ErlPL-1.1 AND MPL-1.0 AND CC0-1.0
        AND (BSD-3-Clause OR EPL-2.0) AND BSD-2-Clause AND (Apache-2.0 OR MPL-2.0)
        AND BSD-3-Clause AND MPL-2.0 AND MPL-1.1
      short_summary: RabbitMQ messaging server
      supplier: 'Organization: Broadcom, Inc.'
