sources:
- archive: cloud-network-setup-0.2.3.tar.gz
  archive_sha512sum: c4c40c5ed5d4052ab40e90cb40a9376793790245ceef678ddda343468ae798e9eab39fe514901f6b3d2995023ebb9ddd359582255298be9e1ae842562c1cfe24
  archive_type: upstream
  commit_id: acc2ca41318e5c5e3f9c53242243d6f4365fc13d
  missing: []
  skip_list: []
  skip_validation: false
  name: cloud-network-setup-0.2.3
  version: '0.2.3'
  repo_url: https://github.com/vmware/cloud-network-setup
  url: https://github.com/vmware/cloud-network-setup/archive/refs/tags/v0.2.3.tar.gz
  spdx:
    package:
      detailed_description: 'cloud-network configures network in cloud environment.
        In cloud environment instances are set public IPs and private IPs. If more
        than one private IP is configured then except the IP which is provided by
        DHCP others can''t be fetched and configured. This project is adopting towards
        cloud network environment such as Azure, GCP and Amazon EC2. '
      home_page: https://github.com/vmware/cloud-network-setup/archive/refs/tags/v0.2.2.tar.gz
      license_concluded: BSD-3-Clause AND MPL-2.0 AND Apache-2.0 AND BSD-2-Clause
        AND MIT
      license_declared: BSD-3-Clause AND MPL-2.0 AND Apache-2.0 AND BSD-2-Clause AND
        MIT
      short_summary: Configures network interfaces in cloud enviroment
      supplier: 'Organization: Broadcom, Inc.'
