shared_sources:
  - shared-cfg-yml/cmake.yaml

sources:
- archive: clang-18.1.8.src.tar.xz
  archive_sha512sum: 4147ef5e3547e80fbea573a6e3964870b38e7a547e796deb8859ca670b039ddd1af289cd4feadcb4ab5e94211b2ab5e91dfa84f58f114fdcbc9e807c9de901ca
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The goal of the Clang project is to create a new C based
        language front-end: C, C++, Objective C/C++, OpenCL C and others for the LLVM
        compiler. You can get and build the source today. '
      home_page: http://clang.llvm.org
      license_concluded: MIT-0 AND GPL-3.0-only AND Apache-2.0 AND Apache-2.0 WITH
        LLVM-exception AND NCSA AND MIT
      license_declared: MIT-0 AND GPL-3.0-only AND Apache-2.0 AND Apache-2.0 WITH
        LLVM-exception AND NCSA AND MIT
      short_summary: C, C++, Objective C and Objective C++ front-end for the LLVM
        compiler.
      supplier: 'Organization: Broadcom, Inc.'
