sources:
- archive: boto3-1.42.73.tar.gz
  archive_sha512sum: d02444f976814373d9dc8a89ae52e1df59e04d1c4ee4c2babaef96f7a22a8c5dad302fa717ecd1f6daae26bacc59211ba0015608df9e06792c6953f8e1138495
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Boto3 is the Amazon Web Services (AWS) Software Development
        Kit (SDK) for Python, which allows Python developers to write software that
        makes use of services like Amazon S3 and Amazon EC2'
      home_page: https://github.com/boto/boto3
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: The AWS SDK for Python
      supplier: 'Organization: Broadcom, Inc.'
