sources:
- archive: http-5.3.1.gem
  archive_sha512sum: 57902d997cfa51b8cb091ce0651d12a9bffb05992b6582c7fc0260a5208539faebedbcc1e837a2ff502336a8930abf4a1b8d531bac3f5643986850735efaa658
  skip_validation: true
  spdx:
    package:
      detailed_description: 'An easy-to-use client library for making requests from
        Ruby. It uses a simple method chaining system for building requests, similar
        to Python''s Requests.'
      home_page: https://rubygems.org/gems/http/versions/5.3.1
      license_concluded: MIT
      license_declared: MIT
      short_summary: An easy-to-use client library for making requests from Ruby.
      supplier: 'Organization: Broadcom, Inc.'
