sources:
- archive: openresty-1.21.4.3.tar.gz
  archive_sha512sum: dd0f36a367177a2d03378abf7995bad466965705fb549fa1f2a3bfc1cf5ba153de2849f789a718e1a4abb85996fde90f79f7f7571677ec32ee596aa076261c52
  skip_validation: true
  license_manual_review:
  - archive_path: bundle/opm-0.0.7/bin/opm
    sha256sum: e190a396bcb82891b8df94f106d8e7911fe595432a4af6305179e0897e3dfb50
    spdx_exp: ''
  - archive_path: bundle/pod/opm-0.0.7/opm-0.0.7.pod
    sha256sum: 163828894b196a9e0487669e3836d10c46207f75d6e614763f61d0409b7d1701
    spdx_exp: ''
  - archive_path: bundle/pod/opm-0.0.7/web.docs.md.docs.pod
    sha256sum: 708968ab64ade8240998447264774e89f2359a0ecddc38ee493ad76aa3abe3c5
    spdx_exp: ''
  spdx:
    package:
      detailed_description: 'This package contains the core server for OpenResty.
        Built for production uses.  OpenResty is a full-fledged web platform by integrating
        the standard Nginx core, LuaJIT, many carefully written Lua libraries, lots
        of high quality 3rd-party Nginx modules, and most of their external dependencies.
        It is designed to help developers easily build scalable web applications,
        web services, and dynamic web gateways.  By taking advantage of various well-designed
        Nginx modules (most of which are developed by the OpenResty team themselves),
        OpenResty effectively turns the nginx server into a powerful web app server,
        in which the web developers can use the Lua programming language to script
        various existing nginx C modules and Lua modules and construct extremely high-performance
        web applications that are capable to handle 10K ~ 1000K+ connections in a
        single box. '
      home_page: https://openresty.org/en
      license_concluded: (BSD-2-Clause OR GPL-2.0-only) AND Artistic-2.0 AND BSD-1-Clause
        AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND CC-BY-4.0 AND
        CC-BY-NC-4.0 AND CC-BY-NC-ND-4.0 AND CC-BY-NC-SA-4.0 AND CC-BY-ND-4.0 AND
        CC-BY-SA-4.0 AND CDDL-1.0 AND EPL-1.0 AND GPL-1.0-or-later AND GPL-2.0-only
        AND GPL-3.0-only AND LGPL-2.0-or-later AND MIT AND MPL-2.0 AND OpenSSL AND
        OpenSSL-standalone AND SSLeay-standalone AND Zlib AND dtoa
      license_declared: (BSD-2-Clause OR GPL-2.0-only) AND Artistic-2.0 AND BSD-1-Clause
        AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND CC-BY-4.0 AND
        CC-BY-NC-4.0 AND CC-BY-NC-ND-4.0 AND CC-BY-NC-SA-4.0 AND CC-BY-ND-4.0 AND
        CC-BY-SA-4.0 AND CDDL-1.0 AND EPL-1.0 AND GPL-1.0-or-later AND GPL-2.0-only
        AND GPL-3.0-only AND LGPL-2.0-or-later AND MIT AND MPL-2.0 AND OpenSSL AND
        OpenSSL-standalone AND SSLeay-standalone AND Zlib AND dtoa
      short_summary: A Fast and Scalable Web Platform by Extending NGINX with Lua
      supplier: 'Organization: Broadcom, Inc.'
