sources:
- archive: openscap-1.3.14.tar.gz
  archive_type: upstream
  archive_sha512sum: 4b037fd739443fe7dad6edc6e78f6aed6193d2d3a9b32940aeb0add31ecdd8c76887836446d1def72e3b8baf231a20de14626c6f5176858694afd853b05ccdeb
  skip_validation: false
  name: openscap-1.3.14
  version: 1.4.3
  url: https://github.com/OpenSCAP/openscap/archive/refs/tags/1.3.14.tar.gz
  repo_url: https://github.com/OpenSCAP/openscap
  commit_id: 5323ca8c17a2f79da9670454d5765292c83bbbb4
  skip_list: []
  missing: ['.gitmodules', 'build', 'tests', 'utils/__pycache__/autotailorcpython-312.pyc', 'utils/__pycache__/autotailorcpython-313.pyc', '.travis.yml', 'CMakeLists.txt', 'LICENSE', 'README.md', 'cmake', 'LICENSE', 'docs', 'res', 'sonar-project.properties', 'src', '.pytest_cache', '.gitignore', 'noarch', '.github', 'Testing']
  spdx:
    package:
      detailed_description: 'SCAP is a multi-purpose framework of specifications that
        supports automated configuration, vulnerability and patch checking, technical
        control compliance activities, and security measurement. OpenSCAP has received
        a NIST certification for its support of SCAP 1.2. '
      home_page: https://www.open-scap.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND
        (GPL-2.0-only OR MIT) AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause
        AND GPL-2.0-or-later AND LGPL-2.0-only AND LGPL-2.0-or-later AND
        LGPL-2.1-only AND LGPL-2.1-or-later AND MIT AND W3C-19980720
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND
        (GPL-2.0-only OR MIT) AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause
        AND GPL-2.0-or-later AND LGPL-2.0-only AND LGPL-2.0-or-later AND
        LGPL-2.1-only AND LGPL-2.1-or-later AND MIT AND W3C-19980720
      short_summary: Open Source Security Compliance Solution
      supplier: 'Organization: Broadcom, Inc.'
