sources:
- archive: photon-motdgen-1.0.tar.gz
  archive_sha512sum: 
    031d2209e0a582bab9457cf82e80d920b2b121eab9a685dee54aaa0e4556598b949462e4e1fba6342dbbef22231ba29cd9c66d72139a0ed727b093d75eed5004
  skip_validation: true
  spdx:
    package:
      detailed_description: Generates Dynamic MOTD.
      home_page: https://github-vcf.devops.broadcom.net/vcf/photon-motdgen
      license_concluded: GPL-2.0-only
      license_declared: GPL-2.0-only
      short_summary: Message of the Day
      supplier: 'Organization: Broadcom, Inc.'
