sources:
- archive: cython-3.2.4.tar.gz
  archive_sha512sum: 5ab8e39739a79debbe89b2ff5b6d88e1b7aafd5ad34460f14f3fc2bd90c10bdc9d6aa5b5844a48e30402dde9790cb9abcba3dc2b4e8cde24c4eeee818a180099
  archive_type: upstream
  skip_validation: false
  name: cython-3.2.4
  version: 3.2.4
  url: https://github.com/cython/cython/archive/refs/tags/3.2.4.tar.gz
  repo_url: https://github.com/cython/cython
  commit_id: 21bda420d583bcf464fb9efb932b09c5f3db1efd
  missing: ['.codespellrc', '.editorconfig', '.github', '.gitignore', '.hgignore', '.hgtags', '.mailmap', '.readthedocs.yaml', 'BUILD.bazel', 'CONTRIBUTING.md', 'Doc', 'LICENSE', 'Makefile', 'PKG-INFO', 'README.rst', 'ipython-COPYING.rst', 'limited_api_bugs_38.txt', 'locking', 'memoryview_tests.txt', 'pyproject.toml', 'runcodestyle.py', 'windows_bugs_39.txt']
  skip_list: []
  spdx:
    package:
      detailed_description: 'Cython is an optimising static compiler for both the
        Python programming language, and the extended Cython programming language
        (based on Pyrex). It makes writing C extensions for Python as easy as Python
        itself. '
      home_page: http://cython.org/
      license_concluded: Apache-2.0 AND BSD-3-Clause AND LGPL-2.0-only AND
        LGPL-2.0-or-later AND MIT AND Python-2.0
      license_declared: Apache-2.0 AND BSD-3-Clause AND LGPL-2.0-only AND
        LGPL-2.0-or-later AND MIT AND Python-2.0
      short_summary: C extensions for Python3
      supplier: 'Organization: Broadcom, Inc.'
