sources:
- archive: fluent-plugin-concat-2.6.0.gem
  archive_sha512sum: 7cffce6de8e06b38747f41dc237c3409c4a206f168ecbc417e460528d507e39415fabb6658449206854308f82b9a3f759726ba5ce423c38fc067cf744b1aab28
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Fluentd Filter plugin to concatenate multiline log separated
        in multiple events. '
      home_page: https://rubygems.org/gems/fluent-plugin-concat/versions/2.5.0
      license_concluded: MIT
      license_declared: MIT
      short_summary: Fluentd Filter plugin to concat multiple event messages.
      supplier: 'Organization: Broadcom, Inc.'
