sources:
- archive: google-cloud-storage-1.58.0.gem
  archive_sha512sum: a6f6fc0c00a64de15f66d9c66753d8b9fda57011a880ab590c14b455001a30b5a6f3c1eee88b1321df95eaf8655650b622474f743d6a4c3e193459db04c78958
  skip_validation: true
  spdx:
    package:
      detailed_description: 'google-cloud-storage is the official library for Google Cloud Storage.'
      home_page: https://rubygems.org/gems/google-cloud-storage
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: google-cloud-storage is the official library for Google Cloud Storage.
      supplier: 'Organization: Broadcom, Inc.'
