sources:
- archive: rdma-core-60.1.tar.gz
  archive_sha512sum: 43a0ba2f04e1a79329246336515d51acac576a783c40c18c00e23d0dde9dd5d75f5c669abdc2e5b0a8e9bb0ee724d8f6336a19001ee21928ecf22cb09c633089
  archive_type: upstream
  skip_validation: false
  name: rdma-core-60.1
  version: "60.1"
  url: https://github.com/linux-rdma/rdma-core/releases/download/v60.1/rdma-core-60.1.tar.gz
  repo_url: https://github.com/linux-rdma/rdma-core
  commit_id: 54224f4c9c1d4b9d81b0b717307fc6ce177df127
  missing: ['pandoc-prebuilt']
  spdx:
    package:
      detailed_description: 'Userspace libraries and daemons for the Linux Kernel''s
        drivers/infiniband subsystem. '
      home_page: https://github.com/linux-rdma/rdma-core
      license_concluded: (BSD-3-Clause OR GPL-2.0-only) AND MIT AND (GPL-2.0-only
        WITH Linux-syscall-note OR BSD-2-Clause) AND (GPL-2.0-only WITH Linux-syscall-note
        OR Linux-OpenIB) AND GPL-2.0-or-later AND BSD-2-Clause AND (GPL-2.0-only OR
        BSD-2-Clause OR CPL-1.0) AND (GPL-2.0-only WITH Linux-syscall-note OR BSD-2-Clause)
        AND CPL-1.0 AND Linux-OpenIB AND (MIT OR GPL-1.0-or-later) AND CC0-1.0 AND
        (Linux-OpenIB OR GPL-2.0-only) AND GPL-2.0-only AND (GPL-2.0-only OR BSD-2-Clause)
        AND BSD-3-Clause AND (GPL-2.0-only OR BSD-3-Clause) AND (GPL-2.0-only OR BSD-3-Clause)
        AND (GPL-2.0-only WITH Linux-syscall-note OR BSD-3-Clause) AND (GPL-2.0-only
        WITH Linux-syscall-note OR Linux-OpenIB) AND GPL-2.0-only WITH Linux-syscall-note
        AND (GPL-2.0-only OR Linux-OpenIB) AND (GPL-2.0-only WITH Linux-syscall-note
        OR BSD-3-Clause) AND (GPL-2.0-only OR Linux-OpenIB) AND (GPL-2.0-only OR BSD-2-Clause)
      license_declared: (BSD-3-Clause OR GPL-2.0-only) AND MIT AND (GPL-2.0-only WITH
        Linux-syscall-note OR BSD-2-Clause) AND (GPL-2.0-only WITH Linux-syscall-note
        OR Linux-OpenIB) AND GPL-2.0-or-later AND BSD-2-Clause AND (GPL-2.0-only OR
        BSD-2-Clause OR CPL-1.0) AND (GPL-2.0-only WITH Linux-syscall-note OR BSD-2-Clause)
        AND CPL-1.0 AND Linux-OpenIB AND (MIT OR GPL-1.0-or-later) AND CC0-1.0 AND
        (Linux-OpenIB OR GPL-2.0-only) AND GPL-2.0-only AND (GPL-2.0-only OR BSD-2-Clause)
        AND BSD-3-Clause AND (GPL-2.0-only OR BSD-3-Clause) AND (GPL-2.0-only OR BSD-3-Clause)
        AND (GPL-2.0-only WITH Linux-syscall-note OR BSD-3-Clause) AND (GPL-2.0-only
        WITH Linux-syscall-note OR Linux-OpenIB) AND GPL-2.0-only WITH Linux-syscall-note
        AND (GPL-2.0-only OR Linux-OpenIB) AND (GPL-2.0-only WITH Linux-syscall-note
        OR BSD-3-Clause) AND (GPL-2.0-only OR Linux-OpenIB) AND (GPL-2.0-only OR BSD-2-Clause)
      short_summary: RDMA Core Userspace Libraries and Daemons
      supplier: 'Organization: Broadcom, Inc.'
