sources:
- archive: docker-cli-29.8.0.tar.gz
  archive_type: upstream
  version: 29.8.0
  name: cli-29.8.0
  url: https://github.com/docker/cli/archive/refs/tags/v29.8.0.tar.gz
  repo_url: https://github.com/docker/cli.git
  commit_id: 88096ef00576baf72a9cb45caa45c0544c40e0a7
  skip_list: []
  missing: []
  archive_sha512sum: 75d475d4198fc87085fa1fd881caf18f2fafe0b8483bf3ba4c19f1057ed03f336e7d2f6eeb0c14697c82c0d1b3bf93dadc96a007b9c499e634dd44a8438e132c
  skip_validation: false
  spdx:
    package:
      detailed_description: Docker CLI
      home_page: https://github.com/docker/cli
      license_concluded: BSD-3-Clause AND CC-BY-SA-4.0 AND Apache-2.0 AND BSD-2-Clause
        AND MIT
      license_declared: BSD-3-Clause AND CC-BY-SA-4.0 AND Apache-2.0 AND BSD-2-Clause
        AND MIT
      short_summary: Docker CLI
      supplier: 'Organization: Broadcom, Inc.'
- archive: docker-v29.8.0.tar.gz
  archive_type: upstream
  version: 29.8.0
  name: moby-docker-v29.8.0
  url: https://github.com/moby/moby/archive/refs/tags/docker-v29.8.0.tar.gz
  repo_url: https://github.com/moby/moby.git
  commit_id: 3ce5872b7950c63ba2ffbc5123101019ff3e6682
  skip_list: []
  missing: []
  archive_sha512sum: 2e2b6079d69b6e1cf4e2c6c1609cab64aceed402c966c31efdef42b8b7f2a5a7e7c39c06b2eeb191b00f4bb5b4eb83eb1c5ec82ddde020009f3c0a39c1739244
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Docker is an open source project to build, ship and run
        any application as a lightweight container. '
      home_page: http://docs.docker.com
      license_concluded: (OpenSSL OR BSD-3-Clause) AND (Apache-2.0 OR GPL-2.0-or-later)
        AND MIT AND ISC AND CC-BY-SA-4.0 AND CC0-1.0 AND GPL-2.0-only AND BSD-2-Clause
        AND Apache-2.0 AND CC-BY-4.0 AND GPL-1.0-or-later AND BSD-3-Clause AND MPL-2.0
      license_declared: (OpenSSL OR BSD-3-Clause) AND (Apache-2.0 OR GPL-2.0-or-later)
        AND MIT AND ISC AND CC-BY-SA-4.0 AND CC0-1.0 AND GPL-2.0-only AND BSD-2-Clause
        AND Apache-2.0 AND CC-BY-4.0 AND GPL-1.0-or-later AND BSD-3-Clause AND MPL-2.0
      short_summary: Docker
      supplier: 'Organization: Broadcom, Inc.'
