sources:
- archive: docker-cli-29.4.1.tar.gz
  archive_type: upstream
  version: 29.4.1
  name: cli-29.4.1
  url: https://github.com/docker/cli/archive/refs/tags/v29.4.1.tar.gz
  repo_url: https://github.com/docker/cli.git
  commit_id: 055a478ea9010a19d0d4674c0d0e87ade37a4223
  skip_list: []
  missing: []
  archive_sha512sum: 28ef073e7e384744a45ba82c48e7ab695fa066e979b12b0f3d2ecdc91d315ffe13e43d0b483ce38b014301406a5530b1bd425b5b6af0fc3b368f774a565872af
  skip_validation: false
  spdx:
    package:
      detailed_description: Docker CLI
      home_page: https://github.com/docker/cli
      license_concluded: BSD-3-Clause AND CC-BY-SA-4.0 AND Apache-2.0 AND BSD-2-Clause
        AND MIT
      license_declared: BSD-3-Clause AND CC-BY-SA-4.0 AND Apache-2.0 AND BSD-2-Clause
        AND MIT
      short_summary: Docker CLI
      supplier: 'Organization: Broadcom, Inc.'
- archive: docker-v29.4.1.tar.gz
  archive_type: upstream
  version: 29.4.1
  name: moby-docker-v29.4.1
  url: https://github.com/moby/moby/archive/refs/tags/docker-v29.4.1.tar.gz
  repo_url: https://github.com/moby/moby.git
  commit_id: 6c91b92cc71077b70c779c510da125301a8e40f3
  skip_list: []
  missing: []
  archive_sha512sum: f8f38570d9a2f6f1d162f532c2c2337079dca594d134fc5d78128d46d31f0957dbc1a79b44a89649ba078e74c2ed01079c32b590acc123b1422d0749f16fe4bf
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Docker is an open source project to build, ship and run
        any application as a lightweight container. '
      home_page: http://docs.docker.com
      license_concluded: (OpenSSL OR BSD-3-Clause) AND (Apache-2.0 OR GPL-2.0-or-later)
        AND MIT AND ISC AND CC-BY-SA-4.0 AND CC0-1.0 AND GPL-2.0-only AND BSD-2-Clause
        AND Apache-2.0 AND CC-BY-4.0 AND GPL-1.0-or-later AND BSD-3-Clause AND MPL-2.0
      license_declared: (OpenSSL OR BSD-3-Clause) AND (Apache-2.0 OR GPL-2.0-or-later)
        AND MIT AND ISC AND CC-BY-SA-4.0 AND CC0-1.0 AND GPL-2.0-only AND BSD-2-Clause
        AND Apache-2.0 AND CC-BY-4.0 AND GPL-1.0-or-later AND BSD-3-Clause AND MPL-2.0
      short_summary: Docker
      supplier: 'Organization: Broadcom, Inc.'
