sources:
- archive: docker-cli-29.5.2.tar.gz
  archive_type: upstream
  version: 29.5.2
  name: cli-29.5.2
  url: https://github.com/docker/cli/archive/refs/tags/v29.5.2.tar.gz
  repo_url: https://github.com/docker/cli.git
  commit_id: 79eb04c7d8e1d73247cb7fe011eecc645063e0f0
  skip_list: []
  missing: []
  archive_sha512sum: 3c569dbbcef6e9720a126147175f67297acab9a4ae8dd2af544b48eca70519dfd3c5312bf4ffab777e59a251cfdc5965217b0d3ca4c2eb41117c2e3b465bbb8a
  skip_validation: false
  spdx:
    package:
      detailed_description: Docker CLI
      home_page: https://github.com/docker/cli
      license_concluded: BSD-3-Clause AND CC-BY-SA-4.0 AND Apache-2.0 AND BSD-2-Clause
        AND MIT
      license_declared: BSD-3-Clause AND CC-BY-SA-4.0 AND Apache-2.0 AND BSD-2-Clause
        AND MIT
      short_summary: Docker CLI
      supplier: 'Organization: Broadcom, Inc.'
- archive: docker-v29.5.2.tar.gz
  archive_type: upstream
  version: 29.5.2
  name: moby-docker-v29.5.2
  url: https://github.com/moby/moby/archive/refs/tags/docker-v29.5.2.tar.gz
  repo_url: https://github.com/moby/moby.git
  commit_id: 568f755ebeb1ac9c6a8febbda6cd371ea0a9630b
  skip_list: []
  missing: []
  archive_sha512sum: c5cbb956711e9ce8dbab010bf1eab3fd9b35e35806188e3030a3bbeafb545f4024504577df7c39588672c8d5252f6ab071bcfd6377867f4668b75855571469fb
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Docker is an open source project to build, ship and run
        any application as a lightweight container. '
      home_page: http://docs.docker.com
      license_concluded: (OpenSSL OR BSD-3-Clause) AND (Apache-2.0 OR GPL-2.0-or-later)
        AND MIT AND ISC AND CC-BY-SA-4.0 AND CC0-1.0 AND GPL-2.0-only AND BSD-2-Clause
        AND Apache-2.0 AND CC-BY-4.0 AND GPL-1.0-or-later AND BSD-3-Clause AND MPL-2.0
      license_declared: (OpenSSL OR BSD-3-Clause) AND (Apache-2.0 OR GPL-2.0-or-later)
        AND MIT AND ISC AND CC-BY-SA-4.0 AND CC0-1.0 AND GPL-2.0-only AND BSD-2-Clause
        AND Apache-2.0 AND CC-BY-4.0 AND GPL-1.0-or-later AND BSD-3-Clause AND MPL-2.0
      short_summary: Docker
      supplier: 'Organization: Broadcom, Inc.'
