sources:
- archive: httpclient-2.8.3.gem
  archive_sha512sum: d02c7b7c9e1a386b6e16ebbf4b00ce916233a08cca7286f03c39aee0935fc5a811cb20c0613b50dff9dd8bd5d92d1a5c7e8d45fb724aeaa36bf90b597bd9d428
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Gives something like the functionality of libwww-perl (LWP) in Ruby'
      home_page: https://rubygems.org/gems/httpclient
      license_concluded: Ruby
      license_declared: Ruby
      short_summary: Gives something like the functionality of libwww-perl (LWP) in Ruby
      supplier: 'Organization: Broadcom, Inc.'
