sources:
- archive: pluggy-1.6.0.tar.gz
  archive_sha512sum: 8b88eb778ab955910bcde2b3a6c4925d0a239f932aa9b1d8a351aa21b8a922bd842f735e397ef15ed9bd8e51085a88723660e1e691888a9879e7144add32bff2
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The plugin manager stripped of pytest specific details.'
      home_page: https://pypi.org/project/pluggy/
      license_concluded: MIT
      license_declared: MIT
      short_summary: The plugin manager stripped of pytest specific details
      supplier: 'Organization: Broadcom, Inc.'
