sources:
- archive: runc-1.2.8.tar.gz
  archive_sha512sum: 8d29a2ca179320f9a01c37383506f10aea1764e18b3321c507787556e3a531e23221f8369696d8caaf30124a523a68d0ad3609bae5ab06aa6c519e644d54d4ef
  archive_type: upstream
  name: runc-1.2.8
  version: 1.2.8
  url: https://github.com/opencontainers/runc/archive/refs/tags/v1.2.8.tar.gz
  repo_url: https://github.com/opencontainers/runc
  commit_id: eeb7e6024f9ee43876301b1d23c353384fa6dcdd
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'runC is a CLI tool for spawning and running containers
        according to the OCI specification. Containers are started as a child process
        of runC and can be embedded into various other systems without having to run
        a daemon. '
      home_page: https://runc.io
      license_concluded: BSD-3-Clause AND (Apache-2.0 OR LGPL-2.1-or-later) AND LGPL-2.1-or-later
        AND CC-BY-4.0 AND GPL-1.0-or-later AND Apache-2.0 AND MIT AND BSD-2-Clause
      license_declared: BSD-3-Clause AND (Apache-2.0 OR LGPL-2.1-or-later) AND LGPL-2.1-or-later
        AND CC-BY-4.0 AND GPL-1.0-or-later AND Apache-2.0 AND MIT AND BSD-2-Clause
      short_summary: CLI tool for spawning and running containers per OCI spec.
      supplier: 'Organization: Broadcom, Inc.'
