sources:
- archive: i40e-2.22.18.tar.gz
  archive_sha512sum: 042fd064528cb807894dc1f211dcb34ff28b319aea48fc6dede928c93ef4bbbb109bdfc903c27bae98b2a41ba01b7b1dffc3acac100610e3c6e95427162a26ac
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This Linux package contains the Intel i40e v2.22.18 driver. '
      home_page: https://sourceforge.net/projects/e1000
      license_concluded: (GPL-2.0-only OR MIT) AND GPL-2.0-only AND GPL-2.0-or-later
        AND BSD-3-Clause
      license_declared: (GPL-2.0-only OR MIT) AND GPL-2.0-only AND GPL-2.0-or-later
        AND BSD-3-Clause
      short_summary: Intel i40e driver v2.22.18
      supplier: 'Organization: Broadcom, Inc.'
- archive: i40e-2.23.17.tar.gz
  archive_sha512sum: 5dbe5186f23d14aac185f74283377d9bfc0837ab16b145a107f735d5439a207e27db871e278656cd06ba595f426d7095a294d39110df5ad6b30ea9f6d3a2a3a7
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This Linux package contains the Intel i40e v2.23.17 driver. '
      home_page: https://sourceforge.net/projects/e1000
      license_concluded: (GPL-2.0-only OR MIT) AND BSD-3-Clause AND GPL-2.0-or-later
        AND GPL-2.0-only
      license_declared: (GPL-2.0-only OR MIT) AND BSD-3-Clause AND GPL-2.0-or-later
        AND GPL-2.0-only
      short_summary: Intel i40e driver v2.23.17
      supplier: 'Organization: Broadcom, Inc.'
- archive: i40e-2.25.7.tar.gz
  archive_sha512sum: d1a206806be1b2481704a9d928c3d77769ef6f1d94798b8a35258e191a091252c75222b04a85049b52fb06ce68b8bd8543ddcc0e938a6ec75320432d75f71530
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This Linux package contains the Intel i40e v2.25.7 driver. '
      home_page: https://sourceforge.net/projects/e1000
      license_concluded: (GPL-2.0-only OR MIT) AND GPL-2.0-or-later AND GPL-2.0-only
        AND BSD-3-Clause
      license_declared: (GPL-2.0-only OR MIT) AND GPL-2.0-or-later AND GPL-2.0-only
        AND BSD-3-Clause
      short_summary: Intel i40e driver v2.25.7
      supplier: 'Organization: Broadcom, Inc.'
- archive: iavf-4.11.1.tar.gz
  archive_sha512sum: 201961b1f4b891368060f321e414d3d28b18a7c7b15bb6ad7c8e517216228bd67cbf68a018d59ce6b38e97cbb620f5ca1d88f829679d15930bc06688f40fa757
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This Linux package contains the Intel iavf v%{src_ver}
        driver. '
      home_page: https://sourceforge.net/projects/e1000
      license_concluded: (GPL-2.0-only OR MIT) AND GPL-2.0-only AND BSD-3-Clause AND
        GPL-2.0-or-later
      license_declared: (GPL-2.0-only OR MIT) AND GPL-2.0-only AND BSD-3-Clause AND
        GPL-2.0-or-later
      short_summary: Intel iavf driver v4.11.1
      supplier: 'Organization: Broadcom, Inc.'
- archive: iavf-4.8.2.tar.gz
  archive_sha512sum: 5406b86e61f6528adfd7bc3a5f330cec8bb3b4d6c67395961cc6ab78ec3bd325c3a8655b8f42bf56fb47c62a85fb7dbb0c1aa3ecb6fa069b21acb682f6f578cf
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This Linux package contains the Intel iavf v%{src_ver}
        driver. '
      home_page: https://sourceforge.net/projects/e1000
      license_concluded: (GPL-2.0-only OR MIT) AND GPL-2.0-or-later AND GPL-2.0-only
        AND BSD-3-Clause
      license_declared: (GPL-2.0-only OR MIT) AND GPL-2.0-or-later AND GPL-2.0-only
        AND BSD-3-Clause
      short_summary: Intel iavf driver v4.8.2
      supplier: 'Organization: Broadcom, Inc.'
- archive: iavf-4.5.3.tar.gz
  archive_sha512sum: 573b6b92ff7d8ee94d1ec01c56b990063c98c6f785a5fb96db30cf9c3fac4ff64277500b8468210464df343831818f576dd97cd172193491e3d47fec146c43fa
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This Linux package contains the Intel iavf v4.5.3 driver. '
      home_page: https://sourceforge.net/projects/e1000
      license_concluded: (GPL-2.0-only OR MIT) AND GPL-2.0-or-later AND GPL-2.0-only
        AND BSD-3-Clause
      license_declared: (GPL-2.0-only OR MIT) AND GPL-2.0-or-later AND GPL-2.0-only
        AND BSD-3-Clause
      short_summary: Intel iavf driver v4.5.3
      supplier: 'Organization: Broadcom, Inc.'
- archive: iavf-4.9.5.tar.gz
  archive_sha512sum: 2e97671d1fd51b5b0017b49dcfa62854ef55a85182fcd4990d2d7faea0c3dc9532fe3896c81eabff3c30fb3b2b9573c22416adfec3a1e0f0107c44a9216fbf3a
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This Linux package contains the Intel iavf v%{src_ver}
        driver. '
      home_page: https://sourceforge.net/projects/e1000
      license_concluded: (GPL-2.0-only OR MIT) AND GPL-2.0-or-later AND BSD-3-Clause
        AND GPL-2.0-only
      license_declared: (GPL-2.0-only OR MIT) AND GPL-2.0-or-later AND BSD-3-Clause
        AND GPL-2.0-only
      short_summary: Intel iavf driver v4.9.5
      supplier: 'Organization: Broadcom, Inc.'
- archive: ice-1.12.7.tar.gz
  archive_sha512sum: 71b08c90ee6c03242b0b11eef2425ec55fe089fa7735cc5ae9bae7469e14768b67505315a456e98b0b09ce0be71ffd35f119f2df211b927265f4d4eb8cbdf60b
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This Linux package contains the Intel ice v%{src_ver}
        driver. '
      home_page: https://sourceforge.net/projects/e1000
      license_concluded: (GPL-2.0-only OR MIT) AND (GPL-2.0-only OR Linux-OpenIB)
        AND BSD-3-Clause AND Intel AND GPL-2.0-only AND GPL-2.0-or-later
      license_declared: (GPL-2.0-only OR MIT) AND (GPL-2.0-only OR Linux-OpenIB) AND
        BSD-3-Clause AND Intel AND GPL-2.0-only AND GPL-2.0-or-later
      short_summary: Intel ice driver v1.12.7
      supplier: 'Organization: Broadcom, Inc.'
- archive: ice-1.13.7.tar.gz
  archive_sha512sum: 6167a0240624915ee6dce8f2186d6980c224baab8bcccee2b1d991d5cc15510b95b7b2a309cc60e57eae7dfffc4e2186730650ba104a231e54711c3b01f20f7b
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This Linux package contains the Intel ice v%{src_ver}
        driver. '
      home_page: https://sourceforge.net/projects/e1000
      license_concluded: (GPL-2.0-only OR Linux-OpenIB) AND (GPL-2.0-only OR MIT)
        AND Intel AND BSD-3-Clause AND GPL-2.0-or-later AND GPL-2.0-only
      license_declared: (GPL-2.0-only OR Linux-OpenIB) AND (GPL-2.0-only OR MIT) AND
        Intel AND BSD-3-Clause AND GPL-2.0-or-later AND GPL-2.0-only
      short_summary: Intel ice driver v1.13.7
      supplier: 'Organization: Broadcom, Inc.'
- archive: ice-1.9.11.tar.gz
  archive_sha512sum: 4ca301ea7d190d74f2eebf148483db5e2482ca19ff0eaf1c3061c9550ab215d1b0ab12e1f6466fe6bccc889d2ddae47058043b3d8622fd90c2b29c545bbcd3fc
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This Linux package contains the Intel ice v%{src_ver}
        driver. '
      home_page: https://sourceforge.net/projects/e1000
      license_concluded: (GPL-2.0-only OR MIT) AND (GPL-2.0-only OR Linux-OpenIB)
        AND Intel AND GPL-2.0-only AND BSD-3-Clause
      license_declared: (GPL-2.0-only OR MIT) AND (GPL-2.0-only OR Linux-OpenIB) AND
        Intel AND GPL-2.0-only AND BSD-3-Clause
      short_summary: Intel ice driver v1.9.11
      supplier: 'Organization: Broadcom, Inc.'
- archive: ice-1.11.14.tar.gz
  archive_sha512sum: a2a6a498e553d41e4e6959a19cdb74f0ceff3a7dbcbf302818ad514fdc18e3d3b515242c88d55ef8a00c9d16925f0cd8579cb41b3b1c27ea6716ccd7e70fd847
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This Linux package contains the Intel ice v1.11.14 driver. '
      home_page: https://sourceforge.net/projects/e1000
      license_concluded: (GPL-2.0-only OR Linux-OpenIB) AND (GPL-2.0-only OR MIT)
        AND BSD-3-Clause AND GPL-2.0-only AND Intel AND GPL-2.0-or-later
      license_declared: (GPL-2.0-only OR Linux-OpenIB) AND (GPL-2.0-only OR MIT) AND
        BSD-3-Clause AND GPL-2.0-only AND Intel AND GPL-2.0-or-later
      short_summary: Intel ice driver v1.11.14
      supplier: 'Organization: Broadcom, Inc.'
- archive: ice-1.14.9.tar.gz
  archive_sha512sum: 4a7fdc7b451d88ccd1ebcda45f1549407873c8d6fdd82bf549d47ef97acbafe13e5a09f03d3dc1ed22c76fa0486fca7186cfea76ba715a13bc83262f6aee37b3
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This Linux package contains the Intel ice v1.14.9 driver. '
      home_page: https://sourceforge.net/projects/e1000
      license_concluded: (GPL-2.0-only OR MIT) AND (GPL-2.0-only OR Linux-OpenIB)
        AND Intel AND GPL-2.0-or-later AND BSD-3-Clause AND GPL-2.0-only
      license_declared: (GPL-2.0-only OR MIT) AND (GPL-2.0-only OR Linux-OpenIB) AND
        Intel AND GPL-2.0-or-later AND BSD-3-Clause AND GPL-2.0-only
      short_summary: Intel ice driver v1.14.9
      supplier: 'Organization: Broadcom, Inc.'
