sources:
- archive: pyasn1-0.6.3.tar.gz
  archive_sha512sum: c58962b3f11f486da3e73c09dbe2aff7500879b29c4a7be4295878e4edbcaaa2680d608720ad5af86a2457de7da50471ab7a9e925f717db5c467553fc552e6d6
  version: 0.6.3
  name: pyasn1-0.6.3
  url: https://files.pythonhosted.org/packages/source/p/pyasn1/pyasn1-0.6.3.tar.gz
  repo_url: https://github.com/pyasn1/pyasn1
  commit_id: af65c3b92e9deeae50db4de390982dd970d87f98
  skip_list: []
  missing: ['.bandit.yml', 'devel-requirements.txt', '.readthedocs.yaml', 'requirements.txt', '.gitignore', 'pyasn1.egg-info', 'css', 'THANKS.txt', 'favicon.ico', 'PKG-INFO', '.github', 'setup.cfg', 'tox.ini']
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This is an implementation of ASN.1 types and codecs in
        Python programming language. It has been first written to support particular
        protocol (SNMP), but then generalized to be suitable for a wide range of protocols
        based on ASN.1 specification. '
      home_page: https://github.com/pyasn1/pyasn1
      license_concluded: BSD-2-Clause AND BSD-3-Clause
      license_declared: BSD-2-Clause AND BSD-3-Clause
      short_summary: Implementation of ASN.1 types and codecs in Python programming
        language
      supplier: 'Organization: Broadcom, Inc.'
