#!/bin/sh

# Begin /etc/systemd/scripts/iptables

# Insert connection-tracking modules
# (not needed if built into the kernel)
modprobe nf_conntrack
modprobe xt_LOG

# Enable broadcast echo Protection
echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

# deactivate Source Routed Packets
echo 0 > /proc/sys/net/ipv4/conf/all/accept_source_route
echo 0 > /proc/sys/net/ipv4/conf/default/accept_source_route

# Enable TCP SYN Cookie Protection
echo 1 > /proc/sys/net/ipv4/tcp_syncookies

# deactivate ICMP Redirect Acceptance
echo 0 > /proc/sys/net/ipv4/conf/default/accept_redirects

# Do not send Redirect Messages
echo 0 > /proc/sys/net/ipv4/conf/all/send_redirects
echo 0 > /proc/sys/net/ipv4/conf/default/send_redirects

# Drop Spoofed Packets coming in on an interface, where responses
# would result in the reply going out a different interface.
echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter
echo 1 > /proc/sys/net/ipv4/conf/default/rp_filter

# Log packets with impossible addresses.
echo 1 > /proc/sys/net/ipv4/conf/all/log_martians
echo 1 > /proc/sys/net/ipv4/conf/default/log_martians

# be verbose on dynamic ip-addresses  (not needed in case of static IP)
echo 2 > /proc/sys/net/ipv4/ip_dynaddr

# deactivate Explicit Congestion Notification
# too many routers are still ignorant
echo 0 > /proc/sys/net/ipv4/tcp_ecn

WAIT_OPTIONS="--wait 1 --wait-interval 20000"

# Set a known state
iptables $WAIT_OPTIONS -P INPUT   DROP
iptables $WAIT_OPTIONS -P FORWARD DROP
iptables $WAIT_OPTIONS -P OUTPUT  DROP

ip6tables $WAIT_OPTIONS -P INPUT   DROP
ip6tables $WAIT_OPTIONS -P FORWARD DROP
ip6tables $WAIT_OPTIONS -P OUTPUT  DROP

# These lines are here in case rules are already in place and the
# script is ever rerun on the fly. We want to remove all rules and
# pre-existing user defined chains before we implement new rules.
iptables $WAIT_OPTIONS -F
iptables $WAIT_OPTIONS -X
iptables $WAIT_OPTIONS -Z

iptables $WAIT_OPTIONS -t nat -F
iptables $WAIT_OPTIONS -t nat -X
iptables $WAIT_OPTIONS -t mangle -F
iptables $WAIT_OPTIONS -t mangle -X

ip6tables $WAIT_OPTIONS -F
ip6tables $WAIT_OPTIONS -X
ip6tables $WAIT_OPTIONS -Z

ip6tables $WAIT_OPTIONS -t nat -F
ip6tables $WAIT_OPTIONS -t nat -X
ip6tables $WAIT_OPTIONS -t mangle -F
ip6tables $WAIT_OPTIONS -t mangle -X

#restore ipv4 rules
iptables-restore $WAIT_OPTIONS < /etc/systemd/scripts/ip4save

#restore ipv6 rules
ip6tables-restore $WAIT_OPTIONS < /etc/systemd/scripts/ip6save

# End /etc/systemd/scripts/iptables
