sources:
- archive: vernemq-2.0.1.tar.gz
  archive_sha512sum: e4f1cd4c74d2cb67ab1524a76bdc6071e7b1e38ede574bc11e5ffe861bff99321647be0730f5f17d724dd792aa0fb86d0e9a92417f45bc43fef1461f1f64ae52
  skip_validation: true
  spdx:
    package:
      detailed_description: 'A high-performance, distributed MQTT message broker. '
      home_page: https://github.com/vernemq/vernemq
      license_concluded: Apache-2.0 AND MIT AND BSD-4-Clause AND GPL-1.0-or-later
        AND BSD-3-Clause AND FSFAP-no-warranty-disclaimer AND BSD-2-Clause AND ISC
        AND JSON AND MPL-2.0
      license_declared: Apache-2.0 AND MIT AND BSD-4-Clause AND GPL-1.0-or-later AND
        BSD-3-Clause AND FSFAP-no-warranty-disclaimer AND BSD-2-Clause AND ISC AND
        JSON AND MPL-2.0
      short_summary: VerneMQ is a high-performance, distributed MQTT message broker
      supplier: 'Organization: Broadcom, Inc.'
- archive: vernemq_vendor-2.0.1-rev1.tar.xz
  archive_sha512sum: feaa699595d500de1fab4617539838f1f52ad2b4e590323eed3a4c378afae75b43695e09f6c6ecabf621a188dcbf663e53fb6b6036e642a79c708148e17424a4
  skip_validation: true
  spdx:
    package:
      detailed_description: Contains vendor sources for building vernemq to perform
        offline build
      home_page: https://github.com/vmware/photon
      license_concluded: AGPL-3.0-only AND CAL-1.0 AND LiLiQ-P-1.1 AND GFDL-1.2-no-invariants-or-later
        AND GPL-3.0-only WITH GCC-exception-3.1 AND BSD-3-Clause-No-Military-License
        AND GPL-1.0-only AND BSD-3-Clause AND OGC-1.0 AND GPL-2.0-only WITH Autoconf-exception-2.0
        AND BSD-2-Clause-Views AND CERN-OHL-W-2.0 AND PolyForm-Small-Business-1.0.0
        AND GFDL-1.1-only AND GPL-3.0-only WITH Autoconf-exception-3.0 AND GFDL-1.1-no-invariants-only
        AND CC-BY-SA-2.0 AND CPOL-1.02 AND Parity-6.0.0 AND NAIST-2003 AND BSD-2-Clause-Patent
        AND OFL-1.1-no-RFN AND GPL-3.0-only AND GFDL-1.1-no-invariants-or-later AND
        LGPL-3.0-only AND GFDL-1.1-invariants-or-later AND OGL-UK-3.0 AND OGL-Canada-2.0
        AND CERN-OHL-1.2 AND Parity-7.0.0 AND etalab-2.0 AND Apache-1.1 AND CERN-OHL-S-2.0
        AND CECILL-2.0 AND NTP-0 AND CAL-1.0-Combined-Work-Exception AND TU-Berlin-1.0
        AND LGPL-2.1-or-later AND AGPL-3.0-or-later AND MPL-1.0 AND PSF-2.0 AND LAL-1.3
        AND OGDL-Taiwan-1.0 AND TAPR-OHL-1.0 AND BSD-4-Clause-Shortened AND GFDL-1.2-no-invariants-only
        AND OGL-UK-2.0 AND LiLiQ-Rplus-1.1 AND GPL-2.0-only WITH Font-exception-2.0
        AND GFDL-1.3-no-invariants-or-later AND GFDL-1.2-invariants-only AND GPL-1.0-or-later
        AND copyleft-next-0.3.1 AND BSD-4-Clause AND Zimbra-1.3 AND IBM-pibs AND LGPL-2.0-or-later
        AND MPL-1.1 AND EFL-2.0 AND Interbase-1.0 AND NGPL AND GFDL-1.3-invariants-or-later
        AND EPL-1.0 AND APSL-1.1 AND Zimbra-1.4 AND LGPL-2.1-only AND BSD-2-Clause
        AND MIT AND Frameworx-1.0 AND CDDL-1.0 AND Apache-2.0 AND HPND AND MPL-2.0
        AND CDDL-1.1 AND CECILL-2.1 AND PolyForm-Noncommercial-1.0.0 AND CERN-OHL-P-2.0
        AND GPL-2.0-or-later WITH eCos-exception-2.0 AND AGPL-1.0-only AND ErlPL-1.1
        AND Linux-man-pages-copyleft AND GFDL-1.2-invariants-or-later AND LGPL-3.0-or-later
        AND HPND-sell-variant AND GFDL-1.3-invariants-only AND CC-BY-SA-4.0 AND copyleft-next-0.3.0
        AND CERN-OHL-1.1 AND libselinux-1.0 AND GPL-3.0-or-later AND NIST-PD-fallback
        AND GFDL-1.1-invariants-only AND TMate AND GFDL-1.3-no-invariants-only AND
        AFL-3.0 AND HaskellReport AND TU-Berlin-2.0 AND Spencer-86 AND BSD-4-Clause-UC
        AND CC0-1.0 AND APSL-1.0 AND GPL-2.0-only WITH Bison-exception-2.2 AND FSFAP-no-warranty-disclaimer
        AND GPL-2.0-only AND NCGL-UK-2.0 AND OGL-UK-1.0 AND ISC AND UCL-1.0 AND BSD-3-Clause-Modification
        AND LiLiQ-R-1.1 AND GPL-2.0-only WITH GCC-exception-2.0 AND NIST-PD AND SSPL-1.0
      license_declared: AGPL-3.0-only AND CAL-1.0 AND LiLiQ-P-1.1 AND GFDL-1.2-no-invariants-or-later
        AND GPL-3.0-only WITH GCC-exception-3.1 AND BSD-3-Clause-No-Military-License
        AND GPL-1.0-only AND BSD-3-Clause AND OGC-1.0 AND GPL-2.0-only WITH Autoconf-exception-2.0
        AND BSD-2-Clause-Views AND CERN-OHL-W-2.0 AND PolyForm-Small-Business-1.0.0
        AND GFDL-1.1-only AND GPL-3.0-only WITH Autoconf-exception-3.0 AND GFDL-1.1-no-invariants-only
        AND CC-BY-SA-2.0 AND CPOL-1.02 AND Parity-6.0.0 AND NAIST-2003 AND BSD-2-Clause-Patent
        AND OFL-1.1-no-RFN AND GPL-3.0-only AND GFDL-1.1-no-invariants-or-later AND
        LGPL-3.0-only AND GFDL-1.1-invariants-or-later AND OGL-UK-3.0 AND OGL-Canada-2.0
        AND CERN-OHL-1.2 AND Parity-7.0.0 AND etalab-2.0 AND Apache-1.1 AND CERN-OHL-S-2.0
        AND CECILL-2.0 AND NTP-0 AND CAL-1.0-Combined-Work-Exception AND TU-Berlin-1.0
        AND LGPL-2.1-or-later AND AGPL-3.0-or-later AND MPL-1.0 AND PSF-2.0 AND LAL-1.3
        AND OGDL-Taiwan-1.0 AND TAPR-OHL-1.0 AND BSD-4-Clause-Shortened AND GFDL-1.2-no-invariants-only
        AND OGL-UK-2.0 AND LiLiQ-Rplus-1.1 AND GPL-2.0-only WITH Font-exception-2.0
        AND GFDL-1.3-no-invariants-or-later AND GFDL-1.2-invariants-only AND GPL-1.0-or-later
        AND copyleft-next-0.3.1 AND BSD-4-Clause AND Zimbra-1.3 AND IBM-pibs AND LGPL-2.0-or-later
        AND MPL-1.1 AND EFL-2.0 AND Interbase-1.0 AND NGPL AND GFDL-1.3-invariants-or-later
        AND EPL-1.0 AND APSL-1.1 AND Zimbra-1.4 AND LGPL-2.1-only AND BSD-2-Clause
        AND MIT AND Frameworx-1.0 AND CDDL-1.0 AND Apache-2.0 AND HPND AND MPL-2.0
        AND CDDL-1.1 AND CECILL-2.1 AND PolyForm-Noncommercial-1.0.0 AND CERN-OHL-P-2.0
        AND GPL-2.0-or-later WITH eCos-exception-2.0 AND AGPL-1.0-only AND ErlPL-1.1
        AND Linux-man-pages-copyleft AND GFDL-1.2-invariants-or-later AND LGPL-3.0-or-later
        AND HPND-sell-variant AND GFDL-1.3-invariants-only AND CC-BY-SA-4.0 AND copyleft-next-0.3.0
        AND CERN-OHL-1.1 AND libselinux-1.0 AND GPL-3.0-or-later AND NIST-PD-fallback
        AND GFDL-1.1-invariants-only AND TMate AND GFDL-1.3-no-invariants-only AND
        AFL-3.0 AND HaskellReport AND TU-Berlin-2.0 AND Spencer-86 AND BSD-4-Clause-UC
        AND CC0-1.0 AND APSL-1.0 AND GPL-2.0-only WITH Bison-exception-2.2 AND FSFAP-no-warranty-disclaimer
        AND GPL-2.0-only AND NCGL-UK-2.0 AND OGL-UK-1.0 AND ISC AND UCL-1.0 AND BSD-3-Clause-Modification
        AND LiLiQ-R-1.1 AND GPL-2.0-only WITH GCC-exception-2.0 AND NIST-PD AND SSPL-1.0
      short_summary: Contains vendor sources for building vernemq
      supplier: 'Organization: Broadcom, Inc.'
