sources:
- archive: gnutls-3.7.10.tar.xz
  archive_type: upstream
  archive_sha512sum: 23e0890abd00c433f11c2d4ceb328fe4ac0a0b765de89dff52f16e7d20694a7c61a6acb084d9f58f15c1a9609d70efdac489ac4759963c0ff1d1b8bb7183269e
  name: gnutls-3.7.10
  version: 3.7.10
  url: https://www.gnupg.org/ftp/gcrypt/gnutls/v3.7/gnutls-3.7.10.tar.xz
  repo_url: https://github.com/gnutls/gnutls
  commit_id: 0fe45c03bc206d9fd5ec70998f28699354aedf94
  missing: []
  skip_validation: true
  license_manual_review:
  - archive_path: src/psktool-options.c
    sha256sum: 3ca5976d2c777d73cc8deb6724e89cc108b0e5aaa48468cb90f3e9c218b27995
    spdx_exp: GPL-3.0-or-later
  - archive_path: src/srptool-options.c
    sha256sum: c7a620ae793ae6c0d7e29af57282d249118105653cea1d5164dc24b71ff0bec3
    spdx_exp: GPL-3.0-or-later
  - archive_path: src/systemkey-tool-options.c
    sha256sum: 4a68e2537f78aaf74d4e7b79eed34785e36c42a07a440c11235371539a882350
    spdx_exp: GPL-3.0-or-later
  - archive_path: src/tpmtool-options.c
    sha256sum: ecbc2d923399cc897dacecdcd60576225abec9e4ed5e1c4960c6180dd78d4b82
    spdx_exp: GPL-3.0-or-later
  - archive_path: src/gnutls-cli-debug-options.c
    sha256sum: 729701b488a90fc1e17c4355909ff8c70ba604391b2a55c8710caa7855857262
    spdx_exp: GPL-3.0-or-later
  - archive_path: src/gnutls-serv-options.c
    sha256sum: 26ece20963746d17373633d13242fd5ee5dc50e4976b0ab3c867725a08c9db24
    spdx_exp: GPL-3.0-or-later
  - archive_path: src/gnutls-cli-options.c
    sha256sum: 4854bb6a0044c6ae56fabaa0fc7dcd2417b43dd85ba4e84b5898254d1ebe05ad
    spdx_exp: GPL-3.0-or-later
  - archive_path: src/ocsptool-options.c
    sha256sum: ae0b19f02d24bf02aefd45a094a8cb85c04fd5a18161ec819c1c0939efe77ffb
    spdx_exp: GPL-3.0-or-later
  - archive_path: src/certtool-options.c
    sha256sum: d65635916618188269b6aced3d422702c322b77317755effbab1ccd57745c48b
    spdx_exp: GPL-3.0-or-later
  - archive_path: src/danetool-options.c
    sha256sum: 25b72d181ee318bf5d86b02e8aaf2712c14fc5fc38afd7edd580664e4c775830
    spdx_exp: GPL-3.0-or-later
  - archive_path: src/p11tool-options.c
    sha256sum: 76ae1bb02d3c8885d316dc9a098d00923f7c4b3790b431a72711a6e6db121b51
    spdx_exp: GPL-3.0-or-later
  spdx:
    package:
      detailed_description: 'GnuTLS is a secure communications library implementing
        the SSL, TLS and DTLS protocols and technologies around them. It provides
        a simple C language application programming interface (API) to access the
        secure communications protocols as well as APIs to parse and write X.509,
        PKCS #12, OpenPGP and other required structures. It is aimed to be portable
        and efficient with focus on security and interoperability. '
      home_page: http://www.gnutls.org
      license_concluded: (BSD-3-Clause OR GPL-1.0-or-later) AND (BSD-3-Clause OR GPL-2.0-or-later)
        AND (GPL-2.0-or-later OR LGPL-3.0-or-later) AND AGPL-3.0-or-later AND Apache-2.0
        AND BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND FSFAP AND FSFAP-no-warranty-disclaimer
        AND FSFUL AND FSFULLR AND FSFULLRWD AND GFDL-1.1-or-later AND GFDL-1.3-only
        AND GFDL-1.3-or-later AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later
        AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later
        WITH Libtool-exception AND GPL-3.0-only AND GPL-3.0-or-later AND GPL-3.0-or-later
        WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic
        AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later
        WITH Bison-exception-2.2 AND GPL-3.0-or-later WITH Texinfo-exception AND ISC
        AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later
        AND LGPL-3.0-or-later AND MIT AND X11
      license_declared: (BSD-3-Clause OR GPL-1.0-or-later) AND (BSD-3-Clause OR GPL-2.0-or-later)
        AND (GPL-2.0-or-later OR LGPL-3.0-or-later) AND AGPL-3.0-or-later AND Apache-2.0
        AND BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND FSFAP AND FSFAP-no-warranty-disclaimer
        AND FSFUL AND FSFULLR AND FSFULLRWD AND GFDL-1.1-or-later AND GFDL-1.3-only
        AND GFDL-1.3-or-later AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later
        AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later
        WITH Libtool-exception AND GPL-3.0-only AND GPL-3.0-or-later AND GPL-3.0-or-later
        WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic
        AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later
        WITH Bison-exception-2.2 AND GPL-3.0-or-later WITH Texinfo-exception AND ISC
        AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later
        AND LGPL-3.0-or-later AND MIT AND X11
      short_summary: The GnuTLS Transport Layer Security Library
      supplier: 'Organization: Broadcom, Inc.'
