sources:
- archive: protocol-http1-0.36.0.gem
  archive_sha512sum: a89582b2240de83281bf0aff463b442ab3a54587f5f11f8754dcc803591fe09517a7ed2f8badaafdc2197df0c11fdf42c3a49a891ffcaad76b22d555885471e7
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Provides a low-level implementation of the HTTP/1 protocol. '
      home_page: https://rubygems.org/gems/protocol-http1/versions/0.36.0
      license_concluded: MIT
      license_declared: MIT
      short_summary: A low level implementation of the HTTP/1 protocol.
      supplier: 'Organization: Broadcom, Inc.'
