sources:
- archive: libdrm-2.4.125.tar.xz
  archive_sha512sum: faad141f48a49915c0312eb635df76968f0f4d41bb6851be625a7ae0e24826e7283b5ec9ec3b09ead9a96297bf42221c411288f9b000c3dbc159ed8dde93a7e4
  skip_validation: true
  spdx:
    package:
      detailed_description: 'libdrm provides a user space library for accessing the
        DRM, direct rendering manager, on operating systems that support the ioctl
        interface. libdrm is a low-level library, typically used by graphics drivers
        such as the Mesa DRI drivers, the X drivers, libva and similar projects. '
      home_page: http://dri.freedesktop.org/
      license_concluded: MIT AND GPL-2.0-only AND GPL-2.0-only WITH Linux-syscall-note
        AND BSD-1-Clause
      license_declared: MIT AND GPL-2.0-only AND GPL-2.0-only WITH Linux-syscall-note
        AND BSD-1-Clause
      short_summary: user space library for accessing the DRM.
      supplier: 'Organization: Broadcom, Inc.'
