sources:
- archive: zchunk-1.2.3.tar.gz
  archive_sha512sum: 5e46d8c3e36034de8424937cdfac59acdfaf332203e6e5d8b290614cbbe0340998d53b0583b0ef93189f41dc89219a75f50572757ebcea9abd83bd9aad861a73
  skip_validation: true
  license_manual_review:
  - file_paths:
    - zchunk-1.2.3/test/files/LICENSE.fodt
    sha256sum: 394ed6c2fc4ac47e5ee111a46f2a35b8010a56c7747748216f52105e868d5a3e
    spdx_exp: BSD-2-Clause
  - file_paths:
    - zchunk-1.2.3/test/files/LICENSE.nocomp.fodt.zck
    sha256sum: 8d06d7a8badc83b2f47b4a827013cb1897407cad3fd9ff62fa4c6630de8f813b
    spdx_exp: BSD-2-Clause
  spdx:
    package:
      detailed_description: 'zchunk is a compressed file format that splits the file
        into independent chunks.  This allows you to only download the differences
        when downloading a new version of the file, and also makes zchunk files efficient
        over rsync. zchunk files are protected with strong checksums to verify that
        the file you downloaded is in fact the file you wanted. '
      home_page: https://github.com/zchunk/zchunk
      license_concluded: AGPL-3.0-only AND Apache-2.0 AND BSD-1-Clause AND BSD-2-Clause
        AND BSD-3-Clause AND Bitstream-Vera AND CC-BY-3.0 AND CC-BY-SA-3.0 AND FTL
        AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only
        AND IJG AND ISC AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only
        AND LGPL-2.1-or-later AND LGPL-3.0-only AND LPPL-1.3c AND Libpng AND MIT AND
        MPL-1.0 AND MPL-1.1 AND MPL-2.0 AND MPL-2.0-no-copyleft-exception AND OFL-1.1
        AND OLDAP-2.8 AND OpenSSL AND Python-2.0.1 AND W3C-19980720
      license_declared: AGPL-3.0-only AND Apache-2.0 AND BSD-1-Clause AND BSD-2-Clause
        AND BSD-3-Clause AND Bitstream-Vera AND CC-BY-3.0 AND CC-BY-SA-3.0 AND FTL
        AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only
        AND IJG AND ISC AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only
        AND LGPL-2.1-or-later AND LGPL-3.0-only AND LPPL-1.3c AND Libpng AND MIT AND
        MPL-1.0 AND MPL-1.1 AND MPL-2.0 AND MPL-2.0-no-copyleft-exception AND OFL-1.1
        AND OLDAP-2.8 AND OpenSSL AND Python-2.0.1 AND W3C-19980720
      short_summary: Compressed file format
      supplier: 'Organization: Broadcom, Inc.'
