sources:
- archive: s3fs-fuse-1.97.tar.gz
  archive_sha512sum: 24b70877a5c162252f08e55176a9e9fa2fd380ed3bbe8f51306f0e1489038a80cbd2a07699689431e3294661fa8d0f2434e7fc94cd14e6c9b4b8fa8be2e1f8a7
  archive_type: upstream
  name: s3fs-fuse-1.97
  version: 1.97
  url: https://github.com/s3fs-fuse/s3fs-fuse/archive/refs/tags/v1.97.tar.gz
  repo_url: https://github.com/s3fs-fuse/s3fs-fuse
  commit_id: 0d96734dade0546a949932b56cdb5c8dd5f54e9b
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 's3fs is a FUSE filesystem that allows you to mount an
        Amazon S3 bucket as a local filesystem. It stores files natively and transparently
        in S3 (i.e., you can use other programs to access the same files).'
      home_page: https://github.com/s3fs-fuse/s3fs-fuse
      license_concluded: FSFAP AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-or-later
      license_declared: FSFAP AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-or-later
      short_summary: s3fs allows Linux, macOS, and FreeBSD to mount an S3 bucket via
        FUSE
      supplier: 'Organization: Broadcom, Inc.'
