sources:
- archive: xz-5.4.0.tar.xz
  archive_sha512sum: 29b2cd25bb5b234b329ffe9547692d2c29be393db9d8d4ce70a66dfdaebd54433e79a89d80c57e58cd4559c3c68b9845507d5fedf3eec1c528a81e3d9ddbd811
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The Xz package contains programs for compressing and
        decompressing files '
      home_page: http://tukaani.org/xz
      license_concluded: GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND LGPL-2.1-or-later AND GPL-3.0-or-later
        AND X11 AND GPL-2.0-or-later WITH Libtool-exception AND GPL-2.0-only AND GPL-2.0-or-later
        AND FSFUL AND GPL-2.0-or-later WITH Autoconf-exception-generic AND MIT AND
        GPL-3.0-only AND BSD-3-Clause AND FSFULLR AND FSFULLRWD AND LGPL-2.1-only
        AND FSFAP
      license_declared: GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND LGPL-2.1-or-later AND GPL-3.0-or-later
        AND X11 AND GPL-2.0-or-later WITH Libtool-exception AND GPL-2.0-only AND GPL-2.0-or-later
        AND FSFUL AND GPL-2.0-or-later WITH Autoconf-exception-generic AND MIT AND
        GPL-3.0-only AND BSD-3-Clause AND FSFULLR AND FSFULLRWD AND LGPL-2.1-only
        AND FSFAP
      short_summary: Programs for compressing and decompressing files
      supplier: 'Organization: Broadcom, Inc.'
