sources:
- archive: rpm-6.1.0.tar.bz2
  archive_sha512sum: e07324fd7b32f650713edd904801c77fa0796f72b53bec863ad7d332f3ad5897a67840ec0c1a84ce1e67ef2fdd69dff17ad72e0601c07bba7b4e7798cd9af77a
  archive_type: upstream
  name: rpm-6.1.0
  version: 6.1.0
  url: https://github.com/rpm-software-management/rpm/releases/download/rpm-6.1.0-release/rpm-6.1.0.tar.bz2
  repo_url: https://github.com/rpm-software-management/rpm
  commit_id: f832c7e69945248dd5bcfcacfd10c176ee300fa2
  skip_list: []
  missing: ['*.po', ChangeLog, rpm.pot, vi.po, zh_TW.po, README, POTFILES.in, Makevars, CMakeLists.txt, LINGUAS]
  spdx:
    package:
      detailed_description: 'RPM package manager'
      home_page: http://rpm.org
      license_concluded: LGPL-2.1-or-later AND DOC AND GPL-2.0-only AND FSFULLRWD
        AND (GPL-1.0-or-later OR LGPL-2.0-or-later) AND BSD-3-Clause AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND MIT AND GPL-3.0-only AND X11 AND LGPL-2.0-only
        AND LGPL-2.0-or-later AND CC-BY-2.5 AND Apache-1.0 AND (GPL-2.0-only OR LGPL-2.0-only)
        AND CC0-1.0 AND GPL-2.0-or-later AND FSFAP AND GPL-1.0-or-later AND (GPL-2.0-only
        OR MIT) AND FSFUL AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        FSFULLR AND GPL-2.0-or-later WITH Libtool-exception
      license_declared: LGPL-2.1-or-later AND DOC AND GPL-2.0-only AND FSFULLRWD AND
        (GPL-1.0-or-later OR LGPL-2.0-or-later) AND BSD-3-Clause AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND MIT AND GPL-3.0-only AND X11 AND LGPL-2.0-only
        AND LGPL-2.0-or-later AND CC-BY-2.5 AND Apache-1.0 AND (GPL-2.0-only OR LGPL-2.0-only)
        AND CC0-1.0 AND GPL-2.0-or-later AND FSFAP AND GPL-1.0-or-later AND (GPL-2.0-only
        OR MIT) AND FSFUL AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        FSFULLR AND GPL-2.0-or-later WITH Libtool-exception
      short_summary: Package manager
      supplier: 'Organization: Broadcom, Inc.'
