sources:
- archive: rpm-6.0.1.tar.bz2
  archive_sha512sum: 55a03b6c65c6bd009ce824feb6298d305eb497464d860aa92ccdf15bcea9af0e2dd70e9ac4b26a8494a222656201314dc1c7a245d9cb5416b058f66f8276f4e9
  archive_type: upstream
  name: rpm-6.0.1
  version: 6.0.1
  url: https://github.com/rpm-software-management/rpm/releases/download/rpm-6.0.1-release/rpm-6.0.1.tar.bz2
  repo_url: https://github.com/rpm-software-management/rpm
  commit_id: 58a917a6c5e24e9e8a01976c17d2eee06249b9b6
  skip_list: []
  missing: [ka.po, kw.po, ChangeLog, el.po, cmn.po, es.po, sr@latin.po, nl.po, rpm.pot, vi.po, zh_TW.po, README, tr.po, da.po, eo.po, ms.po, pt_BR.po, te.po, ja.po, POTFILES.in, nb.po, sr.po, he.po, zh_CN.po, Makevars, it.po, pl.po, CMakeLists.txt, ca.po, gu.po, ar.po, si.po, sv.po, is.po, id.po, de.po, cs.po, pa.po, LINGUAS, pt.po, uk.po, sk.po, fi.po, ko.po, fr.po, ie.po, ro.po, ru.po, sl.po, br.po]
  spdx:
    package:
      detailed_description: 'RPM package manager'
      home_page: http://rpm.org
      license_concluded: LGPL-2.1-or-later AND DOC AND GPL-2.0-only AND FSFULLRWD
        AND (GPL-1.0-or-later OR LGPL-2.0-or-later) AND BSD-3-Clause AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND MIT AND GPL-3.0-only AND X11 AND LGPL-2.0-only
        AND LGPL-2.0-or-later AND CC-BY-2.5 AND Apache-1.0 AND (GPL-2.0-only OR LGPL-2.0-only)
        AND CC0-1.0 AND GPL-2.0-or-later AND FSFAP AND GPL-1.0-or-later AND (GPL-2.0-only
        OR MIT) AND FSFUL AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        FSFULLR AND GPL-2.0-or-later WITH Libtool-exception
      license_declared: LGPL-2.1-or-later AND DOC AND GPL-2.0-only AND FSFULLRWD AND
        (GPL-1.0-or-later OR LGPL-2.0-or-later) AND BSD-3-Clause AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND MIT AND GPL-3.0-only AND X11 AND LGPL-2.0-only
        AND LGPL-2.0-or-later AND CC-BY-2.5 AND Apache-1.0 AND (GPL-2.0-only OR LGPL-2.0-only)
        AND CC0-1.0 AND GPL-2.0-or-later AND FSFAP AND GPL-1.0-or-later AND (GPL-2.0-only
        OR MIT) AND FSFUL AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        FSFULLR AND GPL-2.0-or-later WITH Libtool-exception
      short_summary: Package manager
      supplier: 'Organization: Broadcom, Inc.'
