sources:
- archive: firefox-140.7.0esr.source.tar.xz
  archive_sha512sum: 7781b1e203130c1cdf2a0c2ecb05a9cfa824c75d467e7faca78b66bd5568c821324112aecb774883d9f447af7fa4ade36488ff1017255af5510c8f641990e472
  archive_type: upstream
  skip_validation: false
  name: firefox-140.7.0
  version: "140.7.0"
  url: https://ftp.mozilla.org/pub/firefox/releases/140.7.0esr/source/firefox-140.7.0esr.source.tar.xz
  repo_url: https://github.com/mozilla-firefox/firefox
  commit_id: 73462f0ff623648c49b17892d06fab955d6a6ee1
  missing: ['.hgrc', '.hgtags', '.hgempty', '.hg-annotate-ignore-revs', '.gitkeep', '.cvsignore', '.gitmodules', '.hgignore', 'sourcestamp.txt', '.gitattributes']
  spdx:
    package:
      detailed_description: 'SpiderMonkey is the code-name for Mozilla Firefox''s
        C++ implementation of JavaScript. It is intended to be embedded in other applications
        that provide host environments for JavaScript. '
      home_page: https://spidermonkey.dev
      license_concluded: (AFL-2.1 OR BSD-3-Clause) AND (Apache-2.0 OR Apache-2.0 WITH
        LLVM-exception OR MIT) AND (Apache-2.0 OR BSD-2-Clause) AND (Apache-2.0 OR
        BSD-3-Clause) AND (Apache-2.0 OR MIT) AND (Apache-2.0 OR MIT) AND (BSD-2-Clause
        OR GPL-2.0-only) AND (BSD-3-Clause OR GPL-1.0-or-later OR MIT) AND (BSD-3-Clause
        OR GPL-1.0-or-later) AND (BSD-3-Clause OR GPL-2.0-only OR MIT) AND (BSD-3-Clause
        OR GPL-2.0-only) AND (BSD-3-Clause OR MIT) AND (FTL OR GPL-3.0-only) AND (GPL-2.0-only
        OR LGPL-2.1-only OR MPL-1.1) AND (GPL-2.0-only OR MIT) AND (GPL-2.0-only OR
        MPL-2.0) AND (GPL-2.0-or-later OR LGPL-2.1-or-later OR MPL-1.1) AND (GPL-2.0-or-later
        OR LGPL-2.1-or-later OR MPL-1.1) AND (GPL-2.0-or-later OR MIT) AND (GPL-2.0-or-later
        OR MIT) AND (GPL-3.0-only OR MIT) AND (LGPL-2.1-only OR MPL-1.1) AND (LGPL-2.1-only
        OR MPL-1.1) AND (MIT OR NCSA) AND (MIT OR Unlicense) AND 0BSD AND AFL-2.1
        AND AFL-3.0 AND APSL-2.0 AND Apache-2.0 AND Apache-2.0 WITH LLVM-exception
        AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND BSD-3-Clause-Clear
        AND BSD-3-Clause-No-Nuclear-Warranty AND BSD-4-Clause AND BSD-4-Clause-Shortened
        AND BSD-4-Clause-UC AND BSD-Protection AND BSD-Source-Code AND BSL-1.0 AND
        Beerware AND Bitstream-Vera AND CC-BY-3.0 AND CC-BY-4.0 AND CC-BY-NC-4.0 AND
        CC-BY-NC-ND-2.5 AND CC-BY-NC-ND-3.0 AND CC-BY-NC-ND-4.0 AND CC-BY-NC-SA-2.0
        AND CC-BY-NC-SA-4.0 AND CC-BY-ND-3.0 AND CC-BY-SA-3.0 AND CC-BY-SA-4.0 AND
        CC-PDDC AND CC0-1.0 AND CMU-Mach AND CPL-1.0 AND ClArtistic AND DOC AND FSFAP
        AND FSFAP-no-warranty-disclaimer AND FSFUL AND FSFULLR AND FSFULLRWD AND FTL
        AND FTL WITH Autoconf-exception-generic AND GFDL-1.1-or-later AND GPL-1.0-or-later
        AND GPL-1.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-only AND
        GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Libtool-exception
        AND GPL-3.0-only AND GPL-3.0-or-later AND GPL-3.0-or-later WITH Autoconf-exception-2.0
        AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-macro AND GPL-3.0-or-later WITH Bison-exception-2.2
        AND GPL-3.0-or-later WITH Font-exception-2.0 AND GPL-3.0-or-later WITH Libtool-exception
        AND GPL-3.0-or-later WITH Texinfo-exception AND HPND AND HPND-sell-variant
        AND ICU AND IJG AND ISC AND JPNIC AND LGPL-2.0-or-later AND LGPL-2.0-or-later
        WITH WxWindows-exception-3.1 AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only
        AND LGPL-3.0-or-later AND LPPL-1.3a AND LPPL-1.3c AND LZMA-SDK-9.22 AND Libpng
        AND MIT AND MIT-CMU AND MIT-Khronos-old AND MIT-Modern-Variant AND MIT-Wu
        AND MIT-open-group AND MIT-testregex AND MPL-1.0 AND MPL-1.1 AND MPL-2.0 AND
        MPL-2.0-no-copyleft-exception AND NAIST-2003 AND NCL AND NCSA AND NTP AND
        NTP-0 AND OFL-1.0 AND OFL-1.1 AND OLDAP-2.8 AND PSF-2.0 AND Python-2.0 AND
        Spencer-94 AND SunPro AND TMate AND TU-Berlin-1.0 AND Unicode-3.0 AND Unicode-DFS-2016
        AND Unicode-TOU AND Unlicense AND Vim AND W3C AND W3C-19980720 AND W3C-20150513
        AND WTFPL AND X11 AND Zlib AND blessing AND bzip2-1.0.6 AND curl AND dtoa
        AND mplus AND pkgconf
      license_declared: (AFL-2.1 OR BSD-3-Clause) AND (Apache-2.0 OR Apache-2.0 WITH
        LLVM-exception OR MIT) AND (Apache-2.0 OR BSD-2-Clause) AND (Apache-2.0 OR
        BSD-3-Clause) AND (Apache-2.0 OR MIT) AND (Apache-2.0 OR MIT) AND (BSD-2-Clause
        OR GPL-2.0-only) AND (BSD-3-Clause OR GPL-1.0-or-later OR MIT) AND (BSD-3-Clause
        OR GPL-1.0-or-later) AND (BSD-3-Clause OR GPL-2.0-only OR MIT) AND (BSD-3-Clause
        OR GPL-2.0-only) AND (BSD-3-Clause OR MIT) AND (FTL OR GPL-3.0-only) AND (GPL-2.0-only
        OR LGPL-2.1-only OR MPL-1.1) AND (GPL-2.0-only OR MIT) AND (GPL-2.0-only OR
        MPL-2.0) AND (GPL-2.0-or-later OR LGPL-2.1-or-later OR MPL-1.1) AND (GPL-2.0-or-later
        OR LGPL-2.1-or-later OR MPL-1.1) AND (GPL-2.0-or-later OR MIT) AND (GPL-2.0-or-later
        OR MIT) AND (GPL-3.0-only OR MIT) AND (LGPL-2.1-only OR MPL-1.1) AND (LGPL-2.1-only
        OR MPL-1.1) AND (MIT OR NCSA) AND (MIT OR Unlicense) AND 0BSD AND AFL-2.1
        AND AFL-3.0 AND APSL-2.0 AND Apache-2.0 AND Apache-2.0 WITH LLVM-exception
        AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND BSD-3-Clause-Clear
        AND BSD-3-Clause-No-Nuclear-Warranty AND BSD-4-Clause AND BSD-4-Clause-Shortened
        AND BSD-4-Clause-UC AND BSD-Protection AND BSD-Source-Code AND BSL-1.0 AND
        Beerware AND Bitstream-Vera AND CC-BY-3.0 AND CC-BY-4.0 AND CC-BY-NC-4.0 AND
        CC-BY-NC-ND-2.5 AND CC-BY-NC-ND-3.0 AND CC-BY-NC-ND-4.0 AND CC-BY-NC-SA-2.0
        AND CC-BY-NC-SA-4.0 AND CC-BY-ND-3.0 AND CC-BY-SA-3.0 AND CC-BY-SA-4.0 AND
        CC-PDDC AND CC0-1.0 AND CMU-Mach AND CPL-1.0 AND ClArtistic AND DOC AND FSFAP
        AND FSFAP-no-warranty-disclaimer AND FSFUL AND FSFULLR AND FSFULLRWD AND FTL
        AND FTL WITH Autoconf-exception-generic AND GFDL-1.1-or-later AND GPL-1.0-or-later
        AND GPL-1.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-only AND
        GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-2.0 AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Libtool-exception
        AND GPL-3.0-only AND GPL-3.0-or-later AND GPL-3.0-or-later WITH Autoconf-exception-2.0
        AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-macro AND GPL-3.0-or-later WITH Bison-exception-2.2
        AND GPL-3.0-or-later WITH Font-exception-2.0 AND GPL-3.0-or-later WITH Libtool-exception
        AND GPL-3.0-or-later WITH Texinfo-exception AND HPND AND HPND-sell-variant
        AND ICU AND IJG AND ISC AND JPNIC AND LGPL-2.0-or-later AND LGPL-2.0-or-later
        WITH WxWindows-exception-3.1 AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only
        AND LGPL-3.0-or-later AND LPPL-1.3a AND LPPL-1.3c AND LZMA-SDK-9.22 AND Libpng
        AND MIT AND MIT-CMU AND MIT-Khronos-old AND MIT-Modern-Variant AND MIT-Wu
        AND MIT-open-group AND MIT-testregex AND MPL-1.0 AND MPL-1.1 AND MPL-2.0 AND
        MPL-2.0-no-copyleft-exception AND NAIST-2003 AND NCL AND NCSA AND NTP AND
        NTP-0 AND OFL-1.0 AND OFL-1.1 AND OLDAP-2.8 AND PSF-2.0 AND Python-2.0 AND
        Spencer-94 AND SunPro AND TMate AND TU-Berlin-1.0 AND Unicode-3.0 AND Unicode-DFS-2016
        AND Unicode-TOU AND Unlicense AND Vim AND W3C AND W3C-19980720 AND W3C-20150513
        AND WTFPL AND X11 AND Zlib AND blessing AND bzip2-1.0.6 AND curl AND dtoa
        AND mplus AND pkgconf
      short_summary: SpiderMonkey JavaScript library
      supplier: 'Organization: Broadcom, Inc.'
  license_manual_review:
  - file_paths:
    - firefox-102.12.0/third_party/rust/ryu/README.md
    sha256sum: 91f2433b0f7134b35703c316a73e145f23d9a44c6e340eb971a72d0a4a87eea8
    spdx_exp: Apache-2.0 OR BSL-1.0
  - file_paths:
    - firefox-102.12.0/third_party/rust/ryu/src/lib.rs
    sha256sum: 2ec3fb787f11a492e5d82c90ada3c2ea89c1880ffd281f4e02f769a30cf6e140
    spdx_exp: ''
  - file_paths:
    - firefox-102.12.0/third_party/jpeg-xl/lib/jxl/color_management.cc
    sha256sum: c3142c72b516a803e06cd0bfa1320b6a5f4fab7d0c0b16ee1c867df324d36ca7
    spdx_exp: ''
    # This filename has some unencodable unicode chars which is causing failure in scancode command
    # so ignoring this file for scaning. It has nothing to do with copyleft license.
  - file_paths:
    - "firefox-102.12.0/modules/libjar/test/unit/data/test_umlaute.zip-extract/test_\uDCFC\
      .txt"
    sha256sum: 0c85dcbb13f73eabef6dcf5ee4e59c5a2a67682a0ee8af6185465c4c1221a881
    spdx_exp: ''
    # This file is licensed as MPL-2.0 but has all the license content in it.
    # so it is not licensed as copyleft license
  - file_paths:
    - firefox-102.12.0/toolkit/content/license.html
    sha256sum: f623a668d482c8c3bc158e5a6c3a6e104b94a3e58319c941de073487dc5fea03
    spdx_exp: ''
