sources:
- archive: meson-1.3.2.tar.gz
  archive_sha512sum: b44c28bb8d5ca955b74d64c13b845adfeed814afd92d15ecc8cedb0674932063972644b7fba3a1e60aa76ff2ecea8ab40108a8210ff3698900215342096f35d2
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Meson is an open source build system meant to be both
        extremely fast, and, even more importantly, as user friendly as possible.
        The main design point of Meson is that every moment a developer spends writing
        or debugging build definitions is a second wasted. So is every second spent
        waiting for the build system to actually start compiling code. '
      home_page: https://mesonbuild.com
      license_concluded: GPL-2.0-or-later AND GPL-1.0-or-later AND GPL-2.0-only AND
        MIT AND BSD-3-Clause AND BSL-1.0 AND Apache-2.0 AND CC-BY-SA-4.0 AND Vim AND
        CC0-1.0 AND FSFAP
      license_declared: GPL-2.0-or-later AND GPL-1.0-or-later AND GPL-2.0-only AND
        MIT AND BSD-3-Clause AND BSL-1.0 AND Apache-2.0 AND CC-BY-SA-4.0 AND Vim AND
        CC0-1.0 AND FSFAP
      short_summary: Extremely fast and user friendly build system
      supplier: 'Organization: Broadcom, Inc.'
