sources:
- archive: meson-1.4.2.tar.gz
  archive_sha512sum: 4aed1a5f133de2c6839bab361a0e911dd5697f5dac2a8f100df69d43a8880a810dcfa1aa6402cdfb9c5e14fdceec76925f0496c301c31ba733a32618c403eaf0
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Meson is an open source build system meant to be both
        extremely fast, and, even more importantly, as user friendly as possible.
        The main design point of Meson is that every moment a developer spends writing
        or debugging build definitions is a second wasted. So is every second spent
        waiting for the build system to actually start compiling code. '
      home_page: https://mesonbuild.com
      license_concluded: Apache-2.0 AND BSD-3-Clause AND BSL-1.0 AND CC-BY-SA-4.0
        AND CC0-1.0 AND FSFAP AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later
        AND MIT AND Vim
      license_declared: Apache-2.0 AND BSD-3-Clause AND BSL-1.0 AND CC-BY-SA-4.0 AND
        CC0-1.0 AND FSFAP AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later
        AND MIT AND Vim
      short_summary: Extremely fast and user friendly build system
      supplier: 'Organization: Broadcom, Inc.'
