sources:
- archive: Vulkan-Headers-1.4.358.tar.gz
  archive_type: upstream
  archive_sha512sum: c01bcd042f72df3db59fe551773599c6951df17ca656fa6a3bb50eb50a16dabcacdb4dea4c6ca4125b10b291f7c9156c5ffd875b003be425a2b3773cec2cf58e
  name: "Vulkan-Headers-1.4.358"
  version: 1.4.358
  url: https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v1.4.358.tar.gz
  repo_url: https://github.com/KhronosGroup/Vulkan-Headers.git
  commit_id: 43711cfe7d642355a20af7c0a850ef4de88bcb60
  skip_list: []
  missing: []
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Vulkan Header files and API registry '
      home_page: https://github.com/KhronosGroup/Vulkan-Headers
      license_concluded: Apache-2.0 AND (Apache-2.0 OR MIT) AND BSD-3-Clause
      license_declared: Apache-2.0 AND (Apache-2.0 OR MIT) AND BSD-3-Clause
      short_summary: Vulkan Header files and API registry
      supplier: 'Organization: Broadcom, Inc.'
