sources:
- archive: kubernetes-dns-1.22.23.tar.gz
  archive_sha512sum: ee745d1695784d620ab1d8c254265f1522ad655de3d8c4886bb219ded1eff2c52189770d756aa8b60d9dfd8136f3887b29230829f888ddc6aa228f47e564f94a
  skip_validation: true
  spdx:
    package:
      detailed_description: Kubernetes DNS is a name lookup service for kubernetes pods.
      home_page: https://github.com/kubernetes/dns/archive/1.22.20.tar.gz
      license_concluded: (Apache-2.0 OR BSD-3-Clause) AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT
      license_declared: (Apache-2.0 OR BSD-3-Clause) AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT
      short_summary: Kubernetes DNS
      supplier: 'Organization: Broadcom, Inc.'
