sources:
- archive: remote_syslog_sender-1.2.3.gem
  archive_sha512sum: e88c0335db2c0223b5f61899ebe441a06ba8a34eb6ca966ed84c18ee39610dd360fd72f39b664d5edd32e5a5f4b45b66f2c4395f59f3c6a14d054136c330b6e0
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Message sender that sends directly to a remote syslog
        endpoint (Support UDP, TCP, TCP+TLS) '
      home_page: https://rubygems.org/gems/remote_syslog_sender/versions/1.2.3
      license_concluded: MIT
      license_declared: MIT
      short_summary: Message sender that sends directly to a remote syslog endpoint
        (Support UDP, TCP, TCP+TLS)
      supplier: 'Organization: Broadcom, Inc.'
