sources:
- archive: unbound-1.26.1.tar.gz
  archive_sha512sum: f0ed03059b265d87d5d8cfc7f552f7d335c266056b5a0dd92597a326c2164193206d7dc38aa2be91b9fde5178a468dbbdad1a0e347c146618c0c8817ae1641e1
  archive_type: upstream
  name: unbound-release-1.26.1
  version: 1.26.1
  url: https://github.com/NLnetLabs/unbound/archive/refs/tags/release-1.26.1.tar.gz
  repo_url: https://github.com/NLnetLabs/unbound
  commit_id: 13b6717f1716810523ffb60f971a6c9c5e8ce127
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'Unbound is a validating, recursive, and caching DNS resolver.'
      home_page: http://www.unbound.net
      license_concluded: CC0-1.0 AND FSFULLR AND ISC AND HPND AND MIT AND GPL-3.0-or-later
        AND BSD-3-Clause AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        DOC AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH
        Bison-exception-2.2 AND GPL-3.0-or-later WITH Libtool-exception AND GPL-2.0-or-later
        WITH Autoconf-exception-macro AND FSFULLRWD AND BSD-2-Clause AND GPL-3.0-or-later
        WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND FSFUL AND Apache-2.0 AND X11
      license_declared: CC0-1.0 AND FSFULLR AND ISC AND HPND AND MIT AND GPL-3.0-or-later
        AND BSD-3-Clause AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        DOC AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH
        Bison-exception-2.2 AND GPL-3.0-or-later WITH Libtool-exception AND GPL-2.0-or-later
        WITH Autoconf-exception-macro AND FSFULLRWD AND BSD-2-Clause AND GPL-3.0-or-later
        WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND FSFUL AND Apache-2.0 AND X11
      short_summary: unbound dns server
      supplier: 'Organization: Broadcom, Inc.'
