sources:
- archive: btrfs-progs-v7.0.tar.xz
  archive_sha512sum: f6fc13f16a1f170eacbcb53efb2e5a86e89c73fd797fc8d9a419b7024f5a13a788cd92e0caa41964e7716d8bccc24ce4b8a5e3b3861d85c793642021c5b03791
  archive_type: upstream
  name: btrfs-progs-v7.0
  version: 7.0
  url: https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v7.0.tar.xz
  repo_url: https://github.com/kdave/btrfs-progs
  commit_id: 9c5987432906daebde23f9703c0f6f90c35fa9da
  skip_list: []
  missing: ['*.8', '*.5', install-sh, config.guess, config.sub, config.h.in, btrfs-ioctl.2, configure]
  spdx:
    package:
      detailed_description: 'The btrfs-progs package provides all the userspace programs
        needed to create, check, modify and correct any inconsistencies in the btrfs
        filesystem.'
      home_page: http://btrfs.wiki.kernel.org/index.php/Main_Page
      license_concluded: (Apache-2.0 OR CC0-1.0 OR OpenSSL) AND (GPL-2.0-only OR Linux-OpenIB) AND (GPL-2.0-only OR MIT) AND BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND FSFAP AND FSFUL AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-or-later AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-or-later AND X11
      license_declared: (Apache-2.0 OR CC0-1.0 OR OpenSSL) AND (GPL-2.0-only OR Linux-OpenIB) AND (GPL-2.0-only OR MIT) AND BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND FSFAP AND FSFUL AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-or-later AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-or-later AND X11
      short_summary: Userspace programs for btrfs
      supplier: 'Organization: Broadcom, Inc.'
