sources:
- archive: iniconfig-2.3.0.tar.gz
  archive_sha512sum: 65f9200c904fae6d4691823a8c1c7af7d80d91438db47a6fa84a7688d0b95c73b65702a9ada16383a6c2036438b657b9981d2fcffbe6bbb5ed744b54557094eb
  archive_type: upstream
  name: iniconfig-2.3.0
  version: 2.3.0
  url: https://github.com/pytest-dev/iniconfig/releases/download/v2.3.0/iniconfig-2.3.0.tar.gz
  repo_url: https://github.com/pytest-dev/iniconfig
  commit_id: 7faed13ae50bad7c5da3f5782f254a8a7736bb84
  skip_list: []
  missing: [setup.cfg, _version.py, PKG-INFO, iniconfig.egg-info]
  spdx:
    package:
      detailed_description: "iniconfig is a small and simple INI-file parser module\
        \ having a unique set of features:  1. tested against Python2.4 across to\
        \ Python3.2, Jython, PyPy 2. maintains order of sections and entries 3. supports\
        \ multi-line values with or without line-continuations 4. supports \u201C\
        #\u201D comments everywhere 5. raises errors with proper line-numbers 6. no\
        \ bells and whistles like automatic substitutions 7. iniconfig raises an Error\
        \ if two sections have the same name. "
      home_page: http://github.com/RonnyPfannschmidt/iniconfig
      license_concluded: MIT
      license_declared: MIT
      short_summary: 'iniconfig: brain-dead simple config-ini parsing'
      supplier: 'Organization: Broadcom, Inc.'
