sources:
- archive: hwdata-0.405.tar.gz
  archive_type: upstream
  archive_sha512sum: a6e68c70a438eeabd8c733e1fe34ff3147c5fb2e4d7da41ba0c0041aee9aa8b88240631fc292c41caeaf663a384a148c28a08efad8c646d702060eac6768b7d1
  name: "hwdata-0.405"
  version: 0.405
  url: https://github.com/vcrhonek/hwdata/archive/refs/tags/v0.405.tar.gz
  repo_url: https://github.com/vcrhonek/hwdata.git
  commit_id: be46d7186e918e62eb75de399e800145a781c8db
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'Hardware identification and configuration data'
      home_page: https://github.com/vcrhonek/hwdata
      license_concluded: (Apache-2.0 OR MIT) AND (GPL-2.0-only OR MIT) AND (GPL-2.0-only WITH Linux-syscall-note OR MIT) AND (MIT OR Unlicense) AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSL-1.0 AND CC0-1.0 AND GPL-1.0-only AND GPL-1.0-or-later AND GPL-1.0-or-later WITH Linux-syscall-note AND GPL-2.0-only AND GPL-2.0-only WITH Linux-syscall-note AND GPL-2.0-or-later AND HPND AND HPND-sell-variant AND ICU AND ISC AND LGPL-2.1-only AND LGPL-2.1-or-later AND MIT AND MIT-Khronos-old AND NCSA AND SGI-B-2.0 AND X11
      license_declared: (Apache-2.0 OR MIT) AND (GPL-2.0-only OR MIT) AND (GPL-2.0-only WITH Linux-syscall-note OR MIT) AND (MIT OR Unlicense) AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSL-1.0 AND CC0-1.0 AND GPL-1.0-only AND GPL-1.0-or-later AND GPL-1.0-or-later WITH Linux-syscall-note AND GPL-2.0-only AND GPL-2.0-only WITH Linux-syscall-note AND GPL-2.0-or-later AND HPND AND HPND-sell-variant AND ICU AND ISC AND LGPL-2.1-only AND LGPL-2.1-or-later AND MIT AND MIT-Khronos-old AND NCSA AND SGI-B-2.0 AND X11
      short_summary: Mesa is an OpenGL compatible 3D graphics library.
      supplier: 'Organization: Broadcom, Inc.'
