sources:
- archive: pywbem-1.9.0.tar.gz
  archive_sha512sum: 2e2e870588e7587da2558c79c4037736c1362195d8dbfc83a5dff6d0a287a0fbf93f9d3aeb26a50395f723b62f232bb589c65fbbb854a0e1e79a7859a3f6e2d6
  archive_type: upstream
  skip_validation: false
  name: pywbem-1.9.0
  version: "1.9.0"
  url: https://github.com/pywbem/pywbem/archive/refs/tags/1.9.0.tar.gz
  repo_url: https://github.com/pywbem/pywbem
  commit_id: 50b9ae780cc5a74f35fa9b205540cc35b2cdd697
  missing: []
  spdx:
    package:
      detailed_description: 'PyWBEM is a Python library for making CIM operations
        over HTTP using the WBEM CIM-XML protocol.  WBEM is a manageability protocol,
        like SNMP, standardised by the Distributed Management Task Force (DMTF) available
        at http://www.dmtf.org/standards/wbem. '
      home_page: http://pywbem.sourceforge.net
      license_concluded: LGPL-2.1-only AND LGPL-2.0-or-later AND LGPL-2.1-or-later
      license_declared: LGPL-2.1-only AND LGPL-2.0-or-later AND LGPL-2.1-or-later
      short_summary: Python WBEM Client
      supplier: 'Organization: Broadcom, Inc.'
