sources:
- archive: openssl-3.0.18.tar.gz
  archive_type: upstream
  archive_sha512sum: 6bdd16f33b83ae2a12777230c4ff00d0595bbc00253ac8c3ac31e1375e818fc74d7f491bd2e507ff33cab9f0498cfb28fa8690f75a98663568d40901523cdf3c
  version: 3.0.18
  name: openssl-3.0.18
  url: https://github.com/openssl/openssl/releases/download/openssl-3.0.18/openssl-3.0.18.tar.gz
  repo_url: https://github.com/openssl/openssl
  commit_id: c10e643222ce5a185f2980d7352d545afacb0fed
  missing:
  - .github
  - gost-engine
  - .gitmodules
  - pyca-cryptography
  - 90-team.norelease.conf
  - mktar.sh
  - krb5
  - .gitignore
  - .gitattributes
  - corpora
  - dev
  spdx:
    package:
      detailed_description: 'The OpenSSL package contains management tools and libraries
        relating to cryptography. These are useful for providing cryptography functions
        to other packages, such as OpenSSH, email applications and web browsers (for
        accessing HTTPS sites). '
      home_page: http://www.openssl.org
      license_concluded: (Artistic-1.0 OR GPL-1.0-or-later) AND (Artistic-1.0-Perl
        OR GPL-1.0-or-later) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (BSD-2-Clause
        OR OpenSSL) AND (BSD-3-Clause OR GPL-1.0-or-later OR GPL-2.0-only OR OpenSSL)
        AND (BSD-3-Clause OR GPL-1.0-or-later OR OpenSSL) AND (BSD-3-Clause OR GPL-2.0-or-later
        OR LGPL-2.1-or-later OR MPL-1.1) AND (BSD-3-Clause OR OpenSSL) AND Apache-2.0
        AND Artistic-1.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-Source-Code AND
        CC0-1.0 AND GPL-1.0-only AND OpenSSL AND snprintf
      license_declared: (Artistic-1.0 OR GPL-1.0-or-later) AND (Artistic-1.0-Perl
        OR GPL-1.0-or-later) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (BSD-2-Clause
        OR OpenSSL) AND (BSD-3-Clause OR GPL-1.0-or-later OR GPL-2.0-only OR OpenSSL)
        AND (BSD-3-Clause OR GPL-1.0-or-later OR OpenSSL) AND (BSD-3-Clause OR GPL-2.0-or-later
        OR LGPL-2.1-or-later OR MPL-1.1) AND (BSD-3-Clause OR OpenSSL) AND Apache-2.0
        AND Artistic-1.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-Source-Code AND
        CC0-1.0 AND GPL-1.0-only AND OpenSSL AND snprintf
      short_summary: Management tools and libraries relating to cryptography
      supplier: 'Organization: Broadcom, Inc.'
- archive: openssl-3.1.2.tar.gz
  archive_type: upstream
  archive_sha512sum: c48ad86265b0fee18b23863b645a286d131a863a3418c7d2ed6c819eebb822ad0f2985ba3ecbf4def32515442f0eb40aba08f3146d113247e86ec80fbddca1c1
  version: 3.1.2
  name: openssl-openssl-3.1.2
  url: https://github.com/openssl/openssl/archive/refs/tags/openssl-3.1.2.tar.gz
  repo_url: https://github.com/openssl/openssl
  commit_id: 17a2c5111864d8e016c5f2d29c40a3746b559e9d
  missing:
  - .github
  - .gitattributes
  - .gitmodules
  - mktar.sh
  - gost-engine
  - corpora
  - krb5
  - pyca-cryptography
  - .gitignore
  - dev
  spdx:
    package:
      detailed_description: 'Fips library for enabling fips. '
      home_page: http://www.openssl.org
      license_concluded: (Artistic-1.0 OR GPL-1.0-or-later) AND (Artistic-1.0-Perl
        OR GPL-1.0-or-later) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (BSD-2-Clause
        OR OpenSSL) AND (BSD-3-Clause OR GPL-1.0-or-later OR GPL-2.0-only OR OpenSSL)
        AND (BSD-3-Clause OR GPL-1.0-or-later OR OpenSSL) AND (BSD-3-Clause OR GPL-2.0-or-later
        OR LGPL-2.1-or-later OR MPL-1.1) AND (BSD-3-Clause OR OpenSSL) AND Apache-2.0
        AND Artistic-1.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-Source-Code AND
        CC0-1.0 AND GPL-1.0-only AND OpenSSL AND snprintf
      license_declared: (Artistic-1.0 OR GPL-1.0-or-later) AND (Artistic-1.0-Perl
        OR GPL-1.0-or-later) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (BSD-2-Clause
        OR OpenSSL) AND (BSD-3-Clause OR GPL-1.0-or-later OR GPL-2.0-only OR OpenSSL)
        AND (BSD-3-Clause OR GPL-1.0-or-later OR OpenSSL) AND (BSD-3-Clause OR GPL-2.0-or-later
        OR LGPL-2.1-or-later OR MPL-1.1) AND (BSD-3-Clause OR OpenSSL) AND Apache-2.0
        AND Artistic-1.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-Source-Code AND
        CC0-1.0 AND GPL-1.0-only AND OpenSSL AND snprintf
      short_summary: FIPS Libraries for openssl
      supplier: 'Organization: Broadcom, Inc.'
