sources:
- archive: fail2ban-1.1.0.tar.gz
  archive_sha512sum: 9bff7b9c41e58a953901800468e5c4153c9db6af01c7eb18111ad8620b40d03a0771020472fb759b2809d250e2bb45471e6c7e8283e72ea48290ecf7bf921821
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Fail2Ban scans log files and bans IP addresses that makes
        too many password failures. It updates firewall rules to reject the IP address.
        These rules can be defined by the user. Fail2Ban can read multiple log files
        such as sshd or Apache web server ones.  The main package contains the core
        server components for Fail2Ban with minimal dependencies.  You can install
        this directly if you want to have a small installation and know what you are
        doing. '
      home_page: http://fail2ban.sourceforge.net
      license_concluded: GPL-2.0-or-later AND GPL-2.0-only AND MIT AND Apache-2.0
        AND GPL-1.0-or-later AND GPL-3.0-or-later
      license_declared: GPL-2.0-or-later AND GPL-2.0-only AND MIT AND Apache-2.0 AND
        GPL-1.0-or-later AND GPL-3.0-or-later
      short_summary: Daemon to ban hosts that cause multiple authentication errors
      supplier: 'Organization: Broadcom, Inc.'
