sources:
- archive: uwsgi-2.0.31.tar.gz
  archive_sha512sum: d4d327f36455438e165298cb5a7d483c951f4acd3d834b46ceeda105bd3664792ead226b02e06db62e92c210544778119bf75a55d9d4f30f8fba896c7de51e6d
  version: 2.0.31
  name: uwsgi-2.0.31
  archive_type: upstream
  skip_validation: false
  url: https://github.com/unbit/uwsgi/archive/refs/tags/2.0.31.tar.gz
  repo_url: https://github.com/unbit/uwsgi
  commit_id: ce518cce893d20e9c79eb2607f3a6c250468ae4d
  missing: []
  spdx:
    package:
      detailed_description: 'The uWSGI project aims at developing a full stack for
        building hosting services. Application servers (for various programming languages
        and protocols), proxies, process managers and monitors are all implemented
        using a common api and a common configuration style.  Thanks to its pluggable
        architecture it can be extended to support more platforms and languages. Currently,
        you can write plugins in C, C++ and Objective-C.  The "WSGI" part in the name
        is a tribute to the namesake Python standard, as it has been the first developed
        plugin for the project. Versatility, performance, low-resource usage and reliability
        are the strengths of the project (and the only rules followed). '
      home_page: https://github.com/unbit/uwsgi
      license_concluded: GPL-2.0-only WITH GCC-exception-2.0 AND Apache-2.0 AND GPL-2.0-only
        AND GPL-2.0-or-later
      license_declared: GPL-2.0-only WITH GCC-exception-2.0 AND Apache-2.0 AND GPL-2.0-only
        AND GPL-2.0-or-later
      short_summary: Application Container Server for Networked/Clustered Web Applications
      supplier: 'Organization: Broadcom, Inc.'
