sources:
- archive: talloc-2.4.4.tar.gz
  archive_sha512sum: 3273ef4f2de463293a515df8269cd585c46a1cae1889455d7c3438399541769cb5c55944ad77257ae6498cecbcc0c65bc81843b70d1f98b5e7fd107f67eec867
  archive_type: None
  license_manual_review:
  - file_paths:
    - talloc-2.4.4/man/talloc.3.xml
    sha256sum: 8e5ca81cdafeb321224f9a26ab41c58c336c248f333d9957267f674cd25a1184
    spdx_exp: LGPL-3.0-or-later
  skip_validation: true
  name: talloc-2.4.4
  version: 2.4.4
  url: https://download.samba.org/pub/talloc/talloc-2.4.4.tar.gz
  repo_url: https://gitlab.com/samba-team/samba/-/tree/master/lib/talloc
  commit_id: 51d05da70e8461834396d361eead807127751b76
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'Libtalloc alloc is a hierarchical, reference counted
        memory pool system with destructors. It is the core memory allocator used
        in Samba. '
      home_page: https://talloc.samba.org
      license_concluded: PostgreSQL AND AGPL-3.0-or-later AND snprintf AND GPL-3.0-or-later
        AND BSD-3-Clause AND LGPL-2.1-or-later AND LGPL-3.0-or-later AND ISC
      license_declared: PostgreSQL AND AGPL-3.0-or-later AND snprintf AND GPL-3.0-or-later
        AND BSD-3-Clause AND LGPL-2.1-or-later AND LGPL-3.0-or-later AND ISC
      short_summary: Talloc is a hierarchical, reference counted memory pool system
      supplier: 'Organization: Broadcom, Inc.'
