sources:
- archive: talloc-2.4.1.tar.gz
  archive_sha512sum: 4de3b66d7cd1ff3f53e28e86bf9e89528635465c67868e1262aab6946106c228b2c184e988561361c3194fb260d83e016477254c9dbea7abff40c4dc0d31c76c
  archive_type: None
  skip_validation: true
  name: "talloc-2.4.1"
  version: 2.4.1
  url: https://download.samba.org/pub/talloc/talloc-2.4.1.tar.gz
  repo_url: https://gitlab.com/samba-team/samba/-/tree/master/lib/talloc
  commit_id: 2eda24663f8b9d6d03bffe96785518d16d06ae6e
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'Libtalloc alloc is a hierarchical, reference counted
        memory pool system with destructors. It is the core memory allocator used
        in Samba. '
      home_page: https://talloc.samba.org
      license_concluded: PostgreSQL AND AGPL-3.0-or-later AND snprintf AND GPL-3.0-or-later
        AND BSD-3-Clause AND LGPL-2.1-or-later AND LGPL-3.0-or-later AND ISC
      license_declared: PostgreSQL AND AGPL-3.0-or-later AND snprintf AND GPL-3.0-or-later
        AND BSD-3-Clause AND LGPL-2.1-or-later AND LGPL-3.0-or-later AND ISC
      short_summary: Talloc is a hierarchical, reference counted memory pool system
      supplier: 'Organization: Broadcom, Inc.'
