sources:
- archive: glib-2.88.0.tar.xz
  archive_sha512sum: ceead8d88720db17dc6bbff7aff14f261f90afc5e8261448aae0657f89b5fcc616cf62f4b049be88a4ddd3f50a869bbcdb66b29777da4969a47987828ecac280
  license_manual_review:
  # This file itself is not licensed and just lists the tests files
  - file_paths:
    - glib-2.88.0/.reuse/dep5
    sha256sum: 2e79c13df143ec611331d2a963b07f4c6da9fa50d84dd6df5064c2b68faf2db1
    spdx_exp: LGPL-2.1-or-later
  # This file itself is not licensed and just lists the tests files
  - file_paths:
    - glib-2.88.0/docs/reference/glib/gvariant-specification-1.0.rst
    sha256sum: 7b09dbf254808acac3c6ce0fd1ae6de6c9a2eafe8bc7622e8c8c154c5a932164
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The GLib package contains a low-level libraries useful
        for providing data structure handling for C, portability wrappers and interfaces
        for such runtime functionality as an event loop, threads, dynamic loading
        and an object system. Development libs and headers are in glib-devel.'
      home_page: https://developer.gnome.org/glib/
      license_concluded: LGPL-3.0-or-later AND LGPL-2.0-only AND GPL-2.0-or-later
        WITH Autoconf-exception-2.0 AND GPL-2.0-or-later AND FSFULLR AND Apache-2.0
        AND bzip2-1.0.6 AND GPL-2.0-only AND BSD-3-Clause AND GCR-docs AND LGPL-2.0-or-later
        AND GPL-1.0-or-later AND CC0-1.0 AND LGPL-2.1-or-later AND (AFL-2.0 OR LGPL-2.0-or-later)
        AND LGPL-2.1-only AND CC-BY-SA-3.0 AND CC-BY-3.0 AND MIT AND Apache-2.0 WITH
        LLVM-exception AND GPL-1.0-or-later WITH Autoconf-exception-generic
      license_declared: LGPL-3.0-or-later AND LGPL-2.0-only AND GPL-2.0-or-later WITH
        Autoconf-exception-2.0 AND GPL-2.0-or-later AND FSFULLR AND Apache-2.0 AND
        bzip2-1.0.6 AND GPL-2.0-only AND BSD-3-Clause AND GCR-docs AND LGPL-2.0-or-later
        AND GPL-1.0-or-later AND CC0-1.0 AND LGPL-2.1-or-later AND (AFL-2.0 OR LGPL-2.0-or-later)
        AND LGPL-2.1-only AND CC-BY-SA-3.0 AND CC-BY-3.0 AND MIT AND Apache-2.0 WITH
        LLVM-exception AND GPL-1.0-or-later WITH Autoconf-exception-generic
      short_summary: Low-level libraries useful for providing data structure handling
        for C.
      supplier: 'Organization: Broadcom, Inc.'
