sources:
- archive: libpng-1.6.56.tar.gz
  archive_sha512sum: 352ea0d78ae50c19ee2b99714f9a66773ad18f22c18a5fb693481d9c87a372a6bf8cd7b3e7c482f2e0474ed80ddc337a2e8ec38d148212eb175d15ca0257c03a
  archive_type: upstream
  version: 1.6.56
  name: libpng-1.6.56
  url: https://github.com/pnggroup/libpng/archive/refs/tags/v1.6.56.tar.gz
  repo_url: https://github.com/pnggroup/libpng
  commit_id: d5515b5b8be3901aac04e5bd8bd5c89f287bcd33
  skip_list: []
  missing: []
  skip_validation: false
  spdx:
    package:
      detailed_description: 'The libpng package contains libraries used by other programs
        for reading and writing PNG files. The PNG format was designed as a replacement
        for GIF and, to a lesser extent, TIFF, with many improvements and extensions
        and lack of patent problems. '
      home_page: http://www.libpng.org/
      license_concluded: X11 AND GPL-2.0-only AND GPL-1.0-or-later AND GPL-2.0-or-later
        AND BSD-3-Clause AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        FSFULLRWD AND FSFUL AND GPL-2.0-or-later WITH Libtool-exception AND FSFULLR
        AND Libpng AND Zlib AND CC0-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND MIT AND Apache-2.0
      license_declared: X11 AND GPL-2.0-only AND GPL-1.0-or-later AND GPL-2.0-or-later
        AND BSD-3-Clause AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        FSFULLRWD AND FSFUL AND GPL-2.0-or-later WITH Libtool-exception AND FSFULLR
        AND Libpng AND Zlib AND CC0-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND MIT AND Apache-2.0
      short_summary: contains libraries for reading and writing PNG files.
      supplier: 'Organization: Broadcom, Inc.'
