sources:
  - archive: ImageMagick-7.1.2-32.tar.gz
    archive_sha512sum: e6132ffdec21eacff5da9f9513c70e01a284292eb90265e9eda3eb1a1e8dc9014e3fc9d88fecffc8db2a50424001bc50f4dd8ee026a7c18f09a18b2983b92a7b
    archive_type: upstream
    name: ImageMagick-7.1.2-32
    version: 7.1.2-32
    url: https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.2-32.tar.gz
    repo_url: https://github.com/ImageMagick/ImageMagick
    commit_id: ad98b244c995d2e3051757fa3b7855f45b550d24
    skip_list: []
    missing: []
    license_manual_review:
    - file_paths:
      - ImageMagick-7.1.2-32/MagickCore/nt-base.c
      sha256sum: 782b7c135f8a1bbd3d308e34f7b98ca7c782e5b825f1b59e6e5c49e0210d0ca7
      spdx_exp: ""
    spdx:
      package:
        detailed_description: 'ImageMagick is a free, open-source software suite for creating, editing, converting, and displaying images.'
        short_summary: 'ImageMagick is a free, open-source software suite for creating, editing, converting, and displaying images.'
        home_page: https://imagemagick.org/
        license_concluded: BSD-2-Clause AND FSFAP AND FSFAP-no-warranty-disclaimer AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND IJG AND ImageMagick AND LGPL-3.0-only AND Libpng AND MIT AND X11
        license_declared: BSD-2-Clause AND FSFAP AND FSFAP-no-warranty-disclaimer AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND IJG AND ImageMagick AND LGPL-3.0-only AND Libpng AND MIT AND X11
        supplier: "Organization: Broadcom, Inc."
