sources:
- archive: retriable-3.1.2.gem
  archive_sha512sum: 11061a8aa1413ae557ea6c7d0117a6554adf420f40c0c3a93f91bc86f97bf660ef9f3ebc5e56550351473fe8efa96169b27ececbc10b3381fee440fa08d8ef92
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Retriable is an simple DSL to retry failed code blocks with randomized exponential backoff.'
      home_page: https://rubygems.org/gems/retriable
      license_concluded: MIT
      license_declared: MIT
      short_summary: Retriable is an simple DSL to retry failed code blocks with randomized exponential backoff.
      supplier: 'Organization: Broadcom, Inc.'
