sources:
- archive: fluentd-1.19.1.gem
  archive_sha512sum: 9526eba9373c2b8c42831cfd9a7398d31a5aec992ca5fe4e7b3ac6df715fa6f13faa78930a69b28d5511178deae297b3bb300acd65f2374d5273ba32fb383e1d
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Fluentd is an open source data collector designed to
        scale and simplify log management. It can collect, process and ship many kinds
        of data in near real-time. '
      home_page: https://rubygems.org/gems/fluentd/versions/1.19.1
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: An open source data collector designed to scale and simplify
        log management
      supplier: 'Organization: Broadcom, Inc.'
