sources:
- archive: rpcsvc-proto-1.4.4.tar.xz
  archive_sha512sum: 0138ac8fb2d8de3cb56f661bd1b6435fa0a35d3bd12c5cb7081c9ae1701e3620f47fe3dd002263db456655b61316749768e9a1a44325a1a6a542beae364a0393
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The rpcsvc-proto package contains the rcpsvc protocol.x
        files and headers, formerly included with glibc, that are not included in
        replacement libtirpc-1.1.4, along with the rpcgen program. '
      home_page: https://github.com/thkukuk/rpcsvc-proto
      license_concluded: FSFULLR AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND BSD-3-Clause AND FSFUL AND X11 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND FSFULLRWD AND FSFAP
      license_declared: FSFULLR AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND BSD-3-Clause AND FSFUL AND X11 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND FSFULLRWD AND FSFAP
      short_summary: rcpsvc protocol.x files and headers
      supplier: 'Organization: Broadcom, Inc.'
