#!/bin/sh

# Begin /etc/systemd/scripts/iptables

# Insert connection-tracking modules
# (not needed if built into the kernel)
modprobe nf_conntrack
modprobe xt_LOG

WAIT_OPTIONS="--wait 1 --wait-interval 20000"

# Set a known state
iptables $WAIT_OPTIONS -P INPUT   DROP
iptables $WAIT_OPTIONS -P FORWARD DROP
iptables $WAIT_OPTIONS -P OUTPUT  DROP

ip6tables $WAIT_OPTIONS -P INPUT   DROP
ip6tables $WAIT_OPTIONS -P FORWARD DROP
ip6tables $WAIT_OPTIONS -P OUTPUT  DROP

# These lines are here in case rules are already in place and the
# script is ever rerun on the fly. We want to remove all rules and
# pre-existing user defined chains before we implement new rules.
iptables $WAIT_OPTIONS -F
iptables $WAIT_OPTIONS -X
iptables $WAIT_OPTIONS -Z

iptables $WAIT_OPTIONS -t nat -F
iptables $WAIT_OPTIONS -t nat -X
iptables $WAIT_OPTIONS -t mangle -F
iptables $WAIT_OPTIONS -t mangle -X

ip6tables $WAIT_OPTIONS -F
ip6tables $WAIT_OPTIONS -X
ip6tables $WAIT_OPTIONS -Z

ip6tables $WAIT_OPTIONS -t nat -F
ip6tables $WAIT_OPTIONS -t nat -X
ip6tables $WAIT_OPTIONS -t mangle -F
ip6tables $WAIT_OPTIONS -t mangle -X

#restore ipv4 rules
iptables-restore $WAIT_OPTIONS < /etc/systemd/scripts/ip4save

#restore ipv6 rules
ip6tables-restore $WAIT_OPTIONS < /etc/systemd/scripts/ip6save

# End /etc/systemd/scripts/iptables
