sources:
- archive: nginx-ingress-5.4.2.tar.gz
  archive_sha512sum: e82ef30728686085ef58841aaed3193b9c901d9d9e216c0bf9acceccb901d25af37b86aa935baa9ffdb0269d3451463ebeb4613b2a86f2337bcac8986c6e840c
  archive_type: upstream
  commit_id: cd864d71a5e3b6698b80daee02b2785c4020db10
  missing: []
  skip_list: []
  skip_validation: false
  name: kubernetes-ingress-5.4.2
  version: '5.4.2'
  repo_url: https://github.com/nginxinc/kubernetes-ingress
  url: https://github.com/nginxinc/kubernetes-ingress/archive/refs/tags/v5.4.2.tar.gz
  spdx:
    package:
      detailed_description: 'This is an implementation of kubernetes ingress controller
        for NGINX. '
      home_page: https://github.com/nginxinc/kubernetes-ingress
      license_concluded: MIT AND (CC-BY-4.0 AND OFL-1.1 AND MIT) AND Apache-2.0 AND
        0BSD AND CC0-1.0 AND BSD-3-Clause AND CC-BY-3.0 AND MPL-2.0
      license_declared: MIT AND (CC-BY-4.0 AND OFL-1.1 AND MIT) AND Apache-2.0 AND
        0BSD AND CC0-1.0 AND BSD-3-Clause AND CC-BY-3.0 AND MPL-2.0
      short_summary: NGINX Ingress Controller for Kubernetes
      supplier: 'Organization: Broadcom, Inc.'
