sources:
- archive: rsyslog-8.2504.0.tar.gz
  archive_sha512sum: 327d4d1cbfa3aa9de4107199da1f9d5e534a80873c1bb612790c752f650acd12b9b7b7017c11b6132e3b869709c1d6c15fe684d6bc9eef155aca2d779f542994
  skip_validation: true
  repo_url: https://github.com/rsyslog/rsyslog
  url: https://github.com/rsyslog/rsyslog/archive/refs/tags/v8.2504.0.tar.gz
  commit_id: 53c8bd9387ea16b5fa992075136daa2f52ab964d
  spdx:
    package:
      detailed_description: 'RSYSLOG is the rocket-fast system for log processing.
        It offers high-performance, great security features and a modular design.
        While it started as a regular syslogd, rsyslog has evolved into a kind of
        swiss army knife of logging, being able to accept inputs from a wide variety
        of sources, transform them, and output to the results to diverse destinations. '
      home_page: http://www.rsyslog.com
      license_concluded: (MIT OR BSD-3-Clause OR GPL-2.0-only) AND (MIT OR GPL-2.0-only)
        AND (MIT OR BSD-3-Clause OR GPL-1.0-or-later) AND LGPL-2.0-only AND GPL-1.0-or-later
        AND Apache-1.0 AND FSFAP AND CC0-1.0 AND BSD-3-Clause AND GPL-3.0-or-later
        AND Apache-2.0 AND GPL-2.0-or-later AND GPL-3.0-only AND LGPL-3.0-only AND
        LGPL-3.0-or-later AND CDDL-1.0
      license_declared: (MIT OR BSD-3-Clause OR GPL-2.0-only) AND (MIT OR GPL-2.0-only)
        AND (MIT OR BSD-3-Clause OR GPL-1.0-or-later) AND LGPL-2.0-only AND GPL-1.0-or-later
        AND Apache-1.0 AND FSFAP AND CC0-1.0 AND BSD-3-Clause AND GPL-3.0-or-later
        AND Apache-2.0 AND GPL-2.0-or-later AND GPL-3.0-only AND LGPL-3.0-only AND
        LGPL-3.0-or-later AND CDDL-1.0
      short_summary: Rocket-fast system for log processing
      supplier: 'Organization: Broadcom, Inc.'
