sources:
- archive: gdb-13.2.tar.xz
  archive_sha512sum: 8185d3e11ab60dafff5860a5016577bfe7dd7547ef01ebc867bc247603d82b74ff74c4f29492c7d2aee57076f52be33e289f4c6b414a4b870d4b3004909f4c34
  skip_validation: true
  spdx:
    package:
      detailed_description: 'GDB, the GNU Project debugger, allows you to see what
        is going on `inside'' another program while it executes -- or what another
        program was doing at the moment it crashed. '
      home_page: http://www.gnu.org/software/gdb
      license_concluded: (BSD-3-Clause OR GPL-2.0-only) AND GPL-2.0-or-later WITH
        Libtool-exception AND FSFAP AND FSFUL AND ISC AND GPL-3.0-or-later AND LPD-document
        AND GPL-3.0-or-later WITH Texinfo-exception AND LGPL-2.0-or-later WITH GCC-exception-2.0
        AND BSD-4.3TAHOE AND SunPro AND CC-BY-ND-3.0 AND GPL-2.0-or-later WITH GNAT-exception
        AND GPL-2.0-or-later AND FSFAP-no-warranty-disclaimer AND GFDL-1.1-only AND
        LGPL-3.0-only AND GPL-3.0-or-later WITH Autoconf-exception-generic AND LGPL-2.0-only
        AND FSFULLRWD AND GPL-3.0-or-later WITH Bison-exception-2.2 AND NTP AND GFDL-1.3-or-later
        AND BSD-4.3RENO AND GPL-2.0-or-later WITH GCC-exception-2.0 AND BSL-1.0 AND
        CMU-Mach AND FSFULLR AND GPL-3.0-or-later WITH Autoconf-exception-macro AND
        LGPL-2.1-or-later AND X11 AND Zlib AND GPL-2.0-only AND Latex2e-translated-notice
        AND GPL-1.0-or-later WITH Autoconf-exception-generic AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND Latex2e AND GPL-3.0-or-later WITH
        GCC-exception-3.1 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        BSD-3-Clause AND HPND-Markus-Kuhn AND LGPL-3.0-or-later AND GPL-3.0-only AND
        GFDL-1.3-only AND GPL-1.0-or-later AND LGPL-2.0-or-later AND LGPL-2.1-only
        AND GPL-2.0-or-later WITH GNU-compiler-exception AND GFDL-1.1-or-later AND
        GPL-2.0-or-later WITH Bison-exception-1.24 AND GPL-3.0-or-later WITH Autoconf-exception-2.0
      license_declared: (BSD-3-Clause OR GPL-2.0-only) AND GPL-2.0-or-later WITH Libtool-exception
        AND FSFAP AND FSFUL AND ISC AND GPL-3.0-or-later AND LPD-document AND GPL-3.0-or-later
        WITH Texinfo-exception AND LGPL-2.0-or-later WITH GCC-exception-2.0 AND BSD-4.3TAHOE
        AND SunPro AND CC-BY-ND-3.0 AND GPL-2.0-or-later WITH GNAT-exception AND GPL-2.0-or-later
        AND FSFAP-no-warranty-disclaimer AND GFDL-1.1-only AND LGPL-3.0-only AND GPL-3.0-or-later
        WITH Autoconf-exception-generic AND LGPL-2.0-only AND FSFULLRWD AND GPL-3.0-or-later
        WITH Bison-exception-2.2 AND NTP AND GFDL-1.3-or-later AND BSD-4.3RENO AND
        GPL-2.0-or-later WITH GCC-exception-2.0 AND BSL-1.0 AND CMU-Mach AND FSFULLR
        AND GPL-3.0-or-later WITH Autoconf-exception-macro AND LGPL-2.1-or-later AND
        X11 AND Zlib AND GPL-2.0-only AND Latex2e-translated-notice AND GPL-1.0-or-later
        WITH Autoconf-exception-generic AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND Latex2e AND GPL-3.0-or-later WITH GCC-exception-3.1 AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND BSD-3-Clause AND HPND-Markus-Kuhn AND
        LGPL-3.0-or-later AND GPL-3.0-only AND GFDL-1.3-only AND GPL-1.0-or-later
        AND LGPL-2.0-or-later AND LGPL-2.1-only AND GPL-2.0-or-later WITH GNU-compiler-exception
        AND GFDL-1.1-or-later AND GPL-2.0-or-later WITH Bison-exception-1.24 AND GPL-3.0-or-later
        WITH Autoconf-exception-2.0
      short_summary: C debugger
      supplier: 'Organization: Broadcom, Inc.'
