sources:
- archive: gdb-17.1.tar.xz
  archive_type: upstream
  archive_sha512sum: f1a6751e439a2128fecf3eae8b57c1608a0dc7cfe79b4356a937874e5a42bb2df0aba36eb6a9452c41966908b9a59076c7cad9720f684688ab956b65080f1d7c
  name: gdb-17.1
  version: 17.1
  url: https://sourceware.org/pub/gdb/releases/gdb-17.1.tar.xz
  repo_url: https://sourceware.org/git/binutils-gdb.git
  commit_id: 631a49c452a4a456dd9889d172541ea789f8bcae
  skip_list: ['djunpack.bat', 'configure.ac']
  missing: ['*.gmo', '*.texi', '*.info', 'gdb.info-*', '*-exp.c', ada-lex.c, cp-name-parser.c, setup.com, binutils, elfcpp, gas, ld, gold, gprofng, gprof, gdb.pot, gdb.1, gcore.1, gdbserver.1, gdbinit.5, gdb-add-index.1, gstack.1, gcore.in, gdb-add-index.in, version.subst, libctf-nobfd.ver, gstdint.h, sha256.sum, makefile.vms, COPYING.LIBGLOSS, COPYING.NEWLIB, .pre-commit-config.yaml, .gitattributes, .gitignore, .editorconfig, .gdbinit, .cvsignore]
  spdx:
    package:
      detailed_description: 'GDB, the GNU Project debugger, allows you to see what
        is going on `inside'' another program while it executes -- or what another
        program was doing at the moment it crashed. '
      home_page: http://www.gnu.org/software/gdb
      license_concluded: (BSD-3-Clause OR GPL-2.0-only) AND GPL-2.0-or-later WITH
        Libtool-exception AND FSFAP AND FSFUL AND ISC AND GPL-3.0-or-later AND LPD-document
        AND GPL-3.0-or-later WITH Texinfo-exception AND LGPL-2.0-or-later WITH GCC-exception-2.0
        AND BSD-4.3TAHOE AND SunPro AND CC-BY-ND-3.0 AND GPL-2.0-or-later WITH GNAT-exception
        AND GPL-2.0-or-later AND FSFAP-no-warranty-disclaimer AND GFDL-1.1-only AND
        LGPL-3.0-only AND GPL-3.0-or-later WITH Autoconf-exception-generic AND LGPL-2.0-only
        AND FSFULLRWD AND GPL-3.0-or-later WITH Bison-exception-2.2 AND NTP AND GFDL-1.3-or-later
        AND BSD-4.3RENO AND GPL-2.0-or-later WITH GCC-exception-2.0 AND BSL-1.0 AND
        CMU-Mach AND FSFULLR AND GPL-3.0-or-later WITH Autoconf-exception-macro AND
        LGPL-2.1-or-later AND X11 AND Zlib AND GPL-2.0-only AND Latex2e-translated-notice
        AND GPL-1.0-or-later WITH Autoconf-exception-generic AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND Latex2e AND GPL-3.0-or-later WITH
        GCC-exception-3.1 AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        BSD-3-Clause AND HPND-Markus-Kuhn AND LGPL-3.0-or-later AND GPL-3.0-only AND
        GFDL-1.3-only AND GPL-1.0-or-later AND LGPL-2.0-or-later AND LGPL-2.1-only
        AND GPL-2.0-or-later WITH GNU-compiler-exception AND GFDL-1.1-or-later AND
        GPL-2.0-or-later WITH Bison-exception-1.24 AND GPL-3.0-or-later WITH Autoconf-exception-2.0
      license_declared: (BSD-3-Clause OR GPL-2.0-only) AND GPL-2.0-or-later WITH Libtool-exception
        AND FSFAP AND FSFUL AND ISC AND GPL-3.0-or-later AND LPD-document AND GPL-3.0-or-later
        WITH Texinfo-exception AND LGPL-2.0-or-later WITH GCC-exception-2.0 AND BSD-4.3TAHOE
        AND SunPro AND CC-BY-ND-3.0 AND GPL-2.0-or-later WITH GNAT-exception AND GPL-2.0-or-later
        AND FSFAP-no-warranty-disclaimer AND GFDL-1.1-only AND LGPL-3.0-only AND GPL-3.0-or-later
        WITH Autoconf-exception-generic AND LGPL-2.0-only AND FSFULLRWD AND GPL-3.0-or-later
        WITH Bison-exception-2.2 AND NTP AND GFDL-1.3-or-later AND BSD-4.3RENO AND
        GPL-2.0-or-later WITH GCC-exception-2.0 AND BSL-1.0 AND CMU-Mach AND FSFULLR
        AND GPL-3.0-or-later WITH Autoconf-exception-macro AND LGPL-2.1-or-later AND
        X11 AND Zlib AND GPL-2.0-only AND Latex2e-translated-notice AND GPL-1.0-or-later
        WITH Autoconf-exception-generic AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND Latex2e AND GPL-3.0-or-later WITH GCC-exception-3.1 AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND BSD-3-Clause AND HPND-Markus-Kuhn AND
        LGPL-3.0-or-later AND GPL-3.0-only AND GFDL-1.3-only AND GPL-1.0-or-later
        AND LGPL-2.0-or-later AND LGPL-2.1-only AND GPL-2.0-or-later WITH GNU-compiler-exception
        AND GFDL-1.1-or-later AND GPL-2.0-or-later WITH Bison-exception-1.24 AND GPL-3.0-or-later
        WITH Autoconf-exception-2.0
      short_summary: C debugger
      supplier: 'Organization: Broadcom, Inc.'
