sources:
- archive: zlib-1.3.2.tar.gz
  archive_sha512sum: 70963771ea5d763614278a69b474f09b7d237ef8f53b675a10fe31d9923aeef601504b35d7ebd1b1e7f347e9ebb048e6b3b47fffdf137e7bdc7e8d5eb4ec4692
  archive_type: upstream
  name: zlib-1.3.2
  version: '1.3.2'
  url: https://github.com/madler/zlib/releases/download/v1.3.2/zlib-1.3.2.tar.gz
  repo_url: https://github.com/madler/zlib.git
  commit_id: da607da739fa6047df13e66a2af6b8bec7c2a498
  skip_validation: false
  skip_list: []
  missing:
  - .github
  - .gitignore
  - find_package_no_components_test
  - find_package_wrong_components_test
  spdx:
    package:
      detailed_description: 'Compression and decompression routines '
      home_page: http://www.zlib.net
      license_concluded: GPL-1.0-or-later AND GPL-2.0-or-later WITH GNAT-exception
        AND Zlib AND BSL-1.0 AND LPD-document
      license_declared: GPL-1.0-or-later AND GPL-2.0-or-later WITH GNAT-exception
        AND Zlib AND BSL-1.0 AND LPD-document
      short_summary: Compression and decompression routines
      supplier: 'Organization: Broadcom, Inc.'
