sources:
  - archive: ImageMagick-7.1.2-13.tar.gz
    archive_sha512sum: fe0ee9d89bc8be98e12a03304ed0853f12af744dffd236e8dc5c7fd8c7d0d4b1e8874a8d0609de9f0ea3f554859dd7497b51c26f4f34fdbb9811d54691d61074
    archive_type: upstream
    name: ImageMagick-7.1.2-13
    version: 7.1.2-13
    url: https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.2-13.tar.gz
    repo_url: https://github.com/ImageMagick/ImageMagick
    commit_id: dd991e286b96918917a3392d6dc3ffc0e6907a4e
    skip_list: []
    missing: []
    license_manual_review:
    - file_paths:
      - ImageMagick-7.1.2-13/MagickCore/nt-base.c
      sha256sum: 3a8fb4c66aae73f742ffa91232713fee2beda7f0acfdd6a351445bb121f884c5
      spdx_exp: ""
    spdx:
      package:
        detailed_description: 'ImageMagick is a free, open-source software suite for creating, editing, converting, and displaying images.'
        short_summary: 'ImageMagick is a free, open-source software suite for creating, editing, converting, and displaying images.'
        home_page: https://imagemagick.org/
        license_concluded: BSD-2-Clause AND FSFAP AND FSFAP-no-warranty-disclaimer AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND IJG AND ImageMagick AND LGPL-3.0-only AND Libpng AND MIT AND X11
        license_declared: BSD-2-Clause AND FSFAP AND FSFAP-no-warranty-disclaimer AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND IJG AND ImageMagick AND LGPL-3.0-only AND Libpng AND MIT AND X11
        supplier: "Organization: Broadcom, Inc."
