sources:
  - archive: ImageMagick-7.1.2-11.tar.gz
    archive_sha512sum: 940c483cd5c069e8c81e7a373ef694c3050b946294caeaf0b751d9f77f541b07107cc4b0b9ac1f189e08ee92c5d66b640ae2b83a66e5e2f12c523e48845c4432
    archive_type: upstream
    name: ImageMagick-7.1.2-11
    version: 7.1.2-11
    url: https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.2-11.tar.gz
    repo_url: https://github.com/ImageMagick/ImageMagick
    commit_id: 578d60d1bf77be54b16ef2673d507932885570dd
    skip_list: []
    missing: []
    license_manual_review:
    - file_paths:
      - ImageMagick-7.1.2-11/MagickCore/nt-base.c
      sha256sum: e93d5807292733ad0edd1659425608f36a5b5121a1023ae38eeecebadbed7ab2
      spdx_exp: ""
    spdx:
      package:
        detailed_description: 'ImageMagick is a free, open-source software suite for creating, editing, converting, and displaying images.'
        short_summary: 'ImageMagick is a free, open-source software suite for creating, editing, converting, and displaying images.'
        home_page: https://imagemagick.org/
        license_concluded: BSD-2-Clause AND FSFAP AND FSFAP-no-warranty-disclaimer AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND IJG AND ImageMagick AND LGPL-3.0-only AND Libpng AND MIT AND X11
        license_declared: BSD-2-Clause AND FSFAP AND FSFAP-no-warranty-disclaimer AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND IJG AND ImageMagick AND LGPL-3.0-only AND Libpng AND MIT AND X11
        supplier: "Organization: Broadcom, Inc."
