sources:
    - archive: ImageMagick-7.1.1-38.tar.xz
      archive_sha512sum: 636e2061c11c012e2607a53a893eb227569f3a4e04e331499722f2c84dc0db3eedae63525bd530972a639e3a262ab4f61383a21ca8603f8f81e5629a29f54b89
      skip_validation: true
      spdx:
          package:
              detailed_description:
                  software suite, used for editing and manipulating digital
                  images
              home_page: https://imagemagick.org/
              license_concluded: GPL-2.0-or-later AND ImageMagick AND FSFAP-no-warranty-disclaimer AND Apache-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-macro AND MIT AND IJG AND X11 AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-2.0-only AND FSFULLRWD AND GPL-2.0-or-later WITH Libtool-exception AND LGPL-3.0-only AND FSFAP AND FSFUL AND GPL-2.0-or-later WITH Autoconf-exception-generic AND Libpng AND FSFULLR AND BSD-2-Clause
              license_declared: GPL-2.0-or-later AND ImageMagick AND FSFAP-no-warranty-disclaimer AND Apache-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-macro AND MIT AND IJG AND X11 AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-2.0-only AND FSFULLRWD AND GPL-2.0-or-later WITH Libtool-exception AND LGPL-3.0-only AND FSFAP AND FSFUL AND GPL-2.0-or-later WITH Autoconf-exception-generic AND Libpng AND FSFULLR AND BSD-2-Clause
              originator: "Organization: ImageMagick Studio LLC."
              short_summary: software suite, used for editing and manipulating digital images
              supplier: "Organization: Broadcom, Inc."
