sources:
- archive: Perl4-CoreLibs-0.005.tar.gz
  archive_sha512sum: 87e4c153f2fead9eae9ea338b965294d8a2a1b0b5c6a25c7a4b18cab049526c26efaa7bb99f264e025d4a2893165b5960a6bff83c18f50af2106174b5b344981
  skip_validation: true
  spdx:
    package:
      detailed_description: 'This is a collection of ''.pl'' files that were bundled
        with the Perl core until core version 5.15.1. Relying on their presence in
        the core distribution is deprecated; they should be acquired from this CPAN
        distribution instead. From core version 5.13.3 until their removal, the core
        versions of these libraries emit a deprecation warning when loaded. The CPAN
        version does not emit such a warning. '
      home_page: http://search.cpan.org/dist/Perl4-CoreLibs/
      license_concluded: Artistic-1.0-Perl OR GPL-1.0-or-later
      license_declared: Artistic-1.0-Perl OR GPL-1.0-or-later
      short_summary: Core Perl4 Libs
      supplier: 'Organization: Broadcom, Inc.'
