sources:
- archive: gevent-25.9.1.tar.gz
  archive_sha512sum: 8c7f6030020fd6d762ebb1afccb7fb8306e2cf1a45dabf8a471709264acc35003ea2be44f4e0733a75c703256776b4f22a96be50e926c9dc053f453f0b1f3522
  skip_validation: true
  name: gevent-25.9.1
  version: "25.9.1"
  url: https://files.pythonhosted.org/packages/9e/48/b3ef2673ffb940f980966694e40d6d32560f3ffa284ecaeb5ea3a90a6d3f/gevent-25.9.1.tar.gz
  repo_url: https://github.com/gevent/gevent/
  commit_id: 86937db8eadc4e1a4e1ffc374dc67d2fcf4c7196
  missing: ['config.yml', '.gitignore', '_generated_include', 'cares.html', 'gevent.egg-info', 'corecext.html', 'PKG-INFO', 'cares.c', 'workflows', 'm4', 'dependabot.yml', 'corecext.h', 'corecext.c']
  skip_list: ['setup.cfg']
  spdx:
    package:
      detailed_description: gevent is a coroutine-based Python networking library.
      home_page: https://pypi.python.org/pypi/gevent
      license_concluded: (BSD-2-Clause OR GPL-2.0-or-later) AND BSD-3-Clause AND GPL-3.0-or-later
        WITH Autoconf-exception-2.0 AND GPL-3.0-or-later AND GPL-2.0-or-later WITH
        Libtool-exception AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        GPL-2.0-only AND FSFUL AND Apache-2.0 AND LGPL-2.1-or-later AND WTFPL AND
        ISC AND FSFULLR AND NTP AND GPL-2.0-or-later AND Python-2.0 AND BSD-2-Clause
        AND GPL-3.0-or-later WITH Libtool-exception AND MIT AND FSFAP AND FSFULLRWD
        AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND X11 AND CC-BY-4.0
      license_declared: (BSD-2-Clause OR GPL-2.0-or-later) AND BSD-3-Clause AND GPL-3.0-or-later
        WITH Autoconf-exception-2.0 AND GPL-3.0-or-later AND GPL-2.0-or-later WITH
        Libtool-exception AND GPL-2.0-or-later WITH Autoconf-exception-generic AND
        GPL-2.0-only AND FSFUL AND Apache-2.0 AND LGPL-2.1-or-later AND WTFPL AND
        ISC AND FSFULLR AND NTP AND GPL-2.0-or-later AND Python-2.0 AND BSD-2-Clause
        AND GPL-3.0-or-later WITH Libtool-exception AND MIT AND FSFAP AND FSFULLRWD
        AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND X11 AND CC-BY-4.0
      short_summary: Coroutine-based network library
      supplier: 'Organization: Broadcom, Inc.'
