sources:
- archive: policycoreutils-3.10.tar.gz
  archive_sha512sum: 
    80e7cdd0c27c010c05758fcbe7da15cc112d9328eec726ae7a0d45d42b88b60aad2ebbe589062c84569a981ed7008832706ca4e538d1d97d31496f4333450e2f
  skip_validation: true
  spdx:
    package:
      detailed_description: 'policycoreutils contains the policy core utilities that
        are required for basic operation of a SELinux system. '
      home_page: https://github.com/SELinuxProject/selinux/wiki
      license_concluded: GPL-2.0-only AND GPL-2.0-or-later
      license_declared: GPL-2.0-only AND GPL-2.0-or-later 
      short_summary: SELinux policy core utilities
      supplier: 'Organization: Broadcom, Inc.'
