sources:
- archive: policycoreutils-3.5.tar.gz
  archive_sha512sum: 7978ef6b7a278c6384c9b397734d03c4932c8aefecceaa1e6a1345be27b253dbe276fdcd219ce83ad732c6ed55d53bbc3254e39bccadd67d2cd1152a14749444
  archive_type: upstream
  skip_validation: false
  name: policycoreutils-3.5
  version: "3.5"
  url: https://github.com/SELinuxProject/selinux/releases/download/3.5/policycoreutils-3.5.tar.gz
  repo_url: https://github.com/SELinuxProject/selinux
  commit_id: d6e96c5929a3f1aa1dce93505edd9f0158757ac2
  missing: ['.github', 'CleanSpec.mk', '.travis.yml', 'oss-fuzz.sh', 'libsepol', 'run-scan-build', 'lgtm.yml', 'Makefile', '.tx', 'mcstrans', 'sandbox', 'libsemanage', 'run_init', 'newrole', 'run-flake8', 'CONTRIBUTING.md', 'README.md', 'python', 'policycoreutils', 'man', 'semodule-utils', 'setsebool', 'release', 'po', 'gui', '.circleci', 'fixfiles', 'secon', 'ci', 'secilc', 'setfiles', 'restorecond', 'libselinux', 'env_use_destdir', 'make-update', 'sestatus', 'Lindent', 'fixfiles.8', 'ru', 'load_policy', 'SECURITY.md', 'checkpolicy', 'hll', 'dbus', 'semodule']
  skip_list: ['.gitignore', 'Makefile', 'LICENSE']
  spdx:
    package:
      detailed_description: 'policycoreutils contains the policy core utilities that
        are required for basic operation of a SELinux system. '
      home_page: https://github.com/SELinuxProject/selinux/wiki
      license_concluded: GPL-2.0-only AND GPL-2.0-or-later
      license_declared: GPL-2.0-only AND GPL-2.0-or-later
      short_summary: SELinux policy core utilities
      supplier: 'Organization: Broadcom, Inc.'
