sources:
- archive: io-endpoint-0.16.0.gem
  archive_sha512sum: 22d9be3dd54cadad3d44309c483bfa04c261bf2dd8090daf4eb8980c8a736b9d85fbde276a62d469e70d28545817d76b2e2a9601fccce6964cf7af83d72fd5c9
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Abstraction for IO endpoints including sockets, SSL, pipes, etc..'
      home_page: https://rubygems.org/gems/io-endpoint
      license_concluded: MIT
      license_declared: MIT
      short_summary: Abstraction for IO endpoints including sockets, SSL, pipes, etc.
      supplier: 'Organization: Broadcom, Inc.'
