sources:
- archive: lz4-1.10.0.tar.gz
  archive_sha512sum: 8c4ceb217e6dc8e7e0beba99adc736aca8963867bcf9f970d621978ba11ce92855912f8b66138037a1d2ae171e8e17beb7be99281fea840106aa60373c455b28
  archive_type: upstream
  name: lz4-1.10.0
  url: https://github.com/lz4/lz4/archive/refs/tags/v1.10.0.tar.gz
  repo_url: https://github.com/lz4/lz4
  commit_id: ebb370ca83af193212df4dcbadcc5d87bc0de2f0
  skip_list: []
  missing: []
  skip_validation: true
  spdx:
    package:
      detailed_description: 'LZ4 is lossless compression algorithm, providing compression
        speed at 400 MB/s per core, scalable with multi-cores CPU.  It features an
        extremely fast decoder, with speed in multiple GB/s per core, typically reaching
        RAM speed limits on multi-core systems. '
      home_page: http://lz4.github.io/lz4
      license_concluded: BSD-2-Clause AND GPL-2.0-or-later AND GPL-2.0-only AND BSD-2-Clause-Patent
        AND CC0-1.0 AND BSD-3-Clause AND (BSD-3-Clause OR GPL-2.0-only) AND LPD-document
      license_declared: BSD-2-Clause AND GPL-2.0-or-later AND GPL-2.0-only AND BSD-2-Clause-Patent
        AND CC0-1.0 AND BSD-3-Clause AND (BSD-3-Clause OR GPL-2.0-only) AND LPD-document
      short_summary: Extremely fast compression.
      supplier: 'Organization: Broadcom, Inc.'
