sources:
- archive: runc-1.4.2.tar.gz
  archive_sha512sum: 93bd1d6641b55afa7fa415d26fd898371c63f3caae353c6bea7318eeac49835a29df0331f62d54bf2ab1a640105c541c7eb04c32bc3d1006df53d857d113775e
  archive_type: upstream
  name: runc-1.4.2
  version: 1.4.2
  url: https://github.com/opencontainers/runc/archive/refs/tags/v1.4.2.tar.gz
  repo_url: https://github.com/opencontainers/runc
  commit_id: c241c0bb5e60a8e8c1b2e53d4eca8d0068d8d57e
  skip_list: []
  missing: []
  skip_validation: false
  spdx:
    package:
      detailed_description: 'runC is a CLI tool for spawning and running containers
        according to the OCI specification. Containers are started as a child process
        of runC and can be embedded into various other systems without having to run
        a daemon. '
      home_page: https://runc.io
      license_concluded: BSD-3-Clause AND (Apache-2.0 OR LGPL-2.1-or-later) AND LGPL-2.1-or-later
        AND CC-BY-4.0 AND GPL-1.0-or-later AND Apache-2.0 AND MIT AND BSD-2-Clause
      license_declared: BSD-3-Clause AND (Apache-2.0 OR LGPL-2.1-or-later) AND LGPL-2.1-or-later
        AND CC-BY-4.0 AND GPL-1.0-or-later AND Apache-2.0 AND MIT AND BSD-2-Clause
      short_summary: CLI tool for spawning and running containers per OCI spec.
      supplier: 'Organization: Broadcom, Inc.'
