sources:
- archive: aws-sdk-sqs-1.110.0.gem
  archive_sha512sum: 434abd0b15184706a0e9a4130a99219a88221b1494f946b7c2b1aeacf1a24aff3a1184dc12de16ae707f5392dafdfb82a9f7afd84c749eb0dc34dd8cc22d735e
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Official AWS Ruby gem for Amazon Simple Queue Service
        (Amazon SQS). This gem is part of the AWS SDK for Ruby. '
      home_page: https://rubygems.org/gems/aws-sdk-sqs/versions/1.110.0
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: Official AWS Ruby gem for Amazon Simple Queue Service (Amazon
        SQS).
      supplier: 'Organization: Broadcom, Inc.'
