sources:
- archive: gst-plugins-bad-1.25.1.tar.xz
  archive_sha512sum: 51a11258d3c3c58ba3860da3f1a85138fa60f5094259cd874fd4ca8bc17bb5df066e7e3cbebdcd1fbf384d13df4aaf168fe5503d302016936a2ac54d029d2063
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The GStreamer Good Plug-ins is a set of plug-ins considered
        by the GStreamer developers to have good quality code, correct functionality,
        and the preferred license (LGPL). A wide range of video and audio decoders,
        encoders, and filters are included. '
      home_page: http://gstreamer.freedesktop.org/
      license_concluded: (MPL-1.1 OR MIT OR LGPL-2.0-or-later) AND (GPL-2.0-or-later
        WITH Linux-syscall-note OR BSD-3-Clause) AND (GPL-2.0-or-later OR BSD-3-Clause)
        AND GPL-2.0-only AND BSD-2-Clause AND LGPL-2.1-or-later AND HPND-Pbmplus AND
        GPL-2.0-or-later AND CC-BY-SA-4.0 AND BSL-1.0 AND GPL-1.0-or-later AND Apache-2.0
        AND MIT-Festival AND MIT AND GPL-2.0-or-later WITH Linux-syscall-note AND
        GPL-2.0-only WITH Linux-syscall-note AND ISC AND LGPL-2.1-only AND BSD-3-Clause
        AND LGPL-2.0-or-later AND BSD-2-Clause-Views AND MPL-1.1 AND DOC
      license_declared: (MPL-1.1 OR MIT OR LGPL-2.0-or-later) AND (GPL-2.0-or-later
        WITH Linux-syscall-note OR BSD-3-Clause) AND (GPL-2.0-or-later OR BSD-3-Clause)
        AND GPL-2.0-only AND BSD-2-Clause AND LGPL-2.1-or-later AND HPND-Pbmplus AND
        GPL-2.0-or-later AND CC-BY-SA-4.0 AND BSL-1.0 AND GPL-1.0-or-later AND Apache-2.0
        AND MIT-Festival AND MIT AND GPL-2.0-or-later WITH Linux-syscall-note AND
        GPL-2.0-only WITH Linux-syscall-note AND ISC AND LGPL-2.1-only AND BSD-3-Clause
        AND LGPL-2.0-or-later AND BSD-2-Clause-Views AND MPL-1.1 AND DOC
      short_summary: The GStreamer Bad Plug-ins package contains a set a set of plug-ins
        that aren't up to par compared to the rest
      supplier: 'Organization: Broadcom, Inc.'
