sources:
- archive: gst-plugins-bad-1.25.1.tar.xz
  archive_sha512sum: 51a11258d3c3c58ba3860da3f1a85138fa60f5094259cd874fd4ca8bc17bb5df066e7e3cbebdcd1fbf384d13df4aaf168fe5503d302016936a2ac54d029d2063
  skip_validation: true
  spdx:
    package:
      detailed_description: The GStreamer Bad Plug-ins is a set of plug-ins that are
        not up to par compared to the rest. They might be close to being good quality,
        but they are missing something - be it a good code review, some documentation,
        a set of tests, a real live maintainer, or some actual wide use.
      home_page: http://gstreamer.freedesktop.org/
      license_concluded: (BSD-3-Clause OR GPL-2.0-or-later WITH Linux-syscall-note)
        AND (BSD-3-Clause OR GPL-2.0-or-later) AND (LGPL-2.0-or-later OR MIT OR MPL-1.1)
        AND Apache-2.0 AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND
        BSL-1.0 AND CC-BY-SA-4.0 AND DOC AND GPL-1.0-or-later AND GPL-2.0-only AND
        GPL-2.0-only WITH Linux-syscall-note AND GPL-2.0-or-later AND GPL-2.0-or-later
        WITH Linux-syscall-note AND HPND-Pbmplus AND ISC AND LGPL-2.0-or-later AND
        LGPL-2.1-only AND LGPL-2.1-or-later AND MIT AND MIT-Festival AND MPL-1.1
      license_declared: (BSD-3-Clause OR GPL-2.0-or-later WITH Linux-syscall-note)
        AND (BSD-3-Clause OR GPL-2.0-or-later) AND (LGPL-2.0-or-later OR MIT OR MPL-1.1)
        AND Apache-2.0 AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND
        BSL-1.0 AND CC-BY-SA-4.0 AND DOC AND GPL-1.0-or-later AND GPL-2.0-only AND
        GPL-2.0-only WITH Linux-syscall-note AND GPL-2.0-or-later AND GPL-2.0-or-later
        WITH Linux-syscall-note AND HPND-Pbmplus AND ISC AND LGPL-2.0-or-later AND
        LGPL-2.1-only AND LGPL-2.1-or-later AND MIT AND MIT-Festival AND MPL-1.1
      short_summary: The GStreamer Bad Plug-ins package contains a set a set of plug-ins
        that aren't up to par compared to the rest
      supplier: 'Organization: Broadcom, Inc.'
