sources:
- archive: signet-0.21.0.gem
  archive_sha512sum: 34c3bbffaad07afb8dabecb4ae21347ac095a811033582c1b1e332132475683de6de8c1a738641deefbfc62148cc79e0527d463a9b993f4377b7646935ee0482
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Signet is an OAuth 1.0 / OAuth 2.0 implementation.'
      home_page: https://rubygems.org/gems/signet
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: Signet is an OAuth 1.0 / OAuth 2.0 implementation.
      supplier: 'Organization: Broadcom, Inc.'
