sources:
- archive: webob-1.8.11.tar.gz
  archive_sha512sum: 341512295b2085eb39d3fb956dd8b876d6db0bcdad82167549772f1a1a7c7fb48382f77560cefe1c73f4d3f2222053a63f3453decb2fcb453361564e87f376be
  archive_type: upstream
  name: webob-1.8.11
  version: '1.8.11'
  url: https://github.com/Pylons/webob/archive/refs/tags/1.8.11.tar.gz
  repo_url: https://github.com/Pylons/webob
  commit_id: ebf7054032ae2fb93c51c5fd3fc0adb24cc29af3
  skip_validation: true
  spdx:
    package:
      detailed_description: 'WebOb provides objects for HTTP requests and responses.
        Specifically it does this by wrapping the WSGI request environment and response
        status/headers/app_iter(body).  The request and response objects provide many
        conveniences for parsing HTTP request and forming HTTP responses. Both objects
        are read/write: as a result, WebOb is also a nice way to create HTTP requests
        and parse HTTP responses.'
      home_page: https://pypi.python.org/pypi/WebOb
      license_concluded: MIT
      license_declared: MIT
      short_summary: WebOb provides objects for HTTP requests and responses..
      supplier: 'Organization: Broadcom, Inc.'
