sources:
  - archive: ImageMagick-7.1.2-16.tar.gz
    archive_sha512sum: 2efefad8347af4b4408c8a9d19709aa5f7d2f2c036b9851e4ee5dc0f5e0894dc26be81fb536e97c9f0b48a85cf06f3600f0ec6eaf81c324dcfefe978c6b1bb8c
    archive_type: upstream
    name: ImageMagick-7.1.2-16
    version: 7.1.2-16
    url: https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.2-16.tar.gz
    repo_url: https://github.com/ImageMagick/ImageMagick
    commit_id: 70563ce3759b7a55801900a11e69978a9301fbeb
    skip_list: []
    missing: []
    license_manual_review:
    - file_paths:
      - ImageMagick-7.1.2-16/MagickCore/nt-base.c
      sha256sum: 076aed9955e303213e2ccc1ba6a11ff62bd8a88b299d3daecc941e2cc239bec1
      spdx_exp: ""
    spdx:
      package:
        detailed_description: 'ImageMagick is a free, open-source software suite for creating, editing, converting, and displaying images.'
        short_summary: 'ImageMagick is a free, open-source software suite for creating, editing, converting, and displaying images.'
        home_page: https://imagemagick.org/
        license_concluded: BSD-2-Clause AND FSFAP AND FSFAP-no-warranty-disclaimer AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND IJG AND ImageMagick AND LGPL-3.0-only AND Libpng AND MIT AND X11
        license_declared: BSD-2-Clause AND FSFAP AND FSFAP-no-warranty-disclaimer AND FSFUL AND FSFULLR AND FSFULLRWD AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-2.0-or-later WITH Autoconf-exception-macro AND GPL-2.0-or-later WITH Libtool-exception AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND IJG AND ImageMagick AND LGPL-3.0-only AND Libpng AND MIT AND X11
        supplier: "Organization: Broadcom, Inc."
