sources:
- archive: mime-types-data-3.2025.0507.gem
  archive_sha512sum: bfd122838caa1dba1278760036a10f41abed34e1cdff36ff27108219a7c6eb65067f985d8b790d7a6c04cc466689fc74ab283b4142d76dccab6ecdf4d902994d
  skip_validation: true
  spdx:
    package:
      detailed_description: 'mime-types-data provides a registry for information about
        MIME media type definitions. It can be used with the Ruby mime-types library
        or other software to determine defined filename extensions for MIME types,
        or to use filename extensions to look up the likely MIME type definitions. '
      home_page: https://rubygems.org/gems/mime-types-data/versions/3.2025.0507
      license_concluded: MIT
      license_declared: MIT
      short_summary: Provides a registry for information about MIME media type definitions.
      supplier: 'Organization: Broadcom, Inc.'
