sources:
- archive: pgbackrest-2.54.2.tar.gz
  archive_type: upstream
  archive_sha512sum: 083a99059fd1cbd78e063a7ec816e9f6e4a06688911a6ff71d3e4cfb4ca0795cd83983d49acf0c55ac2d0b0dc77bc928595d7e44e054b6e9bfb69c626678c3d7
  name: pgbackrest-release-2.54.2
  repo_url: https://github.com/pgbackrest/pgbackrest
  url: https://github.com/pgbackrest/pgbackrest/archive/refs/tags/release/2.54.2.tar.gz
  commit_id: 962346080f859535b9b6395bb34d2d0da9c04684
  spdx:
    package:
      detailed_description: 'pgBackRest aims to be a reliable, easy-to-use backup
        and restore solution that can seamlessly scale up to the largest databases
        and workloads by utilizing algorithms that are optimized for database-specific
        requirements. '
      home_page: https://pgbackrest.org
      license_concluded: MIT AND X11 AND BSD-2-Clause AND FSFUL AND FSFAP AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND FSFULLRWD AND BSD-3-Clause
      license_declared: MIT AND X11 AND BSD-2-Clause AND FSFUL AND FSFAP AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND FSFULLRWD AND BSD-3-Clause
      short_summary: Reliable PostgreSQL Backup & Restore
      supplier: 'Organization: Broadcom, Inc.'
