sources:
- archive: faraday-2.12.2.gem
  archive_sha512sum: 1cae919a782b17e62abbbf6f41a6ce16f48dc0500d354694cdae4e7b5fd0b8cac3b6fd4a6a8f1284c50fc4de1db65283a7185d757135fea76f65404175ef8efd
  skip_validation: true
  spdx:
    package:
      detailed_description: 'HTTP/REST API client library.'
      home_page: https://rubygems.org/gems/faraday
      license_concluded: MIT
      license_declared: MIT
      short_summary: HTTP/REST API client library.
      supplier: 'Organization: Broadcom, Inc.'
