sources:
- archive: faraday-2.14.3.gem
  archive_sha512sum: 185156a86d4f690431c69d358b54aa6e85dc6090fdf951a56f4f926d90101d24c5ad5e39cefcf01b015e61da68e718741d04397f18678baec9277882f6897700
  skip_validation: true
  spdx:
    package:
      detailed_description: 'HTTP/REST API client library.'
      home_page: https://rubygems.org/gems/faraday
      license_concluded: MIT
      license_declared: MIT
      short_summary: HTTP/REST API client library.
      supplier: 'Organization: Broadcom, Inc.'
