sources:
- archive: omi-1.9.0-0.tar.gz
  archive_sha512sum: 73b60237173079707de8dbab29c3225643a8bf262348911724d542409b674f0a6593b046b87801e6998b0aad50b8dfe14748a2a6de115564e129bbb035b76759
  skip_validation: true
  spdx:
    package:
      detailed_description: Open Management Infrastructure (OMI) provides production
        quality implementation of the DMTF CIM/WBEM standards. he OMI CIMOM is also
        designed to be portable and highly modular.
      home_page: https://github.com/microsoft/omi
      license_concluded: HPND-export-US-modify AND Apache-2.0 AND MIT
      license_declared: HPND-export-US-modify AND Apache-2.0 AND MIT
      short_summary: OMI provides production quality implementation of the DMTF CIM/WBEM
        standards.
      supplier: 'Organization: Broadcom, Inc.'
- archive: powershell-7.4.7-linux-x64.tar.gz
  archive_sha512sum: 523d778a45ee01be48b97bdfd6b46b58a93b0cb1643f50c531ace8f5a53dd7e8f9bef07e5e715a9969280db04aa18afb5002ae27a9b968dc04952abd78583da2
  skip_validation: true
  spdx:
    package:
      detailed_description: Powershell is a cross-platform automation and configuration
        tool/framework that works well with your existing tools and is optimized for
        dealing with structured data (e.g. JSON, CSV, XML, etc.), REST APIs, and object
        models. It includes a command-line shell, an associated scripting language
        and a framework for processing cmdlets.
      home_page: https://github.com/PowerShell/PowerShell
      license_concluded: BSD-2-Clause AND CC-BY-SA-2.0 AND Apache-2.0 AND LGPL-2.1-or-later
        AND MIT AND Parity-6.0.0 AND Parity-7.0.0
      license_declared: BSD-2-Clause AND CC-BY-SA-2.0 AND Apache-2.0 AND LGPL-2.1-or-later
        AND MIT AND Parity-6.0.0 AND Parity-7.0.0
      short_summary: A cross-platform automation tool/framework.
      supplier: 'Organization: Broadcom, Inc.'
- archive: powershell-7.4.7-nuget-deps.tar.xz
  archive_sha512sum: fe1a918f13f36b0aecefed8cc669568f647a74ee08c015b688f03cbfe4ab69d1057a62f8821d471a05aee10beeb3cd525e284a728965341db386500550c3b643
  skip_validation: true
  spdx:
    package:
      detailed_description: Powershell extension for NuGet which is a package manager
        for .NET.
      home_page: https://github.com/PowerShell/PowerShell
      license_concluded: Zlib AND NCSA AND Unicode-3.0 AND W3C-20150513 AND Apache-2.0
        AND HP-1989 AND CC0-1.0 AND LGPL-2.1-or-later AND CC-BY-SA-3.0 AND MIT AND
        BSD-3-Clause AND CC-BY-3.0 AND BSD-4-Clause-UC AND bzip2-1.0.6 AND BSD-2-Clause
      license_declared: Zlib AND NCSA AND Unicode-3.0 AND W3C-20150513 AND Apache-2.0
        AND HP-1989 AND CC0-1.0 AND LGPL-2.1-or-later AND CC-BY-SA-3.0 AND MIT AND
        BSD-3-Clause AND CC-BY-3.0 AND BSD-4-Clause-UC AND bzip2-1.0.6 AND BSD-2-Clause
      short_summary: Powershell extension for NuGet which is a package manager for
        .NET.
      supplier: 'Organization: Broadcom, Inc.'
- archive: powershell-7.4.7.tar.gz
  archive_sha512sum: c1f39f53c8b94e5f41d03d5f286632e8e67a3e3a7b9c1bac0a1d53407e7a3858234934e7e64bd65e1c0f03a2c730ff5b515a3ae68f83e705d2074caff752816e
  skip_validation: true
  spdx:
    package:
      detailed_description: 'PowerShell is an automation and configuration management
        platform. It consists of a cross-platform command-line shell and associated
        scripting language. '
      home_page: https://microsoft.com/powershell
      license_concluded: MS-PL AND JSON AND MIT AND BSD-2-Clause AND Apache-2.0 AND
        LGPL-2.1-or-later AND BSD-3-Clause
      license_declared: MS-PL AND JSON AND MIT AND BSD-2-Clause AND Apache-2.0 AND
        LGPL-2.1-or-later AND BSD-3-Clause
      short_summary: PowerShell is an automation and configuration management platform.
      supplier: 'Organization: Broadcom, Inc.'
- archive: powershell-native-7.4.0.tar.gz
  archive_sha512sum: 6f00c3b7bc45307530bd04065138c4d0f613dcae3cca6bfbca3544c1cf4012b195f230a1b3d1968c1cf7f62fa1850ca6325ab81c668932886fc22fb7284e4370
  skip_validation: true
  spdx:
    package:
      detailed_description: This library provides functionality missing from .NET
        Core via system calls, that are called from from the CorePsPlatform.cs file
        of PowerShell. The method to do this is a Platform Invoke, which is C#'s Foreign
        Function Interface to C code (and C++ by way of extern C).
      home_page: https://github.com/PowerShell/PowerShell-Native
      license_concluded: MIT AND BSD-3-Clause AND Apache-2.0
      license_declared: MIT AND BSD-3-Clause AND Apache-2.0
      short_summary: This library provides functionality missing from .NET Core via
        system calls.
      supplier: 'Organization: Broadcom, Inc.'
