sources:
- archive: omi-1.9.0-0.tar.gz
  archive_sha512sum: 73b60237173079707de8dbab29c3225643a8bf262348911724d542409b674f0a6593b046b87801e6998b0aad50b8dfe14748a2a6de115564e129bbb035b76759
  skip_validation: true
  spdx:
    package:
      detailed_description: Open Management Infrastructure (OMI) provides production
        quality implementation of the DMTF CIM/WBEM standards. he OMI CIMOM is also
        designed to be portable and highly modular.
      home_page: https://github.com/microsoft/omi
      license_concluded: HPND-export-US-modify AND Apache-2.0 AND MIT
      license_declared: HPND-export-US-modify AND Apache-2.0 AND MIT
      short_summary: OMI provides production quality implementation of the DMTF CIM/WBEM
        standards.
      supplier: 'Organization: Broadcom, Inc.'
- archive: powershell-7.4.11-linux-x64.tar.gz
  archive_sha512sum: 46839371f415aff1cf4183449da2dfb570b0d57cb52e0f65e08114e27aa55d4f0f89c2293556b9b33ccba216ce265ddf43e56cd89e37bd1bd1775a1d6ee2a261
  skip_validation: true
  license_manual_review:
  - archive_path: Modules/Microsoft.PowerShell.PSResourceGet/dependencies/NuGet.Packaging.dll
    sha256sum: 877e82582d7802aca0b2fd53d34175b42d01bcf713a77d6d0a9e8a73c47ee2a4
    spdx_exp: ''
  spdx:
    package:
      detailed_description: Powershell is a cross-platform automation and configuration
        tool/framework that works well with your existing tools and is optimized for
        dealing with structured data (e.g. JSON, CSV, XML, etc.), REST APIs, and object
        models. It includes a command-line shell, an associated scripting language
        and a framework for processing cmdlets.
      home_page: https://github.com/PowerShell/PowerShell
      license_concluded: BSD-2-Clause AND CC-BY-SA-2.0 AND Apache-2.0 AND LGPL-2.1-or-later
        AND MIT AND Parity-6.0.0 AND Parity-7.0.0
      license_declared: BSD-2-Clause AND CC-BY-SA-2.0 AND Apache-2.0 AND LGPL-2.1-or-later
        AND MIT AND Parity-6.0.0 AND Parity-7.0.0
      short_summary: A cross-platform automation tool/framework.
      supplier: 'Organization: Broadcom, Inc.'
- archive: powershell-7.4.11-nuget-deps.tar.xz
  archive_sha512sum: 50c74ee85e25cc19c74e1e532aa4d6402bbf50ca43b01d00456cf2c4eee7efdafda09b648bb4c0365d304766808c59e0de54ad3f1f55fe0ea88601c632bcb484
  skip_validation: true
  spdx:
    package:
      detailed_description: Powershell extension for NuGet which is a package manager
        for .NET.
      home_page: https://github.com/PowerShell/PowerShell
      license_concluded: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause-UC
        AND CC-BY-3.0 AND CC-BY-SA-3.0 AND CC0-1.0 AND HP-1989 AND LGPL-2.1-or-later
        AND MIT AND MS-PL AND NCSA AND Unicode-3.0 AND W3C-20150513 AND Zlib AND bzip2-1.0.6
      license_declared: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause-UC
        AND CC-BY-3.0 AND CC-BY-SA-3.0 AND CC0-1.0 AND HP-1989 AND LGPL-2.1-or-later
        AND MIT AND MS-PL AND NCSA AND Unicode-3.0 AND W3C-20150513 AND Zlib AND bzip2-1.0.6
      short_summary: Powershell extension for NuGet which is a package manager for
        .NET.
      supplier: 'Organization: Broadcom, Inc.'
- archive: powershell-7.4.11.tar.gz
  archive_sha512sum: 6153ce1ea14497c6ad2fbc4dc6e287d130d2ed7e8573a6dccd6ce039453e6a9d33c1ed16f28d52d41b36557945d7b694ea7df852ddc5f13e0a3d2c1c7136d721
  skip_validation: true
  spdx:
    package:
      detailed_description: PowerShell is an automation and configuration management
        platform. It consists of a cross-platform command-line shell and associated
        scripting language.
      home_page: https://microsoft.com/powershell
      license_concluded: MS-PL AND JSON AND MIT AND BSD-2-Clause AND Apache-2.0 AND
        LGPL-2.1-or-later AND BSD-3-Clause
      license_declared: MS-PL AND JSON AND MIT AND BSD-2-Clause AND Apache-2.0 AND
        LGPL-2.1-or-later AND BSD-3-Clause
      short_summary: PowerShell is an automation and configuration management platform.
      supplier: 'Organization: Broadcom, Inc.'
- archive: powershell-native-7.4.0.tar.gz
  archive_sha512sum: 6f00c3b7bc45307530bd04065138c4d0f613dcae3cca6bfbca3544c1cf4012b195f230a1b3d1968c1cf7f62fa1850ca6325ab81c668932886fc22fb7284e4370
  skip_validation: true
  spdx:
    package:
      detailed_description: This library provides functionality missing from .NET
        Core via system calls, that are called from from the CorePsPlatform.cs file
        of PowerShell. The method to do this is a Platform Invoke, which is C#'s Foreign
        Function Interface to C code (and C++ by way of extern C).
      home_page: https://github.com/PowerShell/PowerShell-Native
      license_concluded: MIT AND BSD-3-Clause AND Apache-2.0
      license_declared: MIT AND BSD-3-Clause AND Apache-2.0
      short_summary: This library provides functionality missing from .NET Core via
        system calls.
      supplier: 'Organization: Broadcom, Inc.'
