sources:
- archive: powershell-7.6.2-linux-x64.tar.gz
  archive_sha512sum: effb505a891664d7c885129be67dc829218a074569c36dc00dcb3706435c72075c63ed67a1c533c044944993eefe460500c447163cab9f5b43233cd4d9d51b95
  skip_validation: true
  license_manual_review:
  - file_paths:
    - Modules/Microsoft.PowerShell.PSResourceGet/dependencies/NuGet.Packaging.dll
    sha256sum: 877e82582d7802aca0b2fd53d34175b42d01bcf713a77d6d0a9e8a73c47ee2a4
    spdx_exp: ''
  spdx:
    package:
      detailed_description: Powershell is a cross-platform automation and configuration
        tool/framework that works well with your existing tools and is optimized for
        dealing with structured data (e.g. JSON, CSV, XML, etc.), REST APIs, and object
        models. It includes a command-line shell, an associated scripting language
        and a framework for processing cmdlets.
      home_page: https://github.com/PowerShell/PowerShell
      license_concluded: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND MIT AND MS-PL
      license_declared: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND MIT AND MS-PL
      short_summary: A cross-platform automation tool/framework.
      supplier: 'Organization: Broadcom, Inc.'

- archive: powershell-7.6.2-nuget-deps.tar.xz
  archive_sha512sum: 6fa4f4b7b4255df4f6bc24aec09c71febc6d557b70068bf3a38dbb47a357b6de06694344c1e69aaf13de7b11f1fbf71a4cbf77cec9fd89f0e48b7b022307d9e9
  skip_validation: true
  spdx:
    package:
      detailed_description: Powershell extension for NuGet which is a package manager
        for .NET.
      home_page: https://github.com/PowerShell/PowerShell
      license_concluded: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause-UC
        AND CC-BY-3.0 AND CC-BY-SA-3.0 AND CC0-1.0 AND HP-1989 AND LGPL-2.1-or-later
        AND MIT AND MS-PL AND NCSA AND Unicode-3.0 AND W3C-20150513 AND Zlib AND bzip2-1.0.6
      license_declared: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause-UC
        AND CC-BY-3.0 AND CC-BY-SA-3.0 AND CC0-1.0 AND HP-1989 AND LGPL-2.1-or-later
        AND MIT AND MS-PL AND NCSA AND Unicode-3.0 AND W3C-20150513 AND Zlib AND bzip2-1.0.6
      short_summary: Powershell extension for NuGet which is a package manager for
        .NET.
      supplier: 'Organization: Broadcom, Inc.'

- archive: powershell-7.6.2.tar.gz
  archive_sha512sum: 8f0f1230ef38c7f7e1a0ae6fe6d90c9f6453e5060a30d6870eb1615d348f5c060df716de9587958577643298b43b9939f59dbe04bc32941c07fecad70b2a57ef
  skip_validation: true
  spdx:
    package:
      detailed_description: PowerShell is an automation and configuration management
        platform. It consists of a cross-platform command-line shell and associated
        scripting language.
      home_page: https://microsoft.com/powershell
      license_concluded: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND MIT AND MS-PL
      license_declared: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND MIT AND MS-PL
      short_summary: PowerShell is an automation and configuration management platform.
      supplier: 'Organization: Broadcom, Inc.'
