sources:
- archive: Exporter-Tiny-1.006002.tar.gz
  archive_sha512sum: 684dc97d854686910928f413bd84df3e2d2b351c2304116d5c567ec74eb7384f4085881f2bdeaf96dcf9ade2a959076ebd2bde3977dd5b876f75daaf6ca9d763
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Exporter::Tiny supports many of Sub::Exporter''s external-facing
        features including renaming imported functions with the -as, -prefix and -suffix
        options; explicit destinations with the into option; and alternative installers
        with the installer option. But it''s written in only about 40%% as many lines
        of code and with zero non-core dependencies.  Its internal-facing interface
        is closer to Exporter.pm, with configuration done through the @EXPORT, @EXPORT_OK
        and %%EXPORT_TAGS package variables.  Exporter::Tiny performs most of its
        internal duties (including resolution of tag names to sub names, resolution
        of sub names to coderefs, and installation of coderefs into the target package)
        as method calls, which means they can be overridden to provide interesting
        behavior. '
      home_page: http://search.cpan.org/dist/Exporter-Tiny/
      license_concluded: (GPL-1.0-or-later OR Artistic-1.0) AND (Artistic-1.0-Perl
        OR GPL-1.0-or-later) AND Artistic-1.0 AND GPL-1.0-only AND GPL-1.0-or-later
        AND MIT
      license_declared: (GPL-1.0-or-later OR Artistic-1.0) AND (Artistic-1.0-Perl
        OR GPL-1.0-or-later) AND Artistic-1.0 AND GPL-1.0-only AND GPL-1.0-or-later
        AND MIT
      short_summary: An exporter with the features of Sub::Exporter but only core
        dependencies
      supplier: 'Organization: Broadcom, Inc.'
