shared_sources:
  - shared-cfg-yml/cmake.yaml

sources:
- archive: llvm-18.1.8.src.tar.xz
  archive_sha512sum: 930814730bb2d80cf7f7b2968f0f1f1442009ca62a7ca29992b69d63823270584b059d16aa845bb381411da566e7e4f255fcfbc38acbdf865eb0419b4dfd7459
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The LLVM Project is a collection of modular and reusable
        compiler and toolchain technologies. Despite its name, LLVM has little to
        do with traditional virtual machines, though it does provide helpful libraries
        that can be used to build them. The name "LLVM" itself is not an acronym;
        it is the full name of the project. '
      home_page: https://llvm.org
      license_concluded: Apache-2.0 WITH LLVM-exception AND CC0-1.0 AND GPL-3.0-only
        AND GPL-2.0-or-later WITH Autoconf-exception-generic AND BSD-2-Clause AND
        Apache-2.0 AND Spencer-94 AND GPL-1.0-or-later AND GPL-2.0-only AND MIT AND
        NCSA AND BSD-3-Clause AND ISC
      license_declared: Apache-2.0 WITH LLVM-exception AND CC0-1.0 AND GPL-3.0-only
        AND GPL-2.0-or-later WITH Autoconf-exception-generic AND BSD-2-Clause AND
        Apache-2.0 AND Spencer-94 AND GPL-1.0-or-later AND GPL-2.0-only AND MIT AND
        NCSA AND BSD-3-Clause AND ISC
      short_summary: A collection of modular and reusable compiler and toolchain technologies.
      supplier: 'Organization: Broadcom, Inc.'
