sources:
- archive: wireshark-4.6.8.tar.xz
  archive_type: upstream
  archive_sha512sum: 4692bd15bebd67475502b6afe106e3be85b90add16f932d7e58c4426fd62b5886e96daa522aafd9ee4a8300bf3e091a738b5b1fa20e3e0721d0d0f3be216f3c8
  name: wireshark-4.6.8
  repo_url: https://github.com/wireshark/wireshark
  url: https://www.wireshark.org/download/src/wireshark-4.6.8.tar.xz
  commit_id: e677bf052328efc1ed897a547fa161836a0e4ff7
  missing:
  - .gitattributes
  - .gitignore
  skip_list:
  - make-version.py
  - org.wireshark.Wireshark.metainfo.xml
  - git-export-release.sh.in
  license_manual_review:
  - file_paths:
    - wireshark-4.6.8/tools/licensecheck.pl
    sha256sum: f9e39193d33e3e091f4908f1cf1ef749e427b1e59770a90d4120769e7a1a4fec
    spdx_exp: GPL-2.0-or-later
  spdx:
    package:
      detailed_description: 'Wireshark is a network protocol analyzer. It allows examining
        data from a live network or from a capture file on disk. You can interactively
        browse the capture data, viewing summary and detailed information for each
        packet. Wireshark has several features, including a rich display filter language
        and the ability to view the reconstructed stream of a TCP session. '
      home_page: http://www.wireshark.org
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (BSD-3-Clause
        OR GPL-2.0-only) AND (GPL-2.0-only OR ISC) AND (MIT OR NCSA) AND AFL-3.0 AND
        AGPL-3.0-only AND AGPL-3.0-or-later AND AML AND Apache-2.0 AND Artistic-1.0
        AND Artistic-1.0-Perl AND Artistic-2.0 AND BSD-1-Clause AND BSD-2-Clause AND
        BSD-2-Clause-Views AND BSD-3-Clause AND BSD-4-Clause AND BSL-1.0 AND Beerware
        AND CC-BY-4.0 AND CC-PDDC AND CC0-1.0 AND CDDL-1.0 AND EPL-1.0 AND GPL-1.0-or-later
        AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only AND GPL-3.0-or-later
        AND HPND AND ISC AND Kazlib AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-or-later
        AND LGPL-3.0-only AND Libpng AND MIT AND MIT-open-group AND MPL-1.0 AND MS-PL
        AND MS-RL AND NCSA AND ODbL-1.0 AND Python-2.0 AND WTFPL AND X11 AND Zlib
        AND blessing
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (BSD-3-Clause
        OR GPL-2.0-only) AND (GPL-2.0-only OR ISC) AND (MIT OR NCSA) AND AFL-3.0 AND
        AGPL-3.0-only AND AGPL-3.0-or-later AND AML AND Apache-2.0 AND Artistic-1.0
        AND Artistic-1.0-Perl AND Artistic-2.0 AND BSD-1-Clause AND BSD-2-Clause AND
        BSD-2-Clause-Views AND BSD-3-Clause AND BSD-4-Clause AND BSL-1.0 AND Beerware
        AND CC-BY-4.0 AND CC-PDDC AND CC0-1.0 AND CDDL-1.0 AND EPL-1.0 AND GPL-1.0-or-later
        AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only AND GPL-3.0-or-later
        AND HPND AND ISC AND Kazlib AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-or-later
        AND LGPL-3.0-only AND Libpng AND MIT AND MIT-open-group AND MPL-1.0 AND MS-PL
        AND MS-RL AND NCSA AND ODbL-1.0 AND Python-2.0 AND WTFPL AND X11 AND Zlib
        AND blessing
      short_summary: Wireshark is the world's foremost protocol analyzer
      supplier: 'Organization: Broadcom, Inc.'
