sources:
- archive: botocore-1.42.73.tar.gz
  archive_sha512sum: 677813dca882375e71dbfad32cd7f6cba5591053613c33780b0c418d7cb727770cae6d0c82ed03a193f9049f0fc99a44ef8f07583fa74c045ef4a72b35925365
  skip_validation: true
  spdx:
    package:
      detailed_description: 'A low-level interface to a growing number of Amazon Web
        Services. The botocore package is the foundation for the AWS CLI as well as
        boto3.'
      home_page: https://github.com/boto/botocore
      license_concluded: MIT AND MPL-2.0 AND GPL-1.0-or-later AND Apache-2.0
      license_declared: MIT AND MPL-2.0 AND GPL-1.0-or-later AND Apache-2.0
      short_summary: Amazon Web Services Library.
      supplier: 'Organization: Broadcom, Inc.'
