sources:
- archive: metrics-0.12.2.gem
  archive_sha512sum: 9c7cff3b9a1cbc73e64db8a20a15544e478ea97760eb6829ee3fb06956688e8bd4bbd9f7d3dafec535a41d1746dac18c3e3e001e3351a0f898a822068d71a162
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Collects and exposes metrics from Ruby applications'
      home_page: https://rubygems.org/gems/metrics
      license_concluded: MIT
      license_declared: MIT
      short_summary: Collects and exposes metrics from Ruby applications
      supplier: 'Organization: Broadcom, Inc.'
