sources:
- archive: YAML-1.31.tar.gz
  archive_sha512sum: 7f6af46348c4288541b611cb0d0f6d63a3d671417cadb3e9d60fed1c2c7664b35202b3ee8d15ef68400758604a3b2cb8a04c11b3e9badfd6f9222cf24f4a9edc
  archive_type: upstream
  name: YAML-1.31
  version: 1.31
  url: https://cpan.metacpan.org/authors/id/I/IN/INGY/YAML-1.31.tar.gz
  repo_url: https://github.com/ingydotnet/yaml-pm.git
  commit_id: e40694198951a8c5e0e7a179b795a662103e8e68
  skip_validation: false
  skip_list: ['RCS', 'CVS', 'tags', '.git', '.hg', '.bzr', '_darcs', '__pycache__']
  missing: ['.git', '.github', 'Meta', 'ReadMe.pod', 'doc', 'test', 'Changes', 'CONTRIBUTING', 'LICENSE', 'MANIFEST', 'META.json', 'META.yml', 'Makefile.PL', 'README', 't', 'xt', 'YAML.pod', 'Any.pod', 'Dumper.pod', 'Error.pod', 'Loader.pod', 'Marshall.pod', 'Node.pod', 'Tag.pod', 'Types.pod', 'Base.pod']
  spdx:
    package:
      detailed_description: 'The YAML.pm module implements a YAML Loader and Dumper
        based on the YAML 1.0 specification. http://www.yaml.org/spec/ YAML is a generic
        data serialization language that is optimized for human readability. It can
        be used to express the data structures of most modern programming languages,
        including Perl. For information on the YAML syntax, please refer to the YAML
        specification. '
      home_page: http://search.cpan.org/dist/YAML/
      license_concluded: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Artistic-1.0
        AND GPL-1.0-only
      license_declared: (Artistic-1.0-Perl OR GPL-1.0-or-later) AND Artistic-1.0 AND
        GPL-1.0-only
      short_summary: YAML Ain't Markup Language (tm)
      supplier: 'Organization: Broadcom, Inc.'
