sources:
- archive: emacs-30.1.tar.xz
  archive_type: upstream
  skip_validation: true
  archive_sha512sum: 511a6a1d2a170a207913692e1349344b70a0b5202b8d1ae27dc7256e589c77ae9e35da16fc2a098bf9f1b8d0f60233f452ed8d6744b70b907f3484c42f2d7d7f
  name: emacs-30.1
  version: '30.1'
  url: https://ftp.gnu.org/gnu/emacs/emacs-30.1.tar.xz
  repo_url: https://github.com/emacs-mirror/emacs
  commit_id: 8ac894e2246f25d2a2a97d866b10e6e0b0fede5a
  skip_list:
  - Makefile.in
  missing: []
  spdx:
    package:
      detailed_description: 'Emacs is a powerful, customizable, self-documenting,
        modeless text editor. Emacs contains special code editing features, a scripting
        language (elisp), and the capability to read mail, news, and more without
        leaving the editor. '
      home_page: http://www.gnu.org/software/emacs
      license_concluded: (LGPL-3.0-or-later OR GPL-2.0-or-later) AND GPL-3.0-or-later
        AND GFDL-1.1-or-later AND GPL-2.0-or-later WITH Bison-exception-1.24 AND BSD-3-Clause
        AND BSD-2-Clause AND LGPL-2.0-or-later AND MIT AND GPL-2.0-or-later AND FSFUL
        AND LGPL-3.0-only AND GPL-3.0-or-later WITH Autoconf-exception-generic AND
        GPL-1.0-or-later AND GPL-3.0-or-later WITH Texinfo-exception AND FSFULLR AND
        GPL-2.0-only AND GFDL-1.3-only AND PSF-2.0 AND CC-BY-SA-3.0 AND FSFAP AND
        GPL-2.0-or-later WITH Autoconf-exception-generic AND CC-BY-3.0 AND LGPL-2.0-only
        AND GPL-3.0-only AND FSFULLRWD AND BSD-2-Clause-Views AND Unicode-TOU AND
        NTP AND MPL-2.0 AND Apache-2.0 AND W3C AND BSD-4-Clause-UC AND CC-BY-SA-4.0
        AND ICU AND NTP-0 AND GPL-1.0-only AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND LGPL-2.1-or-later AND Latex2e-translated-notice AND GFDL-1.3-or-later
        AND BSL-1.0 AND Apache-1.1 AND LGPL-3.0-or-later AND X11
      license_declared: (LGPL-3.0-or-later OR GPL-2.0-or-later) AND GPL-3.0-or-later
        AND GFDL-1.1-or-later AND GPL-2.0-or-later WITH Bison-exception-1.24 AND BSD-3-Clause
        AND BSD-2-Clause AND LGPL-2.0-or-later AND MIT AND GPL-2.0-or-later AND FSFUL
        AND LGPL-3.0-only AND GPL-3.0-or-later WITH Autoconf-exception-generic AND
        GPL-1.0-or-later AND GPL-3.0-or-later WITH Texinfo-exception AND FSFULLR AND
        GPL-2.0-only AND GFDL-1.3-only AND PSF-2.0 AND CC-BY-SA-3.0 AND FSFAP AND
        GPL-2.0-or-later WITH Autoconf-exception-generic AND CC-BY-3.0 AND LGPL-2.0-only
        AND GPL-3.0-only AND FSFULLRWD AND BSD-2-Clause-Views AND Unicode-TOU AND
        NTP AND MPL-2.0 AND Apache-2.0 AND W3C AND BSD-4-Clause-UC AND CC-BY-SA-4.0
        AND ICU AND NTP-0 AND GPL-1.0-only AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND LGPL-2.1-or-later AND Latex2e-translated-notice AND GFDL-1.3-or-later
        AND BSL-1.0 AND Apache-1.1 AND LGPL-3.0-or-later AND X11
      short_summary: GNU Emacs text editor
      supplier: 'Organization: Broadcom, Inc.'
