sources:
- archive: libssh-0.11.5.tar.xz
  archive_sha512sum: 9cf40f1bbf072d5e176289b7aee0bb498a17dfff932a2197da00872959fa59a134890e81decd66f419ac1382e44a5d32546fe0b191f975af96db21d6de953faf
  archive_type: upstream
  name: libssh-0.11.5
  version: 0.11.5
  repo_url: https://git.libssh.org/projects/libssh.git
  commit_id: a09fdd00416e53b6ed436df6ff14339a4f884601
  url: https://git.libssh.org/projects/libssh.git/snapshot/libssh-0.11.5.tar.xz
  skip_list: []
  missing: []
  spdx:
    package:
      detailed_description: 'The ssh library was designed to be used by programmers
        needing a working SSH implementation by the mean of a library. The complete
        control of the client is made by the programmer. With %{name}, you can remotely
        execute programs, transfer files, use a secure and transparent tunnel for
        your remote programs. With its Secure FTP implementation, you can play with
        remote files easily, without third-party programs others than libcrypto (from
        openssl).'
      home_page: https://www.libssh.org
      license_concluded: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND ISC AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND MIT AND SSH-short
      license_declared: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later AND ISC AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND MIT AND SSH-short
      short_summary: A library implementing the SSH protocol
      supplier: 'Organization: Broadcom, Inc.'
