sources:
- archive: sphinxcontrib_serializinghtml-2.0.0.tar.gz
  archive_sha512sum: a71f8a25f1ab4b8cec9a2bf6a1fafbf19ee7211cb428b2cfa6d5e37c89d9ba4311e809621fcdaf3b94706d03334359d675eff16d4a6c2b32b4f20430a98544db
  skip_validation: true
  spdx:
    package:
      detailed_description: 'sphinxcontrib-serializinghtml is a sphinx extension which
        outputs "serialized" HTML files (json and pickle).'
      home_page: https://pypi.org/project/sphinxcontrib-serializinghtml
      license_concluded: BSD-2-Clause AND BSD-3-Clause
      license_declared: BSD-2-Clause AND BSD-3-Clause
      short_summary: Sphinx extension for serialized HTML
      supplier: 'Organization: Broadcom, Inc.'
