sources:
- archive: libfastjson-1.2304.0.tar.gz
  archive_sha512sum: a43dc809c0fc073f8bddaebdf91c996ccfc6275d7dcc312762e8dfb366dc121c7698c316b71bd5b43f2f7e9b3c326c90cfa927ce415824a7d32dd5e6667048ab
  skip_validation: true
  spdx:
    package:
      detailed_description: 'LIBFASTJSON is fast json library for C It offers a small
        library with essential json handling functions, suffieciently good json support
        and very fast in processing. '
      home_page: https://github.com/rsyslog/libfastjson
      license_concluded: FSFAP AND Apache-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-macro
        AND MIT
      license_declared: FSFAP AND Apache-2.0 AND GPL-3.0-or-later WITH Autoconf-exception-macro
        AND MIT
      short_summary: A fast json library for C
      supplier: 'Organization: Broadcom, Inc.'
