sources:
- archive: protocol-http-0.58.0.gem
  archive_sha512sum: 30d8914a7586e5b9e9bd25f68ec3a642c5337eebe153f37f59f99937bbbfa36e43012fa239d53f89b5652df1d88c6ecb055963f023884ea7e062337bcde71aeb
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Provides abstractions for working with the HTTP protocol. '
      home_page: https://rubygems.org/gems/protocol-http/versions/0.58.0
      license_concluded: MIT
      license_declared: MIT
      short_summary: Provides abstractions to handle HTTP protocols.
      supplier: 'Organization: Broadcom, Inc.'
