sources:
- archive: protocol-http-0.50.1.gem
  archive_sha512sum: e1e7b461564b17130d953c1a9d23c87546fc467384e62f97c7d37492c240c60f905844301f23c6eeffa5ed8f764ace3c46df0a2c1833fa877c1d317cfa8fc095
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Provides abstractions for working with the HTTP protocol. '
      home_page: https://rubygems.org/gems/protocol-http/versions/0.50.1
      license_concluded: MIT
      license_declared: MIT
      short_summary: Provides abstractions to handle HTTP protocols.
      supplier: 'Organization: Broadcom, Inc.'
