sources:
- archive: PyYAML-6.0.3.tar.gz
  archive_sha512sum: 0df64497f51bd07ee01d7676afc4cf3eff228e1a73d4b1c7f034c7cba762f3451aa686e594af54e8e359173262cc0e47c110491bc7e29c3dd712a66c4316b2cf
  archive_type: upstream
  skip_validation: false
  name: pyyaml-6.0.3
  version: "6.0.3"
  url: https://files.pythonhosted.org/packages/05/8e/961c0007c59b8dd7729d542c61a4d537767a59645b82a0b521206e1e25c2/pyyaml-6.0.3.tar.gz
  repo_url: https://github.com/yaml/pyyaml
  commit_id: 49790e73684bebad1df05ef8d828fa12f685bffb
  missing: ['.gitignore', 'PKG-INFO', 'PyYAML.egg-info', 'setup.cfg', 'announcement.msg', 'tox.ini', '.github']
  spdx:
    package:
      detailed_description: 'YAML is a data serialization format designed for human
        readability and interaction with scripting languages.  PyYAML is a YAML parser
        and emitter for Python.  PyYAML features a complete YAML 1.1 parser, Unicode
        support, pickle support, capable extension API, and sensible error messages.  PyYAML
        supports standard YAML tags and provides Python-specific tags that allow to
        represent an arbitrary Python object.  PyYAML is applicable for a broad range
        of tasks from complex configuration files to object serialization and persistence. '
      home_page: http://pyyaml.org/
      license_concluded: MIT
      license_declared: MIT
      short_summary: YAML parser and emitter for Python
      supplier: 'Organization: Broadcom, Inc.'
