sources:
- archive: rootlesskit-3.0.0.tar.gz
  archive_sha512sum: fbe8d0c5fbb52bec474a330fd2d6f72be4d2ca68d7d552e9cec82c4f66cc0e6aed4b633d106f4de0b916ea1c7a8544195c19640a4053b2cc9bb3cf3a84b9ffe8
  archive_type: upstream
  commit_id: 01885f675def8cf9202791b7e3517cdad52bf837
  missing: []
  skip_list: []
  skip_validation: false
  name: rootlesskit-3.0.0
  version: '3.0.0'
  repo_url: https://github.com/rootless-containers/rootlesskit
  url: https://github.com/rootless-containers/rootlesskit/archive/refs/tags/v3.0.0.tar.gz
  spdx:
    package:
      detailed_description: 'RootlessKit is a Linux-native implementation of "fake
        root" using user_namespaces(7). The purpose of RootlessKit is to run Docker
        and Kubernetes as an unprivileged user (known as "Rootless mode"), so as to
        protect the real root on the host from potential container-breakout attacks. '
      home_page: https://github.com/rootless-containers/rootlesskit
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: Linux-native fakeroot using user namespaces
      supplier: 'Organization: Broadcom, Inc.'
