#!/bin/bash
#################################################
#       Title:  mk-initrd                       #
#        Date:  2015-04-08                      #
#     Version:  1.0                             #
#      Author:  dthaluru@vmware.com             #
#     Options:                                  #
#################################################
#	Overview
#		Creates initial ramdisk
#	End
#

source config.inc		#	configuration parameters
source function.inc		#	commonn functions


if [ -d ${BUILDROOT} ] ; then
	[ -e ${BUILDROOT}/dev/ram0 ]    || mknod ${BUILDROOT}/dev/ram0 b 1 0
	# Try to reduce this size to 8G or less later...maybe strip debug symbols off.
	dd if=/dev/zero of=${BUILDROOT}/boot/initrd bs=1024 count=16384
	mke2fs -m 0 -i 1024 -F ${BUILDROOT}/boot/initrd
        mount -o loop ${BUILDROOT}/boot/initrd ${BUILDROOT}/mnt
        cp BUILD_DVD/linuxrc ${BUILDROOT}/mnt/
	cp BUILD_DVD/fstab ${BUILDROOT}/mnt/
	pushd ${BUILDROOT}/mnt
	mkdir bin lib dev proc mnt etc
	ln -s lib lib64
	ln -s bin sbin
	popd
	mknod ${BUILDROOT}/mnt/dev/ram0    b  1  0
	mknod ${BUILDROOT}/mnt/dev/null    c  1  3
	mknod ${BUILDROOT}/mnt/dev/zero    c  1  5
	mknod ${BUILDROOT}/mnt/dev/console c  5  1
	mknod ${BUILDROOT}/mnt/dev/ttyS0   c  4 64
	mknod ${BUILDROOT}/mnt/dev/sr0     b 11  0
	mknod ${BUILDROOT}/mnt/dev/sr1     b 11  1
	mknod ${BUILDROOT}/mnt/dev/sda     b  8  0
	mknod ${BUILDROOT}/mnt/dev/sdb     b  16  0
	mknod ${BUILDROOT}/mnt/dev/sdc     b  32  0
	mknod ${BUILDROOT}/mnt/dev/sdd     b  48  0
	mknod ${BUILDROOT}/mnt/dev/hda     b  3  0
	mknod ${BUILDROOT}/mnt/dev/hdb     b  3  64
	mknod ${BUILDROOT}/mnt/dev/hdc     b  22  0
	mknod ${BUILDROOT}/mnt/dev/hdd     b  22 64
	mknod ${BUILDROOT}/mnt/dev/hde     b  33  0
	cp ${BUILDROOT}/bin/{bash,mount,grep,umount,echo} ${BUILDROOT}/mnt/bin/
	cp ${BUILDROOT}/usr/sbin/chroot ${BUILDROOT}/mnt/bin/
	cp ${BUILDROOT}/sbin/pivot_root ${BUILDROOT}/mnt/bin/
	ln -s bash ${BUILDROOT}/mnt/bin/sh
	cp ${BUILDROOT}/lib/{libncursesw.so.*,libreadline.so.*} ${BUILDROOT}/mnt/lib/
	cp ${BUILDROOT}/lib/{libhistory.so.*,libblkid.so.*,libuuid.so.*,libmount.so.*} ${BUILDROOT}/mnt/lib/
	for f in "ld-linux-x86-64.so.2" "libc.so.6" "libdl.so.2" "libpthread.so.0"
	do
		orig=$(readlink ${BUILDROOT}/lib/$f)
    		orig_basename="${orig##*/}"
    		cp ${BUILDROOT}/lib/$f ${BUILDROOT}/mnt/lib/$orig_basename
		ln -sfv $orig_basename ${BUILDROOT}/mnt/lib/$f
	done
	cp ${BUILDROOT}/bin/{cat,sleep,mknod} ${BUILDROOT}/mnt/bin/
	chmod 0755 ${BUILDROOT}/mnt/linuxrc
	sleep 1
	umount ${BUILDROOT}/mnt
	gzip ${BUILDROOT}/boot/initrd
fi

