sources:
- archive: pygobject-3.56.1.tar.gz
  archive_sha512sum: c995ab179729a7e11932f4a233337931522f869542c751b58be44e02ba2a394d7a0cd75d7d9f36c536776f1a2c165c70e6267a2d3e1720259bda443f166b55bd
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Python bindings for GLib and GObject.'
      home_page: https://pypi.org/project/PyGObject
      license_concluded: LGPL-2.1-or-later AND LGPL-2.1-only AND MIT AND LGPL-2.0-or-later
        AND CC-BY-4.0
      license_declared: LGPL-2.1-or-later AND LGPL-2.1-only AND MIT AND LGPL-2.0-or-later
        AND CC-BY-4.0
      short_summary: Python Bindings for GObject
      supplier: 'Organization: Broadcom, Inc.'
