sources:
- archive: JSON-4.11.tar.gz
  archive_sha512sum: 45ff2c020074e9279f6f98da819af4079ce2dec07c4e908ccd9af9f66b38e451dfa3edec30ef00d43c00b926e304380e602979acf8becb73ac3f7e9497276558
  archive_type: upstream
  name: JSON-4.11
  version: 4.11
  url: https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/JSON-4.11.tar.gz
  repo_url: https://github.com/makamaka/JSON.git
  commit_id: 2e2812bb38a143ef2e0a553104c0a58a693f8ca7
  skip_validation: false
  skip_list: ['MANIFEST']
  missing: ['Changes', 't', '.git', '.github', '.gitignore', '.travis.yml', 'MANIFEST.SKIP', 'author', 'xt', 'META.json', 'META.yml', '121_reentrant.t', '99_binary.pl', '99_binary00.t', '99_binary01.t', '99_binary02.t', '99_binary03.t', '99_binary04.t', '99_binary05.t', '99_binary06.t', '99_binary07.t', '99_binary08.t', '99_binary09.t', '99_binary10.t', '99_binary11.t', '99_binary12.t', '99_binary13.t', '99_binary14.t', '99_binary15.t', 'core_bools.t', 'gh_54_context_sensitive_read_file.t', 'gh_89_space_after_comma.t']
  spdx:
    package:
      detailed_description: 'This module is a thin wrapper for JSON::XS-compatible
        modules with a few additional features. All the backend modules convert a
        Perl data structure to a JSON text and vice versa. This module uses JSON::XS
        by default, and when JSON::XS is not available, falls back on JSON::PP, which
        is in the Perl core since 5.14. If JSON::PP is not available either, this
        module then falls back on JSON::backportPP (which is actually JSON::PP in
        a different .pm file) bundled in the same distribution as this module. You
        can also explicitly specify to use Cpanel::JSON::XS, a fork of JSON::XS by
        Reini Urban.  All these backend modules have slight incompatibilities between
        them, including extra features that other modules don''t support, but as long
        as you use only common features (most important ones are described below),
        migration from backend to backend should be reasonably easy. For details,
        see each backend module you use. '
      home_page: https://metacpan.org/pod/JSON
      license_concluded: Artistic-1.0-Perl OR GPL-1.0-or-later
      license_declared: Artistic-1.0-Perl OR GPL-1.0-or-later
      short_summary: Perl wrapper for JSON. Provides JSON.pm
      supplier: 'Organization: Broadcom, Inc.'
